### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by internaught** [koekeishiya/kwm#1]
This looks really cool, but how would someone go about installing it? I've been looking for a tiling WM for OSX and I'm currently using your Hammerspoon init.lua script, but something like this project seems to be the better solution.

It'd be cool if we could talk on IRC or something like that to get some more documentation around this.

I'm also looking for a bar solution, like https://github.com/stayradiated/bar but I'm having some issues with that as well.

Anyways, if you could put some installation instructions in the readme, I think it'd be awesome.

**Comment by koekeishiya** [comment]
uh, it doesn't create an app bundle.
All you have to do is to execute the build script included to compile it, then launch it from a terminal.
The build script is just running the g++ command.

so cd into the source directory, ./build.sh to compile and launch with ./kwm

**Comment by internaught** [comment]
Thanks man! Love the image too. What are you using for the bar at the top? Can it be customized?

**Comment by koekeishiya** [comment]
The bar is created using "nerdTool", it hasnt been maintained for quite a while i believe, but the latest version works just fine on el capitan

**Comment by internaught** [comment]
nerdTool huh? Bar looks good! I've been trying to build a bar with [Hammerspoon](http://www.hammerspoon.org/) and it's getting tricky. 

Mind sharing your nerdTool bar config?

**Comment by koekeishiya** [comment]
It's kinda tricky as each entry is a separate script, i could upload them as a .zip i guess.
What i did tho, is just create a picture in photoshop that i added to nerdTool (add image).
Now you just add whatever script you want, and set the X,Y coordinates to be somewhere on the bar.

**Comment by internaught** [comment]
cmd+alt+ctrl k creates the segfault ... wish i could try this out, that spaces.plist issue is pretty annoying though.

**Comment by koekeishiya** [comment]
uh if we can talk on IRC or some other IM we can probably figure out why it's happening, if you'd like

**Comment by internaught** [comment]
yeah, perfect, I'm yuppie on freenode and rizon :sushi:

**Comment by internaught** [comment]
Dude! Excellent work on this! Just cloned it and started running! Working great so far. Jump on IRC again sometime.

**Comment by koekeishiya** [comment]
Cheers, still a long way to go for a release tho.
Please do open issues if you discover something that appears to misbehave as it's quite hard finding them by myself.
