### ISSUE TITLE
Remapping hot keys

### ISSUE THREAD

**Issue by dtreiter** [koekeishiya/kwm#10]
What's your stance on allowing users to remap the hotkeys? Currently it seems like you have to modify hotkeys.cpp and recompile.

An alternate approach could be to keep user defined hotkeys in a YAML file, for example, and allow reloading that file while Kwm is running?

**Comment by koekeishiya** [comment]
Kwms builtin hotkeys will remain as is. If you edit hotkeys.cpp and recompile changes take effect without having to restart Kwm. If you do not want to use this approach, you can disable the builtin hotkeys support and make custom mappings to "kwmc <command>" using any external program for exeuting external programs for example hammerspoon.

**Comment by dtreiter** [comment]
Cool, thanks.
