### ISSUE TITLE
Very Very strange issue

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#101]
I don't really know how to describe this. 

All of a sudden KWM started acting very very very strangely. BSP tiling worked. Focusing screens with the keyboard worked. Focusing windows with keyboard __didn't__ work. Autoraise didn't work. The border wasn't drawn. __I lost the ability to type.__ 

This now happens with __any__ build of kwm. I went back to before the focused border changes and still couldn't get it to work for more than a few seconds before it broke. 

Things I have tried
- Using the example kwmrc 
- Turning off different combinations of settings
- Trying different builds, going back to before the focused border
- revoking and granting accessibility access  
- Rebuild and run with out codesinging
- Restarting my computer from a cold boot
- With and with out a 2nd display.

None of these made any difference. I am at such a loss for what could cause this and why it was so sudden. I added or changed no software. I built and updated kwm the exact same way I have been doing all this time. 

Other apps that use the accessibility API seem to work fine, when KWM launches my computer goes bonkers. 

I don't think that this is exactly a bug with KWM, but I am _so confused_ why it was working fine for so long and all off a sudden it's completely broken. 

Do you have _any_ ideas whatsoever?

**Comment by chrishoage** [comment]
I have run kwm in dev mode, and every time I move my mouse or do anything i get 

```
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
GetWindowRef() Could not get AppWindowLst
```


over and over and over again

**Comment by chrishoage** [comment]
Ok, so I think I solved my issue. 

I added `<< Window->Name` to the log listed above. I noticed that it was Flipping out over `Dock`. I noticed that `Dock` had switched itself from Auto Hide to Show. Switching this back to Auto Hide solved the repeated log above. 

After this I discovered a second issue: In my frustration I changed a bunch of settings, one of these config options i changed was from `autoraise` to `autofocus`. Having `focus autofocus` kept Alfred from opening (it kept a bunch of other system shortcuts from working too). Changing this back to `autoraise` allowed Alfred to work again. 


I am going to leave this issue open for you to look at it later, because I _think_ (it's difficult to say) that there may be a bug in kwm somewhere, maybe. This was a very strange experience.

**Comment by koekeishiya** [comment]
The autofocus thing sounds like a bug, not sure whats up with that.
The Dock-log is not exactly a bug, however I've made Kwm ignore the dock now.

**Comment by chrishoage** [comment]
Just seems odd that `autoraise` the key command works, and `autofocus` the same key command does not work. 

It doesn't bother me at all because I use `autoraise`, just thought I'd bring it up. 

The real head scratcher is why the dock captured all focus when it was not set to "AutoHide". 

Thanks for taking a look at it!
