### ISSUE TITLE
Having 2 Chrome windows open segfaults kwm

### ISSUE THREAD

**Issue by AhmedAA** [koekeishiya/kwm#102]
I don't know if anything else could have triggered this, but it seems to be related with space transitioning and having a space with 2 instances of Chrome in monocle mode open.

1: After a little time kwm 'randomly' (of course it's only seemingly random) segfaults.
2: In monocle mode, it is not possible to cycle from 2 to 1 by using the 'next' bind. The same goes for previous to wrap from 1 to 2 (again only when having 2 or more instances of chrome open).

I am on the following version: commit 59385dcfebbebd462a04dadbaa30d7a8f6b5a829
It's the commit with the 'improved draganddrop float' message.

**Comment by AhmedAA** [comment]
I have been running for while now without segfaulting. I don't know what triggers it then. Will update if I frequently segfault again.

**Comment by koekeishiya** [comment]
I'm unable to reproduce this issue.

**Comment by AhmedAA** [comment]
Me too, it is annoying the crap out of me..
I was literally unable to use it, because it kept segfaulting..
I think it has something to do with accessibility though. I rarely shutdown/restart/logout from my mac, but I had updated the binary for kwm a couple of times without re-granting accessibility access (it does not automatically prompt for this). It might be the reason why it kept segfaulting, otherwise, I really can't find any other reason. I feel like a dunce right now though.

On another node, did you remove cycle wrapping in monocle mode? I can't seem to cycle from the last window to the first anymore in monocle. Works fine in bsp.

Also, thank you so much for all your work!

**Comment by koekeishiya** [comment]
Uh. it works just fine for me with `cycle-focus screen` have not tested monocle and `cycle-focus all`.

**Comment by AhmedAA** [comment]
Hmm, I have set ```kwmc config cycle-focus all```
I don't know what else to do then..

**Comment by koekeishiya** [comment]
If you dont use multiple monitors, set it to `kwmc config cycle-focus screen` instead.

**Comment by AhmedAA** [comment]
That fixed it.
Looks like I need to focus more on reading your changelogs then. Sorry for this.

Btw, do you have a donation link or something? I'd like to help out the best I can :)

**Comment by koekeishiya** [comment]
I can reproduce the focus not cycling with `kwmc config cycle-focus all`.

I do not currently have a donation link no. I guess I could set up a patreon or so if people want to offer support, however Kwm is something I mainly develop for my own use I will continue to do so as long as I continue using it.

**Comment by AhmedAA** [comment]
I think I speak for many people when I say that it is incredibly amazing to have a proper tiling WM on os x. I thought I would have to switch back to Linux to get a proper workflow again.
So I don't really care whether you do it for yourself, for recognition, or whatever. I just appreciate it, and would love to help you in any way :)

**Comment by koekeishiya** [comment]
I've added a patreon link at the end of the readme, for people wish to show support. Again, Kwm will always be free and this is not something you should feel the need to do for me to keep improving it.

**Comment by koekeishiya** [comment]
Don't think I'm gonna make changes to `kwmc config cycle-focus all` for now. I kinda like the way it works.

I do believe this issue is related to the newly added borders, it seems to be causing quite a bit if problems.
