### ISSUE TITLE
kwm-overlay broke compatibilty with OS X 10.9.5

### ISSUE THREAD

**Issue by mrsmn** [koekeishiya/kwm#103]
Hi there,

I've been following this project for quite a while now and use it on a daily basis.
Commit 3b8836d241c89ccd39b53f6bfc2eabe825a05944 introduced a "regression" that won't
allow to compile kwm on 10.9.5 anymore which is a shame.

Would you consider making the kwm-overlay app optional so that users on older systems
can still enjoy this awesome piece of software?

Thank you for your time.

Cheers.

**Comment by koekeishiya** [comment]
Uh the overlay can be disabled in the kwmrc config file.
```
`kwmc config focused-border disable`
`kwmc config marked-border disable`
```
You may have to edit the makefile, not totally sure about this as of yet,

**Comment by mrsmn** [comment]
Hi,

thank you for the quick reply. I didn't see the config option to disable the overlay, works like a charm.
You indeed have to edit the makefile manually to prevent make from failing.

Cheers.

**Comment by chrishoage** [comment]
So, the overlay uses the 10.11 SDK to compile, I have yet to do experiments with older SDKs. 

I'd be curious if the pre built binaries work for you?

**Comment by mrsmn** [comment]
@chrishoage I'll give the pre-built binaries a spin tomorrow and I'll get back to you.

Cheers.
