### ISSUE TITLE
Floating followed by unfloating a window can create kwm-overlay with wrong dimensions in bsp-mode

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#104]
All I did was press `cmd+alt+shift-w` twice, this was the result. This happens with the example config as well and is not dependent on the application. 

<img width="1431" alt="screen shot 2016-01-21 at 16 55 10" src="https://cloud.githubusercontent.com/assets/4488655/12485727/e5b65e62-c05f-11e5-96dc-73b52523a214.png">

**Comment by koekeishiya** [comment]
I'm unable to reproduce on current master branch. I feel like this issue might be system specific.

**Comment by chrishoage** [comment]
I can't reproduce this either on HEAD.

**Comment by dominiklohmann** [comment]
Just updated from 59385dc to HEAD and this issue no longer occurs for me.
