### ISSUE TITLE
kwm-overlay causes crash during screen-transitions caused by mouse

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#105]
This crash only happens when focused-border is enabled.
It seems to happen at random and leaves the following log:

```
UpdateActiveWindowList() Active Display Changed
GiveFocusToScreen() 2
Populated Screen Key/Mouse Focus
UpdateFocusedBorder()
alpha: 1.000000 r:0.741176 g: 0.827451 b:0.133333
40093 r:0.741176 g:0.827451 b:0.133333 a:1.000000 s:5
SetWindowRefFocus() Focused Window: borderless (vifm)
ShouldBSPTreeUpdate() Remove Window
UpdateFocusedBorder()
fatal error: unexpectedly found nil while unwrapping an Optional value
alpha: 1.000000 r:0.741176 g: 0.827451 b:0.133333
40093 r:0.741176 g:0.827451 b:0.133333 a:1.000000 s:5
SetWindowRefFocus() Focused Window: borderless (vifm)
UpdateFocusedBorder()
alpha: 1.000000 r:0.741176 g: 0.827451 b:0.133333
59 r:0.741176 g:0.827451 b:0.133333 a:1.000000 s:5
```

I'm not yet sure why this is happening.

**Comment by chrishoage** [comment]
Curious if this happens if you don't use the `windowId` feature of the overlay and pass the width, height, x, and y manually? 

All the "complexity" of the overlay lies in the ability to take a `windowId` as an argument. I wonder if there could be some race condition or getting passed a window with incomplete data (missing a bounds object or something)

**Comment by koekeishiya** [comment]
It does happen without using the windowId feature of the overlay.
To be honest I am really close to just going back to using Honer again, and avoid all these random issues that I have no idea how to debug.

**Comment by chrishoage** [comment]
Feel free to disable / remove the overlay if you want. 

The overlay is really pretty much just Honer that takes commands from outside itself. It really don't do anything Honer doesn't do. I'd honestly be a little surprised if it was the overlay itself causing the issue. 

However the overlay did balloon the complexly of `kwm` itself, it's just a question of is having a marked border worth the extra complexity?  

As far as debugging this: It might be useful to log the window ID / all arguments passed of the border to be focused right before 
`fatal error: unexpectedly found nil while unwrapping an Optional value`. 

If we can find arguments that reproducibly crash the overlay I can fix the issue

**Comment by koekeishiya** [comment]
I dont think the issue is with the kwm-overlay itself, its rather having Kwm call the overlay to update itself from various places, and the complexity this brings with it seems to just break at a certain point (still no idea why). I have printed out the parameters passed to the overlay while debugging this, and there is really no pattern at all.

**Comment by chrishoage** [comment]
I have found out _one_ thing that causes that crash: 

If I pass a space after an argument say `r: 1`

I get this 

```
r:
fatal error: unexpectedly found nil while unwrapping an Optional value
[1]    17511 illegal hardware instruction  ./bin/kwm-overlay
```

**Comment by koekeishiya** [comment]
```
Left mouse button was pressed
Left mouse button was released
UpdateFocusedBorder()
alpha: 1.000000 r:0.741176 g: 0.827451 b:0.133333
x:80 y:81 w:872 h:447 r:0.741176 g:0.827451 b:0.133333 a:1.000000 s:5
SetWindowRefFocus() Focused Window: borderless (bash)
UpdateFocusedBorder()
alpha: 1.000000 r:0.741176 g: 0.827451 b:0.133333
x:-1840 y:80 w:1760 h:910 r:0.741176 g:0.827451 b:0.133333 a:1.000000 s:5
SetWindowRefFocus() Focused Window: borderless (bash)
UpdateActiveWindowList() Active Display Changed
GiveFocusToScreen() 2
Populated Screen Key/Mouse Focus
UpdateFocusedBorder()
alpha: 1.000000 r:0.741176 g: 0.827451 b:0.133333
x:-1840 y:80 w:1760 h:910 r:0.741176 g:0.827451 b:0.133333 a:1.000000 s:5
SetWindowRefFocus() Focused Window: borderless (bash)
ShouldBSPTreeUpdate() Remove Window
fatal error: unexpectedly found nil while unwrapping an Optional value
UpdateFocusedBorder()
alpha: 1.000000 r:0.741176 g: 0.827451 b:0.133333
x:-1840 y:80 w:1760 h:910 r:0.741176 g:0.827451 b:0.133333 a:1.000000 s:5
SetWindowRefFocus() Focused Window: borderless (bash)
UpdateFocusedBorder()
alpha: 1.000000 r:0.741176 g: 0.827451 b:0.133333
x:80 y:543 w:872 h:447 r:0.741176 g:0.827451 b:0.133333 a:1.000000 s:5
```

Passing values to the overlay.

**Comment by chrishoage** [comment]
This is super strange. Let me add some more safety checks in the overlay code and see if I can prevent any `unexpectedly found nil while unwrapping an Optional value` crashes from happening. If we are still having issues because of the overlay crashing after that lets remove it. 

I'll have a PR out in a few hours.

**Comment by koekeishiya** [comment]
Alright, I'm really not sure if this is a bug in kwm or the overlay, all I know is that after this crash has occurred, I need to `pkill kwm-overlay` before I can start Kwm again, as it locks port 3020, due to invalid crash. Despite "kwm-overlay" still running, the border is not showing up anywhere on my screens.

**Comment by chrishoage** [comment]
`unexpectedly found nil while unwrapping an Optional value` is coming from the overlay for certain, I am just not 100% sure why. I'm going to try and cover all my bases with optional values in the overlay code

**Comment by chrishoage** [comment]
Please let me know if you're able to reproduce this crash

**Comment by koekeishiya** [comment]
I believe this has fixed the issue. I can no longer make the crash happen, Thanks.
