### ISSUE TITLE
Re-enable tiling after manually dragging a window

### ISSUE THREAD

**Issue by bensinc** [koekeishiya/kwm#109]
Is there a command to re-enable tiling after manually dragging a window?

I don't like Safari full width, so I often make it smaller on its own workspace. But, I inevitably want to bring something else in, but it's now outside of the tiling system. I thought -c refresh might be candidate, but it doesn't seem to do it.

Thanks!

**Comment by chrishoage** [comment]
` kwmc window -t float` should do the trick.

**Comment by bensinc** [comment]
I'll give that a shot! I also just realized if I hide a window and restore it, kwm fires back up.

**Comment by chrishoage** [comment]
`kwmc config dragndrop` is enabled by default, which will auto toggle a window to floating when it is resized or moved. (I run with this disabled) 

Toggling the window floating again through the previously mentioned command is how you would tell kwm to tile it again.

**Comment by bensinc** [comment]
The space method does work! And if I just resize without switching the space to float mode, switching to float and back right away resets everything just right.

The second idea doesn't seem to work though. I have Safari full screen, via kwm, then drag it around and resize. I next hit cmd+alt+ctrl-w, which is kwm's example config's shortcut for float toggle. It resizes Safari into a small box right in the center, but doesn't return it to tiling. If I open other windows they just go full screen on top of Safari.

Thanks for the help!

**Comment by chrishoage** [comment]
When you want to manually manage windows like you are talking about it's probably "best practice" to have the space set to `floating` anyway. 

Both methods I described work for me, I'd be curious to know what your space is set to. What you are describing makes it sound like the space isn't set to bsp. 

I have created this bitbar script for kwm: https://gist.github.com/chrishoage/4a767c064bbd75f65d58

it has some simple commands and shows what the currently focused tiling mode is set to. It is still very much a WIP and you might have to modify it slightly, but it will allow you to have more info about the state of kwm

**Comment by koekeishiya** [comment]
> The second idea doesn't seem to work though. I have Safari full screen, via kwm, then drag it around and resize. I next hit cmd+alt+ctrl-w, which is kwm's example config's shortcut for float toggle. It resizes Safari into a small box right in the center, but doesn't return it to tiling. If I open other windows they just go full screen on top of Safari.

If i make a window floating using drag&drop (move the window around), it becomes floating for me.
If i perform the command `kwmc window -t float` again, it gets tiled as expected.

I'm unable to reproduce the problem you have with this.

**Comment by bensinc** [comment]
I tinkered with it some more, and I think it's setting it back to tile mode, but not actually retiling it immediately. If I then open another window, it tiles properly. Maybe that's the expected behavior, but I was thinking it would jump back to full screen after using window -t float.

I also just suddenly lost my OSX space switching shortcuts, which came back after killing and restarting kwm.

kwm is great though, I'm really enjoying it!

**Comment by koekeishiya** [comment]
It should re-tile immediately.
Are you sure the space is in bsp (binary space partitioning) mode, and not monocle?

**Comment by bensinc** [comment]
Well, I just realized I had commented out drag to float while I was tinkering. It does now seem to work well with my workflow!

But, I think there is still something weird going on, and maybe just with Safari windows, or two windows from the same application. Here's what I'm doing:

1. Open Safari on an empty space: It fills the screen
2. Drag and resize Safari to the center of the screen
3. Open a new Safari window: They both tile as if I hadn't dragged the first one, like it's not really in float mode

As a test I also tried this:

1. Open iTerm: It filles the screen
2. Open Safari: They both tile
3. Drag Safari a little and let go: It moves, but the iTerm stays in its spot
4. Drag Safari some more: iTerm fills the screen, Safari stays the same size
5. Hit window -t float on Safari and it tiles everything again

In that scenario, the weird part is that I have to move Safari several times for the iTerm to resize, or if I drag if on top of the iTerm window with the first drag, it will resize the iTerm.

I wonder if Safari just does some unexpected things and I was seeing some of that while trying to figure out and reproduce what I was seeing.

Either way, it does work well for me!

**Comment by koekeishiya** [comment]
>In that scenario, the weird part is that I have to move Safari several times for the iTerm to resize, or if I drag if on top of the iTerm window with the first drag, it will resize the iTerm.

I don't think is Safari specfic, but there is some delay to how often it can check for window movement, you might have to "keep it moving" for like 1-2sec before stopping, for Kwm to be able to detect it.

**Comment by lovelydream** [comment]
How to re-tiling in the latest version? I try `kwmc window -t float` but it tells me that
Unknown selector 'float'
