### ISSUE TITLE
Can break fullscreen mode

### ISSUE THREAD

**Issue by ianyh** [koekeishiya/kwm#11]
![screen shot 2015-12-22 at 11 05 11 am 2](https://cloud.githubusercontent.com/assets/212270/11959578/23f3c24a-a89c-11e5-82f8-3fbd7be83360.png)

I ran into this problem with Amethyst (https://github.com/ianyh/Amethyst/issues/254). The short version is that windows from multiple spaces can be on screen at the same time in Mission Control.

**Comment by koekeishiya** [comment]
That seems weird, I was under the impression that i already handled this matter. It would be great if you could list the steps taken just now so i can try to reproduce. Does this happen with every application?

**Comment by ianyh** [comment]
I seem to be able to consistently reproduce by doing the following with two monitors with multiple spaces.

* Put a window into fullscreen
* Open Mission Control
* Use Mission Control to switch to a different space on a different screen

The window appears to get tiled as if it were on the screen that had a space change.

**Comment by koekeishiya** [comment]
Do you happen to know if this only happens when using two or more monitors?
I currently do not have external monitors available and so I'm unable to work on this for the time being.

Will look into it when I can, Thanks.

**Comment by ianyh** [comment]
I have only tested it with more than one monitor. I can try to test it with a single monitor later.

**Comment by koekeishiya** [comment]
Just leaving this here as future reference.
I have now been able to consistently reproduce this bug in the lastest commit,
however I really do not know If i can be bothered fixing it as I never use OSX-fullscreen myself.

I would advice using the monocle mode provided by Kwm and just remove all screen-padding if completely fullscreen windows is something you want.

**Comment by koekeishiya** [comment]
I've tested this quite a bit and this is not really an issue anymore.
It appears that Apple has changed something in El Capitan 10.11.3

To prevent any form of bad behaviour from happening when using the OSX Fullscreen mode,
make sure to make Kwm treat the window as floating (issue kwmc window -t float), and then
turn the window fullscreen.
