### ISSUE TITLE
Issues with kwmc read focused

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#110]
`kwmc read focused` has three issues holding it back right now.

1. It doesn't update the window title every time when `kwmc read focused` is invoked, but rather when the focus switches. The window title can change at any time though.

2. When a title cannot be read or a title does not exist, the trailing " - " should be stripped from the result of `kwmc read focused`.

3. The title can sometimes not be read, I notice this a lot with umlauts (äöüß) and and when there's some other special characters in the window title like in this terminal screenshot.
<img width="348" alt="screen shot 2016-01-23 at 12 40 22" src="https://cloud.githubusercontent.com/assets/4488655/12530002/ab20c18c-c1ce-11e5-9ab8-f24c7e919eb7.png">

**Comment by koekeishiya** [comment]
> It doesn't update the window title every time when kwmc read focused is invoked, but rather when the focus switches. The window title can change at any time though.

Not sure what you mean by this. `kwmc read focused` should simply return a value and not invoke any form of action in Kwm.

> When a title cannot be read or a title does not exist, the trailing " - " should be stripped from the result of kwmc read focused.

This is something I have done on purpose for consistency such that I can always detect if the focused window has a title or not through simple split of the '-' character.

> The title can sometimes not be read, I notice this a lot with umlauts (äöüß) and and when there's some other special characters in the window title like in this terminal screenshot.

Will take a look at fixing this later.

**Comment by dominiklohmann** [comment]
> Not sure what you mean by this. kwmc read focused should simply return a value and not invoke any form of action in Kwm.

Suppose you have a window open and the focus doesn't change but its title changes. If you keep invoking `kwmc read focused` (through a bitbar script or something like that), it will always show the title the window had when the window focus last changed.

**Comment by koekeishiya** [comment]
> Suppose you have a window open and the focus doesn't change but its title changes. If you keep invoking kwmc read focused (through a bitbar script or something like that), it will always show the title the window had when the window focus last changed.

Fixed in latest commit.

Point 2. is working as I want it to tho. You could achieve the behaviour you want through `sed` or something similar.

I will take a look at 3. later as it seems to require some more effort than the previous one.

**Comment by dominiklohmann** [comment]
Thanks. Will do point 2 with something like sed then, just didn't expect that to be the expected behaviour.

**Comment by koekeishiya** [comment]
Regarding point 2, personally it doesn't matter too much to me, so I might as well just go ahead and do it, as I have seen at least one other user mention it.

**Comment by koekeishiya** [comment]
> The title can sometimes not be read, I notice this a lot with umlauts (äöüß) and and when there's some other special characters in the window title like in this terminal screenshot.

I have tried every single encoding option listed here: https://developer.apple.com/library/ios/documentation/CoreFoundation/Conceptual/CFStrings/Articles/Converting.html

None of them seem to fix the issue.

**Comment by dominiklohmann** [comment]
I don't know much about `std::string` but could it basically being `std::basic_string<char>` be the issue? Can some of the characters allowed in window titles even be represented by an array of 8-bit chars?

Maybe `kCFStringEncodingUTF16` with strings with 16-bit chars does the job?

**Comment by koekeishiya** [comment]
std::string does not seem to support UTF8 indeed, and this is the issue as far as I'm concerned.
Will look into what alternatives there are.
