### ISSUE TITLE
Cannot focus Spotlight or Alfred

### ISSUE THREAD

**Issue by geekuillaume** [koekeishiya/kwm#112]
When using kwm auto-focus, it impossible to write inside Spotlight or Alfred.
I need to disable auto-focus, then open Alfred to use it.

**Comment by koekeishiya** [comment]
This is due to the nature of autofocus redirection all keypresses to the focused application, this causes "overlay" applications such as spotlight, alfred and so on to not receive input correctly. I'd advice using autoraise with `kwmc config focus standby-on-float enable`.

Again, this is due to the limited access given by OSX.

**Comment by geekuillaume** [comment]
Okay, I'm now using the auto-raise and everything is working fine, thanks.

The only problem with auto-raise is with floating windows that are ignored by KWM. If I move the cursor, the window is hidden and I cannot switch to it with regular hotkeys.
The only way I found to do it is to deactivate auto-raise and then switch to the window with Expose.

**Comment by chrishoage** [comment]
> The only way I found to do it is to deactivate auto-raise and then switch to the window with Expose.

You can use `kwmc config focus standby-on-float enable` and `cmd + tab` to the application, this will disable autoraise while a floating application is in focus. (this is what I do)

**Comment by bensinc** [comment]
I was having trouble with Spotlight as well, which prompted me to try LaunchBar again. It works great inside kwm!

**Comment by koekeishiya** [comment]
There should not be any issues with spotlight as long as `kwmc config focus` is not set to `autofocus`.

autofocus is only really there as I use it myself (although rarely), and the limitations that come with it is something that I cannot do anything about, due to the way OSX works.
