### ISSUE TITLE
Option to deactivate margins when only one window in space

### ISSUE THREAD

**Issue by geekuillaume** [koekeishiya/kwm#114]
When a window is the only one in its space, the margin are unnecessary. It would be great to have an option to deactivate the margin in this case.
Simple idea, don't know how hard it is to do.

**Comment by chrishoage** [comment]
Sorta related to this is the ability to have `kwmc config padding` change the values while kwm is running. Right now the only way to get `kwmc config padding` values to be applied is the first time kwm starts. `kwmc config reload` and setting `kwmc config padding` in the terminal has no effect on the padding.

**Comment by koekeishiya** [comment]
`kwmc config padding` isn't really meant to be applied during runtime. It's just for setting the default values.

`kwmc space -p` and `kwmc space -g` is supposed to be used during runtime as they are space-speific.

**Comment by koekeishiya** [comment]
This could be tricky to implement as a "general-purpose" setting, does the user have menubar and dock enabled, and should the padding leave room for those. How big is the dock, and so on.

**Comment by bensinc** [comment]
I was thinking of something similar, but not quite... I would love a way to specify custom margins for certain windows, but only if they're the only visible window. That would make it easy for me to have Safari not fill the width of my ultrawide monitor, but still have it tile when other windows appear.

I suppose that could also be set to 0 margin for geekuillaume's use-case.

**Comment by koekeishiya** [comment]
Still don't really have a good solution for how to implement this.

> I was thinking of something similar, but not quite... I would love a way to specify custom margins for certain windows, but only if they're the only visible window. That would make it easy for me to have Safari not fill the width of my ultrawide monitor, but still have it tile when other windows appear.

This can be achieved by creating pseudo-nodes, `kwmc tree -c pseudo create`

**Comment by matthewdias** [comment]
Maybe have a config for temp fullscreen/monocle/single window padding?

**Comment by koekeishiya** [comment]
This will not be implemented in Kwm, however, in **chunkwm** you can toggle all offsets (padding & gap) for individual spaces.
