### ISSUE TITLE
Directional focus does not allow for monocle windows to be switched

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#117]
Using west / south / north / east does not allow for monocle windows to be changed. 

They also seem to ignore the `kwmc config cycle-focus` setting.

**Comment by koekeishiya** [comment]
Not sure how to best achieve these commands in monocle mode, as there is no concept of directions there. I'll probably have the "west" and "east" default to "prev" and "next" while monocle mode is active.

Having the directions wrap-around is gonna be tricky to implement and will not happen for quite a while, if at all.

**Comment by chrishoage** [comment]
> I'll probably have the "west" and "east" default to "prev" and "next" while monocle mode is active.

This is what my assumption on how it would have worked. 

> Having the directions wrap-around is gonna be tricky to implement and will not happen for quite a while, if at all.

What I expected was the behavior that was there before. If the tile is the first or last item in the tree and I give a focus command that returns "nothing" (i'm on the last leaf and I give an east or south command) I get dumped to the first title. The inverse of that for the first tile. 

I am not expecting (at least currently) to be able to hit `south` and be wrapped to to top of the screen (although it would be neat)

**Comment by koekeishiya** [comment]
> What I expected was the behavior that was there before. If the tile is the first or last item in the tree and I give a focus command that returns "nothing" (i'm on the last leaf and I give an east or south command) I get dumped to the first title. The inverse of that for the first tile. 

I can probably add this behaviour for now.

> I am not expecting (at least currently) to be able to hit south and be wrapped to to top of the screen (although it would be neat) 

This is something I really want to do, will see in the future.
