### ISSUE TITLE
Add kwmc read prefix

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#120]
Please add a `kwmc read prefix` command that returns whether the prefix key is enabled or not. Would love to have that for my Übersicht.

**Comment by koekeishiya** [comment]
Enabled as in a prefix key has been set, or enabled as in the prefix key has been activated and it will now respond to hotkeys.

**Comment by dominiklohmann** [comment]
Enabled as in the prefix key has been activated.

**Comment by dominiklohmann** [comment]
When pressing the prefix key and then waiting for the prefix timeout, the result of `kwmc read prefix` does not update until you press a key.

**Comment by koekeishiya** [comment]
Uh, the prefix does only check whether it should deactivate upon a keypress. 

If the state was to update "live" without detection on actual keypresses, I would have to create yet another separate thread for this, which I think adds an unnecessary performance toll.

**Comment by dominiklohmann** [comment]
No what I mean is that when for example I do prefix-w to float a window I then need to press another button that also has a prefix bind to make kwmc read prefix recognize that the prefix is no longer active.

**Comment by koekeishiya** [comment]
Should be fixed now.
