### ISSUE TITLE
Switching between iGPU and dGPU

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#123]
OS X seems to have changed something with OS X 10.11.3 when switching between iGPU and dGPU (at least I've never seen this happen before updating).

```
Left mouse button was pressed
Left mouse button was released
New display detected! DisplayID: 2077752381 Index: 1
DisplayID 2077752381 has index 0
GiveFocusToScreen() 0
Populated Screen Key/Mouse Focus
UpdateFocusedBorder()
SetWindowRefFocus() Focused Window: dominiklohmann — -zsh — 97×54 20,40
Display has been removed! DisplayID: 69731266
DisplayID 2077752381 has index 0
GiveFocusToScreen() 0
Empty Screen
Left mouse button was pressed
Left mouse button was released
CreateWindowNodeTree() Create Tree
CreateWindowNodeTree() Create Space 1
CreateBSPTree() Create pair of leafs
UpdateFocusedBorder()
SetWindowDimensions()
UpdateFocusedBorder()
SetWindowDimensions()
UpdateFocusedBorder()
SetWindowRefFocus() Focused Window: kwm — kwm-overlay ◂ kwm — 97×54 727,40
```

This is the relevant part of the kwm output when switching between GPUs, OS X now seems to remove the display and add a new one, which causes kwm to reset the layout of the current space.

**Comment by koekeishiya** [comment]
Could be related somehow to #108
Apple seem to have introduced some "temporary" display things while they deal with their displays in 10.11.3

The "fake" displays always seem to have a DisplayID of "207775XXXX".

I do not have any of these available to me, so this is not something I can investigate further.

**Comment by dominiklohmann** [comment]
As a workaround, could you check for the changed Display ID being 207775XXXX and then maybe save/restore the tree layout automatically?

**Comment by koekeishiya** [comment]
> OS X now seems to remove the display and add a new one, which causes kwm to reset the layout of the current space.

It should cause all of the layouts to be cleared, and not just the current space tho.

> As a workaround, could you check for the changed Display ID being 207775XXXX and then maybe save/restore the tree layout automatically?

Not totally sure if this is possible. The tree-layout could be saved, but restoring it would have to happen manually.

**Comment by dominiklohmann** [comment]
> It should cause all of the layouts to be cleared, and not just the current space tho.

Just force-switched to the dGPU and you are right, it breaks the layout of all spaces.

**Comment by koekeishiya** [comment]
Honestly not sure if it is possible to handle these cases with how Kwm works fundamentally.
I will look into possibly re-writing the display code more or less from scratch, to provide proper support for the changes made in 10.11.3, when I have time.

**Comment by bensinc** [comment]
This may be related... I normally run my MBP on an external monitor, and today unhooked it for the first time. Kwm didn't realize that had happened, and it was tiling to the external monitor dimensions. Restarting kwm fixed it, but is there a way it could do that automatically?

**Comment by koekeishiya** [comment]
See referenced commit for status on this issue.
