### ISSUE TITLE
Does not discover new screen size when changing screen without changning number of screens

### ISSUE THREAD

**Issue by oetting** [koekeishiya/kwm#127]
If I use my laptop built in screen and then close the laptop (wait for it to sleep), connect an external bigger display, it looks like kwm still thinks the display has the size of the laptop display.

The same goes the other way around. If I use my laptop closed, with an external display, disconnect the display, wait for it to sleep and then open the laptop, kwm still thinks the display has the size of the external display.

If kwm at any point sees the two displays at the same time, it finds the right sizes and I can, for instance, close the laptop and use the external screen without issues.

**Comment by bensinc** [comment]
I do the same thing often... Moving from my desk with external display to just the MBP. I end up killing and restarting kwm each time.

**Comment by koekeishiya** [comment]
There seem to be a lot of "random" display issues after 10.11.3, and this will be re-written from scratch when I have time. 

I'm quite busy with university this semester, and have a lot less time to work on Kwm. Feel free to try and make improvements to how this works yourself and submit a PR, if you are interested and have time to do so.

**Comment by koekeishiya** [comment]
See referenced commit for status on this issue.
