### ISSUE TITLE
Config focus disabled doesn't work

### ISSUE THREAD

**Issue by JELGT2011** [koekeishiya/kwm#129]
My kwmrc file has the two lines:

`kwmc config focus disabled`
`kwmc config focus mouse-follows disable`

but my mouse still changes my current application on mouseover.  Also note that the first line is inconsistent as everywhere else it is `disable` and not `disabled`.

**Comment by koekeishiya** [comment]
`kwmc config focus disabled` disables focus on mouseover as expected for me.

**Comment by JELGT2011** [comment]
If it matters, I'm on Yosemite.

**Comment by koekeishiya** [comment]
There is no reason why it would not be disabled on older OSX versions as well.
Try to manually run the command `kwmc config focus disabled` from a terminal while Kwm is running.

**Comment by JELGT2011** [comment]
running it in debug mode I'm seeing "Left mouse button was pressed" and "Left mouse button was released" when I'm not clicking, just moving my mouse over different windows.

**Comment by JELGT2011** [comment]
I tried that as well, didn't seem to do anything.

Running it in debug mode here is some of the logs (note that I didn't click throughout that entire session):

UpdateActiveWindowList() Active Display Changed
GiveFocusToScreen() 0
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: jlibbey@is-mbp-jlibbey: ~/Documents/Repositories/dashboard-web 10,23
SetWindowRefFocus() Focused Window: jlibbey@is-mbp-jlibbey: ~/Documents/Repositories/dashboard-web 10,23
ShouldBSPTreeUpdate() Remove Window
SetWindowRefFocus() Focused Window: jlibbey@is-mbp-jlibbey: ~/Documents/Repositories/dashboard-web 10,23
UpdateActiveWindowList() Active Display Changed
GiveFocusToScreen() 2
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: kwmrc — /Users/jlibbey/.kwm -1910,-170
SetWindowRefFocus() Focused Window: kwmrc — /Users/jlibbey/.kwm -1910,-170
ShouldBSPTreeUpdate() Remove Window
SetWindowRefFocus() Focused Window: kwmrc — /Users/jlibbey/.kwm -1910,-170
UpdateActiveWindowList() Active Display Changed
GiveFocusToScreen() 0
Populated Screen Key/Mouse Focus
ShouldBSPTreeUpdate() Remove Window
Left mouse button was pressed
Left mouse button was released
UpdateActiveWindowList() Active Display Changed
GiveFocusToScreen() 2
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: kwmrc — /Users/jlibbey/.kwm -1910,-170
SetWindowRefFocus() Focused Window: kwmrc — /Users/jlibbey/.kwm -1910,-170
ShouldBSPTreeUpdate() Remove Window
SetWindowRefFocus() Focused Window: kwmrc — /Users/jlibbey/.kwm -1910,-170
UpdateActiveWindowList() Active Display Changed
GiveFocusToScreen() 0
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: jlibbey@is-mbp-jlibbey: ~/Documents/Repositories/dashboard-web 10,23
SetWindowRefFocus() Focused Window: jlibbey@is-mbp-jlibbey: ~/Documents/Repositories/dashboard-web 10,23
ShouldBSPTreeUpdate() Remove Window
SetWindowRefFocus() Focused Window: jlibbey@is-mbp-jlibbey: ~/Documents/Repositories/dashboard-web 10,23
UpdateActiveWindowList() Active Display Changed
GiveFocusToScreen() 2
Populated Screen Key/Mouse Focus
ShouldBSPTreeUpdate() Remove Window
Left mouse button was pressed
Left mouse button was released
UpdateActiveWindowList() Active Display Changed
GiveFocusToScreen() 0
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: jlibbey@is-mbp-jlibbey: ~/Documents/Repositories/dashboard-web 10,23
SetWindowRefFocus() Focused Window: jlibbey@is-mbp-jlibbey: ~/Documents/Repositories/dashboard-web 10,23
ShouldBSPTreeUpdate() Remove Window
SetWindowRefFocus() Focused Window: jlibbey@is-mbp-jlibbey: ~/Documents/Repositories/dashboard-web 10,23
UpdateActiveWindowList() Active Display Changed
GiveFocusToScreen() 2
Populated Screen Key/Mouse Focus
ShouldBSPTreeUpdate() Remove Window
Left mouse button was pressed
SetWindowRefFocus() Focused Window: kwmrc — /Users/jlibbey/.kwm -1910,-170
Left mouse button was released
UpdateActiveWindowList() Active Display Changed

**Comment by JELGT2011** [comment]
I think I figured it out, it only happens with windows on different screens.  How can I disable this behavior?

**Comment by koekeishiya** [comment]
This behaviour is intended between screens, because without it, Kwm cannot detect when a screen transition has occurred, due to limitations within OSX.

**Comment by JELGT2011** [comment]
I see, so there is no way to have GiveFocusToScreen() without changing the current application?

**Comment by koekeishiya** [comment]
Unfortunately no, there is nothing I can do about this.

**Comment by JELGT2011** [comment]
I suppose it could remember the last active application before it calls GiveFocusToScreen().  It's kind of a hack, but it might work.  Love kwm so far by the way!
