### ISSUE TITLE
External display: screen is always empty

### ISSUE THREAD

**Issue by alexfedoseev** [koekeishiya/kwm#134]
Hi! I have weird issue with my external display: `kwm` sees it, but thinks that it's empty and moves all windows from external screen to my build-in screen.

Here is the chronology:

```
### Moved mouse to the external display (without clicking, just moved)
UpdateActiveWindowList() Active Display Changed           # True
GiveFocusToScreen() 1                                     # Thanks!
UpdateActiveWindowList() Space transition ended 8 -> 3    # I'm on the new space
Empty Screen                                              # Oops! This is so not true!
Left mouse button was pressed                             # Never happened
Left mouse button was released                            # Same: never happened!

### Moved mouse back to the first one
UpdateActiveWindowList() Space transition ended 3 -> 8    # I'm on the previous space
UpdateActiveWindowList() Active Display Changed           # True     
GiveFocusToScreen() 0                                     # Thanks!
Populated Screen Key/Mouse Focus                          # Window from external display was moved to this screen
SetWindowRefFocus() Focused Window: kwm 80,80
SetWindowRefFocus() Focused Window: kwm 80,80
```

My [`kwmrc`](https://gist.github.com/alexfedoseev/7e03538967d1fe567758). Not sure what else to provide here.

**Comment by koekeishiya** [comment]
> Empty Screen                                              # Oops! This is so not true!
Left mouse button was pressed                             # Never happened
Left mouse button was released                            # Same: never happened!

The screen is not necessarily empty, it's just a poorly written debug message for myself.
What it means, is that this is the first time Kwm enters this screen/space to retrieve information.

The left-mouse button press/release, is performed by Kwm itself, to force the OSX API to update the information retrieved from CGSGetActiveSpace, because there is no notion of different monitors, only x,y coordinates.

For more information regarding the headache that is multiple monitors, see #65

Quote from some other issue regarding monitors:
> There seem to be a lot of "random" display issues after 10.11.3, in addition to this, the existing display code has not really been written with active testing as I did not have monitors available when this code was written. I will be re-writing the display code from scratch when I have time.

> I'm quite busy with university this semester, and have a lot less time to work on Kwm, so it could potentially take a long time before I'm able to implement a good system for dealing with displays.

> Feel free to try to make improvements for how this works and submit a PR, if you are interested and have time to do so.

**Comment by alexfedoseev** [comment]
@koekeishiya I see, thanks for reply! Should I keep it opened?

**Comment by koekeishiya** [comment]
Can probably just close it for now.

**Comment by alexfedoseev** [comment]
@koekeishiya Accidentally I figured out the root of issue:

![screen_shot_2016-02-03_at_20_26_23](https://cloud.githubusercontent.com/assets/4244251/12791049/6448dc90-cab6-11e5-9efe-7141c473005e.jpg)

![screen_shot_2016-02-03_at_20_27_52](https://cloud.githubusercontent.com/assets/4244251/12791057/6c3bd452-cab6-11e5-8aee-fd2b58773f5b.jpg)

**Comment by koekeishiya** [comment]
Uh right that reminds me I never added support for "stacking monitors", as I dont use this.
If this is something you would like to have support for, I'm sure I can implement it without too much effort.

**Comment by alexfedoseev** [comment]
It's not smth critical (I just moved my macbook a bit to the left haha), but if you'll find a time for it, it'll be great :+1:

**Comment by koekeishiya** [comment]
Should be working now, test briefly.

**Comment by alexfedoseev** [comment]
Now it's working, thanks!
