### ISSUE TITLE
Add option to set anchor for tiled windows

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#135]
A commonly used example application that could use this is QuickTime Player, which when playing video has a fixed width/height ratio. kwm currently anchors windows to the top left of their tile, which is something I would love to be able to center.

For this I would suggest adding both a vertical and a horizontal anchor setting, which could be set to top/left, center or bottom/right.

**Comment by koekeishiya** [comment]
Not entirely sure how to interpret this.

Do you mean anchor as in offsetting the window X,Y coordinate such that the window is centered (or whatever specified) in the created container?

**Comment by dominiklohmann** [comment]
Exactly what I was trying to do.

**Comment by koekeishiya** [comment]
Sounds like a great idea, and should be simple enough to implement. Will give it a shot later tonight.

**Comment by koekeishiya** [comment]
I don't think I'm gonna bother making this an option.
It always makes sense for me to make it be tiled in the center, if it cannot fill the container.

**Comment by dominiklohmann** [comment]
Sure thing, that's what I was intending to use anyways.

Thanks!

**Comment by koekeishiya** [comment]
I believe this should be working now, only tested with mpv.
Would be nice if you can confirm.

**Comment by dominiklohmann** [comment]
Seems to be working just fine, except for container resizing, where windows get moved to the top and then back again. Maybe you can save the width/height ratio here and make it less flashy?

**Comment by koekeishiya** [comment]
Does that issue happen in the latest commit? I've removed the buggy "do not resize tiled windows" code.

**Comment by dominiklohmann** [comment]
Seems to be fixed, thanks!

**Comment by dominiklohmann** [comment]
After a reboot I've had it happen again and managed to capture it on video.

https://gfycat.com/BewitchedFocusedBrownbutterfly

**Comment by koekeishiya** [comment]
There appears to be no easy-to-implement way around the flickering for now. Will keep it in mind tho.

**Comment by dominiklohmann** [comment]
This stopped working in a recent commit (it worked yesterday), @koekeishiya?

**Comment by koekeishiya** [comment]
Still works in the latest commit for me, which applications fail for you?

**Comment by dominiklohmann** [comment]
QuickTime Player fails

**Comment by koekeishiya** [comment]
Still works for me for quicktime player as well. Although you may have to perform `kwmc window -c refresh` on it, or some kwmc command that causes the window to resize.

This is because the window itself is resized before Kwm is able to create an observer for it, and can not track the window-size changed event to re-apply the container.

**Comment by dominiklohmann** [comment]
I tried `window -c refresh` and `window -c reduce|expand x`, but they don't do the job for me. 

<img width="1440" alt="screen shot 2016-02-11 at 10 36 06" src="https://cloud.githubusercontent.com/assets/4488655/12973255/47e41d9e-d0ab-11e5-8d8f-38f150b89de2.png">

**Comment by koekeishiya** [comment]
Weird,I just tested and works perfectly on my end.
Could you post your kwmrc?

**Comment by dominiklohmann** [comment]
Sure, it's a bit all over the place, but there you go.

https://gist.github.com/dominiklohmann/f3103f2b8c3add1d39cc

**Comment by koekeishiya** [comment]
I noticed you have `kwmc config focus standby-on-float enable`
Quicktime becomes treated as a floating window on my system, so I had  `kwmc config focus standby-on-float disable` just now when testing. I do not think this should matter on your end though, as it appears to have tiled.

I don't really understand why that happens tho.

On an unrelated note, I see you still have `kwmc window -t mark` bound, this command has been changed to `kwmc mark -w focused`.

**Comment by dominiklohmann** [comment]
> `kwmc config focus standby-on-float enable`

Nothing changes when I set is to disable, it still doesn't center the window.

> On an unrelated note, ...

Yeah, not been keeping up to date with the config changes recently, I really need to clean that config up.

**Comment by dominiklohmann** [comment]
Disabling the following setting in my kwmrc seems to have done the job for me, it's tiling now:

`kwmc config float-non-resizable enable`

**Comment by koekeishiya** [comment]
Ah yeah that's the one I meant earlier, my bad, I got myself confused with the other one somehow..
If you'd like to undo that behaviour, you can move line 1471 in window.cpp to line 1473 (just above the line `if(UpdateWindowInfow`, that's the only change I've made that would affect that behaviour.

It's not something I'll do in Kwm because this behaviour is more correct per se.

**Comment by dominiklohmann** [comment]
I guess it makes sense for kwm to behave like that, I've just gotten used to it working the other way. I'll leave that setting disabled.

Thanks for the help!

**Comment by koekeishiya** [comment]
Actually it's a mistake on my part now that i re-read the code. Will push a commit in a sec that could fix this. Thanks for noticing.
