### ISSUE TITLE
Do you know "defaults read com.apple.spaces"

### ISSUE THREAD

**Issue by oetting** [koekeishiya/kwm#138]
I just stumbled across this http://stackoverflow.com/questions/6768684/osx-lion-applescript-how-to-get-current-space-from-mission-control . I do not know if it is usefull for anything. 
I guess it is used by osx to restore the correct number of spaces after a reboot. As you can read from the SO answers it does not change "live" when you change active space. But it is updated when adding/removing spaces. 

I just wantet to make sure you knew. Feel free to close this issue.

**Comment by koekeishiya** [comment]
I used this before, and it is invalidated after system enters sleep, and will be a downgrade from the current way Kwm works.

**Comment by oetting** [comment]
Thanks
