### ISSUE TITLE
Add "directional move"

### ISSUE THREAD

**Issue by oetting** [koekeishiya/kwm#139]
In many cases I would find it useful to be able to move a window in a direction, instead of swapping. Would that be difficult to implement.

I had a short look at tree.cpp, but could not figure it out. Given any pointers I would love to help implement this.

**Comment by koekeishiya** [comment]
I think I get what you mean. Basically you want to detach a window, and reinsert it in a direction?

If this is the case, it should be quite trivial to implement as it will be more or less the same as the existing command `kwmc window -x`.

**Comment by oetting** [comment]
Exactly. I did not notice the window -x command. I will try to expand on that and see if it is useful in real usage.

**Comment by koekeishiya** [comment]
Implemented in latest commit.

**Comment by oetting** [comment]
Great. You could add an argument to `ToggleWindowFloating` that is passed to `RemoveWindowFromBSPTree` avoid moving on the detatch if the intent is to reattach immediately afterwards. 

`void ToggleWindowFloating(int WindowID, bool MoveOnDetatch)
{
    if(IsWindowOnActiveSpace(WindowID) &&
       KWMScreen.Current->Space[KWMScreen.Current->ActiveSpace].Mode == SpaceModeBSP)
    {
        int WindowIndex;
        if(IsWindowFloating(WindowID, &WindowIndex))
        {
            KWMTiling.FloatingWindowLst.erase(KWMTiling.FloatingWindowLst.begin() + WindowIndex);
            AddWindowToBSPTree(KWMScreen.Current, WindowID);

            if(KWMMode.Focus != FocusModeDisabled && KWMMode.Focus != FocusModeAutofocus && KWMToggles.StandbyOnFloat)
                KWMMode.Focus = FocusModeAutoraise;
        }
        else
        {
            KWMTiling.FloatingWindowLst.push_back(WindowID);
            RemoveWindowFromBSPTree(KWMScreen.Current, WindowID, MoveOnDetatch, MoveOnDetatch);

            if(KWMMode.Focus != FocusModeDisabled && KWMMode.Focus != FocusModeAutofocus && KWMToggles.StandbyOnFloat)
                KWMMode.Focus = FocusModeStandby;
        }
    }
}
`

**Comment by koekeishiya** [comment]
Thanks for noticing, this change is now in effect.
