### ISSUE TITLE
Cmd + Tab does not work when kwm is running

### ISSUE THREAD

**Issue by fedragon** [koekeishiya/kwm#14]
Hello @koekeishiya, 
thanks for this nice tool, it seems really promising! 
I just started playing around with it and noticed that `Cmd + Tab` does not behave as usual while `kwm` is running, do you have any idea why?

Thanks and please keep up the good work!

**Comment by koekeishiya** [comment]
I purposely disabled it in hotkeys.cpp, apparently I have forgotten to mention that.
If you open hotkeys.cpp and remove the "case kVK_Tab:" block, it should work again.

**Comment by fedragon** [comment]
Oh I see, thank you!
