### ISSUE TITLE
kwmc bind with high key-repeat rate

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#140]
I have the following binds:

```
kwmc bind cmd+shift-tab window -f prev
kwmc bind cmd-tab window -f next
``` 

When I hold down either of these or press them to fast over and over again, the default app switcher comes up that I intended to overwrite with these binds.

The same thing happens with `cmd+alt-h` for me every so often, hiding all other applications instead of shrinking the current container.

**Comment by koekeishiya** [comment]
Unable to reproduce on my system.

Held the keybind down for approx 10seconds.
It does cause a lot of delay and I see the effects falling behind, but it does not cause the OSX system bind to take over.

Tested with: `kwmc bind cmd+alt-h window -f west` with `cycle-focus screen`
Not sure if this matters, but I run with fastest "key repeat" and shortest "delay until repeat" in system settings.

**Comment by dominiklohmann** [comment]
I can reproduce this 100% of the time. Guess it doesn't really matter since you normally shouldn't hold these keys down anyways and it only happens when I do so for a few seconds.
