### ISSUE TITLE
Move window

### ISSUE THREAD

**Issue by oetting** [koekeishiya/kwm#144]
The current detach-and-reinsert and swap commands allow you to move a window to any location. 

But I think a more logical way of doing it would be a combination of the two. If I am moving a window east, and the first window to the east has the same parent node as me, the two windows are swapped. If I continue moving east, then the next window to the east might in a different parent, then a detach-and-reinsert is used. 
To make this even better if I insert into a vertically split container from the west, then the window should be inserted as the first node. And so forth for other directions and containers.

Thoughts?

**Comment by koekeishiya** [comment]
This could be useful in some situations, but I find myself often wanting to swap windows that do not have the same parent node, and not necessarily change the bsp-layout.

My first impression is that this is not something I'm gonna implement.

**Comment by oetting** [comment]
I can see how this would certainly add complexity. A few new read commands sound like a good idea.

Maybe the same_parent and dir commands should be generalized so that they work on a passed window?

Something like:

get current window
`read current`

Read window in direction from window
`read dir WINDOW DIRECTION`

Read parent of WINDOW
`read parent WINDOW`

Read split_type of WINDOW
`read split_type WINDOW`

I do not know if it is worth the complexity. Some of them might be usefull for other things though.

**Comment by koekeishiya** [comment]
example script to achieve your suggested behaviour:
```
DIR=$1
WINDOW=$(kwmc read dir "$DIR" wrap)
SAME_PARENT=$(kwmc read parent "$WINDOW")
if [ "$SAME_PARENT" = "1" ]
then
    kwmc window -s "$DIR"
else
    SPAWN=$(kwmc read spawn)
    CHILD=$(kwmc read child "$WINDOW")
    if [ "$CHILD" = "left" ]
    then
        kwmc config spawn right
    else
        kwmc config spawn left
    fi

    kwmc window -x "$DIR"
    kwmc config spawn "$SPAWN"
fi
```

Example usage inside kwmrc:
```
kwmc bind cmd+alt-j sys ~/.kwm/move.sh south
kwmc bind cmd+alt-k sys ~/.kwm/move.sh north
kwmc bind cmd+alt-h sys ~/.kwm/move.sh west
kwmc bind cmd+alt-l sys ~/.kwm/move.sh east
```

**Comment by oetting** [comment]
Awesome. Works very well!
