### ISSUE TITLE
Apps in native fullscreen mode

### ISSUE THREAD

**Issue by alexfedoseev** [koekeishiya/kwm#145]
Is there any way to tell kwm to ignore apps in osx's native fullscreen mode (which are placed next to spaces in Mission Control)?

**Comment by koekeishiya** [comment]
This is probably related to #11

**Comment by koekeishiya** [comment]
I've tested this quite a bit and this is not really an issue anymore.
It appears that Apple has changed something in El Capitan 10.11.3

To prevent any form of bad behaviour from happening when using the OSX Fullscreen mode,
make sure to make Kwm treat the window as floating (issue `kwmc window -t float`), and then
turn the window fullscreen.

**Comment by alexfedoseev** [comment]
Already did that :+1:

**Comment by matthewdias** [comment]
I'm wondering if there's a better way to automate this. My first instinct would be to bind a shortcut to float the window and then activate fullscreen (is it possible to have two actions per bind?), however, we'd need a way to programmatically activate fullscreen. The other problem with this is that some apps kick you into native fullscreen automatically. For example, Chrome was updated recently to do so when a youtube video or something goes fullscreen. If we could somehow listen for fullscreen activation and float before letting the action continue that would be ideal. Both options would probably require cocoa stuff so maybe this will have to wait for #111. 

Relevant links:
http://stackoverflow.com/questions/15872873/detecting-full-screen-applications-on-mac
http://dougscripts.com/itunes/2011/07/detect-full-screen-mode/
https://github.com/shinypb/FullScreenDetector

**Comment by koekeishiya** [comment]
I just pushed a commit that makes it so that you do not have to make a window floating for Kwm to ignore it in fullscreen mode. However, this will cause the window tree that originally held the window to have an empty tile where the fullscreened window was prior.

**Comment by matthewdias** [comment]
works great thanks

**Comment by alexfedoseev** [comment]
+1 works great :+1:
