### ISSUE TITLE
Quitting an application with a window on another space breaks the other spaces window tree

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#146]

**Comment by koekeishiya** [comment]
Probably can't be fixed, as Kwm tracks individual windows and not applications windows.
In addition to this, OSX does not offer any way to get information about windows that are on a different space than the active one.

**Comment by dominiklohmann** [comment]
Makes sense, so I'm just gonna write a script that closes the application when the last window closes.
