### ISSUE TITLE
Use AppleScripts to resize stubborn windows

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#149]
There are certain windows that have minimum constraints which means that kwm can't resize them as small as they need to go. Consider using AppleScripts which for some reason can bypass these restraints. I haven't looked into the code closely enough yet to see how window resizing is accomplished, but something like this might solve this:
```
tell application "System Events" to tell process "Wunderlist"
    tell window 1
        set size to {100, 100}
        set position to {10, 10}
    end tell
end tell
```

**Comment by koekeishiya** [comment]
Does not work for me using applescript either. Windows still respect their minimum size.

**Comment by matthewdias** [comment]
Oh that's weird, it used to work. I can't reproduce anymore either. Maybe it has to do with the 10.11.3 update.
