### ISSUE TITLE
Some iTerm windows are ignored by kwm

### ISSUE THREAD

**Issue by alexfedoseev** [koekeishiya/kwm#152]
Some iTerm windows are ignored by kwm on creation. Here is the gif: http://share.minima.pro/f4qr

My current [`kwmrc`](https://gist.github.com/alexfedoseev/7e03538967d1fe567758). And I use [patched iTerm](https://github.com/jaredculp/iterm2-borderless-padding).

**Comment by koekeishiya** [comment]
This is due to the window spawning outside of the screen. Will look into fixing it at some point.

**Comment by alexfedoseev** [comment]
Confirm it's fixed, thanks!

**Comment by alexfedoseev** [comment]
Nope, it's still present: http://share.minima.pro/f65r

**Comment by koekeishiya** [comment]
Hm I'm unable to reproduce on my end

**Comment by koekeishiya** [comment]
Reverted the previous solution. Instead, it will now handle windows between monitors (e.g outside of screen bounds), as being on the screen that has the mouse pointer.

This should be a more "correct" fix to this problem, I hope.

**Comment by alexfedoseev** [comment]
Thanks! I reseted all my iTerm stuff yesterday, and it currently works w/o issues with solution from 	0909ce3. I'll update kwm today/tomorrow and let you know if it's ok or not.
