### ISSUE TITLE
`focused-border enable` binding shows border only after first focus change

### ISSUE THREAD

**Issue by alexfedoseev** [koekeishiya/kwm#153]
```
kwmc bind cmd+ctrl-o config focused-border enable
```

When I hit this hot key to enable `focused-border`, border shows up only after first focus change (so current focused window doesn't has a border). Disabling `focused-border` works fine (border disappears immediately).

And one more question : is it possible to have one hot key to toggle border visibility (enable if disabled and vice versa)?

**Comment by koekeishiya** [comment]
> When I hit this hot key to enable focused-border, border shows up only after first focus change (so current focused window doesn't has a border). Disabling focused-border works fine (border disappears immediately).

Will look into this.

 > And one more question : is it possible to have one hot key to toggles border visibility (enable if disabled and vice versa)?

This is possible to do, but I'd have to implement a function for it inside Kwm as of now.
What I would rather to, is improve/extend the `kwmc read` support such that all "toggling" or "do <x> if <y> else <z>" kinda thing is performed by allowing the users to write their own scripts, that they bind to a hotkey.

**Comment by alexfedoseev** [comment]
> What I would rather to, is improve/extend the kwmc read support such that all "toggling" or "do if else " kinda thing is performed by allowing the users to write their own scripts, that they bind to a hotkey.

:+1:

**Comment by koekeishiya** [comment]
added: `kwmc read border focused|marked|prefix` which return 1 if enabled, 0 if not.

Example "toggle-focused-border.sh" script:
```
ENABLED=$(kwmc read border focused)
if [ "$ENABLED" = "1" ]
then
    kwmc config focused-border disable
else
    kwmc config focused-border enable
fi
```

Bind script within kwmrc:
```
kwmc bind .. sys ~/.kwm/focused-border-toggle.sh
```

**Comment by alexfedoseev** [comment]
Thanks! One issue:

> kwmc bind .. sys ~/.kwm/toggle-focused-border.sh

This works if I run kwm from console manually, but it doesn't work if kwm lunched on system startup.
I tried chmod it `u+x` & `+x`.

**Comment by koekeishiya** [comment]
try using full path instead of the tilde expansion, e.g: /Users/<name>/.kwm/script.sh

**Comment by alexfedoseev** [comment]
No luck, this also doesn't work.

**Comment by koekeishiya** [comment]
probably need absolute path to `kwmc` inside the script as well.

**Comment by alexfedoseev** [comment]
> probably need absolute path to kwmc inside the script as well.

This was it. Thanks!
