### ISSUE TITLE
option to quit apps when all windows are closed

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#156]
not sure if this is within the scope of this project, but given that focus is given to a new app when a window is closed, it's harder to quit an app after closing its window. maybe consider adding a per-app preference to enable quitting after closing all windows of the app.

**Comment by dominiklohmann** [comment]
I tried implementing something like that once and ran into issues where applications would have no window while loading. In the end I settled on only doing this for my Terminal and I am pretty sure you don't need to modify much to get that script working with iTerm as well.

script.scpt
```AppleScript
tell application "Terminal"
	if ((count of (tabs of (every window whose visible is true))) = 1) then
		try
			set theContents to words of ((contents of tab 1 of window 1) as Unicode text)
			set exitLastTab to (theContents contains "logout")
		on error
			set exitLastTab to false
		end try
		if exitLastTab is true then
			quit
		end if
	else if (count of (tabs of (every window whose visible is true))) < 1 then
		quit
	end if
end tell
```

Then add the following to your .zshrc or .bash_profile
```sh
# auto-closing Terminal.app on last window
if [ "$TERM_PROGRAM" = "Apple_Terminal" ] && [ -x path/to/script.scpt ]; then
  trap '/usr/bin/osascript path/to/script.scpt' EXIT
fi
```

Also make sure to allow Terminal.app to be closed when osascript is still being executed by it, this can be done in the applications settings.

**Comment by koekeishiya** [comment]
This should be doable using the folllowing piece of code:
```
    CFArrayRef AppWindowLst;
    AXUIElementCopyAttributeValue(App, kAXWindowsAttribute, (CFTypeRef*)&AppWindowLst);
    if(!AppWindowLst)
    {
        DEBUG("GetWindowRef() Could not get AppWindowLst")
        return false;
    }
```

Number of windows open for this application would be the count of AppWindowLst. If it is zero, send a sigterm to the associated process through its id.

However, this is not something I will attempt to do for now.

**Comment by koekeishiya** [comment]
Not gonna be implementing this. I find myself always using cmd+q to close an application when I'm on the last window, instead of cmd+w, and so I don't think this is worth adding to Kwm.

**Comment by matthewdias** [comment]
Leaving this here in case anyone else stumbles upon it.
```
define stubborn {Simplenote,Preview,TextEdit,Microsoft Word}
...
kwmc bindsym-passthrough cmd-w press cmd+alt-q stubborn -i
```
