### ISSUE TITLE
kwm resets layouts across spaces sometimes

### ISSUE THREAD

**Issue by AhmedAA** [koekeishiya/kwm#158]
Title says it.
Have no idea when this happens/why it triggers.
See screenshot.

It happens less often with recent updates, still does happen though, and it is quite infuriating :S

As always, keep up the good work :)

EDIT: The space in the screenshot was set to monocle. It seems like it tries to go bsp, and then messes up the sizing.

<img width="1680" alt="screen shot 2016-02-10 at 15 15 46" src="https://cloud.githubusercontent.com/assets/1724181/12949722/a716d506-d009-11e5-904e-4ed69ead8ce5.png">

**Comment by koekeishiya** [comment]
I remember coming across this bug quite some time ago, but have not been able to reproduce it since.
I don't really have any clue as to what causes this to happen yet, and I'm wondering if it is something specific to monocle spaces.

**Comment by matthewdias** [comment]
I have this issue occasionally too, but I don't think I was using monocle at all when it happened. I'll keep an eye out and try to figure out what's going on when it happens.

**Comment by koekeishiya** [comment]
This may be fixed in the latest commit although this bug was not the one I was targetting, and I have no idea how to reproduce this issue, I have made changes that would affect this part of the code.

**Comment by AhmedAA** [comment]
I pulled the latest code, and currently running on the latest version. If the problem persists, I will report back here :)

**Comment by koekeishiya** [comment]
Not much I can do really until someone is able to figure out how to reproduce consistently.
I have not had this happen to me feor the past month or so.
