### ISSUE TITLE
Default layout for space?

### ISSUE THREAD

**Issue by andreaspada** [koekeishiya/kwm#164]
Hi! Recently discovered KWMC and loving it! Just a preliminary quastion: can I specify a default layout for each space? For example, I like my email app and finder to open always on space 1, browsers on space 2, graphical app on space 3 and 4, and so on...
Can I have space 1 and 3 default to tile and 2 and 4 default to monocle? (just one screen)
Cheers,
Andrea

**Comment by koekeishiya** [comment]
See #128 

Might happen in the future.

**Comment by koekeishiya** [comment]
Solution from other issue:

See kwmc config spaces-key and the example init file for how to achieve this.

Note: The space-number used is the number you would use with your keyboard-shortcuts to reach that space.

**Comment by andreaspada** [comment]
Well, just amazing... I'll try it!
