### ISSUE TITLE
Focus follows mouse without tiling

### ISSUE THREAD

**Issue by Evan-Goode** [koekeishiya/kwm#165]
Hello,
I'm wondering whether it is possible to enable focus-follows-mouse but disable tiling?
I have tried setting `kwmc config tiling disable` and `kwmc config space float` in my kwmrc but these lines disable focus-follows-mouse altogether.

**Comment by koekeishiya** [comment]
Doing `kwmc config tiling disable` works fine for me. No tiling and focus-follows-mouse still works.

**Comment by Evan-Goode** [comment]
Thanks!
