### ISSUE TITLE
How to always float finder dialog and info?

### ISSUE THREAD

**Issue by andreaspada** [koekeishiya/kwm#169]
How can is possible to always float information windows (as folder and drive info) and dialogs as copy?
If I use "kwmc read windows" it give me this:

7549, iTerm2, andrea@Mac-Pro: ~/.kwm (zsh)
9667, Finder, Guests Info
9326, Finder, Guests

I want to all *Info windows to stay float...

**Comment by koekeishiya** [comment]
This is not possible as far as I know. There is no way for Kwm to know which finder window is a info window and what is not.

**Comment by dominiklohmann** [comment]
It doesn't float when you don't have a folder selected in the main pane (e.g. when the focus is on an entry in the Favorites to the left) and use "Get Info" for that (either by using the context menu or pressing `cmd-i`).

**Comment by chrishoage** [comment]
Finder transfer dialogs (when copying / moving a  file from one directory to another) do not auto-float either. 

"Get Info" dialogs only sometimes auto-float

**Comment by andreaspada** [comment]
Thanks!
