### ISSUE TITLE
Ctrl-x as default prefix key

### ISSUE THREAD

**Issue by AhmedAA** [koekeishiya/kwm#170]
In Emacs, Ctrl-x is a very common prefix key. Luckily it's easy to change in the config, but it might be an idea to change it to something else?

Unfortunately it's incredibly hard to find THE universal binding on OS X.

Not sure if this is even worth mentioning, just wanted to at least have raised the concern!

The best!

**Comment by koekeishiya** [comment]
The default binds are just a copy of my own personal binds, meant to give people who may be new to tiling wms a starting point. I'm sure that people who use emacs would be no strangers to personalizing config files to their liking.
