### ISSUE TITLE
Send kwm actions inside iTerm2

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/kwm#171]
Hi,

First of all, many thanks for doing the best wm on mac os x. I switched from Linux a few weeks ago and the lack of a proper tiling windows manager was my daily main frustration.

I use kwm since a few days, it works good even if I am not as fluent inside it as I was in awesome wm.

I saw in the default config file that you provide some options to run iTerm. 

I use iTerm2 as my terminal (mainly for its no window title bar option). However, when an iTerm2 window is focused, all my keybindings are not working. I can't control or send actions to kwm. It seems that iTerm2 prevent global key bindings. 

How do you handle this ? Are there any workarounds ?

Thanks

**Comment by koekeishiya** [comment]
Make sure that "Secure keyboard input" is not enabled.

**Comment by mickaelperrin** [comment]
Much better, indeed :)

Many thanks for your reactivity.

What are the best places to discuss about kwm on a user perspective ? There are some concepts I don't understand.

**Comment by koekeishiya** [comment]
> What are the best places to discuss about kwm on a user perspective ? There are some concepts I don't understand. 

No idea, just create issues I guess.

**Comment by matthewdias** [comment]
As this project gets more popular it might be worth setting up a gitter.im chat, or at least providing guidelines to mark help issues with [help].

**Comment by koekeishiya** [comment]
> As this project gets more popular it might be worth setting up a gitter.im chat, or at least providing guidelines to mark help issues with [help].

Setting up a gitter would probably be the best solution, though I have no idea how many people even use Kwm, so no idea how the activity would be.

I'm under the impression that there aren't all that many users, and the gitter would be pretty dead.
