### ISSUE TITLE
Unable to launch kwm

### ISSUE THREAD

**Issue by qnm** [koekeishiya/kwm#175]
I've been unable to start kwm a few times, with the following error:

```
❯ /usr/local/opt/kwm/kwm
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /usr/local/Cellar/kwm/1.1.2/kwm-overlay
  Reason: image not found
```

This was installed form homebrew.

```
❯ /usr/local/opt/kwm/kwm --version
Kwm Version 1.1.2
```

I don't have XCode installed, should that somehow be related.

```
❯ sudo dtruss -f /usr/local/opt/kwm/kwm

dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /usr/local/Cellar/kwm/1.1.2/kwm-overlay
  Reason: image not found
	PID/THRD  SYSCALL(args) 		 = return
 4801/0x50f8:  thread_selfid(0x0, 0x0, 0x0)		 = 20728 0
 4801/0x50f8:  csops(0x0, 0x0, 0x7FFF5142F9B0)		 = 0 0
 4801/0x50f8:  issetugid(0x0, 0x0, 0x7FFF5142F9B0)		 = 0 0
 4801/0x50f8:  shared_region_check_np(0x7FFF5142D8A8, 0x0, 0x7FFF5142F9B0)		 = 0 0
 4801/0x50f8:  stat64("/usr/lib/dtrace/libdtrace_dyld.dylib\0", 0x7FFF5142EE38, 0x7FFF5142F9B0)		 = 0 0
 4801/0x50f8:  open("/usr/lib/dtrace/libdtrace_dyld.dylib\0", 0x0, 0x0)		 = 3 0
 4801/0x50f8:  pread(0x3, "\312\376\272\276\0", 0x1000, 0x0)		 = 4096 0
 4801/0x50f8:  pread(0x3, "\317\372\355\376\a\0", 0x1000, 0x7000)		 = 4096 0
 4801/0x50f8:  fcntl(0x3, 0x61, 0x7FFF5142D180)		 = 0 0
 4801/0x50f8:  mmap(0x0, 0x670, 0x5, 0x1, 0x3, 0x7000)		 = 0x10E80B000 0
 4801/0x50f8:  munmap(0x10E80B000, 0x670)		 = 0 0
 4801/0x50f8:  mmap(0x10E810000, 0x2000, 0x5, 0x12, 0x3, 0x7000)		 = 0x10E810000 0
 4801/0x50f8:  mmap(0x10E812000, 0x1000, 0x3, 0x12, 0x3, 0x9000)		 = 0x10E812000 0
 4801/0x50f8:  mmap(0x10E813000, 0x2F40, 0x1, 0x12, 0x3, 0xA000)		 = 0x10E813000 0
 4801/0x50f8:  close(0x3)		 = 0 0

<snip>
```

**Comment by chrishoage** [comment]
I wrote the overlay, and am a little bit at a loss for why you are experiencing this error. For reference, what version of OS X are you using?

**Comment by dominiklohmann** [comment]
Assuming you have installed the OS X Developer Tools  (`xcode-select --install`), can you tell us what version of the swift compiler you are using?

You can do so by running the following.
```
❯ swiftc -v
Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
```

**Comment by chrishoage** [comment]
He has mentioned he installed though homebrew and does not have xcode installed. However, running `xcode-select --install` may fix this issue if my hunch is correct.

**Comment by qnm** [comment]
Hey folks,

Thanks for your help.

Some details:

 > For reference, what version of OS X are you using? 

```
~
❯ sw_vers -productVersion
10.11.3
```

 >  can you tell us what version of the swift compiler you are using?

```
~
❯ swiftc -v
Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
```

 > However, running xcode-select --install may fix this issue if my hunch is correct. 

```
~
❯ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by chrishoage** [comment]
I will have to experiment with uninstalling xcode and trying to run kwm. That is the difference I can see that may cause this issue. 

In the mean time, I'd be curious if installing xcode fixes the issue, if it doesn't I have no idea what might be causing it.

**Comment by dominiklohmann** [comment]
- What's the output of `xcode-select -p`?
- Can you manually add the paths that are missing to the Makefile using `swiftc -L /path/to/missing.dylib`?

**Comment by qnm** [comment]
> What's the output of xcode-select -p?

```
❯ xcode-select -p
/Library/Developer/CommandLineTools
```

I'm not sure what to do here:

```
/Library/Developer/CommandLineTools/usr/lib/swift/macosx
❯ swiftc -L /Library/Developer/CommandLineTools/usr/lib/swift/macosx/*
ld: warning: path '/Library/Developer/CommandLineTools/usr/lib/swift/macosx/libswiftAVFoundation.dylib' following -L not a directory
ld: can't map file, errno=22 file '/Library/Developer/CommandLineTools/usr/lib/swift/macosx/x86_64' for architecture x86_64
```

I've discovered I can make it work using the following

```
DYLD_LIBRARY_PATH=/Library/Developer/CommandLineTools/usr/lib/swift/macosx /usr/local/Cellar/kwm/1.1.2/kwm-overlay
```

**Comment by dominiklohmann** [comment]
Edit your .bash_profile or .zshrc accordingly and add the following line:

`export DYLD_LIBRARY_PATH=/Library/Developer/CommandLineTools/usr/lib/swift/macosx/:$DYLD_LIBRARY_PATH`

**Comment by qnm** [comment]
@dominiklohmann That doesn't seem to have helped. Opening the console, the logs are full of these:

![screen shot 2016-02-22 at 9 13 12 pm](https://cloud.githubusercontent.com/assets/5343/13215403/f7f477b6-d94c-11e5-9f59-359f7ac421c8.png)

**Comment by koekeishiya** [comment]
As far as I know, applications launched through launchd does not read the .bashrc, or even the PATH environment variables.

I do not know of a way to fix this, nor do I know what causes it.
In the meantime, you can prevent Kwm from trying to load kwm-overlay by making sure your kwmrc contains
```
kwmc config focused-border disable
kwmc config marked-border disable
kwmc config prefix-border disable
```

**Comment by qnm** [comment]
@koekeishiya Thanks! That's allowed `kwm` to run again.

@chrishoage @dominiklohmann I'm going to switch off the overlay for now, but please feel free to get in touch if you want me to debug anything on your behalf.

**Comment by dominiklohmann** [comment]
`launchctl setenv DYLD_LIBRARY_PATH $DYLD_LIBRARY_PATH` right after that line I suggested before should allow applications run through launchctl to pick up that environment variable.

**Comment by chrishoage** [comment]
I will investigate how to set the `DYLD_LIBRARY_PATH` automatically. As of this moment my guess is that installing xcode sets that for me? I need xcode to compile a server I use for work, so I won't be able to investigate this until this weekend. 

There is probably some build flag I need to set. 

http://stackoverflow.com/questions/14888668/how-to-set-dyld-library-path-in-xcode

**Comment by dominiklohmann** [comment]
One kinda ugly solution would be to manually set it before [Line 26 in `kwm/border.cpp`](https://github.com/koekeishiya/kwm/blob/5b73805fb9d3f52fa07dffec69be3efec3be84dc/kwm/border.cpp#L26) if the needed dylib is not in the environment variable already. This can be done by simply changing Line 26 to the following:

```cpp
static const std::string DYLDLibraryPath = "DYLD_LIBRARY_PATH=/Library/Developer/CommandLineTools/usr/lib/swift/macosx/:$DYLD_LIBRARY_PATH";
std::string OverlayBin = DYLDLibraryPath + " " + KWMPath.FilePath + "/kwm-overlay";
```

**Comment by rsff** [comment]
Same here, the solution was to disable the overlay!

**Comment by igorette** [comment]
Same same here, I disabled the overlay.
