### ISSUE TITLE
Persistent space settings

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#176]
This is related to #128 but in addition to setting a default mode, being able to also set padding, gaps, and other  space-dependent settings would be nice. (Including a default bsp-tree instead of manually performing `kwmc tree restore ..`).

Again, this has the same problem, that there are so far no permanent way to identify spaces. I may have come up with a solution that would work good enough, that I will try in the near future.

**Comment by matthewdias** [comment]
In what order does kwm recognize windows at startup? I'm wondering if it would be possible to manipulate that order if its a system thing, that way trees could be preserved on unexpected restarts.

**Comment by oetting** [comment]
I have been thinking the same thing. If the windows are already in the right place it would be nice if they stayed there.

**Comment by koekeishiya** [comment]
The order is based upon front to back (last focus, in an descending order). See CGWindowListCopyWindowInfo from apple docs.

**Comment by koekeishiya** [comment]
After finding a solution to #236 I believe I have also found a way to reliable provide this support.

**Comment by koekeishiya** [comment]
Padding, gaps, and tiling mode, can now be specified for individual spaces in kwmrc.
Check the kwmc/README or `kwmc help` for information.

In short:
```
kwmc config space id mode bsp|monocle|float
kwmc config space id padding top bottom left right
kwmc config space id gap vertical horizontal
```

where id is the number shown in mission control.
