### ISSUE TITLE
Auto focus issue from a user perspective

### ISSUE THREAD

**Issue by andreaspada** [koekeishiya/kwm#178]
So, after some time tweaking and enjoying kwm, I have some user related issue that I cannot solve. Hope someone can point me to the right direction...

1) I cannot disable auto-focus and auto-raise feature. Though I understand they can be really useful, I simply do not like them. For example, if I have a full screen window and I decide to clean my trash, the dialog window which is opened is obscured as soon as I try to reach it with my mouse pointer. I though that my mouse would be auto moved by the new focused window, but this is not working...

2) Another strange thing is some window are auto focused when I move my mouse on to them - System Preferences - but other, for example "about my Mac" do not.

I already tried to disable such features with 'kwmc config focus mouse-follows disable', 'kwmc config focus disable', 'kwmc config focus authorise disable', 'kwmc config autofocus disable'... nothing seems to alter the default behaviour, which is strange, as I already have deeply customised my '~/.kwm/kwmrc' file.

Any clues?

**Comment by koekeishiya** [comment]
> 1) I cannot disable auto-focus and auto-raise feature. Though I understand they can be really useful, I simply do not like them. For example, if I have a full screen window and I decide to clean my trash, the dialog window which is opened is obscured as soon as I try to reach it with my mouse pointer. I though that my mouse would be auto moved by the new focused window, but this is not working...

`kwmc config focus disabled` should do the trick.

> 2) Another strange thing is some window are auto focused when I move my mouse on to them - System Preferences - but other, for example "about my Mac" do not.

"about my mac" does get focus properly for me, when I mouseover
See `kwmc config focus standby-on-float enable|disable`

**Comment by andreaspada** [comment]
Thanks, I'll get a look.
KUDOS
