### ISSUE TITLE
LoadKwmCode() Could not open '~/kwm/hotkeys.so'

### ISSUE THREAD

**Issue by fedragon** [koekeishiya/kwm#18]
Hi,
I just noticed that `hotkeys.so` cannot be loaded if `kwm` is started from a directory other than `kwm/bin` because the path is resolved using the current working directory (https://github.com/koekeishiya/kwm/blob/master/kwm/kwm.cpp#L236). Not a big deal but I thought you might want to know :)

**Comment by stefkin** [comment]
From README:

>If Kwm is added to the path, a launcher script is necessary because it tries to load hotkeys.so from
the executables working-directory.
Example launcher script to be placed in the path instead of the Kwm binary.

    #!/bin/bash
    pushd /path/to/kwm
    ./kwm
    popd

**Comment by fedragon** [comment]
I did not add `kwm` to my path, what I did was:
```
cd ~/kwm
bin/kwm
```
Anyway, it seems like the author is aware of this and that was the goal of my ticket...

**Comment by koekeishiya** [comment]
Kwm no longer looks in the current working directory, but locates the executables full path and uses that to determine the location of hotkeys.so. This should no longer be a problem, and a launch script is also no longer necessary.
