### ISSUE TITLE
Sharing my .kwmrc

### ISSUE THREAD

**Issue by andreaspada** [koekeishiya/kwm#180]
Hi! As I'm new to kwm, I'll love to see some .kwmrc out there, showing some really cool setup. I don't know which place is intended for this; until I discover, I start sharing my own, yet on work, that could be interesting as it's based on a very personal approach. It's similar to the setup I used on my old linux+xmonad.
Golden section split relationship, arrow management.

<pre>
<span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span> 
<span class="darkred">#</span> <span class="teal">Golden</span> <span class="teal">Section</span> <span class="darkred">#</span>
<span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span>

<span class="darkred">#</span> <span class="teal">Set</span> <span class="darkblue">default</span> <span class="darkblue">values</span> <span class="darkblue">for</span> <span class="darkblue">screen</span> <span class="darkblue">padding</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">padding</span> <span class="darkblue">top</span> <span class="darkblue">33</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">padding</span> <span class="darkblue">bottom</span> <span class="darkblue">10</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">padding</span> <span class="darkblue">left</span> <span class="darkblue">10</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">padding</span> <span class="darkblue">right</span> <span class="darkblue">10</span>

<span class="darkred">#</span> <span class="teal">Set</span> <span class="darkblue">default</span> <span class="darkblue">values</span> <span class="darkblue">for</span> <span class="darkblue">container</span> <span class="darkblue">gaps</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">gap</span> <span class="darkblue">vertical</span> <span class="darkblue">10</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">gap</span> <span class="darkblue">horizontal</span> <span class="darkblue">10</span>

<span class="darkred">#</span> <span class="teal">Allow</span> <span class="teal">Kwm</span> <span class="darkblue">to</span> <span class="darkblue">tile</span> <span class="darkblue">windows</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">tiling</span> <span class="darkblue">enable</span>

<span class="darkred">#</span> <span class="teal">Let</span> <span class="teal">Kwm</span> <span class="darkblue">listen</span> <span class="darkblue">for</span> <span class="darkblue">hotkeys</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">hotkeys</span> <span class="darkblue">enable</span>

<span class="darkred">#</span> <span class="teal">Set</span> <span class="darkblue">prefix</span> <span class="darkblue">for</span> <span class="teal">Kwms</span> <span class="darkblue">hotkeys</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">prefix</span> <span class="darkblue">ctrl</span><span class="darkred">-</span><span class="darkblue">x</span>

<span class="darkred">#</span> <span class="teal">Prefix</span> <span class="darkblue">is</span> <span class="darkblue">not</span> <span class="darkblue">applied</span> <span class="darkblue">globally</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">prefix</span><span class="darkred">-</span><span class="darkblue">global</span> <span class="darkblue">disable</span>

<span class="darkred">#</span> <span class="teal">Time</span> <span class="darkblue">in</span> <span class="darkblue">seconds</span><span class="darkred">,</span> <span class="darkblue">before</span> <span class="darkblue">prefix</span> <span class="darkblue">must</span> <span class="darkblue">be</span> <span class="darkblue">re</span><span class="darkred">-</span><span class="darkblue">activated</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">prefix</span><span class="darkred">-</span><span class="darkblue">timeout</span> <span class="darkblue">0.75</span>

<span class="darkred">#</span> <span class="teal">Automatically</span> <span class="darkblue">float</span> <span class="darkblue">windows</span> <span class="darkblue">that</span> <span class="darkblue">fail</span> <span class="darkblue">to</span> <span class="darkblue">resize</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">float</span><span class="darkred">-</span><span class="darkblue">non</span><span class="darkred">-</span><span class="darkblue">resizable</span> <span class="darkblue">enable</span>

<span class="darkred">#</span> <span class="teal">Float</span> <span class="darkblue">a</span> <span class="darkblue">window</span> <span class="darkblue">if</span> <span class="darkblue">moved</span> <span class="darkblue">using</span> <span class="darkblue">the</span> <span class="darkblue">mouse</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">dragndrop</span> <span class="darkblue">disable</span>

<span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span> <span class="teal">Focus</span> <span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">focus</span> <span class="darkblue">enable</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">focus</span> <span class="darkblue">mouse</span><span class="darkred">-</span><span class="darkblue">follows</span> <span class="darkblue">enable</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">focus</span> <span class="darkblue">autoraise</span> <span class="darkblue">enable</span>

<span class="darkred">#</span> <span class="teal">Set</span> <span class="darkblue">focus</span><span class="darkred">-</span><span class="darkblue">follows</span><span class="darkred">-</span><span class="darkblue">mouse</span><span class="darkred">-</span><span class="darkblue">mode</span> <span class="darkblue">to</span> <span class="darkblue">autoraise</span>
<span class="darkred">#</span><span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">focus</span> <span class="darkblue">autoraise</span>

<span class="darkred">#</span> <span class="teal">Focus</span><span class="darkred">-</span><span class="darkblue">follows</span><span class="darkred">-</span><span class="darkblue">mouse</span> <span class="darkblue">is</span> <span class="darkblue">temporarily</span> <span class="darkblue">disabled</span> <span class="darkblue">when</span>
<span class="darkred">#</span> <span class="darkblue">a</span> <span class="darkblue">floating</span> <span class="darkblue">window</span> <span class="darkblue">has</span> <span class="darkblue">focus</span>
<span class="darkred">#</span><span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">focus</span> <span class="darkblue">standby</span><span class="darkred">-</span><span class="darkblue">on</span><span class="darkred">-</span><span class="darkblue">float</span> <span class="darkblue">enable</span>

<span class="darkred">#</span> <span class="teal">The</span> <span class="darkblue">mouse</span> <span class="darkblue">will</span> <span class="darkblue">automatically</span> <span class="darkblue">move</span> <span class="darkblue">to</span> <span class="darkblue">the</span> <span class="darkblue">center</span>
<span class="darkred">#</span> <span class="darkblue">of</span> <span class="darkblue">the</span> <span class="darkblue">focused</span> <span class="darkblue">window</span>
<span class="darkred">#</span><span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">focus</span> <span class="darkblue">mouse</span><span class="darkred">-</span><span class="darkblue">follows</span> <span class="darkblue">enable</span>

<span class="darkred">#</span> <span class="teal">Allow</span> <span class="darkblue">window</span> <span class="darkblue">focus</span> <span class="darkblue">to</span> <span class="darkblue">wrap</span><span class="darkred">-</span><span class="darkblue">around</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">cycle</span><span class="darkred">-</span><span class="darkblue">focus</span> <span class="darkblue">screen</span> <span class="darkred">#</span> <span class="darkblue">all</span> <span class="darkred">|</span> <span class="darkblue">disabled</span>

<span class="darkred">#</span> <span class="teal">Default</span> <span class="darkblue">tiling</span> <span class="darkblue">mode</span> <span class="darkblue">for</span> <span class="darkblue">new</span> <span class="darkblue">spaces</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">space</span> <span class="darkblue">bsp</span>

<span class="darkred">#</span> <span class="teal">Set</span> <span class="darkblue">default</span> <span class="darkblue">container</span> <span class="darkblue">split</span><span class="darkred">-</span><span class="darkblue">ratio</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">split</span><span class="darkred">-</span><span class="darkblue">ratio</span> <span class="darkblue">0.618</span>

<span class="darkred">#</span> <span class="teal">New</span> <span class="darkblue">splits</span> <span class="darkblue">become</span> <span class="darkblue">the</span> <span class="darkblue">left</span> <span class="darkblue">leaf</span><span class="darkred">-</span><span class="darkblue">node</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">spawn</span> <span class="darkblue">left</span>

<span class="darkred">#</span> <span class="teal">Add</span> <span class="darkblue">custom</span> <span class="darkblue">tiling</span> <span class="darkblue">rules</span> <span class="darkblue">for</span> <span class="darkblue">applications</span> <span class="darkblue">that</span>
<span class="darkred">#</span> <span class="darkblue">does</span> <span class="darkblue">not</span> <span class="darkblue">get</span> <span class="darkblue">tiled</span> <span class="darkblue">by</span> <span class="teal">Kwm</span> <span class="darkblue">by</span> <span class="darkblue">default</span><span class="darkred">.</span>
<span class="darkred">#</span> <span class="teal">This</span> <span class="darkblue">is</span> <span class="darkblue">because</span> <span class="darkblue">some</span> <span class="darkblue">applications</span> <span class="darkblue">do</span> <span class="darkblue">not</span> <span class="darkblue">have</span> <span class="darkblue">the</span>
<span class="darkred">#</span> <span class="teal">AXWindowRole</span> <span class="darkblue">and</span> <span class="teal">AXStandardWindowSubRole</span>
<span class="darkred">#</span><span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">add</span><span class="darkred">-</span><span class="darkblue">role</span> <span class="teal">AXDialog</span> <span class="darkblue">iTerm2</span>

<span class="darkred">#</span> <span class="teal">The</span> <span class="darkblue">following</span> <span class="darkblue">command</span> <span class="darkblue">blacklists</span> <span class="darkblue">a</span> <span class="darkblue">specific</span> <span class="darkblue">application</span>
<span class="darkred">#</span> <span class="darkblue">from</span> <span class="teal">Kwms</span> <span class="darkblue">tiling</span> <span class="darkred">(</span><span class="teal">PS</span><span class="darkred">:</span> <span class="teal">The</span> <span class="darkblue">app</span> <span class="darkblue">name</span> <span class="darkblue">is</span> <span class="darkblue">case</span><span class="darkred">-</span><span class="darkblue">sensitive</span><span class="darkred">)</span>
<span class="darkred">#</span> <span class="teal">If</span> <span class="darkblue">the</span> <span class="darkblue">name</span> <span class="darkblue">consist</span> <span class="darkblue">of</span> <span class="darkblue">multiple</span> <span class="darkblue">words</span><span class="darkred">,</span> <span class="darkblue">the</span> <span class="darkblue">command</span>
<span class="darkred">#</span> <span class="darkblue">looks</span> <span class="darkblue">like</span><span class="darkred">:</span> <span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">float</span> <span class="teal">Google</span> <span class="teal">Chrome</span>
<span class="darkred">#</span><span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">float</span> <span class="teal">Steam</span>
<span class="darkred">#</span><span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">float</span> <span class="teal">Photoshop</span>

<span class="darkred">#</span> <span class="teal">The</span> <span class="darkblue">following</span> <span class="darkblue">command</span> <span class="darkblue">captures</span> <span class="darkblue">an</span> <span class="darkblue">application</span> <span class="darkblue">to</span> <span class="darkblue">the</span>
<span class="darkred">#</span> <span class="darkblue">given</span> <span class="darkblue">screen</span><span class="darkred">,</span> <span class="darkblue">if</span> <span class="darkblue">the</span> <span class="darkblue">screen</span> <span class="darkblue">exists</span><span class="darkred">.</span> <span class="teal">By</span> <span class="darkblue">doing</span> <span class="darkblue">this</span>
<span class="darkred">#</span> <span class="darkblue">the</span> <span class="darkblue">application</span> <span class="darkblue">can</span> <span class="darkblue">no</span> <span class="darkblue">longer</span> <span class="darkblue">be</span> <span class="darkblue">moved</span> <span class="darkblue">to</span> <span class="darkblue">other</span> <span class="darkblue">screens</span>
<span class="darkred">#</span> <span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">capture</span> <span class="darkblue">1</span> <span class="darkblue">iTunes</span>

<span class="darkred">#</span> <span class="teal">Enable</span> <span class="darkblue">border</span> <span class="darkblue">for</span> <span class="darkblue">focused</span> <span class="darkblue">window</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">focused</span><span class="darkred">-</span><span class="darkblue">border</span> <span class="darkblue">disable</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">focused</span><span class="darkred">-</span><span class="darkblue">border</span> <span class="darkblue">size</span> <span class="darkblue">2</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">focused</span><span class="darkred">-</span><span class="darkblue">border</span> <span class="darkblue">color</span> <span class="teal">FFBDD322</span>

<span class="darkred">#</span> <span class="teal">Enable</span> <span class="darkblue">border</span> <span class="darkblue">for</span> <span class="darkblue">marked</span> <span class="darkblue">window</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">marked</span><span class="darkred">-</span><span class="darkblue">border</span> <span class="darkblue">enable</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">marked</span><span class="darkred">-</span><span class="darkblue">border</span> <span class="darkblue">size</span> <span class="darkblue">2</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">marked</span><span class="darkred">-</span><span class="darkblue">border</span> <span class="darkblue">color</span> <span class="teal">FFCC5577</span>

<span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span> <span class="teal">Custom</span> <span class="teal">Keybinds</span> <span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span>

<span class="darkred">#</span> <span class="teal">Quit</span> <span class="teal">Kwm</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">-</span><span class="darkblue">q</span> <span class="darkblue">quit</span>

<span class="darkred">#</span> <span class="teal">Reload</span> <span class="darkblue">configuration</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">r</span> <span class="darkblue">config</span> <span class="darkblue">reload</span>

<span class="darkred">#</span> <span class="teal">Switch</span> <span class="darkblue">windows</span>
<span class="darkblue">kwmc</span> <span class="darkblue">config</span> <span class="darkblue">cycle</span><span class="darkred">-</span><span class="darkblue">focus</span> <span class="darkblue">all</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">left</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">f</span> <span class="darkblue">prev</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">right</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">f</span> <span class="darkblue">next</span>

<span class="darkred">#</span> <span class="teal">Set</span> <span class="darkblue">the</span> <span class="darkblue">split</span> <span class="darkblue">mode</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">h</span> <span class="darkblue">screen</span> <span class="darkred">-</span><span class="darkblue">s</span> <span class="darkblue">horizontal</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">v</span> <span class="darkblue">screen</span> <span class="darkred">-</span><span class="darkblue">s</span> <span class="darkblue">vertical</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">o</span> <span class="darkblue">screen</span> <span class="darkred">-</span><span class="darkblue">s</span> <span class="darkblue">optimal</span>

<span class="darkred">#</span> <span class="teal">Set</span> <span class="teal">Space</span> <span class="teal">Tiling</span> <span class="teal">Mode</span> <span class="teal">To</span> <span class="teal">BSP</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">-</span><span class="darkblue">a</span> <span class="darkblue">space</span> <span class="darkred">-</span><span class="darkblue">t</span> <span class="darkblue">bsp</span>

<span class="darkred">#</span> <span class="teal">Set</span> <span class="teal">Space</span> <span class="teal">Tiling</span> <span class="teal">Mode</span> <span class="teal">To</span> <span class="teal">Monocle</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">-</span><span class="darkblue">s</span> <span class="darkblue">space</span> <span class="darkred">-</span><span class="darkblue">t</span> <span class="darkblue">monocle</span>

<span class="darkred">#</span> <span class="teal">Set</span> <span class="teal">Space</span> <span class="teal">Tiling</span> <span class="teal">Mode</span> <span class="teal">To</span> <span class="teal">Floating</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">-</span><span class="darkblue">d</span> <span class="darkblue">space</span> <span class="darkred">-</span><span class="darkblue">t</span> <span class="darkblue">float</span>

<span class="darkred">#</span> <span class="teal">Rotate</span> <span class="teal">Window</span><span class="darkred">-</span><span class="teal">Tree</span> <span class="teal">By</span> <span class="darkblue">90</span><span class="darkred">*</span> <span class="darkred">(</span><span class="teal">Clockwise</span><span class="darkred">)</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">-</span><span class="darkblue">r</span> <span class="darkblue">tree</span> <span class="darkred">-</span><span class="darkblue">r</span> <span class="darkblue">90</span>

<span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span> <span class="teal">Container</span> <span class="teal">Modifiers</span> <span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span>
<span class="darkred">#</span>
<span class="darkred">#</span> <span class="teal">Modify</span> <span class="teal">Container</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkred">/</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">c</span> <span class="darkblue">split</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkred">,</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">c</span> <span class="darkblue">reduce</span> <span class="darkblue">0.05</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkred">.</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">c</span> <span class="darkblue">expand</span> <span class="darkblue">0.05</span>

<span class="darkred">#</span> <span class="teal">Set</span> <span class="teal">Temporary</span> <span class="teal">Window</span> <span class="teal">Container</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">prefix</span><span class="darkred">-</span><span class="darkblue">s</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">t</span> <span class="darkblue">fullscreen</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">prefix</span><span class="darkred">-</span><span class="darkblue">a</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">t</span> <span class="darkblue">parent</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">space</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">t</span> <span class="darkblue">parent</span>

<span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span> <span class="teal">Window</span> <span class="teal">Movements</span> <span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span>
<span class="darkred">#</span>
<span class="darkred">#</span> <span class="teal">Give</span> <span class="teal">Focus</span> <span class="teal">To</span> <span class="teal">Window</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">left</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">f</span> <span class="darkblue">west</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">right</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">f</span> <span class="darkblue">east</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">down</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">f</span> <span class="darkblue">south</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">up</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">f</span> <span class="darkblue">north</span>

<span class="darkred">#</span> <span class="teal">Move</span> <span class="teal">Focused</span> <span class="teal">Window</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">left</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">s</span> <span class="darkblue">west</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">down</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">s</span> <span class="darkblue">south</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">up</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">s</span> <span class="darkblue">north</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">right</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">s</span> <span class="darkblue">east</span>

<span class="darkred">#</span> <span class="teal">Detach</span> <span class="teal">Focused</span> <span class="teal">Window</span> <span class="teal">And</span> <span class="teal">Reinsert</span> <span class="teal">In</span> <span class="teal">Direction</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">shift</span><span class="darkred">-</span><span class="darkblue">up</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">x</span> <span class="darkblue">north</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">shift</span><span class="darkred">-</span><span class="darkblue">right</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">x</span> <span class="darkblue">east</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">shift</span><span class="darkred">-</span><span class="darkblue">down</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">x</span> <span class="darkblue">south</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">shift</span><span class="darkred">-</span><span class="darkblue">left</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">x</span> <span class="darkblue">west</span>

<span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span> <span class="teal">Operations</span> <span class="darkblue">with</span> <span class="darkblue">marked</span> <span class="darkblue">windows</span> <span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span><span class="darkred">#</span>

<span class="darkred">#</span> <span class="teal">Mark</span> <span class="teal">Window</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">-</span><span class="darkblue">down</span> <span class="darkblue">mark</span> <span class="darkred">-</span><span class="darkblue">w</span> <span class="darkblue">focused</span>

<span class="darkred">#</span> <span class="teal">Swap</span> <span class="teal">With</span> <span class="teal">Marked</span> <span class="teal">Window</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">-</span><span class="darkblue">up</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">s</span> <span class="darkblue">mark</span>

<span class="darkred">#</span> <span class="teal">Detach</span> <span class="teal">Marked</span> <span class="teal">Window</span> <span class="teal">And</span> <span class="teal">Reinsert</span> <span class="teal">At</span> <span class="teal">Focused</span> <span class="teal">Window</span>
<span class="darkblue">kwmc</span> <span class="darkblue">bind</span> <span class="darkblue">cmd</span><span class="darkred">+</span><span class="darkblue">ctrl</span><span class="darkred">+</span><span class="darkblue">alt</span><span class="darkred">-</span><span class="darkblue">down</span> <span class="darkblue">window</span> <span class="darkred">-</span><span class="darkblue">x</span> <span class="darkblue">mark</span>

</pre>

**Comment by chrishoage** [comment]
Might be cool to move this configuration to a gist and start a wiki page on `kwmrc` setups, that way people can add them as they see fit, and browse examples.

**Comment by andreaspada** [comment]
Well, I totally agree but I'm not sure I know how to do that. I'll try...
Anyway, I feel think that users lack a wiki and more real cases 
examples, just to figure out how someone else solve common configuration 
issue and to share tweaks.


Chris Hoage wrote:
>
> Might be cool to move this configuration to a gist and start a wiki 
> page on |kwmrc| setups, that way people can add them as they see fit, 
> and browse examples.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/koekeishiya/kwm/issues/180#issuecomment-187446925>.
>

-- 
   -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Andrea Spada :: Liuteria d'Autore
         www.andreaspada.com

**Comment by andreaspada** [comment]
Done. https://gist.github.com/andreaspada/fb18a51bb30d5315a716

**Comment by cdosborn** [comment]
Why not kick off the wiki for this project.

**Comment by koekeishiya** [comment]
> Why not kick off the wiki for this project.

Guess I can do that. I'll try allow for publci edits, as I do not have the time to write extensive information for some time.

**Comment by koekeishiya** [comment]
The wiki now has a place for this [here](https://github.com/koekeishiya/kwm/wiki/Sample-Configurations).

**Comment by cdosborn** [comment]
@koekeishiya :+1:

**Comment by andreaspada** [comment]
Awesome!

Enviado do meu iPad
