### ISSUE TITLE
Allow users to change the optimal split ratio

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#181]
[Relevant part of the code in tree.cpp](https://github.com/koekeishiya/kwm/blob/838ffc29a95ce39d0331da0b0d230bfc645fc826/kwm/tree.cpp#L349-L352)

```cpp
int GetOptimalSplitMode(tree_node *Node)
{
    return (Node->Container.Width / Node->Container.Height) >= 1.618 ? 1 : 2;
}
```

I'd very much like to change the default ratio, since my current window padding and gaps settings make it so my first split is a vertical split, but I'd prefer it to be a horizontal split, since I'm only 0.05 off the default optimal split ratio of 1.618 (Golden Ratio).

Edit - An alternative to this would you can set the split more for the nth window on a space, so I could set it to horizontal for n=1 and leave it optimal for all others.

**Comment by koekeishiya** [comment]
See `kwmc config split-ratio value`

**Comment by dominiklohmann** [comment]
> See `kwmc config split-ratio value`

That sets the split ratio where containers get split. My issue is that with my current paddings/gaps settings, the golden splits thinks my first split should be a vertical split, but I want it to be horizontal (only for the first split, after that the golden split ratio is okay).

**Comment by koekeishiya** [comment]
If it is only for the first split, you can do `kwmc window -c split` for now. Will see in the future about making a config setting instead of hardcoding the golden ratio for changing this.
