### ISSUE TITLE
Feature: Increase spacing or padding in all directions with one key binding

### ISSUE THREAD

**Issue by strages** [koekeishiya/kwm#185]
Its possible to increase or decrease these with the following commands/key shortcuts. I would love to be able to do this with 1 key binding in for example `-g increase vertical & horizontal`

```
kwmc bind cmd+ctrl+alt+shift-v space -g increase vertical
kwmc bind cmd+ctrl+alt+shift-b space -g increase horizontal
kwmc bind cmd+ctrl+alt+shift-n space -p increase right
```

**Comment by koekeishiya** [comment]
You can create a shellscript for now, that performs these calls. Then bind the shellscript with `kwmc bind .. sys shellscript.sh`

**Comment by dominiklohmann** [comment]
You can always use `kwmc bind <shortcut> sys <path/to/script>` to have kwm execute a script for you that does multiple kwmc calls.

For example, you can add the following to your `~/.kwm/kwmrc`:
```
kwmc bind cmd+ctrl+alt+shift-v sys ~/.kwm/scripts/increase-padding`
```

Then add the file `~.kwm/scripts/increase-padding` (and don't forget to `chmod +x` it):
```sh
#! /bin/sh

# Needed if kwm is managed by launchctl
kwmc=/usr/local/bin/kwmc

kwmc space -p increase left
kwmc space -p increase right
kwmc space -p increase top
kwmc space -p increase bottom
```

**Comment by chrishoage** [comment]
What would be nice is the ability to set specific values while kwm is running. Either by `kwmc config padding` allowing the values to be set after kwm has started, or adding a new `kwmc space -p set left 10` set of commands.

**Comment by strages** [comment]
thanks for the reactions!

got the following commands now

```
kwmc bind cmd+ctrl+alt+shift-v sys ~/.kwm/scripts/increase-container-gaps
kwmc bind cmd+ctrl+alt+shift-b sys ~/.kwm/scripts/decrease-container-gaps
kwmc bind cmd+ctrl+alt+shift-n sys ~/.kwm/scripts/increase-padding
kwmc bind cmd+ctrl+alt+shift-m sys ~/.kwm/scripts/decrease-padding
```

chmod +x them.. 

example file increase-padding:
```

#! /bin/sh

# Needed if kwm is managed by launchctl
kwmc=/usr/local/bin/kwmc

kwmc space -p increase left
kwmc space -p increase right
kwmc space -p increase top
kwmc space -p increase bottom
```


none of them are working... installed with brew btw!

**Comment by dominiklohmann** [comment]
If you execute the script from the commandline, does it do what you want?

**Comment by strages** [comment]
yes, it does execute correctly if I do it that way

On Fri, Feb 26, 2016 at 12:03 PM Dominik Lohmann <notifications@github.com>
wrote:

> If you execute the script from the commandline, does it do what you want?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koekeishiya/kwm/issues/185#issuecomment-189222436>.
>
-- 
--

*Dimitrie Hoekstra, UI & Interaction Designer*
dhesign.com  | dimitriehoekstra@gmail.com | LinkedIn
<https://www.linkedin.com/in/dimitrieh> | Twitter
<https://twitter.com/strages33/>

**Comment by dominiklohmann** [comment]
Are you sure that you've given the path the correct script to kwmrc? Because when managed by launchctl, it probably isn't in your path.

**Comment by strages** [comment]
There is an alias to kwmc at that location created by brew...

On Fri, Feb 26, 2016, 12:10 PM Dominik Lohmann <notifications@github.com>
wrote:

> Are you sure that you've given the path the correct script to kwmrc?
> Because when managed by launchctl, it probably isn't in your path.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koekeishiya/kwm/issues/185#issuecomment-189224418>.
>
-- 
--

*Dimitrie Hoekstra, UI & Interaction Designer*
dhesign.com  | dimitriehoekstra@gmail.com | LinkedIn
<https://www.linkedin.com/in/dimitrieh> | Twitter
<https://twitter.com/strages33/>

**Comment by koekeishiya** [comment]
Has  anyone confirmed that the tilde operator actually expands to your users home directory under launchctl?

**Comment by strages** [comment]
Ha I have no idea what you are talking about:) if I am honest I do not know
if I am using launchctl

On Fri, Feb 26, 2016, 12:18 PM koekeishiya <notifications@github.com> wrote:

> Has anyone confirmed that the tilde operator actually expands to your
> users home directory under launchctl?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koekeishiya/kwm/issues/185#issuecomment-189227333>.
>
-- 
--

*Dimitrie Hoekstra, UI & Interaction Designer*
dhesign.com  | dimitriehoekstra@gmail.com | LinkedIn
<https://www.linkedin.com/in/dimitrieh> | Twitter
<https://twitter.com/strages33/>

**Comment by dominiklohmann** [comment]
He said that you should replace the `kwmc bind ... sys ~/path/to/script` with `kwmc bind ... sys /Users/username/path/to/script` to see if it works.

**Comment by strages** [comment]
Will do in 30 min

On Fri, Feb 26, 2016, 12:32 PM Dominik Lohmann <notifications@github.com>
wrote:

> He said that you should replace the kwmc bind ... sys ~/path/to/script
> with kwmc bind ... sys /Users/username/path/to/script to see if it works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koekeishiya/kwm/issues/185#issuecomment-189232726>.
>
-- 
--

*Dimitrie Hoekstra, UI & Interaction Designer*
dhesign.com  | dimitriehoekstra@gmail.com | LinkedIn
<https://www.linkedin.com/in/dimitrieh> | Twitter
<https://twitter.com/strages33/>

**Comment by strages** [comment]
no doesn't work

**Comment by dominiklohmann** [comment]
Can you show us your kwmrc and your shell script? Because my kwm is managed by launchctl as well (although not installed using homebrew) and using the exact same script it works for me.

**Comment by koekeishiya** [comment]
The script should look like this btw, and not the one posted earlier, assuming you are using bash

```
kwmc=/usr/local/bin/kwmc

$kwmc space -p increase left
$kwmc space -p increase right
$kwmc space -p increase top
$kwmc space -p increase bottom
```

**Comment by strages** [comment]
with the `#! /bin/sh` gone and `$` before the commands it works!

I am on zsh here btw

**Comment by strages** [comment]
just for information my kwmrc:

```
##################
# Golden Section #
##################

# Set default values for screen padding
kwmc config padding top 27
kwmc config padding bottom 5
kwmc config padding left 5
kwmc config padding right 5

# Set default values for container gaps
kwmc config gap vertical 5
kwmc config gap horizontal 5

# Allow Kwm to tile windows
kwmc config tiling enable

# Let Kwm listen for hotkeys
kwmc config hotkeys enable

# Set prefix for Kwms hotkeys
kwmc config prefix ctrl-x

# Prefix is not applied globally
kwmc config prefix-global disable

# Time in seconds, before prefix must be re-activated
kwmc config prefix-timeout 0.75

# Automatically float windows that fail to resize
kwmc config float-non-resizable enable

# Float a window if moved using the mouse
kwmc config dragndrop disable


##### Focus #####
kwmc config focus enable
kwmc config focus mouse-follows enable
kwmc config focus autoraise enable

# Set focus-follows-mouse-mode to autoraise
#kwmc config focus autoraise

# Focus-follows-mouse is temporarily disabled when
# a floating window has focus
#kwmc config focus standby-on-float enable

# The mouse will automatically move to the center
# of the focused window
#kwmc config focus mouse-follows enable

# Allow window focus to wrap-around
kwmc config cycle-focus screen # all | disabled

# Default tiling mode for new spaces
kwmc config space bsp

# Set default container split-ratio
kwmc config split-ratio 0.618

# New splits become the left leaf-node
kwmc config spawn left

# Add custom tiling rules for applications that
# does not get tiled by Kwm by default.
# This is because some applications do not have the
# AXWindowRole and AXStandardWindowSubRole
kwmc config add-role AXDialog iTerm2

# The following command blacklists a specific application
# from Kwms tiling (PS: The app name is case-sensitive)
# If the name consist of multiple words, the command
# looks like: kwmc config float Google Chrome
kwmc config float Sketch
kwmc config float Photoshop
kwmc config float Hearthstone
kwmc config float Cities.app


# The following command captures an application to the
# given screen, if the screen exists. By doing this
# the application can no longer be moved to other screens
# kwmc config capture 1 iTunes

# Enable border for focused window
kwmc config focused-border disable
kwmc config focused-border size 3
kwmc config focused-border color FFCC5577

# Enable border for marked window
kwmc config marked-border enable
kwmc config marked-border size 5
kwmc config marked-border color FFCC5577

####### Custom Keybinds #######

# Quit Kwm
kwmc bind cmd+alt+ctrl+shift-q quit

# Reload configuration
kwmc bind cmd+ctrl+alt+shift-r config reload

# Switch windows
kwmc config cycle-focus screen
kwmc bind cmd+alt+ctrl+shift-` window -f next

# Set the split mode
kwmc bind cmd+alt+ctrl+shift-; screen -s horizontal
kwmc bind cmd+alt+ctrl+shift-' screen -s vertical
kwmc bind cmd+alt+ctrl+shift-\ screen -s optimal

# Set Space Tiling Mode To BSP
kwmc bind cmd+alt+ctrl+shift-1 space -t bsp

# Set Space Tiling Mode To Monocle
kwmc bind cmd+alt+ctrl+shift-2 space -t monocle

# Set Space Tiling Mode To Floating
kwmc bind cmd+alt+ctrl+shift-3 space -t float

# Rotate Window-Tree By 90* (Clockwise)
kwmc bind cmd+alt+ctrl+shift-e tree -r 90

#### Container Modifiers ####
#
# Modify Container
kwmc bind cmd+ctrl+alt+shift-c window -c split
kwmc bind cmd+ctrl+alt+shift-z window -c reduce 0.05
kwmc bind cmd+ctrl+alt+shift-x window -c expand 0.05

# Set Temporary Window Container
kwmc bind cmd+ctrl+alt+shift-g window -t fullscreen
kwmc bind cmd+ctrl+alt+shift-h window -t parent

kwmc bind cmd+ctrl+alt+shift-v sys ~/.kwm/scripts/increase-container-gaps
kwmc bind cmd+ctrl+alt+shift-b sys ~/.kwm/scripts/decrease-container-gaps
kwmc bind cmd+ctrl+alt+shift-n sys ~/.kwm/scripts/increase-padding
kwmc bind cmd+ctrl+alt+shift-m sys ~/.kwm/scripts/decrease-padding

#### Window Movements ####
#
# Give Focus To Window
kwmc bind cmd+ctrl+alt+shift-left window -f west
kwmc bind cmd+ctrl+alt+shift-right window -f east
kwmc bind cmd+ctrl+alt+shift-down window -f south
kwmc bind cmd+ctrl+alt+shift-up window -f north

# Move Focused Window
kwmc bind cmd+alt+ctrl+shift-a window -s west
kwmc bind cmd+alt+ctrl+shift-s window -s south
kwmc bind cmd+alt+ctrl+shift-w window -s north
kwmc bind cmd+alt+ctrl+shift-d window -s east

# Detach Focused Window And Reinsert In Direction
kwmc bind cmd+alt+ctrl+shift-j window -x west
kwmc bind cmd+alt+ctrl+shift-k window -x south
kwmc bind cmd+alt+ctrl+shift-i window -x north
kwmc bind cmd+alt+ctrl+shift-l window -x east

# Move windows between displays
kwmc bind cmd+ctrl+alt+shift-[ screen -m prev
kwmc bind cmd+ctrl+alt+shift-] screen -m next

##### Operations with marked windows #####

# Mark Window
# kwmc bind cmd+ctrl+alt+shift-m mark -w focused

# Swap With Marked Window
# kwmc bind cmd+ctrl+alt+shift-, window -s mark

# Detach Marked Window And Reinsert At Focused Window
# kwmc bind cmd+ctrl+alt+shift-. window -x mark
```

**Comment by dominiklohmann** [comment]
It's working in my scripts without the $ sign because I exported my $PATH for launchctl ages ago and apparently never used the local $kwmc variable...  ¯\\\_(ツ)\_/¯
