### ISSUE TITLE
Feature: Be able to assign screen portions in float-mode

### ISSUE THREAD

**Issue by strages** [koekeishiya/kwm#186]
As kwm is a tiling window manager, this is of course a totally different direction. However I still think it would make a great addition. In floating windows mode with the following command:

`kwmc bind cmd+alt+ctrl+shift-3 space -t float`

It would be great to be able to assign screen portions to focussed windows, similar to functionality as https://www.spectacleapp.com/ . This would make kwm the best of both worlds so to say

**Comment by koekeishiya** [comment]
I don't really see the need for this. It's more or less just the same behaviour as a very simple bsp-tree.

**Comment by strages** [comment]
A usecase for example, would be to show the application to the left half of
the screen. The other part of the screen would be empty and show the desktop

On Fri, Feb 26, 2016 at 11:50 AM koekeishiya <notifications@github.com>
wrote:

> I don't really see the need for this. It's more or less just the same
> behaviour as a very simple bsp-tree.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koekeishiya/kwm/issues/186#issuecomment-189219556>.
>
-- 
--

*Dimitrie Hoekstra, UI & Interaction Designer*
dhesign.com  | dimitriehoekstra@gmail.com | LinkedIn
<https://www.linkedin.com/in/dimitrieh> | Twitter
<https://twitter.com/strages33/>

**Comment by dominiklohmann** [comment]
Couldn't that just be solved by having a way for kwm to create empty pseudo-containers? (And with that, also a way for kwm to close containers, closing/quitting the applications inside them)

**Comment by strages** [comment]
mmh good point... how would we go about that or be able to do it right
now... point is that it would be usefull in float mode

`kwmc bind cmd+alt+ctrl+shift-3 space -t float`

On Fri, Feb 26, 2016 at 12:05 PM Dominik Lohmann <notifications@github.com>
wrote:

> Couldn't that just be solved by having a way for kwm to create empty
> pseudo-containers? (And with that, also a way for kwm to close containers,
> closing/quitting the applications inside them)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koekeishiya/kwm/issues/186#issuecomment-189222865>.
>
-- 
--

*Dimitrie Hoekstra, UI & Interaction Designer*
dhesign.com  | dimitriehoekstra@gmail.com | LinkedIn
<https://www.linkedin.com/in/dimitrieh> | Twitter
<https://twitter.com/strages33/>

**Comment by koekeishiya** [comment]
> Couldn't that just be solved by having a way for kwm to create empty pseudo-containers?

I've already implemented most of the behaviour needed for this earlier, and  this is something that will happen.

**Comment by koekeishiya** [comment]
For managing windows in float mode, I would actually go as far as to recommend just using spectacle, hammerspoon or some other window manager for that. 

The reason I made floating mode within Kwm was basically if I wanted a space that was managed by me (the user) completely manually.

**Comment by koekeishiya** [comment]
> Couldn't that just be solved by having a way for kwm to create empty pseudo-containers?

This has been done now, and you can use the command `kwmc tree -c pseudo` to perform an empty split. If this does not allow for the kind of use you want, I would suggest running spectacle, hammerspoon, or perform the needed changes manually in a Kwm fork.

**Comment by dominiklohmann** [comment]
How do you remove the pseudo containers?

**Comment by koekeishiya** [comment]
> How do you remove the pseudo containers?

For now, open a window and close it.
Need to figure out a logical way to navigate the different pseudo nodes, which I have no idea how should work yet.

**Comment by dominiklohmann** [comment]
You could make it so pressing `cmd+q` while your mouse is in a pseudo container closes it, very much like that would close an application. This would work because you cannot close Finder.app with `cmd+q`.

**Comment by koekeishiya** [comment]
> You could make it so pressing cmd+q while your mouse is in a pseudo container closes it, very much like that would close an application. This would work because you cannot close Finder.app with cmd+q.

The way I see it, there will always be one real container and one potential pseudo container, and so something like `kwmc -c pseudo destroy` would remove the pseudo container associated with the parent of the focused node.

**Comment by koekeishiya** [comment]
Updated commands:
`kwmc tree -c pseudo create` - perform split of focused node and creates pseudo node
`kwmc tree -c pseudo remove` - removes the pseudo-leaf in the same parent as the focused node

**Comment by dominiklohmann** [comment]
I think there's now a need to change 
`kwmc window -c <reduce|expand> <value>`
to 
`kwmc window -c <reduce|expand> <vertical|horizontal> <value>`.

**Comment by koekeishiya** [comment]
> I think there's now a need to change
kwmc window -c <reduce|expand> <value>
to
kwmc window -c <reduce|expand> <vertical|horizontal> <value>.

There is no concept of both vertical or horizontal.
`kwmc window -c <reduce|expand> <value>` is using the split-type of a node and adjusts a % used for the left and the right child. The internal structure is always a binary-tree.

**Comment by koekeishiya** [comment]
> Say you have a window and create 2 pseudo containers on it, how do you change the ratio in more than one direction? I understand that you can destroy the pseudo container, change the ratio, create the other container and change the ratio again, but that doesn't seem to be very intuitive.

You can't. Same way you deal with this issue before pseudo nodes were added.
What you'd do, is open one pseudo container. Adjust the ratio, then open another pseudo container.

This is not because I don't want to have the ability to do so, but rather I have not found a good way to traverse the bsp-trees to allow this behaviour. The reason I do not use mouse-position for it, is that I want to have as much keyboard-only support as possible.

**Comment by matthewdias** [comment]
Would it make things easier if you generated a fake, invisible window in the pseudo container? Might simplify things so that you can close the window with cmd+w as usual, and resize etc. as well.

**Comment by koekeishiya** [comment]
> Would it make things easier if you generated a fake, invisible window in the pseudo container? Might simplify things so that you can close the window with cmd+w as usual, and resize etc. as well.

Resize of pseudo nodes work the same way as resizing with window in the node. Creating an invisible window would not change anything except being able to give it focus, but I would argue that having the pseudo containers not steal focus is a good thing.
