### ISSUE TITLE
kwm doesn't seem to tile borderless iterm windows

### ISSUE THREAD

**Issue by Nolski** [koekeishiya/kwm#187]
To illustrate the issue I'm having I posted a screenshot of overlapping windows that should be tiled.
I'm fairly new to kwm so this may be an issue with how I am using it.
<img width="1440" alt="screen shot 2016-02-25 at 1 28 08 pm" src="https://cloud.githubusercontent.com/assets/2600677/13329737/a21ff026-dbc3-11e5-903e-1621c5c0d9e8.png">

**Comment by EdenSG** [comment]
This is #40 — check the `kwmc config add-role AXDialog iTerm2` line in your kwmc, maybe change the `iTerm2` to `iTerm`?

**Comment by andreaspada** [comment]
In regard this topic, I also have a doubt: If I place that code in my 
kwmrc it tiles also my 'visor' like hotkey iTerm, so... there's a way to 
have untitled iTerm windows be tiled BUT the Hotkey window?

Eden S.-G. wrote:
>
> This is #40 <https://github.com/koekeishiya/kwm/issues/40> — check the 
> |kwmc config add-role AXDialog iTerm2| line in your kwmc, maybe change 
> the |iTerm2| to |iTerm|?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/koekeishiya/kwm/issues/187#issuecomment-189021101>.
>

-- 
   -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Andrea Spada :: Liuteria d'Autore
         www.andreaspada.com

**Comment by Nolski** [comment]
@EdenSG could you further elaborate? My kwmc `~/.kwm/kwmc` is non-existant. I tried creating and re-adding that line but it didn't change anything.

**Comment by EdenSG** [comment]
@Nolski you'll need to make one then. Copy the example one from [here](https://github.com/koekeishiya/kwm/blob/master/examples/kwmrc).

**Comment by Nolski** [comment]
@EdenSG Is that path correct? Even when I created one and ran `kwmc config reload` I didn't notice any change in functionality. I've been looking around for some docs to troubleshoot this but I haven't found any yet.

**Comment by koekeishiya** [comment]
The config file for kwm is: `$HOME/.kwm/kwmrc` (short for 'kwm runcom')
`kwmc` is a tool to configure Kwm during runtime, and is also the prefix-string used in the configuration file to let Kwm know what kind of command is on that line.

**Comment by EdenSG** [comment]
@Nolski You shouldn't notice a change — correct me if I'm wrong, but by default kwm uses the default kwmc file.

**Comment by Nolski** [comment]
@koekeishiya Thanks! Adding `kwmc config add-role AXDialog iTerm2` to my `$HOME/.kwm/kwmrc` solved the issue and opened my eyes to a bunch of the configuration abilities available in kwm. :100:

**Comment by koekeishiya** [comment]
I will hopefully be writing more detailed information on the [wiki](https://github.com/koekeishiya/kwm/wiki) during the weekend

**Comment by kurtismullins** [comment]
I had to use `kwmc config add-role AXUnknown iTerm` -- the *Accessibility Inspector* showed it as *AXUnknown* instead of *AXDialog* (which I tried first). I believe I am using iTerm 1 (it doesn't say iTerm 2)
