### ISSUE TITLE
Incorrect resizing iterm2 window?

### ISSUE THREAD

**Issue by strages** [koekeishiya/kwm#188]
minor issue here, what got my attention while editing the values for padding etc.

kwm doesnt resize the iterm2 window the same as other programs, see image

![image](https://cloud.githubusercontent.com/assets/429659/13352583/7f9675fe-dc8e-11e5-816e-e235007a05fc.png)

*added red lines to clearify*

maybe this has to do with: `kwmc config add-role AXDialog iTerm2`

added both
`kwmc config add-role AXDialog iTerm2`
and
`kwmc config add-role AXDialog iTerm`

to the kwmrc file

Also working with the new iterm2 [version 3](http://iterm2.com/version3.html) with shell integration active

**Comment by koekeishiya** [comment]
I've pretty much had this problem with every single window manager on OSX. As far as I know it is unfixable. It happens to some other applications as well.

**Comment by strages** [comment]
nope doesn't fix. 

minor issue so no worries ;)

apps you know of?

**Comment by koekeishiya** [comment]
> apps you know of?
pretty much all terminal applications I've used on OSX

**Comment by EdenSG** [comment]
I'm pretty sure that's because those terminal apps will only resize to multiples of the line height. If you manually resize them, you'll see them snap so that the window size is an integer multiple of the character size.

**Comment by koekeishiya** [comment]
> I'm pretty sure that's because those terminal apps will only resize to multiples of the line height. If you manually resize them, you'll see them snap so that the window size is an integer multiple of the character size.

This sounds about right. Thanks for clarifying that.

**Comment by matthewdias** [comment]
Workaround for this is to change your terminal's font size, tho this might not be desirable, and won't be consistent when changing split ratios.

**Comment by mbigras** [comment]
For iTerm2 there is a fix for this issue described at:

https://superuser.com/questions/581889/iterm-2-window-resizing

Go to the following menu option:

Preferences - Advanced - Windows - Terminal Windows resize smoothly - Yes
