### ISSUE TITLE
native full screen osx functionality

### ISSUE THREAD

**Issue by strages** [koekeishiya/kwm#189]
Sorry for spamming the issues, last one ;)!

Currently using a native osx shortcut for full screen sizing apps. For the curious ones:
```
# http://hints.macworld.com/article.php?story=20131123074223584
# @ for Command, $ for Shift, ~ for Alt and ^ for Ctrl
defaults write -g NSUserKeyEquivalents '{
"Enter Full Screen"="@~^$f";
"Exit Full Screen"="@~^$f";
}'
```

It would be great to be able to do this natively with a shortcut from kwm. However thats the minor point of this issue. 

The big point of functionality of what I would like to discuss is the possibility of when an app is in native full screen functionality, to have it splitscreen (as of osx 10.11) with another application.

**Comment by koekeishiya** [comment]
I never use the OSX fullscreen / splitscreen functionality, so this is not something that I'm gonna spend time on personally, as there are so many other things I need to be working on.

I'm sure that there are other people who would like Kwm to interact better with the navtive OSX windowing capabilities, and if any of you want to try and make this happen, feel free to mess around with the source code and submit a pull request.

**Comment by matthewdias** [comment]
You can achieve this with [BetterTouchTool](https://www.boastr.net/).

**Comment by braham-snyder** [comment]
just so those searching can find this topic faster, Apple's name for the feature is split view
