### ISSUE TITLE
kwm sometimes crash when creating or destroying a Chrome Incongnetio window

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#190]
After pulling today, kwm has started to crash _sometimes_ crashes when creating and destroying a Chrome Incognito window and only an incognito window (as far as I can tell). I tried opening and closing a regular Chrome window, iTerm windows, and Sublime Text windows, and none of them had this behavior. 

It does not happen _every_ time, but open and close an Incognito window enough times it will crash kwm

**Comment by koekeishiya** [comment]
I had this happen to me with iTerm windows after the recent changes. I was under the impression that I did fix it.

Another reason why I dislike using the OSX notifications..

**Comment by chrishoage** [comment]
You may have fixed it with iTerm, i was not able to get it to happen with that application. 

As far as I can tell it's specific to a Chrome Incognito window.

**Comment by koekeishiya** [comment]
I can't reproduce with Chrome Incognito either. Opened/closed about 30 incognito windows.
Are you running a debug build or?

**Comment by chrishoage** [comment]
Welp, I feel dumb. Restarted Chrome (hadn't previously) and all is well. 

Sorry!

**Comment by koekeishiya** [comment]
Aight great. Do open another issue if you find that Kwm seems to crash after todays pull. As mentioned, I did have some issues after I started using the new notifications, but I believe them to be fixed.
