### ISSUE TITLE
kwm config argument and kwmrc folder options

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#191]
After https://github.com/koekeishiya/kwm/commit/241bfcc2ef8ecccc00b3dbd8b73c30d3686783f2 I had a thought: 

Could we have an argument added to `kwm` that specified the `kwmrc` location, and then inside `kwmrc` be allowed to either set the `.kwm` path - or to be more granular - any locations for features, such as `layout` or `scripts` etc...

What this might look like

`kwm -c | --config /path/home/.kwmrc` 

This would allow for customization of how kwm is laid out on the filesystem. 

This is a pretty low priority ticket, but wanted to start discussion on it and track it.

**Comment by koekeishiya** [comment]
`kwm -c /path/to/kwmrc` and `kwm --config /path/to/kwmrc` are now available.

The following directories can be set through the config file:
```
kwm_home ~/.kwm
kwm_layouts ~/.kwm/layouts
kwm_include ~/.kwm
```
The above is what Kwm is hardcoded to by default, if that specific setting has not been set in the config file.

**Comment by maletor** [comment]
Maybe the new version will use XDG style config path lookup? Not that Mac has systemd, but nevertheless.

**Comment by qguv** [comment]
Agreed. XDG_CONFIG_HOME path lookup by default (`~/.config/kwm/`) would be nice to have. The XDG standard doesn't require systemd.
