### ISSUE TITLE
Applications that are quit and not on focused screen are not recognized by kwm

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#192]
This is some seriously inexplicable behavior: Firefox and iTunes will not open up on the display I have focused, instead they open on my 2nd display, while stealing focus with out kwm knowing about it. 

```
Local Daemon is now running..
DisplayID 441231622 has index 0
DisplayID 69733314 has index 1
CreateWindowNodeTree() Create Space 3
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
SetWindowDimensions()
SetWindowDimensions()
SetWindowDimensions()
CREATE NOTIFICATIONS
SetWindowRefFocus() Focused Window: zsh 20,44
window id window-2
ShouldBSPTreeUpdate() Add Window
AddWindowToBSPTree() Create pair of leafs
IsWindowOnActiveSpace() window found
SetWindowDimensions()
SetWindowDimensions()
SetWindowRefFocus() Focused Window: Shell — 100✕25 977,44
CREATE NOTIFICATIONS
SetWindowRefFocus() Focused Window: New Issue · koekeishiya/kwm 20,1077
CREATE NOTIFICATIONS
SetWindowRefFocus() Focused Window: zsh 977,44
CREATE NOTIFICATIONS
SetWindowRefFocus() Focused Window: New Issue · koekeishiya/kwm 20,1077
CREATE NOTIFICATIONS
SetWindowRefFocus() Focused Window: zsh 977,44
CREATE NOTIFICATIONS
SetWindowRefFocus() Focused Window: New Issue · koekeishiya/kwm 20,1077
CREATE NOTIFICATIONS
SetWindowRefFocus() Focused Window: kwm 22,44
```

There are no create notifications for these applications even though I opened them in between changing focus in the log. 

If I give focus using the mouse or keyboard to the other display it recognizes the window. Kwm appears to not notice these applications for some reason, and also not notice that focus has been lost. 

I have removed all `kwmc capture` commands, restarted kwm, restarted my computer, and still this issue remains. 

The only applications I have found so far that have this behavior is iTunes and Firefox. 

Firefox developer edition even works, but not regular Firefox. 

Let me know if there is any more data I can get for you. 

Edit:
One very strange thing I have noticed is this appears to be applications that I have at one time `kwmc screen -m 1` at one point in time. Not sure if Applications remember last location or something.

**Comment by chrishoage** [comment]
Actually, on further investigation I don't think `kwmc config capture` is working at all. At least not as far as I can tell.

**Comment by koekeishiya** [comment]
`kwmc config capture` could indeed be broken after all the internal changes recently, will investigate.

Regarding the issue at hand, I don't think this is something in particular to do with Kwm. OSX always stores and reopens applications at a "previous location", unless the application has some setting to explicitly disable this.

**Comment by chrishoage** [comment]
> OSX always stores and reopens applications at a "previous location"

I now how proper steps to repo, and this has nothing to do with iTunes or Firefox. 

1. Open any application.
2. Send open window from that application to another screen.
3. Focus that screen, and that window. 
4. Quit the app while on that screen. 
5. Change focus back to the original screen. 
6. Open application again. 

Expected Results: Window gets created in the focused container
Actual Results: Window gets created on original screen, entirely ignored by KWM. 

Application / window must be manually focused in order for kwm to recognize window. 

If Application / window is moved back to original screen and quit, it works as expected. 

KWM appears to not be able to handle an application opening on a screen it didn't expect (not the focused screen)

**Comment by koekeishiya** [comment]
> KWM appears to not be able to handle an application opening on a screen it didn't expect (not the focused screen) 

This is correct. Not entirely sure how to handle this yet.
Kwm does recognize it spawning, but ignores it as it is on a different screen. This is to make sure that it does not interfere with the windows that are supposed to be tiled on that screen.

What I have been thinking of doing, is the following:
If Kwm detects a window that is not on its current screen, check if it is either a) a floating window, or b) already tiled on a different screen.

If neither of these are true, tile it on the screen that has focus.

**Comment by chrishoage** [comment]
That sounds pretty reasonable to me. Another potential solution (no idea if the APIs allow for it though) is to watch for an application launching vs a window launching. If its an application launching there should be now windows for it, and therefore shouldn't be tiled anywhere.

**Comment by koekeishiya** [comment]
> That sounds pretty reasonable to me. Another potential solution (no idea if the APIs allow for it though) is to watch for an application launching 

That is indeed possible, does the issue in question only occurr on actual application launch and not on separate windows?

I recall having this issue with finder multilpe times, and it basically makes me not wanna use my external monitors..

**Comment by chrishoage** [comment]
> I recall having this issue with finder multiple times, and it basically makes me not wanna use my external monitors..

I have tested it with finder right now, and I don't experience that issue (since finder is "always" running). 

I only appear to have this issue with a "fresh" application (one that wasn't running previously)

**Comment by koekeishiya** [comment]
> not entirely sure what issue you were having with Finder windows.

Uh, say I am on my main monitor. I move the mouse to my external monitor, which is empty at the moment. I use spotlight to open finder. The window spawns on my other display (same issue as you mention above). This can be mitigated by performing a left-mouse click on the monitor, before doing the spotlight -> open finder, which is also the reason why I have some left-click code left in Kwm still. (I want to get rid of all that completly, eventually)

**Comment by chrishoage** [comment]
So strange, using the steps you describe (expect I used Alfred to open finder) Finder opens on the display that has focus. Going to try with Spotlight to see if there is a difference in behavior

**Comment by chrishoage** [comment]
Ah, it appears to be an issue with opening a specific folder. If I use Spotlight or Finder to launch a window (just `Finder`) it opens correctly. If I use those tools to pick a specific folder, the issue described in this ticket occurs

**Comment by koekeishiya** [comment]
> If Kwm detects a window that is not on its current screen, check if it is either a) a floating window, or b) already tiled on a different screen.

> If neither of these are true, tile it on the screen that has focus.

I'll probably implement this system, as it will deal with all the cases.

**Comment by koekeishiya** [comment]
I have been able to implement the behaviour I described above. Hopefully this will work "flawlessly" so that I can actually start using multiple monitors again. This exact issue has been annoying me for like 4months now.

Will push the commit soon.

**Comment by koekeishiya** [comment]
..So focus between screens seems to be really broken at the moment, and the above commit only seems to work from external display -> primary display.. Not sure what that is about..

**Comment by koekeishiya** [comment]
So the behaviour this issue is for, should now be fixed.

I did notice some issues with the `kwmc screen -f ..` command, however it is not something that makes Kwm crash, it just sometimes stops working after using `kwmc screen -m ..` for no apparent reason. Using the mouse works fine as expected even in this case.
