### ISSUE TITLE
Feature Request: kwm-overlay for all windows

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#193]
E.g. add the following to kwmrc 

```
# Enable border for (un-)focused window
kwmc config border [enable,disable]
kwmc config border size <width>
kwmc config border color <color>
```

This border should be default for every window, but overridden by focused-border, marked-border and prefix-border.

**Comment by koekeishiya** [comment]
While this would be a good looking feature, I suspect it woud require more reasources than I find feasible. It would (at least with the current way kwm-overlay works) require a separate running instance of the kwm-overlay application for every single window you have open and want a border on.

**Comment by dominiklohmann** [comment]
Considering kwm-overlays resource usage is close to 0, that'd be a non-issue imo.

**Comment by chrishoage** [comment]
I kind of agree, a separate `kwm-overlay` process for each window seems excessive. In my opinion this should probably wait until the overlay is baked into kwm itself

**Comment by koekeishiya** [comment]
I've come to the conclusion that this is not something I feel is worth doing. It raises the need to handle a lot of edge-cases, especially when it comes to windows on different monitors, and increases the complexity of Kwm by a very very huge margin.

I find that it is simply not worth experimenting with it.
