### ISSUE TITLE
Issue: key binding prefix plus modifier

### ISSUE THREAD

**Issue by andreaspada** [koekeishiya/kwm#195]
Struggling with some prefix plus mod combination. I'd like to have some key binding as:

...
kwmc bind prefix+cmd-3 some script here
kwmc bind prefix+cmd-4 another script here
kwmc bind prefix+cmd+alt-3 a really cool special script here
...

Although, it do not works, or I cannot understand how it is supposed to work.
Any advice on that?

**Comment by andreaspada** [comment]
Ok, I got it working with prefix+shift-somekey, as per examples, but it seem to not working if use another modifier. It is supposed to be this way?

**Comment by koekeishiya** [comment]
Works fine for me for every modifier. Make sure to adjust `kwmc config prefix-timeout` to fit your needs

**Comment by andreaspada** [comment]
Thanks, I'll give it a try. Sorry to bother with it!
