### ISSUE TITLE
Issue: No matter what I do, cannot disable focus follow mouse...

### ISSUE THREAD

**Issue by andreaspada** [koekeishiya/kwm#199]
Tried all the possible configuration. I simply cannot get any visible difference in my mouse behaviour. I really do not like focus-mouse-follow...

Using 10.11.3, manually compiled kwm from github synced with master - 1.1.3.

**Comment by chrishoage** [comment]
`kwmc config focus disabled` in my `kwmrc` works just fine for me. 

What settings are you using?

**Comment by andreaspada** [comment]
Started with `kwmc config focus disable`, of course. 
Then: 
`kwmc config focus disable`
`kwmc config focus mouse-follows disable`.
Then:
`kwmc config focus disable`
`kwmc config focus mouse-follows disable`
`kwmc config focus autoraise disable`.
Then: 
`kwmc config focus disable`
`kwmc config focus mouse-follows disable`
`kwmc config focus autoraise disable`
`kwmc config focus standby-on-float enable`...

No one seems to change the default behaviour.

**Comment by chrishoage** [comment]
So, it's a little inconstant (maybe @koekeishiya can help with that problem) but the option is `disabled` not `disable` 

Placing `kwmc config focus disabled` in my `kwmrc` file then running `kwmc config reload` works as expected.

**Comment by andreaspada** [comment]
Gotcha! I need to use also `kwmc config focus toggle`, which is strange... but, it's working. Although, do not work with iTerm windows, which continue to refuse to cooperate (they have focus follow disabled!).

**Comment by andreaspada** [comment]
Wow... you said `disabled`? Not `disable`? I'm feeling like an ameba right now... what a dummy!!!

**Comment by andreaspada** [comment]
Well, but even is put `disabled` and remove my `... toggle` line, it do not work. So?

**Comment by chrishoage** [comment]
What are you doing after your make this change in your `kwmrc`? Are you resetting the config or restarting kwm?

**Comment by andreaspada** [comment]
Resetting... but if I restart it, it work. Sorry to bother you. It's working perfectly now. Awesome!

**Comment by chrishoage** [comment]
As I mentioned previously, changing that setting and using `kwmc config reload` functions just fine for me. 

I'd need to know what you were doing when resetting your config to understand why it wasn't working. 

Good to hear that it is now working for you! 

I don't understand what you meant by "not work with iTerm windows". Can you describe your issue in a bit more detail please?

**Comment by koekeishiya** [comment]
> So, it's a little inconstant (maybe @koekeishiya can help with that problem) but the option is disabled not disable

I'll fix up the commands in the near future.
