### ISSUE TITLE
Image for README.md

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#2]
<img width="1920" alt="screen shot 2015-11-11 at 23 02 35" src="https://cloud.githubusercontent.com/assets/6175959/11104379/a4271a1e-88c8-11e5-805e-5d3e0e83d267.png">

**Comment by peteyy** [comment]
@koekeishiya How did you achieve such harmony with your terminal and vim theme? Which one is that? Looks gorgeous

**Comment by koekeishiya** [comment]
I made my own vim / terminal theme inspired by the colors from https://github.com/morhetz/gruvbox  
[iterm&vim.zip](https://github.com/koekeishiya/kwm/files/110652/iterm.vim.zip)

**Comment by peteyy** [comment]
Thanks a lot! Also one more thing what kind of duo pane file manager is that? :)

**Comment by koekeishiya** [comment]
The file manager is vifm, the irc is weechat and the music player is cmus (if screenshot 4), I usually use https://github.com/koekeishiya/ytd which I wrote, that uses youtube tho.

**Comment by cdosborn** [comment]
@koekeishiya Any resources for disabling window decoration on Terminal.app?

**Comment by chrishoage** [comment]
I use the iTerm2 Beta build which has an option to remove the window title. 
<img width="290" alt="screen shot 2016-02-14 at 1 23 14 pm" src="https://cloud.githubusercontent.com/assets/1056886/13036511/2047b604-d31e-11e5-9d78-d7c89453ed5f.png">

**Comment by koekeishiya** [comment]
I use this patched version of iTerm2: https://github.com/jaredculp/iterm2-borderless-padding

**Comment by leothelocust** [comment]
What firefox theme is that in the first screenshot @koekeishiya?

**Comment by koekeishiya** [comment]
https://gist.github.com/koekeishiya/8a4299a7707a2b19edc6

**Comment by cHoco** [comment]
To remove window decoration from Terminal.app you can checkout my SIMBL plugin. I'm in love with Terminal.app text rendering and unable to switch to iTerm so if anyone has similar need here's the link to the project: https://github.com/cHoco/noTitleBar-Terminal 

I'd like to add support for a padding option like the patch below, but from a first look it seems to be quite hard :(

**Comment by koekeishiya** [comment]
> I'm in love with Terminal.app text rendering and unable to switch to iTerm 

I'm fairly certain you can get the same font-rendering on iTerm2.
There is an option under Profiles -> Text -> "use thin strokes for anti-aliased text" that you have to enable. Unless my eyesight is really terrible, it does seem to look the same for me.

**Comment by cHoco** [comment]
Yeah, once you notice it you're fu**ed XD 
I spent so much time writing plugins for Terminal.app to add features because of the, in my opinion, subpar rendering and speed of iTerm. Speed seems to have been fixed in latest nightlies, but before I measured a difference of 30-40ms. Since speed got fixed I should probably open an issue about the rendering differences, the author is a really great guy.

**Comment by dominiklohmann** [comment]
The font rendering issues of iTerm should be fixed when 3.1 hits, according to these issues on their bug tracker. The developer wants to change from his own solution to NSAttributedString and the likes, which means there shouldn't be much of a difference in rendering between Terminal and iTerm2 as soon as that is implemented.
- [Feature Request: Support for Ligatures](https://gitlab.com/gnachman/iterm2/issues/3568)
- [Performance of displaying UTF-8 characters](https://gitlab.com/gnachman/iterm2/issues/3994)
- [Possible text rendering issue using 'spark'](https://gitlab.com/gnachman/iterm2/issues/4152)

It's mostly the ligature font support that holds me back from using iTerm2 right now.

**Comment by ranranking** [comment]
excuse me, how to have similar menu bar in the screenshot? In addition, do you have video player recommendations?

**Comment by koekeishiya** [comment]
For the menubar, see https://github.com/herrbischoff/nerdbar.widget
As for video player, I personally use [mpv](https://mpv.io/)

**Comment by ranranking** [comment]
Thank you very much

**Comment by paradox460** [comment]
How do you handle mpv's fullscreen mode?

**Comment by koekeishiya** [comment]
> How do you handle mpv's fullscreen mode?

I don't use mpv in fullscreen mode, but rather have a monocle space with 0 padding that I use. 

>  Also, how did you get the custom window trim for mpv?

Not sure what you mean by this, I don't have mpv open in any of the above screenshots.
Only thing I put in my mpv config so far is `no-border` and some custom cache value.

**Comment by paradox460** [comment]
![mpv](https://cloud.githubusercontent.com/assets/168193/14293738/b5ba1cbe-fb22-11e5-97c8-ae93ec4f65d2.png)

Isn't this MPV?

**Comment by paradox460** [comment]
![mpv](https://cloud.githubusercontent.com/assets/168193/14293773/da65635c-fb22-11e5-8433-ea1db076493b.png)
Isn't this MPV?

**Comment by koekeishiya** [comment]
> Isn't this MPV?

That's just a firefox window

**Comment by paradox460** [comment]
Oh haha, thank you

**Comment by knightjp** [comment]
Was looking for a tiling window manager for Mac OS X. Current using Moom. I'm not a programmer. But I would how do I get this working on my mac.

**Comment by knightjp** [comment]
I'm currently using Moom at the moment as the window manager. How does this work? Does this Slate or Phoenix?

**Comment by knightjp** [comment]
This window manager looks awesome. How does it work? I'm currently using Moom at the moment.

**Comment by koekeishiya** [comment]
Just follow the `installation` and `configuration` steps listed in the README.

**Comment by AhmedAA** [comment]
Do you have a patched edition of your powerline theme for firefox? It seems a little broken with the newest versions.
Most appreciated :)

**Comment by koekeishiya** [comment]
> Do you have a patched edition of your powerline theme for firefox? It seems a little broken with the newest versions.
Most appreciated :)

I have not experienced any problems with the version I am using.
The gist should be up to date as well.

**Comment by mouthwash** [comment]
how is it you managed to hide titlebars? I know its a built in feature on iterm2, but how did you do it system wide?

**Comment by vanillasoap** [comment]
Very nice, could you paste the code for your bash prompt? `export PS1="xxxxxxxx"`

**Comment by koekeishiya** [comment]
> Very nice, could you paste the code for your bash prompt? export PS1="xxxxxxxx"

```
export PS1="$(tput setaf 1)┌[$(tput sgr0)\u:$(tput setaf 1):\W$(tput setaf 4)\`parse_git_branch\`$(tput setaf 1)\n└┤\[$(tput sgr0)\][\A] ➜  \[$(tput sgr0)\]"
```

**Comment by koekeishiya** [comment]
> how is it you managed to hide titlebars? I know its a built in feature on iterm2, but how did you do it system wide? For example i see those (what im assuming to be firefox) windows with no titlebars. Is it a CSS or is there a hack to do it? 

I have not hidden them system wide, but rather use different applications that all allow me to do this.

**Comment by phuongtailtranminh** [comment]
How did you change the border of terminal?

**Comment by phuongtailtranminh** [comment]
How to fix missing icon issue at the top bar?

<img width="1440" alt="screen shot 2016-10-08 at 2 53 25 pm" src="https://cloud.githubusercontent.com/assets/12473996/19211464/40d8254e-8d67-11e6-9e94-562de10afc93.png">

**Comment by cjbischoff** [comment]
Where did you get the background image with the city/landscape
![image](https://cloud.githubusercontent.com/assets/126409/19604788/06a19a38-9774-11e6-9871-6d1c317e432c.png)

**Comment by koekeishiya** [comment]
I use [wallhaven](https://alpha.wallhaven.cc/) to find my wallpapers. Usually searching for `minimalism`.
