### ISSUE TITLE
Notifications now always sent

### ISSUE THREAD

**Issue by cHoco** [koekeishiya/kwm#200]
Notification setup in `notifications.cpp` aren't always fired. I thought that maybe this was a OS X bug but after investigating a bit I'm pretty sure that this is fixable in kwm in someway, since other apps that use a similar systems get the same notifications.

I personally think it is a focus issue. Here's the step to reproduce it reliably with Safari in the dock.

1- With kwm enabled and no window open, open Safari and close the window (not the application)
2- Click Safari icon and a new window should open.
3- Add a new tab, window should resize but overlay border shouldn't (notification isn't being sent)
4- Open another app, for example finder
5- Move back to Safari, try adding and removing a tab, window will resize and overlay will follow (notification are being sent)

**Comment by koekeishiya** [comment]
Running in debug mode, I have confirmed that the following code is executed when I expect it to, for the correct process, yet notifications do not seem to register. 

```
AXObserverAddNotification(KWMFocus.Observer, KWMFocus.Application, kAXWindowMiniaturizedNotification, NULL);
AXObserverAddNotification(KWMFocus.Observer, KWMFocus.Application, kAXWindowMovedNotification, NULL);
AXObserverAddNotification(KWMFocus.Observer, KWMFocus.Application, kAXWindowResizedNotification, NULL);
AXObserverAddNotification(KWMFocus.Observer, KWMFocus.Application, kAXTitleChangedNotification, NULL);
CFRunLoopAddSource(CFRunLoopGetCurrent(), AXObserverGetRunLoopSource(KWMFocus.Observer), kCFRunLoopDefaultMode);
```

**Comment by koekeishiya** [comment]
Well that was a stupid mistake on my part..... Should be fixed now.

**Comment by cHoco** [comment]
Wow nice, seems fixed here :) great work :+1:
