### ISSUE TITLE
Focus-follows-mouse disabled pulls me away from empty space

### ISSUE THREAD

**Issue by oetting** [koekeishiya/kwm#204]
With focus-follows-mouse disabled i cannot move to an empty space, if I have a window in the previous space focused. 

It might be that kwm will use FocusWindowOfOSX to focus the window of the previous space, and there fore pull me back to that space.

I have not been looking at the code for the updated focus logic, but maybe FocusWindowOfOSX is no longer needed? Maybe It looks like osx will remember the focus on a space, and kwm will detect that focus.

**Comment by koekeishiya** [comment]
> Maybe It looks like osx will remember the focus on a space, and kwm will detect that focus.

That is exactly what FocusWindowOfOSX is doing.

**Comment by andreaspada** [comment]
Same behaviour here, even with focus and focus follow-mouse enabled. Tried with the default config and it did not fix. I only can stay on a new space if I let my iTerm top pinned window opened...

**Comment by oetting** [comment]
I think what happens is that FocusWindowOfOSX ends up focusing a window in the previous space. 

What I am trying to say is that it looks like that FocusWindowOfOSX is not needed now that KWM notices the current focus when changing to a space.
