### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by theobarberbany** [koekeishiya/kwm#206]
I can't seem to get any keyboard shortcuts working. With and without the prefix (default, ctrl+x) ?

**Comment by dominiklohmann** [comment]
- How did you install kwm? What version are you running?
- Are you sure that kwm has the necessary Accessibility permissions?
- What is in your ~/.kwm/kwmrc?

**Comment by theobarberbany** [comment]
I installed using brew, my ~/.kwm/kwmrc is as follows:

`# This is a sample config for Kwm
# The commands listed here can be of
# two types.
#
# Commands prefixed with 'kwmc' will call
# local functions corresponding to the
# kwmc syntax.
#
# To run a system command, use the prefix
# 'sys' and then the requested command
# e.g 'sys mvim' would open macvim

# Read file and execute commands as
# if they were written inside kwmrc.
#
# include filename
#
# e.g: bind-commands in a separate file called 'binds'
# include binds

# Set default values for screen padding
kwmc config padding top 40
kwmc config padding bottom 20
kwmc config padding left 20
kwmc config padding right 20

# Set default values for container gaps
kwmc config gap vertical 15
kwmc config gap horizontal 15

# Allow Kwm to tile windows
kwmc config tiling enable

# Let Kwm listen for hotkeys
kwmc config hotkeys enable

# Set prefix for Kwms hotkeys
kwmc config prefix ctrl-x

# Prefix is applied globally
kwmc config prefix-global enable

# Time in seconds, before prefix must be re-activated
kwmc config prefix-timeout 0.75

# Automatically float windows that fail to resize
kwmc config float-non-resizable enable

# Float a window if moved using the mouse
kwmc config dragndrop disable

# Set focus-follows-mouse-mode to autoraise
kwmc config focus autoraise

# Focus-follows-mouse is temporarily disabled when
# a floating window has focus
kwmc config focus standby-on-float enable

# The mouse will automatically move to the center
# of the focused window
kwmc config focus mouse-follows enable

# Allow window focus to wrap-around
kwmc config cycle-focus screen # all | disabled

# Default tiling mode for new spaces
kwmc config space bsp

# Override default tiling mode for given monitors
# kwmc config screen 0 bsp
# kwmc config screen 1 monocle

# Set default container split-ratio
kwmc config split-ratio 0.5

# New splits become the left leaf-node
kwmc config spawn left

# Add custom tiling rules for applications that
# does not get tiled by Kwm by default.
# This is because some applications do not have the
# AXWindowRole and AXStandardWindowSubRole
kwmc config add-role AXDialog iTerm2

# The following command blacklists a specific application
# from Kwms tiling (PS: The app name is case-sensitive)
# If the name consist of multiple words, the command
# looks like: kwmc config float Google Chrome
kwmc config float Steam
kwmc config float Photoshop
kwmc config float Hacker Menu

# The following command captures an application to the
# given screen, if the screen exists. By doing this
# the application can no longer be moved to other screens
# kwmc config capture 1 iTunes

# Enable border for focused window
kwmc config focused-border enable
kwmc config focused-border size 5
kwmc config focused-border color FFBDD322

# Enable border for marked window
kwmc config marked-border enable
kwmc config marked-border size 5
kwmc config marked-border color FFCC5577

########  Default Keybinds ########

# Quit Kwm
kwmc bind cmd+alt+ctrl-q quit

# Launch iTerm2
kwmc bind cmd-return sys open -na /Applications/iTerm2.app

# Toggle Focus Autoraise
kwmc bind cmd+alt+ctrl-t config focus toggle

# Set Space Tiling Mode To BSP
kwmc bind cmd+ctrl-a space -t bsp

# Set Space Tiling Mode To Monocle
kwmc bind cmd+ctrl-s space -t monocle

# Set Space Tiling Mode To Floating
kwmc bind cmd+ctrl-d space -t float

# Rotate Window-Tree By 90* (Clockwise)
kwmc bind cmd+ctrl-r tree -r 90

# Modify Container
kwmc bind prefix-s window -c split
kwmc bind prefix-h window -c reduce 0.05
kwmc bind prefix-l window -c expand 0.05

# Set Temporary Window Container
kwmc bind prefix-f window -t fullscreen
kwmc bind prefix-p window -t parent
kwmc bind prefix-w window -t float

# Mark Window
kwmc bind cmd+alt+ctrl-m mark -w focused
kwmc bind cmd+alt+ctrl-h mark -w west wrap
kwmc bind cmd+alt+ctrl-l mark -w east wrap
kwmc bind cmd+alt+ctrl-j mark -w south wrap
kwmc bind cmd+alt+ctrl-k mark -w north wrap

# Give Focus To Window
kwmc bind cmd+alt-h window -f west
kwmc bind cmd+alt-l window -f east
kwmc bind cmd+alt-j window -f south
kwmc bind cmd+alt-k window -f north

# Give Focus To Screen
kwmc bind cmd+alt-1 screen -f 0
kwmc bind cmd+alt-2 screen -f 1
kwmc bind cmd+alt-3 screen -f 2

# Move Focused Window
kwmc bind ctrl+alt-h window -s west
kwmc bind ctrl+alt-j window -s south
kwmc bind ctrl+alt-k window -s north
kwmc bind ctrl+alt-l window -s east

# Swap With Marked Window
kwmc bind ctrl+alt-m window -s mark

# Detach Focused Window And Reinsert In Direction
kwmc bind ctrl+shift-k window -x north
kwmc bind ctrl+shift-l window -x east
kwmc bind ctrl+shift-j window -x south
kwmc bind ctrl+shift-h window -x west

# Detach Marked Window And Reinsert At Focused Window
kwmc bind ctrl+shift-x window -x mark

# Move Focused Window To Screen
kwmc bind ctrl+alt-1 screen -m 0
kwmc bind ctrl+alt-2 screen -m 1
kwmc bind ctrl+alt-3 screen -m 2

# Increase Container Gaps
kwmc bind prefix-x space -g increase horizontal
kwmc bind prefix-y space -g increase vertical

# Decrease Container Gaps
kwmc bind prefix+shift-x space -g decrease horizontal
kwmc bind prefix+shift-y space -g decrease vertical

# Increase Screen Padding
kwmc bind prefix-left space -p increase left
kwmc bind prefix-right space -p increase right
kwmc bind prefix-up space -p increase top
kwmc bind prefix-down space -p increase bottom

# Decrease Screen Padding
kwmc bind prefix+shift-left space -p decrease left
kwmc bind prefix+shift-right space -p decrease right
kwmc bind prefix+shift-up space -p decrease top
kwmc bind prefix+shift-down space -p decrease bottom
`

my version of KWM is 

`homebrew/binary/kwm: stable 1.1.2
Tiling window manager with focus follows mouse for OSX.
https://koekeishiya.github.io/kwm/
/usr/local/Cellar/kwm/1.1.2 (6 files, 356.8K) *
  Built from source
From: https://github.com/Homebrew/homebrew-binary/blob/master/kwm.rb`

**Comment by dominiklohmann** [comment]
First of all, wrap the content of the kwmrc in code blocks to not have markdown mess with your formatting.

Second.... are you sure that you're running kwm? Also there's an update to 1.1.3 out, but that should be completely unrelated. When installing kwm via homebrew-binary, it should tell you how to make it autostart via launchctl. Otherwise, you can launch it by executing kwm (requires your terminal to have Accessbility access).

**Comment by theobarberbany** [comment]
Yep, It automatically resizes windows as expected, complete with green outline. 

I've got launchctl autostarting as well. This was just with regards to the keybinds not actually seeming to do something?

**Comment by dominiklohmann** [comment]
When you run `kwmc bind ctrl-t sys say test`, does it say "test" when pressing ctrl-t?

**Comment by theobarberbany** [comment]
If i first press ctrl + x then ctrl + t yes.

Just to clarify, do I have to define all bindings manually?

**Comment by dominiklohmann** [comment]
`kwmc config prefix-global enable` in your kwmrc should be the issue. Completely forgot that setting even existed.

It makes it so prefix- is automatically prepended to all binds, so only the binds without prefix- work. Either manually use prefix- for the binds that you want to use the prefix key for, or remove prefix- from all binds and leave that setting as is to have all of them working with the prefix by default.

**Comment by theobarberbany** [comment]
Thanks, I'll try that! 

Just to clarify do all binds have to be manually defined?

**Comment by dominiklohmann** [comment]
> Just to clarify do all binds have to be manually defined?

Yes. There are no binds that work out of the box. If you need help creating them, there's some samples in the wiki and spread across the issue tracker, and there's also `kwmc help`.
