### ISSUE TITLE
Add option to have screen padding always respect Dock and Menubar

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#207]
This has multiple benefits:
- Screen padding value can respect Dock width/height only on screens it's necessary for
- Dock and Menubar auto-hide would be respected properly

I'm not sure how exactly one would go about implementing this, just bringing this up as an idea.

**Comment by chrishoage** [comment]
My humble opinion is this can pretty easily be achieved with the current padding system. I can maybe see an argument for setting the default `kwmrc` values to account for _most_ Dock and menu bar sizes, but not dynamically adjusting based on the current dock size. 

The added complexity to achieve this seems to outweigh just modifying the values in the `kmmrc` that works best for the user.

**Comment by dominiklohmann** [comment]
The issue I'm currently having is that the dock only appears on one screen, and I'd like to have the padding respect the dock on that one screen only. There is (afaik) no way to do that currently with kwm.

**Comment by chrishoage** [comment]
Ah, you must run with hiding off? 

I _do_ see lots of value in display-specific-config. Perhaps it could be rolled into #154 somehow?

**Comment by dominiklohmann** [comment]
I think it happens because I have my dock at the left side, so it only appears on the leftmost screen. This leaves me with unnecessary padding on the left side of all other screens if I don't have the dock set to autohide (which I'd prefer not to when running 3 monitors).

**Comment by chrishoage** [comment]
Right, I get that. The issue I linked was the display profiles ticket. I think that if there could be a way to apply padding to a specific display, it could happen in the display profile. 

This could allow users to customize how each display is configured, down to the padding values for that display.

**Comment by dominiklohmann** [comment]
Yeah, makes sense to combine that. Probably easier to implement than my idea to dynamically respect the dock and optionally the menu bar.

**Comment by koekeishiya** [comment]
Display-specific settings is the solution I'm going to go with for this.
