### ISSUE TITLE
Feature: Dialog always on top

### ISSUE THREAD

**Issue by andreaspada** [koekeishiya/kwm#208]
Interesting in know if is it possible to have such a feature that allow dialog windows to stay always on top. 
Also, not exactly related, but there's a way to send the mouse to the menu via shortcut? Sometime I need to reach the menu of an app and, if I pass over a window of another app, the menu changes... it's rather annoying...

**Comment by dominiklohmann** [comment]
Not that I know of.

For now you can use (fn+)ctrl-F2 to highlight the menubar, then you can control it with the arrow keys, enter and escape. This keyboard shortcut can be changed under `System Preferences > Keyboard > Shortcuts > Keyboard > Move focus to the menu bar`. 

If you have Karabiner installed, it also comes with a tool called [warp-mouse-cursor-position](https://github.com/tekezo/Karabiner/tree/master/src/util/warp-mouse-cursor-position), which you can use with `kwmc bind ... sys warp-mouse-cursor-position screen 0 top +30 left +10` to get to the top left corner of the screen. That is what I'm currently using, although I'm pretty sure that there are easier solutions with AppleScript available.

**Comment by koekeishiya** [comment]
Not possible to make windows top-most. Requires injecting code into the Dock, which is not something I'm gonna bother looking at. Check out [afloat](https://github.com/millenomi/afloat) if you wish to pursue this.
