### ISSUE TITLE
Ability to turn off KWM for some screens / spaces

### ISSUE THREAD

**Issue by TreyBastian** [koekeishiya/kwm#212]
Maybe I'm missing something, but it would be nice to set a specific space or even an entire monitor to not utilize kwm.

**Comment by dominiklohmann** [comment]
Probably related to #154 - Display Profiles.

**Comment by koekeishiya** [comment]
`kwmc config screen id float`
`kwmc config space float`
`kwmc space -t float`

**Comment by dominiklohmann** [comment]
Making a screen/space/container floating doesn't completely disable kwm, assuming that is what @TreyBastian means.

**Comment by koekeishiya** [comment]
> Making a screen/space/container floating doesn't completely disable kwm,

It disables everything but keybinds for the given monitor / space.

**Comment by TreyBastian** [comment]
> It disables everything but keybinds for the given monitor / space. 

That would actually be ok, but it seems whenever I type kwmc space -t float then kwmc read space it still says it's bsp and can't seem to change the layout.

**Comment by dominiklohmann** [comment]
Oh, I assumed that with `kwmc config standby-on-float disable` the focus-follows-mouse would still work. Just tested it and it does not, is that intended?

**Comment by koekeishiya** [comment]
The only thing that Kwm should do on floating spaces, is allow keybinds to work. All other functionality should be ignored for that space. If this is not the case, then that is a bug.

**Comment by koekeishiya** [comment]
> That would actually be ok, but it seems whenever I type kwmc space -t float then kwmc read space it still says it's bsp and can't seem to change the layout. 

`kwmc read space` gets the global mode used for new created spaces, not the mode of the active space.
The command you are interested in is `kwmc read tag`

**Comment by TreyBastian** [comment]
> kwmc read space gets the global mode used for new created spaces, not the mode of the active space.
The command you are interested in is kwmc read tag

thanks, It didnt seem to be working before, but now float seems to be functioning right, I'm sure it was user error as last time I set it to float it still seemed to mouse over focus windows still.
