### ISSUE TITLE
Unable to launch kwm (Service exited with abnormal code: 1)

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/kwm#213]
Hi,

I am currently using KWM v1.1.0.

I tried to use the latest release of KWM (1.1.3). However, I am unable to run it, I got this error message in the console logs:

    05/03/2016 18:28:13,272 com.apple.xpc.launchd[1]: (com.koekeishiya.kwm[6120]) Service exited with abnormal code: 1
    05/03/2016 18:28:13,272 com.apple.xpc.launchd[1]: (com.koekeishiya.kwm) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

I am running El Capitan 10.11.3.

Am I missing something ?

Can I provide more useful debug logs ?

Regards

**Comment by koekeishiya** [comment]
Do you install with homebrew or compile from source?

**Comment by mickaelperrin** [comment]
Compile from tag 1.1.3

**Comment by koekeishiya** [comment]
If you are not using homebrew, I would recommend to just clone the latest master.
If you do this, notice that config option `enable | disable` has been changed to `on | off`  cb09e9ce6712c9a0228f11962aaf6a4ea41f08b6

**Comment by mickaelperrin** [comment]
Thanks, finally got it working.

I restarted from scratch, remove Homebrew version, pull master, compile, reboot and it works now.

Thanks for your help ;) and keep the (very) good job 👍
