### ISSUE TITLE
Allow use focus window shortcuts in float mode

### ISSUE THREAD

**Issue by maksimr** [koekeishiya/kwm#215]
Shortcuts like `kwmc bind cmd+alt-h window -f west`
 do not work when I enable `float` mode. I think it will be nice cycling between windows using these shortcuts in float mode.

Thanks!

**Comment by chrishoage** [comment]
The directional (`north`, `south`, etc) don't make a lot of sense in `float` mode due to the user having full control over the window position and layout. Windows could be stacked on top of each other, or not in an easily expressed direction. 

From my understanding (I may be wrong about this) `float` is intended to make a space not managed by `kwm`. So the focus giving commands don't make a lot of sense in `float` mode. 

Any reason `cmd + tab` and cmd + ` wouldn't work in this situation?

**Comment by maksimr** [comment]
@chrishoage cmd + tab it's not what I want. cmd + ` works but it will be nice have one combination of shortcuts for switching focus.
Allow bind cmd+alf+h on cmd+` can solve the problem

**Comment by dominiklohmann** [comment]
It'd be nice to have `kwmc bind window -f prev|next` work in float mode. The directional ones don't make much sense.

**Comment by koekeishiya** [comment]
> Shortcuts like kwmc bind cmd+alt-h window -f west
do not work when I enable float mode. I think it will be nice cycling between windows using these shortcuts in float mode.

If people want support for this, that is actually very easy to do. I just do not want it as a feature in Kwm.

> It'd be nice to have kwmc bind window -f prev|next work in float mode. The directional ones don't make much sense.

This would be technically impossible as there is no binary-tree to navigate in float mode.

**Comment by dominiklohmann** [comment]
You could always just rotate (counter-)clockwise by the top left point of the windows for float mode, or sort the windows by window creation timestamp.

**Comment by koekeishiya** [comment]
There are a couple of workarounds that would allow that to happen, yes. I personally do not want to add this feature though. It would not be hard if anyone wants to do this themselves for their own use though.

Some tips on how you coul do this:

The "directed focus" does not ignore floating windows at the moment, and it would be trivial to allow the window list to update on floating spaces and let the focus commands pass through.

The implementation of `prev | next` could be done by using the same list and iterate through til the focused window is found, then give focus to the next/previous one in the list, or something similar.

**Comment by maksimr** [comment]
@koekeishiya thanks,

I see you. I have one more question. Is there something like `kwmc bind screen -f prev|next`? ( I know that exist `kwmc bind ctrl+alt-1 screen -m 0`)

**Comment by koekeishiya** [comment]
For a list of commands, you can do `kwmc help` from a terminal, or go [here](https://github.com/koekeishiya/kwm/tree/master/kwmc)
