### ISSUE TITLE
Execute script on keypress and allow key pass-through

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#218]
I was trying to execute a script on a keypress, but also forward the keypress to the application. I noticed that my kwm ended up stuck in an infinite loop.

Is there a way to have `kwmc press key` not trigger `kwmc bind key ...`?

**Comment by koekeishiya** [comment]
> I was trying to execute a script on a keypress, but also forward the keypress to the application.

If you return `Event`instead of `NULL` at kwm.cpp:46 the keypress will be forwarded to the application.

**Comment by koekeishiya** [comment]
> I was trying to execute a script on a keypress, but also forward the keypress to the application.

Rather than having to use `kwmc press` for this, I could probably allow for `kwmc bind ..` to specify whether or not the keypress should be nullified by Kwm, or allow it to pass through.

**Comment by dominiklohmann** [comment]
I actually wanted to add `kwmc bind-passthrough key command` this weekend when I had some free time, but am very much glad to see that you want to tackle that one by yourself (and I imagine that'd be a lot quicker, too, since I'm not all that familiar with your code) - Thanks! 

For now I've solved the issue locally by just using Karabiner instead to listen to the hotkey, so there wasn't really much of a need there on my end.
