### ISSUE TITLE
Add-on: Hammerspoon script to move windows to space on left or right

### ISSUE THREAD

**Issue by andreaspada** [koekeishiya/kwm#219]
Finally, I encountered a near perfect working setup for bare hammerspoo setup, with no additional extensions. Here it is the code, stolen and adapted from various sources...

```
-- Bound to capslock
local hyper = {"ctrl", "shift", "alt", "cmd"}

-- Remove window movement animation
hs.window.animationDuration = 0

-- Hack to move window between spaces
function moveWindowOneSpace(direction)
  local mouseOrigin = hs.mouse.getAbsolutePosition()
  local win = hs.window.frontmostWindow()
  local clickPoint = win:zoomButtonRect()

  clickPoint.x = clickPoint.x + clickPoint.w + 3
  clickPoint.y = clickPoint.y + (clickPoint.h / 2)

  local mouseClickEvent = hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.left
  mouseClickEvent:post()
  hs.timer.usleep(300000)

  local nextSpaceDownEvent = hs.eventtap.event.newKeyEvent({"ctrl"}, direction, true)
  nextSpaceDownEvent:post()
  hs.timer.usleep(150000)

  local nextSpaceUpEvent = hs.eventtap.event.newKeyEvent({"ctrl"}, direction, false)
  nextSpaceUpEvent:post()
  hs.timer.usleep(150000)

  local mouseReleaseEvent = hs.eventtap.event.newMouseEvent(hs.eventtap.event.types.le
  mouseReleaseEvent:post()
  hs.timer.usleep(150000)

  hs.mouse.setAbsolutePosition(mouseOrigin)
end

hs.hotkey.bind(hyper, "Left", function()
  moveWindowOneSpace("left")
end)

hs.hotkey.bind(hyper, "Right", function()
  moveWindowOneSpace("right")
end)

hs.hotkey.bind(hyper, "T", function()
  script = [[
      set theFolder to ""
      tell application "Finder"
        if front window exists then
          set theFolder to (folder of the front window) as text
          set theFolder to POSIX path of theFolder
        end if
      end tell
      tell application "Terminal" 
          do script "cd " & theFolder  
          activate  
      end tell
    ]]
    hs.applescript(script)
end)

```

I like to reap my CapsLock to Hyper (ctrl+cmd+aly+shift), so I still have plenty of key bind with more simples strokes at my disposal.
There also a nice "Open Terminal in current Folder", which can be very useful.

**Comment by andreaspada** [comment]
There's some strange behaviour, as when the window is moved to a tiling space, is not auto tiled. So, there's something that can be tweaked in .kwmrc to get it properly working?

**Comment by andreaspada** [comment]
Finally, I encountered a better and near perfect working setup: [HotkeyMoveBetweenSpaces/](https://github.com/jredmond/HotkeyMoveBetweenSpaces/blob/master/init.lua). Also there's an interesting idea to remap the Caps Lock to Hyper (ctrl+cmd+alt+shit),which could be great in some trick bind mapping. 

It moves windows between spaces and, after moved, they are also correctly recognised and tiled by KWM. Perfect companion. Do not need stranger undocumented extensions, just bare official **hammerspoon**.

**Comment by andreaspada** [comment]
Still need to improve it to have KWM retiling the recently moved window. 
**Work in Progress...**

**Comment by koekeishiya** [comment]
I've seen this mentioned before, and have implemented this natively for Kwm in the latest commit @ master.

To use this, you must set `kwmc config spaces-key mod+mod+mod` to the key OSX uses (System Preferences -> Keyboard Shortcuts -> Mission Control -> <mod> key)
Example I use: `kwmc config spaces-key cmd+ctrl`

The command `kwmc window -s space` takes as input the key part of <mod> key set in OSX Preferences.

For instance, I have in OSX Keyboard shortcuts "Move right a space" = cmd+ctrl + right arrow.
So I would do `kwmc bind .. window -s space right` to move window one space right.

I have "Switch to desktop 4" = cmd+ctrl + 4.
So I would do `kwmc bind .. window -s space 4` to move window to space 4.

**Comment by andreaspada** [comment]
Well, much better YOUR way! Thanks!!

**Comment by matthewdias** [comment]
`window -s space left|right` don't seem to work. The windows retile for a second to reflect the window being removed from the space, but the window doesn't actually move, and then the windows retile again to how they were.

**Comment by koekeishiya** [comment]
`left|right` should be replaced by whatever key you have as the OSX shortcut, and the modifiers of the OSX shortcut must be set as ´kwmc config spaces-key`

**Comment by matthewdias** [comment]
Got it, thanks
