### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by lrusnac** [koekeishiya/kwm#22]
hi, it's not an issue but more a curiosity, how did you configured in that way the osx, what are you using to make it like in the screenshot, thanks

**Comment by koekeishiya** [comment]
In the screenshot I'm using iTerm2 with no title-bar. This can be achieved by downloading the beta (or alpha) version from the developers webpage. In iTerm2 I am running tmux for tabs, and I let Kwm handle the tiling. The OSX menubar is hidden using El Capitans option, and dock is set to auto-hide.

I use a script written for hammerspoon that uses the hs.drawing extension to draw the green border around the focused window. The bar that you see on top is made by using nerdTool.

The border script for hammerspoon:
https://gist.github.com/koekeishiya/dc48db74f4fdbfbf5648

My tmux config:
https://gist.github.com/koekeishiya/a122b50907a03428bd63

The nerdTool scripts can be found in this issue:
https://github.com/koekeishiya/kwm/issues/8

**Comment by lrusnac** [comment]
cool, thanks

**Comment by lipis** [comment]
:100: Looks beautiful :)

**Comment by lrusnac** [comment]
what about the themes for iterm and vim?

**Comment by koekeishiya** [comment]
[iTerm&Vim-colors.zip](https://github.com/koekeishiya/kwm/files/70926/iTerm.Vim-colors.zip)
My iTerm and vim colorscheme.
