### ISSUE TITLE
kwm hangs when switching spaces with 4 fingers gesture

### ISSUE THREAD

**Issue by cHoco** [koekeishiya/kwm#221]
I haven't had time to debug this issue, but the reproduction steps are pretty easy, but you need to have a trackpad since I can only reproduce it with that. 
1- Be in the first space/desktop
2- Try switching to a space on the left using the four fingers gesture. (since we are in the first space, there are no spaces on the left, but using the four finger gestures there's  a little animation, like when you scroll at the end of a webpage in Safari.)
3- kwm stops working (the process is still up and running but nothing seems to works.

**Comment by koekeishiya** [comment]
Same as #131
