### ISSUE TITLE
Window is not focused if I use spotlight search

### ISSUE THREAD

**Issue by maksimr** [koekeishiya/kwm#223]
UC:

1. Open iTerm on first screen
2. Open Google Chrome on second screen
3. Focus on Google Chrome
4. Launch Spotlight search
5. Select iTerm in spotlight

AR:

I can type to iTerm but focus still on Google Chrome.

ER:

Move focus to first screen on iTerm

**Comment by koekeishiya** [comment]
Should be fixed now.

**Comment by maksimr** [comment]
@koekeishiya I have checked It's worked!
Thanks
