### ISSUE TITLE
Add version option to bin

### ISSUE THREAD

**Issue by maksimr** [koekeishiya/kwm#225]
It will be very helpful when build from source and for debug information in issue

```
kwmc --version
```

or

```
kwmc version
```

**Comment by koekeishiya** [comment]
Not going to add `kwmc --version`. The only reason the version paramter of kwm even exists, is because of the test case required by homebrew

**Comment by maksimr** [comment]
Wow, well

Could you describe what are differences between kwm and kwmc?
Thanks

**Comment by koekeishiya** [comment]
Kwm is the actual program responsible for managing windows and such.

Kwmc is simply a tcp-client sending text-messages to Kwm, telling it to do something.
You could just as well `telnet 127.0.0.1 3020` and type `window -f next ` to shift focus.
