### ISSUE TITLE
some applications ignore focused container

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#226]
Some applications "ignore" or somehow manage to have the focused window change / clear before the tiling is attempted, thus causing the window to follow the default tiling rules for where it should be positioned, rather than tiling at the position of the previously focused container.

I suspect this is due to the changes made to properly support cmd+tab, function `didActivateApplication()` in `kwm/workspace.mm`

**Comment by koekeishiya** [comment]
I have confirmed that his is indeed happening because of the code specified in `didActivateApplication() in kwm/workspace.mm` that allows for cmd+tab support.

**Comment by chrishoage** [comment]
playing with it for a moment it does appear to be fixed

**Comment by chrishoage** [comment]
It also fixed a focus issue when opening a link in a browser across displays! Awesome!
