### ISSUE TITLE
Launchpad is unusable

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#228]
If focus-follows-mouse is enabled, and there are multiple applications on the current space, launchpad will simply close every time the mouse is moved.

Related to #184, see my last comment in said issue for details.

**Comment by chrishoage** [comment]
To fix the linked issue and this issue, maybe an option to disable focus-follows-mouse when the dock is visible? 

It should default to off for people who run with the Dock visible, but people with it hidden could add a config line. 

Something like 

```
# Disable autorise when a floating widnow is focused
kwmc config focus standby-on-float on
```

for the dock

**Comment by koekeishiya** [comment]
That would be a fix for users that have the dock hidden, however I'd prefer to try and work out a fix that works regardless of the dock being visible or not.
