### ISSUE TITLE
Show Desktop functionality breaks kwm

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#229]
Show Desktop (`F11` by default, or as a gesture `spread with thumb and 3 fingers`) seems to break kwm for me, especially when opening new windows while it is activated. 

I imagine a fix to work something like this: Save the current tree before it activates, then enter float mode while it is activated and once it ends, restore the tree and insert any new windows that were created?

**Comment by koekeishiya** [comment]
> I imagine a fix to work something like this: Save the current tree before it activates, then enter float mode while it is activated and once it ends, restore the tree and insert any new windows that were created?

Hmm, I have no idea if it is possible to check if `Show Desktop` has been activated.

**Comment by dominiklohmann** [comment]
This seems to (kinda) be fixed as of 3.0.0. Kwm now behaves as if the windows that are temporarily hidden are tiled, and adding windows while Show Desktop is enabled now tiles these correctly (as if the hidden windows were still in place). 

I'm not sure if there's anything else you can do to make Kwm ignore windows hidden by this, so I am considering this issue fixed.

**Comment by koekeishiya** [comment]
That is probably the best behaviour we will be able to get, indeed.
