### ISSUE TITLE
Brew formula

### ISSUE THREAD

**Issue by napcae** [koekeishiya/kwm#23]
Is this desired? I'd write one.

**Comment by areus** [comment]
:+1:

**Comment by callahanrts** [comment]
:+1:

**Comment by koekeishiya** [comment]
Sounds like a nice idea.

**Comment by napcae** [comment]
kwm doesn't [meet the requirements](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#stable-versions) for formulae, I'd recommend the [devel-only tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#stable-versions) or you, @koekeishiya to create a stable version tag. More info [here](https://github.com/Homebrew/homebrew-devel-only).

**Comment by koekeishiya** [comment]
Not really sure if it belongs in the stable category yet. Personally I'd say the devel-only tap should be it's place. Or make use of the 'tap' system.

**Comment by napcae** [comment]
I'll submit to devel-only then, if it's okay.

**Comment by koekeishiya** [comment]
Sure, Thanks.

**Comment by napcae** [comment]
Pull request was made. As soon as the pull is merged, we can update the readme with install instructions.

**Comment by koekeishiya** [comment]
Alright nice.

Kwm seems to be quite stable at the moment, for my use at least,
and so I am considering to put out the first RC.

**Comment by hhsnopek** [comment]
@napcae link to PR?

**Comment by koekeishiya** [comment]
Just put out a stable release: https://github.com/koekeishiya/kwm/releases/tag/v1.0.0-RC
Feel free to resubmit a pull request to the main homebrew repository.

**Comment by napcae** [comment]
Alright, can you create a github pages site as the homepage? [Here](https://github.com/Homebrew/homebrew-devel-only/pull/39) is the pull request. Maybe I should revoke it and only submit to the main repository. Do you know what test we can run, so kwm returns 0? I.e. 
  
      $ kwm --version
      $ echo $?
      0

**Comment by koekeishiya** [comment]
Added a gh-pages branch.
Does it need to return the actual version, or just 0?

**Comment by napcae** [comment]
return 0 as the return code, not as the version code. I didn't find anything similar, that's why I'm asking. I hope you know what I mean. otherwise query me at freenode.

**Comment by koekeishiya** [comment]
Everything should be set for this to work now. The brew formula simply needs to run the command "make install BUILD_PATH=#{bin}"
