### ISSUE TITLE
Changing spaces on an inactive screen pulls windows to active screen

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#236]
Steps to reproduce:
- 2 screens, at least 3 spaces. Let's say space 1 is on screen 1, space 2-3 are on screen 2. Window A on space 2, window B on space 3.
- Active screen is 1, active space is 1 (focused). 
- Displayed space on screen 2 is space 2 (not focused).
- Press `ctrl+3` to switch to space 3.

Before (`*` indicates focus)
```
      screen 1          |                      screen 2
      space 1           |     space 2 (visible)            space 3
---------------------   |   ---------------------   ---------------------
|                   |   |   |                   |   |                   |
|                   |   |   |                   |   |                   |
|                   |   |   |                   |   |                   |
|                   |   |   |         A         |   |         B         |
|         *         |   |   |                   |   |                   |
|                   |   |   |                   |   |                   |
|                   |   |   |                   |   |                   |
---------------------   |   ---------------------   ---------------------
``` 

Before: (`*` indicates focus)
```
      screen 1          |                      screen 2
      space 1           |          space 2            space 3 (visible)
---------------------   |   ---------------------   ---------------------
|                   |   |   |                   |   |                   |
|                   |   |   |                   |   |                   |
|                   |   |   |                   |   |                   |
|         A         |   |   |                   |   |         B         |
|                   |   |   |                   |   |         *         |
|                   |   |   |                   |   |                   |
|                   |   |   |                   |   |                   |
---------------------   |   ---------------------   ---------------------
```

**Comment by koekeishiya** [comment]
Does this behaviour happen if you create the following script and bind it to a key?
Keep in mind this requires the osx-spaces shortucts and `kwmc config spaces-key` to be configured.

```
kwmc screen -f 2
kwmc kwmc space -s id 3
```

I believe this issue is connected to the fact that the active monitor is not updated properly for Kwm and the windows will appear as if they are untiled, and will be moved to the display it believes has focus.
If the problem is what I assume, using the above script should not reproduce this issue.

**Comment by dominiklohmann** [comment]
Yes it works, if you correct the space id to 1 (for the 2nd screen) and do not use `ctrl-3` as a bind for it. Using another bind like `ctrl+cmd-3` works just fine.

**Comment by koekeishiya** [comment]
Would you mind testing the following change and see what happens?

in the function `activeSpaceDidChange()` @ kwm/workspace.mm:48, call the function `UpdateActiveScreen()` just before `UpdateActiveSpace` is called.

**Comment by dominiklohmann** [comment]
Now it pulls over both windows to the left screen.

**Comment by koekeishiya** [comment]
> Now it pulls over both windows to the left screen.

Not really sure how to handle this, writing code for multi-monitor is really a pain.
It seems like I have to create separate structures for storing all windows that are on a monitor at any time, regardless of space, or something similar to this to handle the above scenario.

At this point, a lot of these issues would probably be solved by rewriting Kwm to use notifcations instead of polling, however this will make focus-follows-mouse impossible to implement properly, as there will be no way to decide the z-order of windows.

**Comment by dominiklohmann** [comment]
Can you detect when `spaces-key+num` is being pressed and focus the screen, just like the shell script above does? The only thing holding me back from creating a script for this is that I do not know how to get the amount of spaces I have per screen.

**Comment by koekeishiya** [comment]
> Can you detect when spaces-key+num is being pressed and focus the screen, just like the shell script above does? The only thing holding me back from creating a script for this is that I do not know how to get the amount of spaces I have per screen.

That would be possible, however, I would not know which screen to focus?

**Comment by dominiklohmann** [comment]
Well if you know how many spaces each screen has you can calculate that, since the spaces are just numerated from left to right. Space 1 is always the leftmost space on screen 0, and if there are n screens on space 1, space n+1 is the leftmost space on screen 1. The leftmost space on screen 2, assuming there are m spaces on screen 1, would be space n+m+1....

**Comment by koekeishiya** [comment]
> Well if you know how many spaces each screen has you can calculate that, since the spaces are just numerated from left to right. Space 1 is always the leftmost space on screen 0, and if there are n screens on space 1, space n+1 is the leftmost space on screen 1. The leftmost space on screen 2, assuming there are m spaces on screen 1, would be space n+m+1....

Currently Kwm does not know how many spaces are on each screen. I suspect this is something that I could find out however, will look into it at some point.

**Comment by dominiklohmann** [comment]
Just a quick idea here: This could also be used to make `kwmc window -s prev|next|id` work across screens, right?

**Comment by koekeishiya** [comment]
> Just a quick idea here: This could also be used to make kwmc window -s prev|next|id work across screens, right? 

I'm assuming you mean `kwmc window -s space id|left|right`
It might be possible by doing some tricky stuff

**Comment by dominiklohmann** [comment]
This very issue just happened to me again because I clicked on a notification from an application on an inactive space on an inactive screen - which probably can not be fixed the same way.

**Comment by koekeishiya** [comment]
If we are lucky, the notification argument passed to `activeSpaceDidChange` @ kwm/workspace.mm includes some information that would allow us to detect which display the new space belongs to?

**Comment by dominiklohmann** [comment]
Is there any documentation on `NSWorkspaceActiveSpaceDidChangeNotification` at all? I cannot find anything on it.

**Comment by koekeishiya** [comment]
Not that I know how, just gonna have to mess around and see what I can get from it.
