### ISSUE TITLE
Is it possible to always float for selected apps?

### ISSUE THREAD

**Issue by tuananh** [koekeishiya/kwm#238]
Coming from Amethyst, I have certain applications that I always want to float. Is it possible in `kwm`?

**Comment by chrishoage** [comment]
`kwmc config float Photoshop`

[From the sample `kwmrc` file](https://github.com/koekeishiya/kwm/blob/master/examples/kwmrc#L89-L90)

More commands can be found in `kwmc help` and `kwmc help config`

**Comment by tuananh** [comment]
Ah thanks. I missed it.
