### ISSUE TITLE
OSX Accessibility

### ISSUE THREAD

**Issue by KalenAnson** [koekeishiya/kwm#24]
Running the binary gives me this message:

   Could not access OSX Accessibility!

So I added the binary to the OSX Accessibility Database using the tool 'tccutil' located in the repo here: [https://github.com/jacobsalmela/tccutil](https://github.com/jacobsalmela/tccutil).

    sudo tccutil -i /Users/myUserName/Development/kwm/bin/kwm
    sudo tccutil --enable /Users/myUserName/Development/kwm/bin/kwm

I can now see the binary in the list of applications that have requested access to the accessibility features in the SystemPreferences>Privace and Security>Privacy menu and it is enabled there.

However I get the same message. "Could not access OSX Accessibility!"

Do I need to resort to signing the code?

Running OSX 10.10.3 Yosemite.

**Comment by koekeishiya** [comment]
It appears that codesigning does not help the issue. I've had to actually enable accessibility for the terminal that I use to run Kwm, which is something I would understand that most people probably is not willing to do, nor should.

The only real exception that I can think of, would be to create an app bundle to be added using the Systen Preferences pane. App bundles are just literally a directory structure, so there are probably guides for doing this.

**Comment by KalenAnson** [comment]
Ok, yeah if i enable my terminal application (iTerm) in the accessibility menu then the binary can run. May try a few more things, thanks.

**Comment by koekeishiya** [comment]
Please do let me know if you are able to find a way that does not require giving the entire terminal accessibility access.

**Comment by koekeishiya** [comment]
When starting OSX from within tmux, it appears that the terminal itself does not need to be checked within the accessibility pane, only the Kwm binary is needed.

**Comment by liamuk** [comment]
It's pretty straightforward to make an app bundle, and then give that access to osx accessibility. The directory structure looks like this:
- kwm.app/
    * Contents/
        - Info.plist
        - MacOS/
            * hotkeys.so
            * kwmc
            * kwm

and Info.plist contains:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"
"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleGetInfoString</key>
  <string>KWM</string>
  <key>CFBundleExecutable</key>
  <string>kwm</string>
  <key>CFBundleIdentifier</key>
  <string>com.koekishiya.kwm</string>
  <key>CFBundleName</key>
  <string>kwm</string>
  <key>CFBundleShortVersionString</key>
  <string>0.01</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>IFMajorVersion</key>
  <integer>0</integer>
  <key>IFMinorVersion</key>
  <integer>1</integer>
  <key>LSUIElement</key>
  <true />
</dict>
</plist>
```

This has the added bonus of letting you set it to start on login.

The only issue is when hotkeys.cpp makes a call like `system('kwmc ... ')` it doesn't find kwmc since it's not in the PATH. I solved this by hardcoding /Applications/kwm.app/Contents/MacOS/kwmc in hotkeys.cpp.

**Comment by koekeishiya** [comment]
Do you still have to hardcode the path in the latest commit? I recently made a change so that it uses the path to the kwm binary when looking for kwmc.

**Comment by liamuk** [comment]
Ah I haven't pulled in a few days. Will do that today and get back to you.

**Comment by liamuk** [comment]
Yeah I don't have to hardcode anymore. I also see you've set it up to use launchd; that seems to be a better system than an app bundle anyway.

**Comment by koekeishiya** [comment]
Thinking about making the launchd system automated as well. Basically you have to start kwm at least once, using a terminal. After that, simply do `kwmc config launchd enable|disable` ,and kwm will automatically create a plist and symlink it to ~/Library/LaunchAgents or remove it. This way the user won't have to deal with that manually.

Sounds like a change for the better, or ?

**Comment by KalenAnson** [comment]
I like where this project is headed. The last commit added some awesome functionality. I have been looking for focus follows mouse on OSX for years.

I pulled commit 693a27b and really like it. I think that the launchd configuration flag is a great idea. Great work.

**Comment by liamuk** [comment]
I agree with everything Kalen said. This is awesome.

**Comment by koekeishiya** [comment]
Added the launchd config flag in the latest commit
