### ISSUE TITLE
kwm running but not working

### ISSUE THREAD

**Issue by UnrealAkama** [koekeishiya/kwm#242]
kwm was working great for me, I had it setup and was using a custom config. However when I rebooted my laptop, kwm was running but there was no border around the active window and it wasn't tiling. I have rebooted it several times before and it was working fine though reboots prior to this.

Since then, I've moved back to the example config & reinstalled kwm. I've rebooted the system as well. It still shows as running but there is no tiling. The two processes I see are listed below. 

  771   ??  S      0:00.87 /usr/local/opt/kwm/kwm
  775   ??  S      0:00.09 /usr/local/Cellar/kwm/1.1.3/kwm-overlay

Do you have any thoughts on how to continue debugging? I've also run it on it's own but there is no output.

**Comment by chrishoage** [comment]
Do you see any messages in your `Applications/Utilities/Console` about kwm?

**Comment by UnrealAkama** [comment]
3/20/16 2:34:03.715 PM com.apple.xpc.launchd[1]: (homebrew.mxcl.kwm) This service is defined to be constantly running and is inherently inefficient.
3/20/16 2:34:47.333 PM com.apple.xpc.launchd[1]: (homebrew.mxcl.kwm[12515]) Service exited due to signal: Terminated: 15

the second one is triggered by me restarted the service using killall

**Comment by koekeishiya** [comment]
Version 1.1.4 is on brew now.
If it still fails after upgrading, remove accessiblity access and reenable it.

Note: the config options have been changed to use `on | off` instead of `enable | disable`

**Comment by UnrealAkama** [comment]
I upgraded to the latest & used the example configuration. Still running with no titling. Is there a log that I am missing or someway to turn on debugging logs?

**Comment by dominiklohmann** [comment]
Add this to the plist in `$HOME/Library/LaunchAgents` to get logs (change the paths as you like). 

```plist
<key>StandardOutPath</key>
<string>/tmp/kwm.out</string>
<key>StandardErrorPath</key
<string>/tmp/kwm.err</string>
```

To view the log while Kwm is running, you can then use something like `tail -f /tmp/kwm.out`.

**Comment by UnrealAkama** [comment]
Both of those files got created but they have nothing in them. Output from ll is listed below. What sort out of output should I be seeing?

-rw-r--r--  1 user  wheel     0B Mar 20 16:14 kwm.err
-rw-r--r--  1 user  wheel     0B Mar 20 16:14 kwm.out

**Comment by dominiklohmann** [comment]
```
KwmExecuteHotkey
ShouldBSPTreeUpdate() Add Window
AddWindowToBSPTree() Create pair of leafs
IsWindowOnActiveSpace() window found
SetWindowDimensions()
SetWindowDimensions()
SetWindowRefFocus() Focused Window: Terminal — login — 80×24 727,35
SetWindowRefFocus() Focused Window: kwm running but not working · Issue #242 · koekeishiya/kwm 15,35
SetWindowRefFocus() Focused Window: dominiklohmann — tail — 98×55 727,35
```

Something like that.

**Comment by chrishoage** [comment]
@dominiklohmann he installed from brew, he will need to build it in dev mode. 
@UnrealAkama If you are able to, you can build kwm from source and it will enable logs.

Perhaps there should be a production flag to enable logs?

**Comment by dominiklohmann** [comment]
I didn't even know there was a separate release mode... that at least explains why there are no logs.

**Comment by koekeishiya** [comment]
> Perhaps there should be a production flag to enable logs? 

Currently that would require a rewrite of how the logging happens.
I use the preprocessor to enable or disable debug logging and assertions, so these do not compile into the binary at all when building in release mode.

**Comment by UnrealAkama** [comment]
I went ahead and used the 1.1.4 tag and compiled from source with debug headers. This is the output from stdout. 

Kwm: Could not start daemon..

And this is output from the Console

3/21/16 10:10:09.816 AM com.apple.xpc.launchd[1]: (com.koekeishiya.kwm[7013]) Service exited with abnormal code: 1
3/21/16 10:10:09.816 AM com.apple.xpc.launchd[1]: (com.koekeishiya.kwm) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.


Any thoughts?

**Comment by koekeishiya** [comment]
There appears to be something blocking port 3020.
What is the output of `lsof -i :3020` ?

**Comment by UnrealAkama** [comment]
COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
kwm       424 adam    4u  IPv4 0x86b029b71d14da4f      0t0  TCP localhost:cifs (LISTEN)
kwm-overl 538 adam    4u  IPv4 0x86b029b71d14da4f      0t0  TCP localhost:cifs (LISTEN)

and then ps

  424   ??  S      0:11.57 /usr/local/opt/kwm/kwm
  538   ??  S      0:00.32 /usr/local/Cellar/kwm/1.1.4/kwm-overlay
10220 s001  R+     0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn kwm

**Comment by koekeishiya** [comment]
Before you compile and run from source, do the following to prevent the Homebrew version from starting:
`launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.kwm`

**Comment by UnrealAkama** [comment]
Sorry, I should have caught that. I've corrected that. 

I've got logs which shows some interesting details, in that it's taking keybindings and working. However I'm still not seeing any tiling.

```

Local Daemon is now running..
ChangeSplitRatio() New Split-Ratio is 0.5
DisplayID 1952349575 has index 0
DisplayID 69732482 has index 1
DisplayID 1952349576 has index 2
DisplayID 1952349577 has index 3
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
UpdateActiveScreen() Active Display Changed
GiveFocusToScreen() 3: Space transition ended -1 -> -1
Uninitialized Screen
UpdateActiveScreen() Active Display Changed
GiveFocusToScreen() 0: Space transition ended -1 -> -1
Uninitialized Screen
UpdateActiveScreen() Active Display Changed
GiveFocusToScreen() 3: Space transition ended -1 -> -1
Uninitialized Screen
UpdateActiveScreen() Active Display Changed
GiveFocusToScreen() 0: Space transition ended -1 -> -1
Uninitialized Screen
UpdateActiveScreen() Active Display Changed
GiveFocusToScreen() 3: Space transition ended -1 -> -1
Uninitialized Screen
UpdateActiveScreen() Active Display Changed
GiveFocusToScreen() 0: Space transition ended -1 -> -1
Uninitialized Screen
IsSpaceTransitionInProgress() Space transition detected
IsSpaceTransitionInProgress() Space transition detected

```

![screen shot 2016-03-21 at 11 58 57 am](https://cloud.githubusercontent.com/assets/2373027/13926896/5cc4c586-ef5c-11e5-8469-20bad96d156f.png)


![screen shot 2016-03-21 at 11 58 57 am 4](https://cloud.githubusercontent.com/assets/2373027/13926887/55c240ec-ef5c-11e5-8a22-192980ba9471.png)

**Comment by koekeishiya** [comment]
Can you run Kwm with only 1monitor and switch between different spaces a few times, then post the following log.

**Comment by UnrealAkama** [comment]
```
Local Daemon is now running..
ChangeSplitRatio() New Split-Ratio is 0.5
DisplayID 2077751165 has index 0
IsSpaceTransitionInProgress() Space transition detected
IsSpaceTransitionInProgress() Space transition detected
IsSpaceTransitionInProgress() Space transition detected

```

**Comment by koekeishiya** [comment]
Right, so this is the expected output:
```
Local Daemon is now running..
ChangeSplitRatio() New Split-Ratio is 0.5
DisplayID 2026445337 has index 0
CreateWindowNodeTree() Create Space 2
..lots of stuff here.
```

**Comment by UnrealAkama** [comment]
So, I'm not creating a window node tree then? Any ideas on why?

**Comment by koekeishiya** [comment]
I know the "why" in the codebase, however it makes no sense as to why that would trigger it.
The "path" it seems to follow, happens when the OSX is in a space transition. However, in your case, it seems to always trigger this.

What happens if you delete all spaces, and create new ones.
Then try to run Kwm again (with no external monitors connected).

**Comment by UnrealAkama** [comment]
I actually solved it. It doesn't seem to work when the option for not using unique spaces is unselected. I've included a screenshot below. Hopefully that helps if you get a report like this in the future. Thanks for all the help. 

![screen shot 2016-03-21 at 1 09 16 pm](https://cloud.githubusercontent.com/assets/2373027/13929085/70ebc0d2-ef66-11e5-96a5-e7160f9173fb.png)

**Comment by koekeishiya** [comment]
Well that is disturbing, Thanks for figuring that out.
Is this something you would prefer to be able to have support for?
I'm not really sure how complicated it would be to fix that. I guess I've just blindly assumed that "Displays have separate Spaces" is used by most ppl.

**Comment by UnrealAkama** [comment]
I have no need for support using that. Tbh I'm not sure why I changed that option. I think that separate spaces for each display is the default.

**Comment by itisbenjamin** [comment]
Hi, 
I came out with the same problems while selected that box. I use this option while connecting my computer to another separate screen and using them together. I guess it would be kind of complicated since the screens' sizes are not usually same, but it would be wonderful if anyone can implement this function. 
Thanks!
