### ISSUE TITLE
Kwm does not work when "Displays have separate Spaces" is disabled

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#246]
Probably not gonna bother fixing this unless there is a lot of demand for it.
I personally do not see any reason as to why someone who is interested in this sort of control would run with "Displays have separate spaces" disabled.

**Comment by chrishoage** [comment]
At minimum offer a runtime warning or some indication to the user _why_ kwm isn't working? Is it possible to detect if that spaces mode is enabled?

**Comment by koekeishiya** [comment]
> Is it possible to detect if that spaces mode is enabled? 

I have not looked into that yet, however I assume there is a way to do this.

**Comment by koekeishiya** [comment]
Great, the value returned through the above method always returns 0...

**Comment by risc12** [comment]
Maybe it is a good idea to put this in the README or the docs. I've been trying to get kwm working for an hour until stumbling apon this, totally forgot I had this feature enabled haha!

**Comment by risc12** [comment]
I upgraded to El Capitan, that fixed this issue so this could be closed I think!

**Comment by koekeishiya** [comment]
Kwm should print a warning and exit if this setting is not enabled.
