### ISSUE TITLE
Suddenly keybinds stop working

### ISSUE THREAD

**Issue by andreaspada** [koekeishiya/kwm#247]
I have just compiled your last commitment, with space configuration support, and my key binding have disappeared. My prefix do not working anymore...

Any clue?

**Comment by koekeishiya** [comment]
I've changed a couple of commands in the latest commits.
`kwmc config prefix ..` is now `kwmc config prefix-key ..`
`kwmc config tiling on` is now `kwmc config tiling bsp` (or monocle, float, off)

See kwmc/README https://github.com/koekeishiya/kwm/commit/bf7970db9d96866bd2cd2a648ec996dfaf00aab3

**Comment by andreaspada** [comment]
Great, thanks! Solved

koekeishiya wrote:
>
> I've changed a couple of commands in the latest commits.
> |kwmc config prefix ..| is now |kwmc config prefix-key ..|
> |kwmc config tiling on| is now |kwmc config tiling bsp| (or monocle, 
> float, off)
>
> See kwmc/README bf7970d 
> <https://github.com/koekeishiya/kwm/commit/bf7970db9d96866bd2cd2a648ec996dfaf00aab3>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/koekeishiya/kwm/issues/247#issuecomment-199430467>
>

-- 

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Andrea Spada :: Liuteria d'Autore
www.andreaspada.com

CNPJ: 12.027.966/0001-00
CPF: 054.545.977-08
IM: 0.586.554.9
