### ISSUE TITLE
Kwm fails to move windows to another space when there are multiple windows of the same application

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#248]
As the title says, Kwm fails to move windows to another space if are more than one non-floating windows of any application on the active space.

**Comment by koekeishiya** [comment]
Everything seems to work fine for me.
Can you post steps to reproduce?

**Comment by dominiklohmann** [comment]
Have two windows of the same application (tested with Safari, Finder and Terminal) on one space. With spaces-key configured, move one of them to another screen. It will switch to the other screen, but not move the window. 

http://gfycat.com/SpitefulHastyEsok is a short screencast I just created. I switch 3 times, the first time I forgot I still had QuickTime focused for the screen recording, the second time you can see the actual bug, the third time I only have one window on the screen and you can see it working and correctly moving the window.
