### ISSUE TITLE
more space/tree settings

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#249]
a few that would be nice to have

- tag a space with a name that can be read later (im guessing reordering spaces would cause issues with this)
- default tree for space tag
- restore tree when space is tagged
- recognize apps when saving/restoring tree so that apps are tiled in the same places they were on save (example: on restore, chrome is always tiled first, then sublime, then terminal)

**Comment by koekeishiya** [comment]
The first 3 seems like it could be doable.

> recognize apps when saving/restoring tree so that apps are tiled in the same places they were on save (example: on restore, chrome is always tiled first, then sublime, then terminal)

This would be possible, but if there was multiple windows of the same application, that would cause problems.

**Comment by matthewdias** [comment]
would it be fine to just grab the first available window that matches the desired application name and tile it? i personally wouldnt care if terminals weren't ordered for example

**Comment by koekeishiya** [comment]
That would be how it would have to work yeah.

**Comment by matthewdias** [comment]
also adding assigning default tags for spaces by id would be useful obviously

**Comment by koekeishiya** [comment]
I've been thinking about this for some time, and just wondering what the need is for assigning tags to spaces?

**default tree for space tag**:
This could be achieved by adding something like: `kwmc config space display_id space_id tree tag`,
and it would just basically perform the `tree restore tag` command when this space is initialized.

**restore tree when space is tagged**:
This just feels like a `kwmc tree restore tag` to me?

**Comment by matthewdias** [comment]
Well basically, I'm trying to create a system where I can start a new project on a space, and have it open stuff automatically for me. It would set the working directory that new finder, terminal, and text editor windows would open with. Having the tag functionality would let me automatically open all the apps/docs/web bookmarks that i need, and restore the tree that I've set for that project.

>default tree for space tag:
This could be achieved by adding something like: kwmc config space display_id space_id tree tag,
and it would just basically perform the tree restore tag command when this space is initialized.

>restore tree when space is tagged:
This just feels like a kwmc tree restore tag to me?

yup, and yup

**Comment by matthewdias** [comment]
>default tree for space tag:
This could be achieved by adding something like: kwmc config space display_id space_id tree tag,
and it would just basically perform the tree restore tag command when this space is initialized.

yeah

>restore tree when space is tagged:
This just feels like a kwmc tree restore tag to me?

The desired functionality here is to be able to tag a space during runtime and then have the associated tree restore automatically. I guess this could all be achieved if you could configure an action (in this case running a script with `sys`) that is run when the space is tagged. This probably falls under support for callbacks tho.

**Comment by koekeishiya** [comment]
> The desired functionality here is to be able to tag a space during runtime and then have the associated tree restore automatically. I guess this could all be achieved if you could configure an action (in this case running a script with sys) that is run when the space is tagged. This probably falls under support for callbacks tho.

Maybe I fail to see the full picture here, but would it not work simply calling `kwmc tree restore name` instead of performing `kwmc space --tag name` which would really just perform `kwmc tree restore name` anyway?

**Comment by matthewdias** [comment]
well the difference is that ideally doing `kwmc space --tag name` would let you later do `kwmc query space` (#320) so that for example, when I want to open finder on a tagged space, I can check what the tag is, and open finder at the appropriate directory. Also, it would allow for `kwmc query spaces` which would be useful to add a list of spaces in a bar, for example.

**Comment by koekeishiya** [comment]
Alright, that makes more sense then.
I assume that assigned tags would ideally become a valid option for `space -f ..` and `window -m space ..` as well?

**Comment by matthewdias** [comment]
yeah, anything that normally allows for a space id as an input. quick thought, would this potentially work with font icons as well?

**Comment by koekeishiya** [comment]
>  would this potentially work with font icons as well?

I have no idea really how that would work.

**Comment by koekeishiya** [comment]
> The desired functionality here is to be able to tag a space during runtime and then have the associated tree restore automatically. I guess this could all be achieved if you could configure an action (in this case running a script with sys) that is run when the space is tagged. This probably falls under support for callbacks tho.

Regarding this. Now that we have the ability to chain commands, I feel like the only thing that really needs to be done, is add a command to tag the current space during runtime: `kwmc space -t my_tag`
You could then bind `kwmc bindsym .. space -t my_tag ; tree restore my_tag_layout`

In addition to this, there could be:
`kwmc config space display_id space_id tree default_layout`
`kwmc config space display_id space_id tag default_tag`
`kwmc query spaces`

**Comment by matthewdias** [comment]
Sounds good to me. 👍

As for this:
>recognize apps when saving/restoring tree so that apps are tiled in the same places they were on save (example: on restore, chrome is always tiled first, then sublime, then terminal)

I'll move it to a new issue, since its kind of unreltaed.

**Comment by koekeishiya** [comment]
Kwm does not prevent you from assigning the same name to multiple spaces.
However, the above case will cause problems. I consider this the users responsibility.

```
# Assign default values in kwmrc
kwmc config space display_id space_id tree default_layout
kwmc config space display_id space_id name default_name

# Assign tag to space during runtime
kwmc space -n name

# Get name of active space
kwmc query space active name

# Get name of previously active space
kwmc query space previous name

# Get list of spaces and their tags
kwmc query space list

# Focus space with the given name
# kwmc space -f name will NOT work as this relies fully on OSX shortcuts.
kwmc space -fExperimental name

# Move window to space with the given name
kwmc window -m space name
```

**Comment by chrishoage** [comment]
>  Kwm does not prevent you from assigning the same name to multiple spaces.
> However, the above case will cause problems. I consider this the users responsibility.

Maybe this could be addressed as apart of #285 ?

**Comment by koekeishiya** [comment]
> Maybe this could be addressed as apart of #285 ?

That wouldn't really work as it is not a syntax issue.

**Comment by chrishoage** [comment]
It's not a syntax issue sure, but it is a config validation issue. Any feedback kwmc can give a user about where they made a copy and paste error would be welcome in my opinion.

**Comment by dominiklohmann** [comment]
Yeah, just had a super annoying issue with this as well. By mistake I wrote "kwmc rule" into my kwmrc as a new line, and the next time I restarted Kwm all my windows became permanently invisible. Was not very easy to figure out what happened there...

**Comment by koekeishiya** [comment]
In some sense it could be seen as a validation issue.
By `causing problems` I meant that Kwm would not be able to see the difference between spaces with equal names, it would always act on the first.

Regarding the issue at hand, how would the feedback regarding mistakes in the kwmrc file be shown to the user?

**Comment by chrishoage** [comment]
There would still be come user action required. As described in the ticket there would be some `kwmc validate` command which would scan the loaded `kwmrc` file and spit out any warnings / errors it comes across.

Apart of the readme could contain a "troubleshooting" section which recommends using this command to find out why kwm might not be working.

**Comment by dominiklohmann** [comment]
Write to stderr and/or use OS X notifications.

**Comment by koekeishiya** [comment]
> use OS X notifications.

Can't be done from Kwm. Already tried this for other purposes.

> There would still be come user action required. As described in the ticket there would be some kwmc validate command which would scan the loaded kwmrc file and spit out any warnings / errors it comes across.

Probably the best approach so far.

**Comment by dominiklohmann** [comment]
[This](https://github.com/julienXX/terminal-notifier) works for me for sending notifications from the terminal.

**Comment by koekeishiya** [comment]
I don't think that is worth the effort I'd have to go through, I'd rather just run an applecsript instead.

**Comment by matthewdias** [comment]
`kwmc query space list` reports names incorrectly for spaces.

Also, is it possible to populate the list at startup?

**Comment by koekeishiya** [comment]
> kwmc query space list reports names incorrectly for spaces.

Can you elaborate? works fine for me.

> Also, is it possible to populate the list at startup?

Not really possible, as a space is not initialized by Kwm until switched to.

**Comment by matthewdias** [comment]
on space 8, i do `kwmc space -n test` space 8 is successfully named `test` according to `kwmc query space active name`, but when i do `kwmc query space list`, space 10 shows as `test` and 8 has no tag.

**Comment by koekeishiya** [comment]
> on space 8, i do kwmc space -n test space 8 is successfully named test according to kwmc query space active name, but when i do kwmc query space list, space 10 shows as test and 8 has no tag.

This probably happens because fullscreen applications count as a space.

**Comment by matthewdias** [comment]
Tried it again after restarting kwm with no fullscreen apps, and got the same result

**Comment by matthewdias** [comment]
Could we also get a command to remove a space name?
