### ISSUE TITLE
"a" key no longer works

### ISSUE THREAD

**Issue by MatanSilver** [koekeishiya/kwm#254]
New user here. After adding kwm to launchd it seems that the "a" key no longer works in any application. unloading the service fixes things, but of course ends the kwm process. Any ideas why this might happen?

**Comment by MatanSilver** [comment]
I had installed using homebrew, and symlinked the plist into the Library/LaunchAgents, then launchctl load -w ......

**Comment by koekeishiya** [comment]
duplicate #243
