### ISSUE TITLE
How to setup prefix keys?

### ISSUE THREAD

**Issue by ranranking** [koekeishiya/kwm#255]
Hi, I homebrew installed kwm. The a key is not working. From https://github.com/koekeishiya/kwm/issues/243 I can see that it was because the prefix key is not setup. I try to set it as `ctrl-x` using `kwmc config prefix`, but I am not exactly sure how to do this. In the`/usr/local/Cellar/kwm/1.1.4/kwmrc`, I can see `kwmc config prefix ctrl-x`, so I think maybe the prefix is already setup? In addition, I saw that you have committed not to block a key if prefix is not setup, to have this feature, do I have to build kwm from source?

**Comment by koekeishiya** [comment]
>  In addition, I saw that you have committed not to block a key if prefix is not setup, to have this feature, do I have to build kwm from source?

Yes, the Homebrew version uses the v1.1.4 tag. To get the latest changes, you have to compile from source.

To set up a prefix key, the syntax is `kwmc config prefix ctrl-x` or `kwmc config prefix-key ctrl-x` depending on which version of Kwm you are running.

**Comment by ranranking** [comment]
Thank you, the first syntax helped. I was using the `kwmrc` file from the example folder, and it was using the second syntax. What I don't understand is in the location where homebrew kwm is installed, `/usr/local/Cellar/kwm/1.1.4`, there is also a `kwmrc`. In this file, the prefix key is set using the first syntax. But this file seems to be not working. I am not sure why. But thank you again, I will close the issue.

**Comment by dominiklohmann** [comment]
To view the source code for the homebrew version, go to the 1.1.4 tag on github: https://github.com/koekeishiya/kwm/tree/v1.1.4

The current master branch is 19 commits ahead.

**Comment by koekeishiya** [comment]
The kwmrc file that Kwm is using, is always located at $HOME/.kwm/kwmrc
The kwmrc file located in the homebrew folder, is just a copy of examples/kwmrc for that version.
