### ISSUE TITLE
kwm-overlay doesn't start when installed from homebrew-binary (1.1.5)

### ISSUE THREAD

**Issue by twouters** [koekeishiya/kwm#258]
kwm-overlay exits with the following error:

~~~
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /usr/local/Cellar/kwm/1.1.5/kwm-overlay
  Reason: Incompatible library version: kwm-overlay requires version 1.0.0 or later, but libswiftAppKit.dylib provides version 0.0.0
~~~

**Comment by twouters** [comment]
Seems to work after latest Xcode upgrade.
I guess it's caused by the new binary package being build using the newer Xcode version, is there some way to provide compatibility with older versions?

**Comment by koekeishiya** [comment]
I really have no idea, I don't program in Swift. The build flags that are used to compile the kwm-overlay app does not specify any specific version, it simply links to Xcode command line tools.
