### ISSUE TITLE
Function keys (F19) in kwm keybind

### ISSUE THREAD

**Issue by ma-con** [koekeishiya/kwm#259]
I'm trying to configure kwm to suit my needs, and ran into a problem.

I have remapped my caps lock key to f19, which I now want to use in keybinding for kwm. 
For example I want to have f19+hjkl to focus windows.
The command 
kwmc bind f19-h window -f west
however does not seem to work as I expect it. Instead of focusing the window west when pressing f19 and h, focus shifts whenever h is pressed even without pressing f19.

When f19 is combined with another key, the keybinding seems to work as expected, shifting windows for example works with 
kwmc bind f19+shift-h window -s west

What am I doing wrong here?

**Comment by koekeishiya** [comment]
> What am I doing wrong here?

Nothing, actually I'm curious as to why `kwmc bind f19+shift-h window -s west` works, as `kwm bind` actually does not support any functions keys iirc.

Will see if this is doable without too much work.

**Comment by ma-con** [comment]
I see, thanks for the clarification.
And of course I was wrong, the binding` kwmc bind f19+shift-h window -s west` doesn't really work, it just seemed to work because I pressed shift..

**Comment by koekeishiya** [comment]
Functions keys can now be used in binds. However, it won't work the way you want it to.
This is because the funtion keys is a key and not a modifier, thus they must fill the `key` part of `kwmc bind prefix+mod+mod+mod-key ..`

Keys can not be used as modifiers for other keys, so `kwmc bind f19-h ..` would not work.

I assume what you originally wanna do is turn CapsLock into a Hyper.
 I've seen people do this by mapping CapsLock to Shift+Ctrl+Option+Command.
You would then have to bind it in kwm like this: `kwmc bind cmd+shift+alt+ctrl-key ..`

**Comment by ma-con** [comment]
Thanks for the update!
I have it running now just the way you described it. I have CapsLock mapped into F19 which in turn is mapped into cmd+shift+option. I just thought that if F19 could be used as a modifier (sorry for not being clear on that) I could use it in combination with other modifiers and use just a few keys with different modifiers (without running into conflicts with shortcuts from other programs).
Nevertheless, kwm works great for me, thanks for all the work!

**Comment by andreaspada** [comment]
In regard that, I found that it could be very useful to use hyper 
(ctrl+alt+shift+cmd) as the prefix, without pairing it with any key. In 
such ways, it could be speed a lot...
Is it possible?


koekeishiya wrote:
>
> Functions keys can now be used in binds. However, it won't work the 
> way you want it to.
> This is because the funtion keys is a key and not a modifier, thus 
> they must fill the |key| part of |kwmc bind prefix+mod+mod+mod-key ..|
>
> Keys can not be used as modifiers for other keys, so |kwmc bind f19-h 
> ..| would not work.
>
> I assume what you originally wanna do is turn CapsLock into a Hyper.
> I've seen people do this by mapping CapsLock to Shift+Ctrl+Option+Command.
> You would then have to bind it in kwm like this: |kwmc bind 
> cmd+shift+alt+ctrl-key ..|
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/koekeishiya/kwm/issues/259#issuecomment-202085317>
>

-- 

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Andrea Spada :: Liuteria d'Autore
www.andreaspada.com

CNPJ: 12.027.966/0001-00
CPF: 054.545.977-08
IM: 0.586.554.9
