### ISSUE TITLE
Setting hotkeys through .kwmrc

### ISSUE THREAD

**Issue by a-morales** [koekeishiya/kwm#26]
It would be useful to just be able to set hotkeys through the `.kwmrc` file instead of modifying `hotkeys.cpp` and recompiling. Something like

```
kwmc bind ctrl+alt+cmd-t focus -t toggle
kwmc bind ctrl+cmd+alt-q quit
kwmc bind cmd+alt-t space -t toggle
```

**Comment by koekeishiya** [comment]
Currently I have no plans of changing the hotkeys system.
While I do agree that this seems like a much more user friendly way to approach this kind of functionality, it will put pretty strict limits on what users can and cannot do.

The current system allows the user to extend by writing C code to write conditions and what not, and so a given hotkey can actually do many tasks depending on things happening on the users system.

**Comment by chrishoage** [comment]
[Something like bspwm might be interesting to see](https://github.com/baskerville/bspwm/blob/master/examples/sxhkdrc). 

I agree that having the hotkey-system being code is powerful, but it makes the config far less portable. If one wanted to use the same hotkey config on different systems they would either have to fork this project or have a special compilation step during install. This makes using package managers like Homebrew a little awkward. 

Using some sort of configuration file or simple scripting language that is interpreted at run time would allow for people to easily maintain a single config across systems.

**Comment by koekeishiya** [comment]
I'll see if I can implement something similar to `kwmc bind keys command` that can be placed in .kwmrc, while still keeping the live-coded hotkey system intact.

**Comment by koekeishiya** [comment]
You can now create binds using the command `kwmc bind mod+mod+mod-key command` and `kwmc unbind mod+mod+mod-key`.  

Example: `kwmc bind cmd+alt-l window -f next`  
You can also bind keys to perform a system command by using the 'sys' prefix as previously.  
Example to launch iTerm: `kwmc bind cmd+alt+ctrl-return sys open -na /Applications/iTerm.app`
