### ISSUE TITLE
kwm updates border for non-managed space

### ISSUE THREAD

**Issue by cHoco** [koekeishiya/kwm#260]
When an application has multiple windows, and one of them is in native fullscreen, switching from the non fullscreen to the fullscreen one triggers a `kAXFocusedWindowChangedNotification` that in turn executes `SetKwmFocus(`) and finally updates the border. Since there are multiple point where we can check for this and I'm not sure which one you'd prefer I haven't opened a pull request.

**Comment by koekeishiya** [comment]
Should probably be handled within `SetKwmFocus()`, I really should refactor this part of the code soon as well, to remove most of the duplication. Thanks for letting me know.

**Comment by cHoco** [comment]
Hi, I still get this with latest changes, but not constantly.
The codepath that triggers the problem is still the same as described above. I think the issue arises when the focus change notification is triggered after the space transition is detected, and so SetKwmFocus is still called :(

**Comment by koekeishiya** [comment]
Would you mind patching it (wherever you think makes sense) and submit a PR?
Looking into revamping `kwmc config float` and implementing a rule system.
