### ISSUE TITLE
Release 1.1.5 broken (homebrew) broken?

### ISSUE THREAD

**Issue by AhmedAA** [koekeishiya/kwm#261]
Title says it all.

My prefix key is broken (tried reverting to default, still broken).
The padding is not respected at all, windows are taking as much of the screen as possible.

I can't seem to find any other information related to this issue. I even tried reverting to 1.1.4 in brew, but it refuses to run that even (but that is probably just an issue with me not fully engaging in brew).

It doesn't matter whether I use my own config, or the example. Yields same result.

If I don't auto hide the menu bar, then it adjusts the window size to the border of where the bar starts.

Any ideas why this happens? :S

**Comment by dominiklohmann** [comment]
From the [1.1.5 release notes](https://github.com/koekeishiya/kwm/releases/v1.1.5): 

> Changed syntax of quite a few kwmc commands

**Comment by AhmedAA** [comment]
@dominiklohmann Thanks for your answer.
Like I stated, it doesn't matter whether I use my own config, or the example config. It's the same problem that comes.
Also, I keep my config up to date with the one shipped from the example every time I update :)

See attached.
Also, I just tested with padding manually through `kwmc space -p increase top 30`
Works just fine.

<img width="1680" alt="screen shot 2016-03-25 at 14 02 19" src="https://cloud.githubusercontent.com/assets/1724181/14044583/7a85ab6a-f292-11e5-912a-453c024f3f77.png">

**Comment by dominiklohmann** [comment]
I was suggesting that because I had the very same issue when still using the old kwmrc when the padding commands got changed - thought it might just have been an oversight on your end.

- Does the same thing happen after restarting kwm? 
- Does it happen on the current master branch?

**Comment by AhmedAA** [comment]
@dominiklohmann Yeah, I appreciate it! (not trying to be a dick at least, just trying to eliminate possibilities to narrow it down).

1: Yes, restarting kwm yields the same.
2: I haven't tried building it myself since I started running it through brew, but I guess it's worth a shot. Will report back.

**Comment by koekeishiya** [comment]
Can you post a gist to the exact kwmrc file you are using?
I tested multiple configs since that change and all of them has worked just fine.

**Comment by AhmedAA** [comment]
@koekeishiya Yeah sensei, I was just stupid.
Sorry...
