### ISSUE TITLE
kwm does not function in recent commits

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#263]
Not sure exactly what changed but I can't get kwm to work anymore in the recent commits. 

When I build in dev mode I get this output 

```
❯ ./bin/kwm
Local Daemon is now running..
DisplayID 441231620 has index 0
DisplayID 69733314 has index 1
```

No tiling happens, nothing gets focus. `read tag` returns `[bsp]` so kwm has started. 

Going to go back though to commits to find one that works

**Comment by koekeishiya** [comment]
I changed the syntax of quite a few commands. You probably have to redo parts of the kwmrc.

**Comment by chrishoage** [comment]
Yeah, I updated after the syntax change. (which reminds me, what do you think of offering warnings for unrecognized commands? or offer a syntax check command in `kwmc`?)

The commit that was working for me is no longer working so something must be up with my system. going for a restart.

**Comment by koekeishiya** [comment]
> Yeah, I updated after the syntax change. (which reminds me, what do you think of offering warnings for unrecognized commands? or offer a syntax check command in kwmc?)

I need to refactor nearly the entire project at this point. Already started this on a local branch. 

The code is no longer separated properly into compilation units like I originally intended to. The interpreter is very prone to causing crashes as it does no form for input validation among other things.
In short, the codebase is a huge mess, but all of it is more or less working properly and there is a lot of features compared to the early stages.

**Comment by chrishoage** [comment]
Everything is working after a restart. Going to blame the system update I installed and forgot to reboot after. 

Sorry!
