### ISSUE TITLE
Release 1.1.5 changes break functionality

### ISSUE THREAD

**Issue by herrbischoff** [koekeishiya/kwm#265]
I just updated kwm via Homebrew and found at least the window padding not working any more. Reviewing #261 and comparing `/usr/local/Cellar/kwm/1.1.5/kwmrc`, I needed to change the following (not recognized) lines:

```
# Set default values for screen padding
kwmc config padding top 40
kwmc config padding bottom 20
kwmc config padding left 20
kwmc config padding right 20

# Set default values for container gaps
kwmc config gap vertical 15
kwmc config gap horizontal 15
```

to the new format

```
# Set default values for screen padding
kwmc config padding 40 20 20 20

# Set default values for container gaps
kwmc config gap 15 15
```

After unloading and loading the LaunchAgent, it again works as expected.

If syntax changes are introduced, those should really be listed in the caveats so we know what to expect. As most people customize their `kwmrc` file (as rc files are for), it should not be assumed that a fresh copy will be used every couple of releases.

Furthermore, as [Semantic Versioning](http://semver.org/) requires:

> Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

as well as

> Major version X (X.y.z | X > 0) **MUST be incremented if any backwards incompatible changes are introduced to the public API**. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

(emphasis mine)

Syntax changes that break previous functionality fall under the latter. Hence, this should have been version 2.0, although it may not feel intuitive for such a comparatively small change.

I'm not trying to be difficult here, just to clear up that proper versioning and heads up information output do have their place and merit.

**Comment by herrbischoff** [comment]
Wow. The more I look through the new `kwmrc`, it looks like every second option was changed to something new. @koekeishiya, this does qualify as a "breaking change". I'm sifting and transferring the new changes line by line right now.

**Comment by koekeishiya** [comment]
The current master has been completel reworked compared to 1.1.5.
The changes in 1.1.5 includes the ones you have above, as well as `kwmc config prefix ..` to `kwmc config prefix-key ..`

**Comment by herrbischoff** [comment]
I'm all for "run fast and break things". All I'm saying is that those changes should be advertised properly so users know what to expect. Since you apparently completely reworked the settings, please consider releasing the upcoming stable version as 2.0.0 to signal breaking changes.

**Comment by koekeishiya** [comment]
To be fair, I do write changelogs between every release where I do mention these things.

**Comment by herrbischoff** [comment]
Absolutely. And I'm completely sympathetic. The Homebrew caveats part should be the maintainer's responsibility anyway. Maybe you can ping him so he becomes aware of this issue.

Still, as you're obviously using semantic versioning (x.x.x), I'd really appreciate sticking to the guidelines as opposed to incrementing at will. In the end, you're of course free to do as you please. In the interest of clearer communication, correct SemVer would be great.

Whatever comes from this, thank you for continuing to work on and improve my favorite window manager ever.

**Comment by koekeishiya** [comment]
> Still, as you're obviously using semantic versioning (x.x.x), I'd really appreciate sticking to the guidelines as opposed to incrementing at will. In the end, you're of course free to do as you please. In the interest of clearer communication, correct SemVer would be great though.

I suppose I should be doing that, yeah.

**Comment by chrishoage** [comment]
SemVer wouldn't save you from breaking changes. It's not like homebrew has NPM style version pinning, not shows you what version will be installed before you do an `brew upgrade kwm` 

I don't really care how kwm is versioned I just wanted to point out one thing. 

> The Homebrew caveats part should be the maintainer's responsibility anyway. Maybe you can ping him so he becomes aware of this issue.

The caveats section is not to be used for anything other than post-install instructions. I originally had `kwm requires Accessibility Permissions` in the caveats and was told to remove it before it was added to homebrew/binaries so they certainly wouldn't' go for release notes being added to the caveats sections.

**Comment by herrbischoff** [comment]
That for your comment, @chrishoage. I would argue that SemVer would be even more important under these circumstances. You would know what kind of changes you'd have to expect by upgrading without checking the website for every minor version iteration. Imagine doing this for dozens of software packages every time you update. Don't get me wrong: breaking changes are and should be completely expected as software progresses. Just not within the same major version.

Besides, *there is* indeed a version pinning function, appropriately named `brew pin/unpin`.
From `man brew`:

```
pin formulae
              Pin  the  specified  formulae,  preventing  them  from  being upgraded when issuing the brew
              upgrade command. See also unpin.
```

**Comment by chrishoage** [comment]
Sorry, I should have been more clear, I mean "npm style" pinning. Ala `~1.1.0` would mean only minor versions will be installed and major versions would be skipped with out user intervention. That does not exist in homebrew.

You are correct, you are able to pin a package. However it is pinned at _that_ version, not minor versions. Which isn't super helpful with what you are talking about.

**Comment by herrbischoff** [comment]
Ah, ok. I see what you mean. That *would* indeed be a helpful function if Homebrew did that.

**Comment by chrishoage** [comment]
Yeah, it would. But so many packages in homebrew don't follow SemVer it would be pretty meaningless, which is why I made the assertion that SemVer wouldn't be super helpful in this situation. 

As I mentioned previously, I don't really care how kwm is versioned, I just wanted to point out that the change log can not be placed in the `caveats` section of the Homebrew Formula.

**Comment by koekeishiya** [comment]
I have nothing against following SemVer and can start doing so from now on. The version tag, for me personally, was only added such that Homebrew had a valid test case (`kwm --version`).

**Comment by herrbischoff** [comment]
@koekeishiya: Thanks for considering this. I'll be very glad to see this versioned in a sane way. Also, I hope I'm not coming across as too pushy, as this is all volunteer/passion work after all.
