### ISSUE TITLE
Default prefix-key breaks Vim

### ISSUE THREAD

**Issue by herrbischoff** [koekeishiya/kwm#266]
I'm using terminal Vim (Neovim that is) and found that the default prefix-key setting of Ctrl-X breaks Vim's autocompletion (Ctrl-X Ctrl-O) as well as every command relying on Ctrl-X. This is because kwm intercepts the keystrokes before they reach the Terminal. In this regard it does exactly what it should be doing, just the default setting is somewhat unfortunate.

There should either be a setting in which active applications the prefix-key should be ignored, much like the floating application window exceptions, or the default should be changed.

I know that all kinds of programs use all kinds of shortcuts that could interfere with any kind of default setting. Seeing that kwm caters to a more terminal-centric crowd anyway, I feel Vim should be considered with some weight.

**Comment by andreaspada** [comment]
Personally, I find that the prefix setup could be allow just a modifier - as hyper (ctrl+shift+alt+cmd), which is as I have remapped my caps lock, or anything else. There's also nano, which suffer from a similar problem (ctrl+x is used to close it). I almost do use just vim, but there's a remote server I logon every while which have only nano available...
Well, is just a matter to remap the prefix to something else - ctrl+/, alt+a... - but j really would love to have just a predefined modifier or function key to do this job. It certainly will not interfere with no app at all.

Enviado do meu iPhone

**Comment by koekeishiya** [comment]
From my pov it doesn't matter what the sample configuration includes, I simply put my own config there (with exceptions to binds that do not relate to Kwm). If you have any ideas as to what would make a better default bind, I'm open for that.

I consider the default kwmrc as a `must change` for anyone. It is simply there to provide an example for people that may not be all that familar with tiling wms.

**Comment by koekeishiya** [comment]
> Personally, I find that the prefix setup could be allow just a modifier - as hyper (ctrl+shift+alt+cmd), which is as I have remapped my caps lock, or anything else. 

Kwm does not intercept at a low enough level to be able to modify keys such as Caps Lock.
There used to be the possibility of remapping keys back in beta, but it was never used so I decided it was not worth maintaining. I think this was the correct choice, considering applications such as Karabiner does this way better than I could with Kwm.

The prefix-key is also optional, simply remove the `kwmc config prefix-key ..` line if you do not use/need it.

**Comment by koekeishiya** [comment]
I've changed the sample prefix-key to `ctrl-s`. See #283 regarding variables in kwmrc.

**Comment by koekeishiya** [comment]
Variables has been implemented, see #283 for details
