### ISSUE TITLE
Rules depending on the program / window title

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/kwm#268]
Hi,

Kwm allows to force some programs to float, but is it possible to force some sub windows to float ?

Mainly, I have some problems with my IDE (Jetbrains products like PyCHARM or PHPSTORM). Each time a new window is popped (like create new file, search...) kwm try to tile the whole windows, but the new window get off-screen in my configuration.

Any hints or workarounds to prevent this behaviour, I would love that my main IDE window tiles properly but its sub windows are left to float.

Thanks again for this incredible project !

**Comment by koekeishiya** [comment]
The only unique window identifier I have is a `window id`, which changes every time a window is closed and reopened.There is no way to track a window through the process of being closed and reopened that I'm aware of.

If the window is not caught by using `kwmc config float-non-resizable on`, then this is not possible at the moment.

**Comment by mickaelperrin** [comment]
`kwmc config float-non-resizable` is enabled in my config file, so no luck there...

On Linux (awesome-wm), I was used to write rules depending on the program / the class / the window title...

By mixing a program identifier and a regexp rule on the title, it would be possible to force some windows to float, but I didn't know if it is possible and the amount of work that represents.

**Comment by mickaelperrin** [comment]
`kwmc config float-non-resizable` is enabled in my config file, so no luck there...

On Linux (awesome-wm), I was used to write rules depending on the program / the class / the window title...

By mixing a program identifier and a regexp rule on the title, it would be possible to force some windows to float, but I didn't know if it is possible and the amount of work that represents.

**Comment by mickaelperrin** [comment]
`kwmc config float-non-resizable` is enabled in my config file, so no luck there...

On Linux (awesome-wm), I was used to write rules depending on the program / the class / the window title...

By mixing a program identifier and a regexp rule on the title, it would be possible to force some windows to float, but I didn't know if it is possible and the amount of work that represents.

**Comment by mickaelperrin** [comment]
`kwmc config float-non-resizable` is enabled in my config file, so no luck there...

On Linux (awesome-wm), I was used to write rules depending on the program / the class / the window title...

By mixing a program identifier and a regexp rule on the title, it would be possible to force some windows to float, but I didn't know if it is possible and the amount of work that represents.

**Comment by mickaelperrin** [comment]
`kwmc config float-non-resizable` is enabled in my config file, so no luck there...

On Linux (awesome-wm), I was used to write rules depending on the program / the class / the window title...

By mixing a program identifier and a regexp rule on the title, it would be possible to force some windows to float, but I didn't know if it is possible and the amount of work that represents.

**Comment by mickaelperrin** [comment]
`kwmc config float-non-resizable` is enabled in my config file, so no luck there...

On Linux (awesome-wm), I was used to write rules depending on the program / the class / the window title...

By mixing a program identifier and a regexp rule on the title, it would be possible to force some windows to float, but I didn't know if it is possible and the amount of work that represents.

**Comment by mickaelperrin** [comment]
`kwmc config float-non-resizable` is enabled in my config file, so no luck there...

On Linux (awesome-wm), I was used to write rules depending on the program / the class / the window title...

By mixing a program identifier and a regexp rule on the title, it would be possible to force some windows to float, but I didn't know if it is possible and the amount of work that represents.

**Comment by mickaelperrin** [comment]
`kwmc config float-non-resizable` is enabled in my config file, so no luck there...

On Linux (awesome-wm), I was used to write rules depending on the program / the class / the window title...

By mixing a program identifier and a regexp rule on the title, it would be possible to force some windows to float, but I didn't know if it is possible and the amount of work that represents.

**Comment by mickaelperrin** [comment]
`kwmc config float-non-resizable` is enabled in my config file, so no luck there...

On Linux (awesome-wm), I was used to write rules depending on the program / the class / the window title...

By mixing a program identifier and a regexp rule on the title, it would be possible to force some windows to float, but I didn't know if it is possible and the amount of work that represents.

**Comment by mickaelperrin** [comment]
`kwmc config float-non-resizable` is enabled in my config file, so no luck there...

On Linux (awesome-wm), I was used to write rules depending on the program / the class / the window title...

By mixing a program identifier and a regexp rule on the title, it would be possible to force some windows to float, but I didn't know if it is possible and the amount of work that represents.

**Comment by mickaelperrin** [comment]
`kwmc config float-non-resizable` is enabled in my config file, so no luck there...

On Linux (awesome-wm), I was used to write rules depending on the program / the class / the window title...

By mixing a program identifier and a regexp rule on the title, it would be possible to force some windows to float, but I didn't know if it is possible and the amount of work that represents.

**Comment by mickaelperrin** [comment]
`kwmc config float-non-resizable` is enabled in my config file, so no luck there...

On Linux (awesome-wm), I was used to write rules depending on the program / the class / the window title...

By mixing a program identifier and a regexp rule on the title, it would be possible to force some windows to float, but I didn't know if it is possible and the amount of work that represents.

**Comment by koekeishiya** [comment]
> By mixing a program identifier and a regexp rule on the title, it would be possible to force some windows to float, but I didn't know if it is possible and the amount of work that represents.

This should be possible. I could implement a rule system that works on the title of a specific program,  however I have very little knowledge about regexp so maybe it is better if someone else implemented this and submitted a PR.

**Comment by koekeishiya** [comment]
This system would replace the old `kwmc config float` option.

**Comment by koekeishiya** [comment]
The current system allows for very basic matching and is really just a replacement for
`kwmc config capture` and `kwmc config float` at this time.

**Comment by mickaelperrin** [comment]
Thanks so much for implementing this.

However, I encounter some problems when trying to use it.

I launch for example the command ```kwmc rule owner="iTerm2" properties={float="true"}``` and then launch a new iTerm window with ``cmd+Enter``, but this window tiles and does not float.

To resolve my problem with my IDE, I launch ```kwmc rule owner="PhpStorm" name="New File" properties={float="true"} ```, but the new file window still tiles.

Am I doing something wrong ?

**Comment by koekeishiya** [comment]
The `owner` or `name` you are providing is most likely not the correct one. You can use the command `kwmc query windows` to get the appropriate information for windows that are currently visible.

**Comment by mickaelperrin** [comment]
Sorry for busying you with this, but I am still unable to get rules working.

**Test scenario:**
1) Launch iterm with Cmd+Enter
2) Run `kwmc query windows`

> 6227, iTerm2, /Users/mickaelperrin/Github/kwm (zsh)
4815, Google Chrome, Rules depending on the program / window title · Issue #268 · koekeishiya/kwm

3) Type in iterm `kwmc rule owner="iTerm2" properties={float="true"}``
4) Launch a new iTerm with Cmd+Enter

**Result :** A new iTerm2 window is opened and is tilled
**Expected result :** a new iTerm2 is opened and is floating

**System information:**
- HEAD version of kwm
- [Kwmrc file](https://gist.github.com/mickaelperrin/ecf1694d0bd9c7507bde8314485b59f2)

Am I missing something ??

**Comment by koekeishiya** [comment]
> 3) Type in iterm kwmc rule owner="iTerm2" properties={float="true"}`

If you are typing this in a shell, you need to escape `"`
It should look like this:`kwmc rule owner="\"iTerm2"\" properties={float="\"true"\"}`

**Comment by mickaelperrin** [comment]
Wow, I didn't expect a such fast answer.

And, that works ! 

Thanks 👍
