### ISSUE TITLE
Regressions, confusion, and docs

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#270]
I've been avoiding upgrading due to the syntax changes and finally did today and have noticed quite a few issues. 

1. 746b35b7034f9ed74d0b3fa839480c3dac0d50fa commit message has radius is obsolete. Looking though the code of kwm-overlay radius is still very much consumed by kwm-overlay. Why was this removed?? 
2. The `cycle-focus screen` bug is back. It cycles across displays again. 

The new docs are _very_ confusing, and even incomplete in some areas. 

```
 Manage window-tree
        kwmc tree <opt>
        <opt>: rotate <arg1> | save <arg2> | restore <arg2>
        <arg1>: 90 | 180 | 270
        <arg2>: filename
```

This syntax for the docs is incredibly difficult to parse. I can't see any reason to organize it like this. `arg1` and `arg2` are very confusing, since they are always actually `arg2`

```
 Rotate the windows in the current focused space clockwise
        kwmc tree rotate <arg>
            <arg>: 90 | 180 | 270
Save the current window size layout of the focused space 
       kwmc tree save <arg>
            <arg>: filename        
Restore the saved window size layout to the focused space
        kwmc tree restore <arg>
            <arg>: filename        
```
 
Something like that is much easier to read and parse as an end user of the tool. I understand it's more verbose, but `Manage window-tree` doesn't mean a whole lot to an end user. 

`swap -window` is missing `mark` 

`node -window` is confusing. An end user does not understand what a "node" is or that it relates to a root node of a binary space partition tree. 

I don't understand the need for the `-` anymore in the commands (for example `focus -window`). Before it made a bit more sense, as they visually appeared as flags. Is there something that makes the `-` necessary and not `focus window`?

`node -window` vs `focus -sub-window`. Again, "node" is confusing with out any explanation. "node" is pretty ambiguous. Then the node is referred to as a -sub-window` with no indication that they are the same thing. 

Still going though my kwmrc file and updating it to the new syntax I'll report anything else I find here. It's been a little bit frustrating upgrade process so far.

**Comment by koekeishiya** [comment]
The new command syntax is very much still in progress. I'm in the first iteration, where I simply wanted to port the existing functionality to a different format. The interpreter as it has been used previously will be removed, as I'm thinking going to be writing a proper parser/pre processor.

**Comment by chrishoage** [comment]
> The radius value has not been affecting how the border was drawn, ever since that commit that added InsetRect.

This is not a true statement.

Top screenshot is a radius of 8. Bottom screenshot is a radius of 18. I reverted to the commit right before you removed support for the radius. I urge you to please revert that change. 

<img width="62" alt="screen shot 2016-03-27 at 3 12 31 pm" src="https://cloud.githubusercontent.com/assets/1056886/14068127/6304ea8a-f42e-11e5-9abe-1600fbc4e36e.png">
<img width="57" alt="screen shot 2016-03-27 at 3 12 20 pm" src="https://cloud.githubusercontent.com/assets/1056886/14068128/6314e688-f42e-11e5-9270-c2e47039ebb2.png">


> I would suggest you remain at the 1.1.5 release as well, unless there has been a fix since that you really need.

I really don't mind living on the bleeding edge, it allows me to catch things like the radius issue and help report bugs during refactors. I'm just reporting my findings from after the syntax change from an end user perspective in hopes to help shape the kwm user experience.

**Comment by chrishoage** [comment]
The cycle-focus regression I am referring to is #233

**Comment by koekeishiya** [comment]
> Top screenshot is a radius of 8. Bottom screenshot is a radius of 18. To test this I reverted to the commit right before you removed support for the radius. I urge you to please revert that change. 

Pretty sure that it made no impact for me. I will however, revert that change.

> I really don't mind living on the bleeding edge, it allows me to catch things like the radius issue and help report bugs during refactors. I'm just reporting my findings from after the syntax change from an end user perspective in hopes to help shape the kwm user experience. 

This is appreciated, however there are huge changes coming, just figured I should let people know.

**Comment by chrishoage** [comment]
> there are huge changes coming

:+1:  excited to test them :)

**Comment by koekeishiya** [comment]
Regarding kwmc commands, I want to have something like the following in the end:
`kwmc [-flags] <opt> <val>` | `kwmc <opt> <val> [-flags]`

**Comment by chrishoage** [comment]
Does that imply that flags would be able to be used together? Currently no flags can be used together, correct? 

If that is the goal, do you have examples of what flags might be able to be used in a single command?

**Comment by koekeishiya** [comment]
> Does that imply that flags would be able to be used together? Currently no flags can be used together, correct? 

That's one of the things I'm hoping to achieve, yeah.

> do you have examples of what flags might be able to be used in a single command?

There are tons of use cases really, but a specific case could be to focus some window and move it to a space on some display.

**Comment by chrishoage** [comment]
That sounds awesome! Excited to see that develop.

**Comment by koekeishiya** [comment]
Currently I'm thinking something like this:

e.g: 
`kwmc f -w $win_id` focus a window  
`kwmc f -s $space_id` focus a space  
`kwmc fmm -wds $win_id $display_id $space_id` focus a window, move it to diff display and space  

opt:
    f: focus
    m: move
    s: swap
    z: zoom
    r: refresh

flags:
    w: window
    d: display
    s: space

Again, I'm really not sure of the best approach myself yet.

**Comment by koekeishiya** [comment]
I'm kinda curious, is chaining operations like the above example a bad idea?
e.g: `kwmc fmm -wds $win_id $display_id $space_id`
The command is chaining three operations:
 - perform a focus command of type -w | --window 
 - perform a move command of type -d | --display
 - perform another move command of type -s | --space

Is this a bad approach or something I can keep iterating on?

**Comment by chrishoage** [comment]
> is chaining operations like the above example a bad idea? ... Is this a bad approach or something I can keep iterating on?

I most certainly think that it is _not_ a bad idea, I do however think it would make kwm a lot more complicated when it is already having a little trouble with regressions. 

I am curious what the style of chaining you suggest might offer that custom shell commands are not able to offer. 

For example a 

`mycommand.sh`

that contains

```
marked=$(kwmc query current)
kwmc focus --window $marked
kwmc move --display $1
kwmc move --space $2
```

`kwmc bind prefix-v sys mycommand 1 3`

It's much more verbose, but keeps the chaining in terms of simple `kwmc` commands, reducing the complexity.

**Comment by koekeishiya** [comment]
> I am curious what the style of chaining you suggest might offer that custom shell commands are not able to offer. 

No difference really that I can think of. It's just less verbose, and doesn't require a shellscript every time.

**Comment by chrishoage** [comment]
Yes, the old syntax did look a little nicer for sequential commands. My opinion is that streamlining the shell script system would offer a little more power, while keeping the  overall complexity relatively low. 

If we could somehow figure out an easier way to supply `kwmc` to the shell scripts, or even better the users `$PATH` with out having to resort to asking users to set up [a launch service to set it](http://apple.stackexchange.com/questions/106355/setting-the-system-wide-path-environment-variable-in-mavericksl) that would make the shell scripts even more useful. Right now there is a bit of boilerplate that could be removed that might make the shell scripts more useful.

**Comment by koekeishiya** [comment]
> Yes, the old syntax did look a little nicer for sequential commands. My opinion is that streamlining the shell script system would offer a little more power, while keeping the overall complexity relatively low. 

Guess I'll just go for this for now, and revert back to the old command style, as that gives me more time to work on the window rule system.

**Comment by koekeishiya** [comment]
Commands now follow the old pattern, but the provided flags should make more sense.
There have changes to the `kwmc config focus` commands as well.

I'll leave it like this and if/when I decide to change things I'll do them on a separate branch at the start.
