### ISSUE TITLE
Is it possible to disable focus-follows-mouse feature?

### ISSUE THREAD

**Issue by ranranking** [koekeishiya/kwm#271]
I set `kwmc config focus off`, `kwmc config focus mouse-follows off`, and ` kwmc config focus standby-on-float off`, but the window focus still follows the mouse. What is the right way to do this?

**Comment by koekeishiya** [comment]
`kwmc config focus off` disables focus-follows-mouse.
`kwmc config mouse-follows off` disables mouse-follows-focus.
You need to reload the config (`kwmc config reload`) or restart kwm for changes to take effect.

**Comment by ranranking** [comment]
The second command works. There are some syntax differences in the example config file. In the file, it is `kwmc config focus mouse-follow`. Do you have documents for changed configuration syntaxes?

**Comment by koekeishiya** [comment]
> The second command works. There are some syntax differences in the example config file. In the file, it is kwmc config focus mouse-follow. Do you have documents for changed configuration syntaxes? 

It is indeed `kwmc config focus mouse-follow`. I was too quck on this one, sorry about that.

**Comment by ranranking** [comment]
Oh, then the one that is working must be the old one. Thank you for your help!
