### ISSUE TITLE
Something weird happens... kwmc do not work anymore!

### ISSUE THREAD

**Issue by andreaspada** [koekeishiya/kwm#278]
Hi! Yesterday I synchronised from master, compiled and installed, but after that, kwmc simply do not work anymore. kwm starts, most keybinding works - not space switching related, though - and kwmc do not work at all. It doesn't display any information, at all.
I missed something important?

**Comment by chrishoage** [comment]
The keybindings changed a lot in the past week or so. There is no validation of the `kwmrc` for unrecognized commands, so ensure that all your commands are correct by looking though the documentation. https://github.com/koekeishiya/kwm/tree/master/kwmc

I hope that there is a config validator added soon with all the changes that have been happening to the syntax. It would make tracking down these issues less tedious.

**Comment by andreaspada** [comment]
Great, thanks for pointing me to the right directions. Indeed, I missed 
the change from -s to -m, and also did not realized that kwmc changed so 
much.
Thanks!
Andrea

Chris Hoage wrote:
>
> The keybindings changed a lot in the past week or so. There is no 
> validation of the |kwmrc| for unrecognized commands, so ensure that 
> all your commands are correct by looking though the documentation. 
> https://github.com/koekeishiya/kwm/tree/master/kwmc
>
> I hope that there is a config validator added soon with all the 
> changes that have been happening to the syntax. It would make tracking 
> down these issues less tedious.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/koekeishiya/kwm/issues/278#issuecomment-204076193>
>

-- 

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Andrea Spada :: Liuteria d'Autore
www.andreaspada.com

CNPJ: 12.027.966/0001-00
CPF: 054.545.977-08
IM: 0.586.554.9
