### ISSUE TITLE
Question: does working space mean different monitors?

### ISSUE THREAD

**Issue by ranranking** [koekeishiya/kwm#279]
I tried to write a start file. But the `kwmc space -f id ` seems not working. I though it was about different monitors if I am correct. If it is not ,what does working space mean? If I am wrong, how do I open applications in different monitors in startup file?

**Comment by chrishoage** [comment]
`space -f` focus a space on the display that has the current focus
`display -f` focuses the display. 

https://github.com/koekeishiya/kwm/tree/master/kwmc

**Comment by koekeishiya** [comment]
workspace_id means space id, or desktop as they are also known as in OSX.
See chrishoage's comment for the current commands
