### ISSUE TITLE
Should focus app when switching spaces

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#281]
When you switch to a space via an app using the dock or command-tab, kwm retains the focus of the app that was previously focused on the space by design. I think it would make more sense to override this and focus the selected app in these cases.

**Comment by koekeishiya** [comment]
> I think it would make more sense to override this and focus the selected app in these cases.

Agreed, however, there is no clear way to differentiate between these cases. Not saying it is impossible, but it requires some creative thinking.

**Comment by matthewdias** [comment]
Im guessing itd have to be something like,
- Keep track of the most recently-selected app (don't know if this is possible)
- After space transition, focus first window owned by that app on the space

**Comment by koekeishiya** [comment]
> Keep track of the most recently-selected app (don't know if this is possible)

How would you know if this app was selected through the dock / cmd+tab and not just the last focused app before the user did a space-transition by himself

**Comment by matthewdias** [comment]
true. you got me there xD

**Comment by matthewdias** [comment]
this could be a candidate for code injection, unless theres some other unknown api for recognizing dock clicks and command-tab activations

**Comment by koekeishiya** [comment]
I think I may have an easy fix for this.

**Comment by koekeishiya** [comment]
Should be working now.

**Comment by matthewdias** [comment]
all good here.

**Comment by mickaelperrin** [comment]
Indeed that works, but should it be possible to focus the application under the mouse pointer ? or to focus the "master" window of the space ?

**Comment by koekeishiya** [comment]
> Indeed that works, but should it be possible to focus the application under the mouse pointer ? or to focus the "master" window of the space ?

This is easy to change if you edit line 264 @ [kwm/space.cpp](https://github.com/koekeishiya/kwm/blob/master/kwm/space.cpp#L264) and perform `FocusWindowBelowCursor()`

Earlier on, Kwm did use `FocusWindowBelowCursor()` for this, but due to requests I changed it to the behaviour it currently has.

**Comment by mickaelperrin** [comment]
Thanks for your update. Finally, after playing around, I finally understood that the window which was selected was last focused window. This is indeed a good default setting, that prevents moving the mouse after each space change.

**Comment by mickaelperrin** [comment]
Is this feature still supported with kwm 3.0.0 ? After each space change, if I don't click in the app the focus is still on the previously focused window.

For example, when I switch from iTerm (space 1) to my IDE (space 2). Space 2 is active, but the keys are displayed inside iTerm till I click with the mouse.

**Comment by koekeishiya** [comment]
In v3.0.0, OSX controls focus.

**Comment by mickaelperrin** [comment]
Ok, so problem seems to be related to the "experimental" quick space change. OSX does'nt understand that space has changed :(

**Comment by koekeishiya** [comment]
> Ok, so problem seems to be related to the "experimental" quick space change. OSX does'nt understand that space has changed :(

Try the latest commit. I've added a special case for the experimental space transition, that will try to focus the window that OSX would have given focus to.

I will not guarantee that this always works, but it should in most cases. Hopefully this works out good enough.

**Comment by mickaelperrin** [comment]
Thanks, that works ! 👍

**Comment by benjaminwood** [comment]
Thanks for making this work! 

One thing I noticed is that OS X seems to lose track of which space you're on after using the feature. This causes problems when you attempt to use alt-tab to toggle between apps. The app focus is changed properly now, but you're not brought back to the space which contains the app. Any ideas on this? Or workarounds?

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/kwm/issues/304 for information about the space feature.
