### ISSUE TITLE
Syntax validator for kwmrc

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#285]
Mistakes in ones `kwmrc` file can lead to `kwm` not working with out a lot of feedback as to why. 

I propose a `kwmc validate-config` (or some other name) that checks the `kwmrc` file for syntax errors. At minimum for unknown commands. 

Maybe this could be apart of `kwmc config reload` and return validation errors as apart of that command? 

Having to hunt though the kwmrc file for syntax errors can be pretty tedious.

**Comment by koekeishiya** [comment]
Agreed, will be done soon.

**Comment by koekeishiya** [comment]
After working quite a bit on this, I really don't find this worth the time required.
I personally feel like users should just be careful when editing their config.
The config can be made readable by splitting it into multiple files and using the `include` option.

At 3.0.0 release, there will be a stable API that will not change for upcoming releases.

**Comment by chrishoage** [comment]
The only reason I suggested it is due to the influx of support issues for invalid config files. There is _no_ feedback given from kwm / kwmc as to why things are not working, and it is not clear to new users if it is set up wrong, broken, or they have an invalid config file. 

I figured some sort of config validation would help reduce most (all?) of those types of support requests. 

If this is something that you think would be useful but just don't want to do, perhaps go though the tickets and add a `help-wanted` tag on issues that you don't want to / can't work on, to signal to potential contributors what issues they could tackle.

**Comment by koekeishiya** [comment]
I have written a "test" parser for the kwmrc file that does report mistakes (currently only to stderr, but this is easy to redirect to a file or something) for everything except `kwmc bind`. The reason I feel like it is not worth doing, is parsing something like `kwmc bind MyMode+cmd+shift-l exec open -na /Applications/SomeApp.app; mode activate default; space -f 2 {iTerm2, Firefox} -e` using a tokenizer is just ....

**Comment by dominiklohmann** [comment]
Can we get Kwm to throw an error on incomplete commands then? 

Try adding `kwmc rule` at the end of your kwmrc and then try to figure out what is happening, it's madness.

**Comment by koekeishiya** [comment]
I'll finish up the one I have been working on so far. It will validate everything but `kwmc bind` I believe.

**Comment by koekeishiya** [comment]
Ok so whenever `kwmrc` is loaded either on launch, or using `kwmc config reload`, any parsing errors will be written to stderr. The errors will often be skewed due to how parsing works, if you have a lot of syntax errors in early commands, that could potentially cause parsing of later commands to fail.

Comments are no longer prefixed as '#', but use the standard C-style block comments.
```
/* followed by
   some text, formatting
really            Does not matter. */
```

The only commands that require to be written in a single line, are these:
```
define ...
kwmc rule ...
kwmc bind ...
```

The syntax for borders have also changed to
```
kwmc config border focused ..
kwmc config border marked ..

instead of

kwmc config focused-border ..
etc..
```

**Comment by chrishoage** [comment]
> Comments are no longer prefixed as '#', but use the standard C-style block comments.

Is it terribly difficult to support both? (if it is never mind, I just like using `#` for comment headings since I don't need to close them)

**Comment by koekeishiya** [comment]
> Is it terribly difficult to support both? (if it is never mind, I just like using # for comment headings since I don't need to close them)

Should be fairly easy. Do you mind if I make it `//` instead of `#` though?

**Comment by chrishoage** [comment]
> Should be fairly easy. Do you mind if I make it // instead of # though?

Not at all `//` is fine.

**Comment by matthewdias** [comment]
Right now I'm getting a lot of parse errors, after switching to the new comment syntax. Also my `p` key isn't working. 

binds: https://gist.github.com/ef7fc3f369b5b4c224c48fd27bc6e922

**Comment by koekeishiya** [comment]
Probably due to this comment, I suspect:

> /* Rotate Window-Tree By 90* (Clockwise) */

Remove the * behind 90. Probably causing some parsing issue.

**Comment by matthewdias** [comment]
Ah yeah. Doesn't like `/` in comments either. also some of the paths i defined are seeming to give it trouble.
```
 Parse error: Unknown token '/'
  Parse error: Unknown token 'Users'
  Parse error: Unknown token '/'
  Parse error: Unknown token 'Matthew'
  Parse error: Unknown token '/'
  Parse error: Unknown token '.'
  Parse error: Unknown token 'kwm'
  Parse error: Unknown token '/'
  Parse error: Unknown token 'scripts'
  Parse error: Unknown token '/'
  Parse error: Unknown token 'layouts'
  Parse error: Unknown token '*'
  Parse error: Unknown token '/'
  Parse error: Unknown token '/'
  Parse error: Unknown token 'Users'
  Parse error: Unknown token '/'
  Parse error: Unknown token 'Matthew'
  Parse error: Unknown token '/'
  Parse error: Unknown token '.'
  Parse error: Unknown token 'kwm'
  Parse error: Unknown token '/'
  Parse error: Unknown token 'scripts'
  Parse error: Unknown token '/'
  Parse error: Unknown token 'pull'
  Parse error: Unknown token '-'
  Parse error: Unknown token 'e'
  Parse error: Unknown token 'left'
  Parse error: Unknown token '*'
  Parse error: Unknown token '/'
```

**Comment by koekeishiya** [comment]
> Ah yeah. Doesn't like / in comments either. 

That might be a problem, not sure why that would ruin the parsing, but will take a look at it later.

> also some of the paths i defined are seeming to give it trouble.

Not sure why that would be the case, mine work just fine:
```
define ytc /usr/local/bin/ytc
define ~ /Users/Koe
define terminal open -na /Applications/iTerm2.app
```

**Comment by matthewdias** [comment]
Oh okay, it was because i used defined terms in comments. All good now, but my `p` key still doesn't work.

**Comment by matthewdias** [comment]
The culprit is `bindsym-passthrough`.

**Comment by koekeishiya** [comment]
The issue regarding `*` and `/` breaking block-comments should now be fixed.

**Comment by koekeishiya** [comment]
> The culprit is bindsym-passthrough.

Right makes sense, `-` is parsed as its own token.
Syntax has changed to `bindsym_passthrough`. 
Fixed on master.

**Comment by matthewdias** [comment]
So last thing would probably be to ignore definitions until the tokenizer gets past a comment

**Comment by koekeishiya** [comment]
> So last thing would probably be to ignore definitions until the tokenizer gets past a comment

This is kinda tricky as variable expansion is simply a full on `find and replace`.
It will expand the variable even tho it is inside a comment, however it is now properly parsed as a part of the comment and will no longer cause any issues.

Unles you do `define wasd */`
`/* this is a comment wasd */`

**Comment by matthewdias** [comment]
Oh ok, right, the slash thing solves it. 👍

**Comment by mickaelperrin** [comment]
Just updated to the latest commit of master and updated my configuration.

While the use of block comment sounds like an interesting addition, I don't understand why classic `#` comments have been removed.

I may be wrong but config files are mainly shell scripts, so, to my eyes, should support the classical shell comments. In addition, syntax highlighting doesn't work and readability of config files is now harder. 

My 2cts.

**Comment by koekeishiya** [comment]
I have reserved `#` for use as a preprocessor mark, for things that will come in the future.

**Comment by justin-parus** [comment]
> I may be wrong but config files are mainly shell scripts, so, to my eyes, should support the classical shell comments. In addition, syntax highlighting doesn't work and readability of config files is now harder.

I agree. Maybe a different preprocessor mark can be chosen?
