### ISSUE TITLE
Issue running KWM.

### ISSUE THREAD

**Issue by daylerees** [koekeishiya/kwm#286]
```
⋊> ~ /usr/local/Cellar/kwm/1.1.5/kwm                                                                                         10:10:46
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /usr/local/Cellar/kwm/1.1.5/kwm-overlay
  Reason: image not found
```

After installing with homebrew and using default config file.

Thanks!

**Comment by cHoco** [comment]
This might be my bad when I refactored the makefile.
1. Do you have CommandLineTools installed?
2. Can you show the output of this command: `otool -l /path/to/kwm-overlay | grep -A 2 LC_RPATH`

**Comment by DonHansDampf** [comment]
Same problem here. Output of `otool -l /usr/local/opt/kwm/kwm-overlay | grep -A 2 LC_RPATH`:
```
cmd LC_RPATH
      cmdsize 112
         path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx (offset 12)
```

**Comment by cHoco** [comment]
Yep, my fault :cry: https://github.com/koekeishiya/kwm/pull/287 should fix this issue. As a temporary workaround you can either install Xcode, compile from that pull request yourself, or replace the kwm-overlay executable with this one
[kwm-overlay.zip](https://github.com/koekeishiya/kwm/files/206289/kwm-overlay.zip).
Or if you prefer you can just wait for 2.0.2 release 💃

**Comment by DonHansDampf** [comment]
New Error? Used you zip and overwrote kwm-overlay in /usr/local/Cellar/kwm/1.1.5/. 
```
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /usr/local/Cellar/kwm/1.1.5/kwm-overlay
  Reason: Incompatible library version: kwm-overlay requires version 1.0.0 or later, but libswiftAppKit.dylib provides version 0.0.0
```

**Comment by cHoco** [comment]
Can you try this version and see if it works? 
[kwm-overlay.zip](https://github.com/koekeishiya/kwm/files/206521/kwm-overlay.zip)

**Comment by DonHansDampf** [comment]
This one works like a charm and without any errors. :+1:

**Comment by koekeishiya** [comment]
This fix has been added in the latest release.

**Comment by daylerees** [comment]
Thanks for the quick response. :)
