### ISSUE TITLE
allow tiling in monocle mode

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#289]
could be useful to have tiling inside monocle space mode, where you could use the monocle-subtree commands to switch between monocle nodes, and then have bsp trees within each of those nodes. kind of duplicates the functionality of spaces, but might be nice to contain it to one space in some situations (eg. using it with all the windows you need for one project. i like to use spaces to organize the different tasks im working on)

**Comment by chrishoage** [comment]
My opinion is to just improve the spaces behavior as much as possible, there isn't really any need for this feature.

**Comment by matthewdias** [comment]
I agree, if spaces can improved to where everything is seamless (adding and removing spaces, and the stuff from #249), then theres not really a need for this. But imo it might be a good stopgap until that's the case, since there's a lot of work needed there.

**Comment by koekeishiya** [comment]
> if spaces can be improved to where everything is seamless (adding and removing spaces, and the stuff from #249)

Adding and removing spaces will probably never happen due to lack of APIs. The private ones that I've looked into does not expose the behaviour necessary.

**Comment by matthewdias** [comment]
rip.. would be nice if apple at least gave us some keyboard shortcuts for those

**Comment by koekeishiya** [comment]
> would be nice if apple at least gave us some keyboard shortcuts for those

I always have about 6 or 7spaces up at all times and just leave them there for future use.
Not sure how your use differs though.

**Comment by chrishoage** [comment]
If this feature were to exist it would allow for the following scenario: 

A monocle space, which can contain `n` BSP Tree "windows". Each of those trees can contain `n` monocle nodes. 

We would could have A monocle tree inside a bsp tree inside a monocle tree. 

Am I the only one who thinks that is excessive?

**Comment by koekeishiya** [comment]
I honestly do not see the need for this either. I'd rather implement a `tag` system that could allow for flexibility within a single space.
