### ISSUE TITLE
Kwmc bind does not work

### ISSUE THREAD

**Issue by telphan** [koekeishiya/kwm#292]
I have just compiled and installed kwm at release 2.0.0. Launchd starts kwm properly and I can also observe that the process uses my config (the example one present in this repo), but for some reason none of the keybindings work. I am running OSX 10.11.4.
I am not sure what am I missing, any advice?

**Comment by matthewdias** [comment]
2.0.0 or 2.0.1? on 2.0.1 there is a bug caused by the support for using fn as a mod key

**Comment by telphan** [comment]
2.0.0, but still I am not using the fn key.

**Comment by koekeishiya** [comment]
There was some really weird issue where simply adding the code that checks for the `fn` key would cause issues for binds that does not use it. It really did not make any sense so I went ahead and removed it again.

**Comment by koekeishiya** [comment]
Also, make sure that your terminal does not have enabled "Secure Keyboard Entry".

**Comment by telphan** [comment]
Disabling "Secure Keyboard Entry" solved my problem. Thank you.
