### ISSUE TITLE
Main display switches to 1st space on lost focus, which goes to 1st space of secondary display

### ISSUE THREAD

**Issue by alexfedoseev** [koekeishiya/kwm#297]
I have 2 displays. On the display `0` I have 2+ spaces. When I switch to 2nd (or other not 1st) space and then move focus to 1st (and only 1st) space of display `1`, display `0` switches back to 1st space. It only happens in direction display `0` -> display `1`, and only when focus goes to 1st space of display `1`.

`kwm 2.0.2`

**Comment by alexfedoseev** [comment]
Updated to `2.0.3` and issue is gone. Note sure what actually fixed it: update or kwm restart.

**Comment by alexfedoseev** [comment]
Actually it's happening again. I'm not sure how to reproduce it tho.

**Comment by koekeishiya** [comment]
Never had this happening to me. Is there something specific with your workflow?

**Comment by alexfedoseev** [comment]
I guess nothing special. Usually I have around 3-4 spaces on the main display (+ around 2 full screen Atom instances) and 1 space on the secondary display. Not too often I create additional spaces on the main display. Sometimes I connect/disconnect secondary display.

**Comment by matthewdias** [comment]
Isnt this related to #246?

**Comment by koekeishiya** [comment]
> I guess nothing special. Usually I have around 3-4 spaces on the main display (+ around 2 full screen Atom instances) and 1 space on the secondary display. Not too often I create additional spaces on the main display. Sometimes I connect/disconnect secondary display.

This could have something to do with spaces being moved from the secondary display to the primary display upon disconnection, and the fact that they are moved back once re-connected.

I don't really see why that would cause any issues, but figured it's worth mentioning.

**Comment by alexfedoseev** [comment]
Currently I'm working around it by creating and switching to second space on secondary display :)

**Comment by koekeishiya** [comment]
Is this still a problem for you in version `2.2.0`? There have been changes regarding spaces and displays. I still have no idea what the cause of this issue could be, as I am unable to reproduce on my end.

**Comment by alexfedoseev** [comment]
@koekeishiya I'm currently moving and will be w/ single display for a few months. So I'll close it for now and in case if it will still be an issue w/ the new display — I'll reopen it. Thanks for help!
