### ISSUE TITLE
Safari 9 tiling Issues

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#3]
First of all: Thanks for your effort – I like kwm very much even in this early state. However, I came across a few issues that you might not have seen so far since you appear to be using Firefox.

In Safari 9, the following actions create new windows that are no new browser windows:
- Address Bar preview/search function 
- Show Downloads function
- Hovering a link with Show Status Bar enabled 

Opening such a window will cause tiling to happen from kwm, then immediately hide the created window and then revert the tiling. Make having the address bar open in Safari impossible when kwm is running.

These fake-windows should be ignored by default probably.

**Comment by koekeishiya** [comment]
Thanks, I'm aware of the issue. It happens with Google Chrome as well.
Basically the reason for it is that the OSX API for retrieving currently open windows, lists these as child-windows of the browser with their own WindowID. They also have no title, so i can't blacklist them directly.

It's definitely something i will fix, when i figure a good way of dealing with these kinds of problems.

**Comment by koekeishiya** [comment]
Getting the associated AXRole and matching it against the appropriate value allows for filtering of such objects.

This issue has now been fixed.
Closing.

-- Koe
