### ISSUE TITLE
Autofocus no longer works

### ISSUE THREAD

**Issue by zachary123212** [koekeishiya/kwm#30]
After initially executing the command to toggle focus mode, I can no longer use Focus Follows Mouse (repeatedly executing the command does not seem to do anything). Selecting a window for manipulation can now only be done through alt-cmd-h and alt-cmd-l commands. Also, unlike previously, when the window is selected through the alt-cmd-h and alt-cmd-l commands, it does not appear to be selected (its colors are muted).

**Comment by koekeishiya** [comment]
This works just fine for me, are you running with default config and hotkeys?

**Comment by zachary123212** [comment]
Yep, that was the problem.
Thanks!
