### ISSUE TITLE
So many changes, things got broken...

### ISSUE THREAD

**Issue by andreaspada** [koekeishiya/kwm#300]
Well, I'm trying to follow the changes tracking but it's not easy at all. Currently, I'm in the process of almost cleaned up my kwmrc for proper syntax updating, although, I noticed that from v 2.0 I cannot compile anymore kwmrc-overlay (not so bad, I did not use it) but, worst then that, I cannot use spaces command anymore: kwmrc crashes always I try to move a window to another space. Any clue?

**Comment by koekeishiya** [comment]
post a gist of your current config/binds

**Comment by andreaspada** [comment]
As soon as i get home! 

Enviado do meu iPhone

**Comment by andreaspada** [comment]
Here it is, just the bind included file:
https://gist.github.com/andreaspada/e22ee75f9e0259ff411cd6e25d5bcba0

**Comment by koekeishiya** [comment]
You have a duplicate bind here, only the first one will be registered:
```
###############
# Screenshots #
###############
kwmc bind prefix+shift-1 sys ~/.kwm/scripts/screencapture -c
kwmc bind prefix+shift-1 sys ~/.kwm/scripts/screencapture
```

`kwmc bind ctrl+shift-r tree -c refresh` is now `kwmc bind ctrl+shift-r space -r focused`
`kwmc bind cmd+ctrl+alt-\ tree -c toggle` is now `kwmc bind cmd+ctrl+alt-\ window -c type toggle`
`kwmc bind cmd+ctrl-r tree -r 90` is now `kwmc bind cmd+ctrl-r tree rotate 90`
`kwmc bind cmd+ctrl+alt-/ window -c split` is now `kwmc bind cmd+ctrl+alt-/ window -c split-mode toggle`
`kwmc bind prefix+cmd-s window -t fullscreen` is now `kwmc bind prefix+cmd-s window -z fullscreen`
`kwmc bind prefix+cmd-t window -t parent` is now `kwmc bind prefix+cmd-t window -z parent`
`kwmc bind prefix+cmd-f window -t float` is now `kwmc bind prefix+cmd-f window -t focused`

There has been changes to a couple of `kwmc config ..` as well.

**Comment by andreaspada** [comment]
Ok, thanks to pointing that. Anyway, I used also the example kwmrc and it crashes same way...

Enviado do meu iPhone

**Comment by koekeishiya** [comment]
> Ok, thanks to pointing that. Anyway, I used also the example kwmrc and it crashes same way...

Everything works fine for me.

**Comment by andreaspada** [comment]
It's so strange it works for you. I'll try to compile again the last commit and to use just your example kwmrc, to test if everything works.

Good night!

**Comment by andreaspada** [comment]
Ok, so... now it works. For some mysterious reason, my git tree was messed. The example kwmrc which was present was not in sync with the changes, so others code as well. It was fixed cloning a brand new tree. 
Although, I still cannot compile kwm-overlay...

```
swiftc obj/kwm-overlay/kwm-overlay.o -lc++ -L /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift_static/macosx -Xlinker -force_load_swift_libs -o bin/kwm-overlay
ld: framework not found Metal for architecture x86_64
make: *** [bin/kwm-overlay] Error 1
```

**Comment by koekeishiya** [comment]
> Although, I still cannot compile kwm-overlay...

@cHogo do you have time to look into this? I really do not have any clue how the Swift compiler works at all.

**Comment by koekeishiya** [comment]
This should now be fixed.

**Comment by cHoco** [comment]
@koekeishiya Ops, sorry I didn't get a notification on this :( Glad it is now resolved :D

**Comment by koekeishiya** [comment]
> Ops, sorry I didn't get a notification on this :( Glad it is now resolved :D

I'm not sure it has been fixed, but I believe the latest changes could have solved it.

@andreaspada Please do open a new ticket specifically for this compilation error if it happens for you
