### ISSUE TITLE
Build failing on Xcode 7.3

### ISSUE THREAD

**Issue by mmmulani** [koekeishiya/kwm#303]
Building on 7.3 fails with a linker error to swift binaries:

```
make
...
swiftc obj/kwm-overlay/kwm-overlay.o -lc++ -L /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift_static/macosx -Xlinker -force_load_swift_libs -o bin/kwm-overlay
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SwiftObject", referenced from:
      __TMdC10Foundation15NSSimpleCString in libswiftFoundation.a(Foundation.o)
      __TMdC10Foundation16NSConstantString in libswiftFoundation.a(Foundation.o)
      __TMdC10Foundation15NSFastGenerator in libswiftFoundation.a(Foundation.o)
      __TMdCE10FoundationCSo12NSDictionary9Generator in libswiftFoundation.a(Foundation.o)
      l_create_generic_metadata222 in libswiftCore.a(Swift.o)
      l_create_generic_metadata235 in libswiftCore.a(Swift.o)
      l_create_generic_metadata237 in libswiftCore.a(Swift.o)
```

this might be related to https://github.com/neonichu/xcode-7.3-linker-issue but I'm not sure

**Comment by koekeishiya** [comment]
Not sure really what the issue could be. kwm-overlay does not change between releases  or on master though. Using the precomiled kwm-overlay binary from the Kwm 2.0.3 release should work fine.
Kwm should be compiled properly even if kwm-overlay fails.

**Comment by mmmulani** [comment]
oh yeah I think it's an Xcode problem. We should add travis-CI support so people can have confidence in the build system, will look at adding it tonight.

**Comment by cHoco** [comment]
I have Xcode 7.3 installed and I don't get that error, can you post the swiftc version `swiftc -v"?

**Comment by mmmulani** [comment]
```
mehdi-pro:~ mehdi$ swiftc --version
Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
Target: x86_64-apple-darwin15.4.0
```

does yours show the same?

**Comment by dominiklohmann** [comment]
The current version is 2.2, not 2.1.1.

**Comment by cHoco** [comment]
Yeah, unfortunately you're gonna need version 2.2, building Swift statically isn't supported by Apple, mine is just an hack, proper support should hopefully come in next versions.

**Comment by mmmulani** [comment]
thanks for the help :) got it compiling by updating Xcode. ironically I installed Xcode 7.3 but was still linking against Xcode 7.2
