### ISSUE TITLE
New location of launchd scripts breaks kwm

### ISSUE THREAD

**Issue by mtneug** [koekeishiya/kwm#305]
Not sure if this or [Homebrew/homebrew-binary](https://github.com/Homebrew/homebrew-binary) is the correct location to post this. I hope it is ok to post here.

I installed `kwm` via Homebrew. In the newest version the location of the `launchd` configuration files has changed from `~/Library/LaunchAgents` to `/Library/LaunchDaemons`:

```
❯ brew info kwm
homebrew/binary/kwm: stable 2.0.3
Tiling window manager with focus follows mouse for OSX.
https://koekeishiya.github.io/kwm/
/usr/local/Cellar/kwm/2.0.3 (6 files, 5.4M) *
  Built from source
From: https://github.com/Homebrew/homebrew-binary/blob/master/kwm.rb
==> Caveats
Copy the example config from /usr/local/Cellar/kwm/2.0.3/kwmrc into your home directory.
  mkdir -p ~/.kwm
  cp /usr/local/Cellar/kwm/2.0.3/kwmrc ~/.kwm/kwmrc

To have launchd start homebrew/binary/kwm at startup:
  sudo cp -fv /usr/local/opt/kwm/*.plist /Library/LaunchDaemons
  sudo chown root /Library/LaunchDaemons/homebrew.mxcl.kwm.plist
Then to load homebrew/binary/kwm now:
  sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.kwm.plist

WARNING: launchctl will fail when run under tmux.
```

For me `kwm` is then no longer able to function correctly. Probably because it's then running as `root` and not as my user? [`plist_options :startup => true` in line 12](https://github.com/Homebrew/homebrew-binary/blob/d31b18aafaf3f03de174e0416b1a91e4eb033346/kwm.rb#L12) is the cause of this location change.

**Comment by koekeishiya** [comment]
This was a change demanded by the homebrew repo maintainers. I personally have no idea what the change did or why it was neccessary. I do not use homebrew myself obviously as I make changes all the time that I have to test.

I use the "manual plist" way described in the README and place save it as: ` ~/Library/LaunchAgents/com.koekeishiya.kwm`

**Comment by cHoco** [comment]
What do you mean by not working correctly? If it this crashing can you post the crash report?
Keep in mind that the configuration file syntax changed a lot from previous versions and that may be the cause of the issues.

**Comment by cHoco** [comment]
@koekeishiya You should probably change the `plist_options :startup` value to `false` in the next release, since by looking at homebrew code, setting it true puts it automatically in the LaunchDaomons directory (https://github.com/Homebrew/legacy-homebrew/blob/4251efa88cc6cc3e937dd2d97cbf745a348d09e8/Library/Homebrew/caveats.rb#L154)

**Comment by koekeishiya** [comment]
That 'setting' makes no sense at all. Why would an application installed through brew without the use of sudo not be placed in the users `LaunchAgents` folder, and why is the setting required for this `false`...

**Comment by mmmulani** [comment]
those homebrew directions are pretty bad, by putting it in /Library and requiring root to start it up, you don't get the accessibility dialog, aka nothing works

**Comment by mtneug** [comment]
Aren't the accessibility settings global? Since I was upgrading `kwm` was already present in the accessibility list, but even then `kwm` was not able to arrange windows. @cHoco I also used the default config file with no luck.

**Comment by cHoco** [comment]
Yeah, but personally I don't know if they're available *before* a login session is available, so kwm may crash/behave in unexpected ways. But since your is the first report we got of not working with the new release I thought that maybe it was just a configuration error.
Keep in mind that since right now it is in LaunchDaemons a new configuration isn't read if you don't restart kwm yourself or restart the computer (logout won't suffice).

If this is still not working, can you try to compile it from master following the readme instruction and report if it works?

**Comment by mtneug** [comment]
Well `kwm` seems running fine, that is it doesn't crash. Using two monitors it also focuses the topmost application. Focusing within one screen is not working for me (not using it anyways) as well as the arrangement of windows and key bindings. I launched it manually so there already was a login session. Also I can't find the location of logs and the system log doesn't report anything other then:

```
12.04.16 10:20:19,538 com.apple.xpc.launchd[1]: (homebrew.mxcl.kwm) This service is defined to be constantly running and is inherently inefficient.
``` 

About changing the configuration: I suppose stoping the service / killing the process should be sufficient. 

I guess `kwm` should just be running as a user LaunchAgent to function correctly. Everything is working normally then. It's just that the instructions given by Homebrew should be changed then.

**Comment by koekeishiya** [comment]
See #310
