### ISSUE TITLE
Ability to have presaved configurations for different monitor configurations

### ISSUE THREAD

**Issue by paradox460** [koekeishiya/kwm#307]
The newest updates sort of approach something like this, with the ability to set configurations per space per monitor, but unfortunately, its just a generic monitor index, `[0,1,2,..]` and not something unique to the monitor.

I've been trying to use a bit of hammerspoon and a latch to toggle between monocle mode when its just my laptop screen and bsp when its my work multi-monitor config, but its been a bit buggy.

The ability to specify one specific monitor ID, regardless of arrangement, to always have one specific configuration, would be incredibly useful

**Comment by koekeishiya** [comment]
This can be done by using the unique display identifier. Might add this in the future as it should be very little work. It would replace the current generic monitor index completely though.

**Comment by koekeishiya** [comment]
Closing as duplicate, see #154 for reference.
