### ISSUE TITLE
Replace spaces-hotkey for move window to space with private APIs

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#308]
I've found a private `Spaces API` that allows a window to be assigned to different spaces. This allows a window to be moved to a space without having to actually make that space active.
It will also be able to move a window from an inactive space and bring it to the active space.

This could be used creatively to implement some sort of a window `tag` system where you'd be able to instantly bring any window with a user specified tag (managed by Kwm) to the currently focused space at the press of a key.

Currently I have only gotten this to work between spaces that belong to the same display.
I'm not sure yet if this is something I can get around.

**Comment by andreaspada** [comment]
Great!

Enviado do meu iPhone

**Comment by koekeishiya** [comment]
I guess the best part about this is that borderless windows can now be moved to spaces.

**Comment by koekeishiya** [comment]
`kwmc window -m space left | right | previous | id` behaves the same way as it used to, except for the fact that it will no longer have to simulate a click on the titlebar and perform a `kwmc press spaceskey-id` action.

This will allow Kwm to move a borderless window to other spaces, and it will also no longer automatically give the new space focus. 

If you want to send a window to another space AND give it focus, the following script can be used:
```
dir=$1
kwmc=/usr/local/bin/kwmc
$kwmc window -m space $dir
$kwmc space -f $dir
```
