### ISSUE TITLE
Fullscreen stacking mode

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#31]
Thinking about looking into adding fullscreen stacking mode kinda like i3 for linux, 
however I doubt it will be possible to show a list of all open windows in the way that i3 does.

From the users perspective, the feature would act as a tiling mode separate to binary space partitioning,
and so a space would then be able to have 3 states - bsp tiling, stacking, floating.

After you set the space to stacking mode, the (last) focused window will take up the entire screen,
and the user might navigate to the prev/next window using some command; hopefully the same
`window -f prev|next` that already exists.

Again, I have not yet been able to think of a way to display all windows available in the stacking space, to the user in a useful manner that complements this windowing-arrangement.

Is this something that people are interested in? If not, it will be dropped.

**Comment by hhsnopek** [comment]
This would be cool to have, maybe in the bottom gap of the screen a terminal could be running or something that mimics i3 - this would be a bit of work, but it could just be a terminal running a small program. Then just updates the ui of the program to whichever window is on top

![https://cldup.com/TPq6gEPlWn.png](https://cldup.com/TPq6gEPlWn.png)
(bottom terminal is separate)

**Comment by koekeishiya** [comment]
Stacking mode should now be in and seems to work.
There is as of right now no way to actually see what windows are in this space,
I guess using OSXs mission control would work, however it does not show the order
that that the windows will be navigated in.

To switch between windows, the kwmc command `window -f prev|next` can be used.

**Comment by gallimatias** [comment]
Thanks for this great feature! Instead of accessing bsp, monocle and float modes through three separate keybindings is it possible to bring all modes under one keybinding through toggling?
