### ISSUE TITLE
README: Homebrew users

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#310]
The homebrew instructions for automatically starting Kwm are currently wrong and should not be used. If you have followed the steps provided, do the following to undo the changes:
```
sudo launchctl unload /Library/LaunchDaemons/homebrew.mxcl.kwm.plist
sudo rm /Library/LaunchDaemons/homebrew.mxcl.kwm.plist
```

The following is what you should do to correctly have Kwm start on login:
```
cp /usr/local/opt/kwm/*.plist ~/Library/LaunchAgents
launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.kwm.plist
```

This will be fixed when a new version of Kwm is submitted to homebrew.

**Comment by levitanong** [comment]
These instructions aren't present in the readme

**Comment by dominiklohmann** [comment]
> These instructions aren't present in the readme

This issue has been closed for a few months now; Homebrew added `brew services start|stop <service>`, so you can just do `brew services start koekeishiya/kwm/kwm` instead. Homebrew informs you about this when installing Kwm.

**Comment by levitanong** [comment]
I just looked back at the log; mea culpa. I only noticed the following:
```
Copy the example config from /usr/local/Cellar/kwm/3.1.0/kwmrc into your home directory.
  mkdir -p ~/.kwm
  cp /usr/local/Cellar/kwm/3.1.0/kwmrc ~/.kwm/kwmrc
```

And didn't notice the `brew services` thing. Sorry for the noise!

**Comment by f1337** [comment]
If kwm stops responding to keybinds for you after a MacOS upgrade, this is probably your issue. At least, it was for me. YMMV.
