### ISSUE TITLE
Error on building kwm-overlay

### ISSUE THREAD

**Issue by EdenSG** [koekeishiya/kwm#314]
When building kwm, I get the following error (both on `make` and `make install`):
````
ld: symbol(s) not found for architecture x86_64
make: *** [bin/kwm-overlay] Error 1
````
I don't feel like I know enough about the build process to trace this back to something. Is there any more info I could provide to help?

**Comment by koekeishiya** [comment]
What's the output of `swiftc -v`?

**Comment by EdenSG** [comment]
````
Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
Target: x86_64-apple-darwin15.4.0
````

**Comment by koekeishiya** [comment]
You need at least version `2.2` for to build properly. Something to do with static linking I believe it was.

**Comment by EdenSG** [comment]
Interesting - okay, thanks.
