### ISSUE TITLE
Add man page to release zip

### ISSUE THREAD

**Issue by johannesfrey** [koekeishiya/kwm#316]
Would it be possible to include the man page entry for kwmc so that the homebrew formula entry could be augmented with a `man1.install` in the install section?
At the moment I have to download the source code zip after installing kwm via homebrew and have to copy it manually everytime I upgrade kwm.

**Comment by koekeishiya** [comment]
Can probably be done for next release.

**Comment by koekeishiya** [comment]
`man1.install` has been added.
