### ISSUE TITLE
Query spaces and notifications

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#320]
A rough idea for a future enhancement:

-kwmc query spaces
-if primary window for application that has a badge is on the space, include an alert flag
-disable alerts per application

something like
`kwmc query spaces`
```
1, Browser
2, Messages, (alert)
```

**Comment by matthewdias** [comment]
also `kwmc query space` to get id of current space

**Comment by koekeishiya** [comment]
> kwmc query spaces

Implemented as `kwmc query space list`. See #249.

> if primary window for application that has a badge is on the space, include an alert flag
disable alerts per application

Could you elaborate on this?

**Comment by matthewdias** [comment]
I was thinking of something similar to `i3-bar`. When a window requires your attention, it will have an `urgent` status, and the label/number for it in the bar will change color. I was thinking it could be just a flag included in the query's output, like in my first comment. Im pretty sure this isn't possible without code injection, but just throwing the idea out there.

**Comment by matthewdias** [comment]
right now `kwmc query space list` adds a new space to the list every time a window is put into native fullscreen.
