### ISSUE TITLE
Key binding with non US keyboard

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/kwm#325]
I am a french user of KWM.

I was used to use shortcuts `ctrl+alt-1` to `ctrl+alt-0` to move windows to space and  `cmd+alt-1` to `cmd+alt-0` to go to space.

However, on a french keyboard, you can't bind directly the numbers 1, 2,... as you need to use the shift modifier to access them.

Here is the default characters of 1 to 0 keys:
> 
1->&
2->é
3->"
4->'
5->(
6->§
7->è
8->!
9->ç
0->à

When I try to use these mapping in my kwmrc config, some are working but others doesn't. 

`kwmc bind ctrl+alt-& window -m space 1` works
`kwmc bind ctrl+alt-é window -m space 2` doesn't work
`kwmc bind ctrl+alt-" window -m space 3` works
`kwmc bind ctrl+alt-' window -m space 4` works
`kwmc bind ctrl+alt-( window -m space 5` works
`kwmc bind ctrl+alt-§ window -m space 6` doesn't work
`kwmc bind ctrl+alt-è window -m space 7`doesn't work
`kwmc bind ctrl+alt-! window -m space 8` works
`kwmc bind ctrl+alt-ç window -m space 9` doesn't work
`kwmc bind ctrl+alt-à window -m space 10` doesn't work

Any ideas on how to resolve this ? like use of keycodes ?

**Comment by matthewdias** [comment]
I think the addition of keycode support would probably be a good fix for this. Something like `kwmc bind mod+mod+mod-key-42`

**Comment by koekeishiya** [comment]
> I think the addition of keycode support would probably be a good fix for this.
 
This should not be an issue as keys are supposed to get translated to keycodes automatically.
See `KeycodeForChar()` @ `kwm/keys.cpp`

**Comment by mickaelperrin** [comment]
Can it be related to the encoding of my `kwmrc` file ? But that seems good as it is in utf-8.

If you look at my test run, you will observe that it's all accentuated characters that fail. Maybe the `KeycodeForChar`method can only retrieve keycodes of characters present in US keyboard ?

**Comment by koekeishiya** [comment]
> CopyCurrent*KeyboardInputSource do not allow access to the unicode data, CopyCurrent*KeyboardLayoutInputSource do.

From #47

**Comment by koekeishiya** [comment]
`kwmc bind` will probably be split into `kwmc bindsym` and `kwmc bindcode` or something similar, as a fix for this.

**Comment by koekeishiya** [comment]
On the branch `binding-modes`, `kwmc bind ..` has been split into 2commands.
The old `kwmc bind ..` is now `kwmc bindsym ..`. It works exactly the same as the old version.
The other one is `kwmc bindcode ..`, which does exactly the same as `bindsym`, but you give it a keycode in hexadecimal instead of an actual letter.

Say I want to bind the following key, 'å'. On my machine, this has the keycode `0x21`.
`kwmc bindcode cmd+alt-21 ..`.

**Comment by mickaelperrin** [comment]
That's awesome and fully functionnal. Big thanks ! 👍
