### ISSUE TITLE
Window focus sometimes spans across displays after moving window to monocle space

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#328]
Steps to reproduce: 

1. Place display 1 in monocle mode
2. Focus display 0
3. Move window to display 1
3. Use `window -f east` and/or `window -f west` to cycle thought he monocle windows
4. After at least two focus commands, focus is moved back to display 0

This only happens when display 1 is in monocle mode. If display 1 is in BSP mode focus stays on the correct display. 

If `cycle-focus` is `off` this still happens, just alternate between `west` and `east`.

**Comment by koekeishiya** [comment]
I am still not able to reproduce using the above steps, both with and without `cycle-focus`.

**Comment by chrishoage** [comment]
So odd, I can reproduce this 100% of the time. I will do a fresh build from master and reboot my computer and see if I can repo it. 

You can see the issue in the logs I posted, right?

**Comment by chrishoage** [comment]
Well, this is supremely frustrating. After a rebuild and reboot I can no longer reproduce this issue. 

Sorry to bother!
