### ISSUE TITLE
Weird border glitch when performing actions in Sublime Text

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#329]
possibly related to changes made for #318 
https://s3.amazonaws.com/f.cl.ly/items/0P3b0b2V3Y0a1S412D2Y/overlay.mp4

**Comment by chrishoage** [comment]
It's difficult to tell what is happening here. Can you post steps to repo in addition to that video?

**Comment by koekeishiya** [comment]
I have come across similar behaviour where I sometimes get a red dot at the upper left corner. I have no idea how to reproduce or why it is happening though.

**Comment by matthewdias** [comment]
There's not really a definite way to tell what's going on. From what I can tell, Sublime throws up a lot of overlays that I guess are a type of window. Sometimes it happens when its just sitting there and not being interacted with. I can, however, reliably reproduce it by closing tabs.

**Comment by koekeishiya** [comment]
Is this a problem in the new version?

**Comment by matthewdias** [comment]
Seems to be fixed 👍
