### ISSUE TITLE
Revamp bind system

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#332]
Regarding the request for #322 (i3-like binding modes). There is most likely gonna be conflicts with how the current prefix-key works, and if the suggestion for binding modes go through, the prefix-key will be removed.

Personally, I do prefer modal keybindings instead of having 4different modifier combinations.

Thoughts?

**Comment by chrishoage** [comment]
What about the comment in that ticket? I imagine there could be some system in place to name prefixes and offer some simple options for them. 

```
kwmc config prefix-key ctrl-k ctrlk
kwmc config prefix-activation toggle # or timeout

kwmc bind ctrlk+cmd-q quit
```

It would go well with the variable system already in place? 

I've read though the binding doc linked in the other ticket, I'm just having trouble visualizing how it would work for kwm.

**Comment by koekeishiya** [comment]
> I imagine there could be some system in place to name prefixes and offer some simple options for them. 

This part is basically what requires the current system to be re-written.

**Comment by matthewdias** [comment]
I think the way i described in #322 is probably a good way for it to work.
>The bind specific prefix is pretty close. Adding the option to toggle it as opposed to a timeout and allowing for multiple prefixes would do the job.

Would the whole bind system need to be written or just the prefix part?

**Comment by koekeishiya** [comment]
> Would the whole bind system need to be written or just the prefix part?

Most of the system, yes. Basically, I'd redo the system with the ability to activate a certain set of binds when some action is triggered. How these sets become active does not matter much at this point.

The underlying problem of the current implementation is that these are both registered as the same bind:
`kwmc bind prefix+cmd-l ..` and `kwmc bind cmd-l ..`.

**Comment by dominiklohmann** [comment]
Can we get support for chaining of keybinds, similar to the prefix key? Basically how it works in vim.

**Comment by koekeishiya** [comment]
> Can we get support for chaining of keybinds, similar to the prefix key? Basically how it works in vim.

This is already possible. When performing a bind after the keypress has been activated. The timer is reset. But yeah, I want modal keybinds as the default setup and a timer may be available as a setting.

**Comment by dominiklohmann** [comment]
Yes, but in vim for example I can define a shortcut that is `C-b t b n`, so it is a chain of 4 separate keybinds. Don't think I can currently do this with Kwm.

**Comment by koekeishiya** [comment]
> Yes, but in vim for example I can define a shortcut that is C-b t b n, so it is a chain of 4 separate keybinds. Don't think I can currently do this with Kwm.

Right, that's correct. I'm not sure how complicated this would be to achieve, due to Kwm intercepting keys globally. 

As we are comparing with vim right now, I guess the aspects I'd like to have is being able to have different modes only. Lets say Kwm has a `default mode`; the equivalent of vims `command mode`.
You'd transition between modes using a bind. The user would be able to create as many of few of these modes as they want.

I imagine having something like the following modes: `focus`, `tree`, `move`.

Lets say I start in `default mode`. I hit some key-combination that brings me over to `focus mode`.
I can now hit only `h, j, k or l` to switch focus. Now lets say I want to resize window a window container, I step into `tree mode` and hit `h, j, k, or l`. 

Now I know that not all people area fan of modal setups, which is why it would be great to be able to hit a key that does: `Enter focus mode but automatically return to mode 'x' when the time expires`. Another option could be to simply not use modes, and all binds would be created in the `default mode`.

**Comment by dominiklohmann** [comment]
With the system you're suggesting, you could always do something like this:

For entering a mode with a timeout of 0.75 seconds, you would create a bind like this. Leaving the timeout out would make it work like vims modal design.
`kwmc bind ... mode mode-name 0.75`

When defining other keybinds, I can then always just define what mode they work in. To enable backwards compatibility, I suggest a design like this.
`kwmc bind mode-mod_1+...+mod_n-key ...`

Now what I'd really like to have, but is hard to achieve with backwards compatibility, is something where you can define a sequence, probably delimited by another character. I'll use `&&` as an example here.
`kwmc bind mod-key&&mod-key&&mod-key ...`

The latter could also be achieved by making modes non-exclusive, e.g. allowing you to be in more than one mode at once.

Another important thing would probably be something like vims `C-o` in insert mode, which returns you to normal mode for exactly one command. 

(just writing this on mobile, hopefully the thought process didn't get lost too much in the formatting hassle)

**Comment by koekeishiya** [comment]
> Now what I'd really like to have, but is hard to achieve with backwards compatibility, is something where you can define a sequence, probably delimited by another character. I'll use && as an example here.
kwmc bind mod-key&&mod-key&&mod-key ...

The problem with this concept tho, which action should be taken if you do not finish this sequence of binds? As Kwm intercepts globally, you'd essentially lock keyboard input for all other applications, until the bind-sequence either completes or receives an invaid key causing it to end.

**Comment by dominiklohmann** [comment]
You'd have to have a global timeout in that scenario.

**Comment by matthewdias** [comment]
I think binds in the normal mode that are not over ridden by a custom mode should still stay active. Also, should be able to define border settings for each mode you create.

**Comment by koekeishiya** [comment]
> I think binds in the normal mode that are not over ridden by a custom mode should still stay active.

Probably not gonna happen due to implementation details.

> Also, should be able to define border settings for each mode you create.

This is gonna happen for sure.

**Comment by matthewdias** [comment]
>the directional border system...

@dominiklohmann since this is only one level deep, wouldn't it work with a normal timeout prefix, and not need further chaining? I'm not sure what the use case for chaining is. Seems like it just handles the same problem as binding modes, but with more customizability and complexity.

**Comment by dominiklohmann** [comment]
I just thought about this a bit more. This issue could be solved with binding modes that can only be entered from specific binding modes. Has the exact same functionality.

**Comment by koekeishiya** [comment]
> This issue could be solved with binding modes that can only be entered from specific binding modes. Has the exact same functionality.

This would be entirely up to the user. If a mode is created, it has absolutely zero binds associated with it. If you want to be able to go back to the `default` mode, or any other. These must be specified.

**Comment by dominiklohmann** [comment]
Well then my wish for sequences is already implicitly granted by that implementation.

**Comment by koekeishiya** [comment]
I've made the initial change to different modes, on the branch `binding-modes`.
There are as of this moment no settings available to the modes.

Specifying the mode of a command is fairly simple. Adding the mode name where you specify modifiers was the simplest way to achieve this with the current system. 

The following bind will only exist for the mode `MyMode`: `kwmc bind MyMode-f window -z fullscreen`.
To enter a different mode: `kwmc mode activate MyMode`
If no mode is specified, it will be stored as a mode called `default`.

Please note that as of now, `prefix-key` is no longer a thing on this branch.
I plan on implementing the ability to set a specific border color (color only) for a given mode.
It may be possible to allow for something like `kwmc mode 'name of mode' timeout 0.75` to specify that this mode should behave as a prefix.

**Comment by chrishoage** [comment]
> Please note that as of now, prefix-key is no longer a thing on this branch.

A change in syntax / functionality is fine, as long as by the time the code makes it to master one can achieve the exact same prefix functionality as before. 

It would be a bummer if in this new system the current prefix behavior was lost entirely for people who desire simple binds.

**Comment by matthewdias** [comment]
>Probably not gonna happen due to implementation details.

That's perfectly fine. It'll just mean longer config files, which can be solved by reusing separate configs

**Comment by koekeishiya** [comment]
> It would be a bummer if in this new system the current prefix behavior was lost entirely for people who desire simple binds. 

I imagine a prefix system like the following could be added:
Binds that should be prefixed have to be bound for the special `prefix` mode.
The syntax for this ends up being exactly like it used to be: `kwm bind prefix-h ..`.
The prefix would no longer be able to be applied globally, 
as this does not make sense anymore with arbitrary number of modes.

To access binds that are prefixed, the prefix-mode must be activated.
This is achieved by performing `kwmc mode activate prefix`.
This will trigger the timeout associated (old syntax should be fine), and revert back to the old mode when the time expires.

Every bind mode that wants to be able to access the prefix-binds,
must have a way of performing `kwmc mode activate prefix`.

Thoughts?

**Comment by matthewdias** [comment]
Is there any issue integration-wise with instead allowing any created mode to instead have a timeout, allowing for arbitrary prefix modes?

**Comment by koekeishiya** [comment]
> Is there any issue integration-wise with instead allowing any created mode to instead have a timeout, allowing for an arbitrary number of prefix modes?

Not really, I'll give this approach a try first.

**Comment by chrishoage** [comment]
> Thoughts?

So it would work something like this? Can `prefix` be any arbitrary string, say for example `foo`? 

```
kwmc bind foo-p window -t parent
kwmc bind ctrl+k mode activate foo
```

Depending on configuration, `foo` would be active until a timeout is reached, or the user disables the mode?

**Comment by koekeishiya** [comment]
That's pretty much how I imagined, yeah

**Comment by chrishoage** [comment]
Then yeah, I like the idea.

**Comment by koekeishiya** [comment]
A mode now have the following properties:

Specify if this mode is a prefix: `kwmc mode MyMode prefix on | off`
If prefix, set the timeout in seconds: `kwmc mode MyMode timeout 'floating point number'`
If prefix, set the mode to activate upon timeout: `kwmc mode MyMode restore 'some mode'`
Set color used by the focused-border: `kwmc mode MyMode color aarrggbb`
```
The color setting is optional, the prefix-restore activate `default` if none specified.
The prefix settting defaults to `off` for newly created modes.

I have only tested the prefix a fair bit, but it seems to retain all the previous functionality.

**Comment by dominiklohmann** [comment]
So... how does this work with the window borders? Can we define one border color per mode, similar to prefix-border?

**Comment by matthewdias** [comment]
yeah, that's how it works right now. 

@koekeishiya the marked border gets disabled when you activate a mode. Is that intentional?

**Comment by koekeishiya** [comment]
>  when resizing, the marked border doesn't get updated

Kwm does not create notifications for the marked window, and so it does not know when it gets moved, resized or closed. This is something that will be fixed soon.

**Comment by koekeishiya** [comment]
Any ideas of how to explain how this system works in a short, concise manner that fits nicely in the `readme` as well as the `kwmc man page`?

**Comment by koekeishiya** [comment]
`kwmc bind ..` has now been split into 2 commands, see #325 for history.

**Comment by koekeishiya** [comment]
For anyone interested in preserving their keybindings prior to this change, the following changes must be made:

Replace the values in the example below with your own:
```
kwmc config prefix-key ctrl-s
kwmc config prefix-timeout 0.75
kwmc config prefix-global .. #removed
kwmc config prefix-border color ff458588
```

must be changed to the following:
```
kwmc mode prefix prefix on
kwmc mode prefix timeout 0.75
kwmc mode prefix restore default
kwmc mode prefix color ff458588
kwmc bind ctrl-s mode activate prefix
```

**Comment by mickaelperrin** [comment]
Is it still possible to bind the `focus-follows-mouse`action ?

    kwmc config focus-follows-mouse toggle

works, but

     kwmc bindsym cmd+alt-t config focus-follows-mouse toggle

doesn't seem to.

**Comment by andreaspada** [comment]
Almost got it all... just my launcher binding do not work anymore. I could easily change all my keycap - as window movement, etc.. - using the new syntax. Anyway, a simple launcher, as:
`kwmc bindsym prefix-f sys open ~`, which I used to open a finder, do not work anymore, even if I strip out the "sys", which maybe is not necessary anymore...
There's something I missed?

**Comment by dominiklohmann** [comment]
`sys` has been changed to `exec`, see #338.

**Comment by andreaspada** [comment]
Yeah, for sure... the problem is:

# Postbox
kwmc bindsym prefix-m exec open -a /Applications/Postbox.app     - this 
work!

# Finder
kwmc bindsym prefix-f exec open ~    - Used to launch my finder, do not 
work anymore!

There defintely something more there...



Dominik Lohmann wrote:
>
> |sys| has been changed to |exec|, see #338 
> <https://github.com/koekeishiya/kwm/issues/338>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/koekeishiya/kwm/issues/332#issuecomment-215405885>
>

-- 

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Andrea Spada :: Liuteria d'Autore
www.andreaspada.com

CNPJ: 12.027.966/0001-00
CPF: 054.545.977-08
IM: 0.586.554.9

**Comment by koekeishiya** [comment]
> The tilde operator does no longer expand I believe, in case you have ~ used in the binds that fail.

`define ~ /Users/Name`

Might do the trick.

**Comment by andreaspada** [comment]
You are right! It's working now... thanks! Sorry to bother you all, I do 
not have the time to follow all the changes...

koekeishiya wrote:
>
>     The tilde operator does no longer expand I believe, in case you
>     have ~ used in the binds that fail.
>
> |define ~ /Users/Name|
>
> Might do the trick.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/koekeishiya/kwm/issues/332#issuecomment-215407975>
>

-- 

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Andrea Spada :: Liuteria d'Autore
www.andreaspada.com

CNPJ: 12.027.966/0001-00
CPF: 054.545.977-08
IM: 0.586.554.9

**Comment by koekeishiya** [comment]
> however, when resizing, the marked border doesn't get updated

@matthewdias This should be fixed now.

**Comment by koekeishiya** [comment]
I got bored of writing shellscripts every single time I wanted to chain commands.
You can now execute multiple commands in a single bind by using the `:` separator.

`kwmc bindsym LaunchMode+cmd-l exec stuff : exec morestuff : mode activate default`

**Comment by andreaspada** [comment]
Awesome!!!


koekeishiya wrote:
>
> I got bored of writing shellscripts every single time I wanted to 
> chain commands.
> You can now execute multiple commands in a single bind by using the 
> |:| separator.
>
> |kwmc bindsym LaunchMode+cmd-l exec stuff : exec morestuff : mode 
> activate default|
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/koekeishiya/kwm/issues/332#issuecomment-215741545>
>

-- 

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Andrea Spada :: Liuteria d'Autore
www.andreaspada.com

CNPJ: 12.027.966/0001-00
CPF: 054.545.977-08
IM: 0.586.554.9

**Comment by dominiklohmann** [comment]
Can we get support for the following two things for legibility? I feel like these are needed as kwmc commands become longer.

Support for more than once whitespace character between tokens:
```
kwmc bindsym cmd-^       window -f next
kwmc bindsym cmd+shift-^ window -f prev
```

Support for multiline commands:
```
kwmc bindsym LaunchMode+cmd-l exec stuff ; \ 
                              exec morestuff ; \ 
                              mode activate default
```

**Comment by koekeishiya** [comment]
> Can we get support for the following two things for legibility? I feel like these are needed as kwmc commands become longer.

Possibly for 3.0.0 or 3.0.1 release.
These require rewriting the config parsing to use the tokenizer provided for the rule system.
The current parser is just a combination of read-line and string splits.

**Comment by chrishoage** [comment]
I've finally got around to upgrading, is there to way to make `default` commands work while a mode is activated? 

Before I could issue a prefix command then issue an unprefixed command while the timeout was still active. Is that ability gone? Or just moved to an opt in config?

**Comment by koekeishiya** [comment]
> Before I could issue a prefix command then issue an unprefixed command while the timeout was still active. Is that ability gone?

That was actually a bug with the old system. You could not have binds such as `prefix+cmd+alt-h dostuff` and at the same time have `cmd+alt-h window -f west`

If you want to have default commands work in other modes, you have to basically make that bind for that mode.

e.g: `kwmc bindsym cmd+alt-h window -f west`
create a second one: `kwmc bindsym prefix+cmd+alt-h window -f west`.

This is intended behaviour and will not change.

**Comment by chrishoage** [comment]
> The functionality is not gone, but it is quite verbose.

Thanks, I'll double up my bind commands. In the (far?) future I wonder if there could be some special syntax that acts as a shortcut to the double bind. 
```
kwmc bindsym (myMod+)cmd+alt-h window -f west
```

Would behind the scenes create a bind for both the modifier and the default mode. 

There's probably some complexity to the idea that i'm missing, and is not super important since it can be achieved by doubling up the binds
