### ISSUE TITLE
Unable to detect / retile GTK applications

### ISSUE THREAD

**Issue by mavant** [koekeishiya/kwm#333]
As the title says. I don't necessarily think this is a problem with kwm, as the application I'm attempting to use (CoqIDE) doesn't seem to be detected by Accessibility Inspector either - but I haven't been able to debug this on my own, so I figured I'd come here for help. Is there an obvious gotcha here that you happen to be aware of?

It is totally okay for you to declare this one Somebody Else's Problem.

**Comment by koekeishiya** [comment]
Kwm fully relies on the accessibility API and applications that does not provide support for this will not be detected. There are probably ways around this, but I have not really looked into it. The same applies to windows running through XQuartz.

**Comment by mavant** [comment]
Fair. Thanks for the swift answer!
