### ISSUE TITLE
Set border of prefix mode with new bindings ?

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/kwm#336]
Hi,

Big up for the new keybindings scheme. However, I didn't found any mention on the examples  or documentation on how to set the size of the border in the prefix mode ?

What's the new syntax of the command `kwmc config prefix-border size 4` and `kwmc config prefix-border radius 6` ?

Thanks

**Comment by koekeishiya** [comment]
Due to implementation details, these will always default to the size and radius of the `focused-border`.
Hopefully this is not a huge proble, as I have no intentions of adding that back in.

**Comment by mickaelperrin** [comment]
Ok, thanks. I was used to increase the border-size to get a better visual help that I am in the prefix mode. I finally increased the border size of the focus window from 1 to 2 and set a red border color in prefix mode. That seems to be sufficient.
