### ISSUE TITLE
Scratchpad

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#337]
I briefly mentioned the possiblity of a `tag` system previously in #308.

My current thoughts around this kind of feature would be that Kwm always has a hardcoded `space id` that is unused by OSX, to be used as a 'scratchpad'. It would have a command for listing information about windows that are currently placed on the scratchpad, and moving a window between the scratchpad and the currently active space.

This could be great for music players, on-demand terminal window (instead of drop-down terminals), and other windows that you do not have to keep in your view all the time.

Now you could argue that simply minimizing a window offers the same effect, but I personally think this could be a great addition. I do not have much experience with `hyperdock` and similar tools, so I'm not sure how good of an idea this is.

Ideally, Kwm would cache the scratchpad information to disk, such that this information is not lost should a crash or abnormal termination occur.

Edit: A window retrieved from the scratchpad should probably be treated as floating, and be centered on the screen. Ideally, this would be a config option for the users.

**Comment by matthewdias** [comment]
As you said, I'm having a hard time figuring out what the difference is between this and minimizing/hiding. Is there other functionality that would be enabled by this?

**Comment by koekeishiya** [comment]
> As you said, I'm having a hard time figuring out what the difference is between this and minimizing/hiding. Is there other functionality that would be enabled by this?

I've never really tried to utilize minimize or hidden windows before, so I'm not sure if they can achieve the following. 

With the above system, I could assign a keybinding to bring, say, a terminal window to the center of my focused space, with the correct size. When I'm done, I simply hit the same bind again, and it's gone.

The key-part for me is the ability is the fact that all the windows placed on the scratchpad would be treated as floating windows, have my desired size when I bring them back, and accessable through keybinds.

**Comment by matthewdias** [comment]
Minimizing preserves the floating state currently with kwm.

As far as accessing them with keybinds, the only way to do that afaik is with `hyperdock`. Maybe kwm could keep track of the minimized window ids and assign binds to them to effectively create a scratchpad?

Would the binds be assigned by application or something?

**Comment by koekeishiya** [comment]
My main problem with minimize (iirc), is that I cannot un-minimize a window on a different space, without OSX activating that space for me.

> Would the binds be assigned by application or something?

I have not really gotten that far yet, as to how binds would be assigned in a good way.
This is of course somthing I will work on a lot before implementing this.
As of now, I just wanted opinions about this kind of a system, or if it is considered a waste of time.

I will probably end up implementing something like this eventually for my own use, however it will not be a priority at this point unless other people see the use for it.

**Comment by matthewdias** [comment]
>I cannot un-minimize a window on a different space, without OSX activating that space for me.

That's a really good point. I personally wouldn't use it, since for these kinds of windows I typically dedicate a space to them, but I'd bet others would find it useful.

**Comment by dominiklohmann** [comment]
I would have use for this if I could open the scratchpad as a space on any screen at any time. I used TotalTerminal before 10.11 and SIP as a fullscreen terminal I can open on a hotkey, and while being able to open a terminal on a keypress can be a replacement, it does not function as well, simply because it forces me to start a new terminal instance every time.

So... if I could swap all windows on the scratchpad with all windows on the active space with one button press, consider me interested.

**Comment by andreaspada** [comment]
I love the idea of a scratchpad. Something like a dashboard, but for useful monitoring apps... I feel the needs for something like you described, koe.

Enviado do meu iPhone

**Comment by koekeishiya** [comment]
> I would have use for this if I could open the scratchpad as a space on any screen at any time.

This was the intention, yeah.

> if I could swap all windows on the scratchpad with all windows on the active space with one button press, consider me interested.

I was not really thinking of swapping out the currently focused space, but rather being able to bring windows from the scratchpad to the foreground as floating - fullscreen, no matter which display or space you are currently on.

**Comment by koekeishiya** [comment]
Soo, the current implementation of this is rather simple.
Any given window can be added or removed from the scratchpad with the following command:
`kwmc scratchpad add` and `kwmc scratchpad remove`. You can only add or remove the currently focused window from the scratchpad.

The scratchpad has an arbitrary number of slots allocated, and when a window is added to the scratchpad using `kwmc scratchpad add`, the first free slot will be used.
When a window is removed from the scratchpad, that slot will on longer be occupied.

The command `kwmc scratchpad show | hide | toggle slot` must be used to hide, show, or toggle a window visible on the focused space (should not matter which display).

There will be added a command `kwmc scratchpad list` to show the current occupied slots and the window they are associated with, similar to `query window-list`.

Currently, a window will be in floating mode and centered in the middle of the screen, when made visible.
The position and size will probably become a config setting, but I think it is reasonable for it to always be treated as a floating window, as the scratchpad is supposed to be used for `show me -> do something -> hide` scenarios.

**Comment by dominiklohmann** [comment]
Just tried the early implementation, seems like a good system so far. 

> [...] but I think it is reasonable for it to always be treated as a floating window, as the scratchpad is supposed to be used for show me -> do something -> hide me scenarios.

Can they be unfloated?

---

I am still thinking about using this to implement some form of the space swapping behaviour I explained above. Do you think it will work with the following steps? Just toying around with ideas on how far I can push this system.

- Save current layout on space as `scratchpad-next`
- Get number of windows on scratchpad, store as `scratchpad-count`
- Send all windows from current space to scratchpad
- Get `scratchpad-count` oldest windows from scratchpad, unfloat them all
- Restore `scratchpad` layout (if available), then rename `scratchpad-next` layout to `scratchpad`

**Comment by koekeishiya** [comment]
> Can they be unfloated?

This is possible, yeah.

> I am still thinking about using this to implement some form of the space swapping behaviour I explained above. Do you think it will work with the following steps? Just toying around with ideas on how far I can push this system.

I'm really not as of now if that would work or not.
