### ISSUE TITLE
sys passes stdin?

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#338]
Whenever I try to do `sys subl -n` (`subl` being the executable for Sublime Text, symlinked from inside the application, and `-n` specifying a new window), Sublime opens with a file called `/private/tmp/subl stdin <alphanumeric>.txt`. I can't reproduce this in bash or zsh. Any insight on how `system()` in C++ works that might be helpful?

**Comment by koekeishiya** [comment]
I'm honestly not sure how `system` works. I usually do a comination of `fork` and `execv`, however this was not possible due to something with Carbon iirc, `fork` failed.

**Comment by matthewdias** [comment]
ok so, subl has an option where it can take input when you do `subl -`. eg. `ls | subl -`. for some reason, it's doing this and ignoring the `n` in `subl -n`

**Comment by matthewdias** [comment]
huh. it works when i run the kwm executable from terminal, but not when it's running from launchctl...

**Comment by dominiklohmann** [comment]
If that is the case you need to tell launchd what your $PATH is.

**Comment by matthewdias** [comment]
@dominiklohmann yeah, for the PATH key in the plist, the value includes /usr/local/bin which is where my subl executable is. Is that what you meant? Also to be clear, using launchctl it runs the command, but ignores the `n` at the end for some reason.

**Comment by dominiklohmann** [comment]
Ohhh... I haven't seen the second but last post before mine. Nvm then, ignore what I said above. 

The actual issue seems to be a parser issue then? Does it work with `subl --new-window`?

**Comment by matthewdias** [comment]
nope, I tried that earlier, and it does the same thing.

**Comment by dominiklohmann** [comment]
Does it work if you create a shell script for Kwm to execute that runs subl?

**Comment by matthewdias** [comment]
Same result.

**Comment by koekeishiya** [comment]
The latest master now uses `fork()` and `execvp()` instead of `system()`.
I do not think this will fix your problem, as the environment used when running under launchctl differs 
from the when used by your user.

The syntax for running external commands have been changed from `sys` to `exec`.

Also, I would advice using the implemented variable-system to provide the full path to an executable.
```
define nvim /usr/local/bin/nvim
kwmc bindsym cmd-return exec nvim arg1 arg2 ..
```

**Comment by matthewdias** [comment]
This commit broke a lot of functionality for me. Many of my binds don't function, including focusing windows.

**Comment by koekeishiya** [comment]
> including focusing windows.

That makes no sense, there has been no changes to how this works in this commit.

**Comment by matthewdias** [comment]
It's very possible I just did something dumb. I'll try again tomorrow.

**Comment by koekeishiya** [comment]
The tilde operator does no longer expand I believe, in case you have `~` used in the binds that fail.

**Comment by matthewdias** [comment]
Ok, works fine now, I have no idea what was causing the issue... also yeah, the `subl` thing still isn't working, but it's not a kwm issue so ill go ahead and close this.
