### ISSUE TITLE
Password input focus steals key input from kwm

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#339]
Steps to reproduce: 

1. Open any browser to a page that has a password input
2. Focus the password input
3. Attempt to make ANY key bind command to kwm. 

Expected Result: kwm receives and executes keybind command. 
Actual Result: kwm does not receive any key press notifications. 

Note: I actually think this is some security feature put in place by OS X, so feel free to close this as won't / can't fix. I just wanted to raise the issue in case there is something that can be done.

**Comment by koekeishiya** [comment]
>I actually think this is some security feature put in place by OS X

This is indeed the case. The only solution would probably be to intercept at an even lower level, but I don't really think this is worth the effort.
