### ISSUE TITLE
Set default rotation in kwmrc ?

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/kwm#340]
Hi,

Is there a way to do a

    kwmc tree rotate 90

by default in `kwmrc`?

I would like that new windows tile vertically instead of horizontally.

Thanks,

Regards,

**Comment by koekeishiya** [comment]
```
 Set active split-mode of display
        kwmc display -c <opt>
        <opt>: optimal | vertical | horizontal
```

This is applied globally and not per display right now. Could be what you are looking for.

**Comment by mickaelperrin** [comment]
Thanks, but this is not exactly what I am looking for.

With `kwmc display -c vertical`, all windows are split vertically.

I would love to use the `optimal` setting, but the second window added in the space splits it vertically instead of horinzontally.

**Comment by koekeishiya** [comment]
> With kwmc display -c vertical, all windows are split vertically. In particular, the third window added to the space continue to be split vertically. 

> I would love to use the optimal setting, but the second window added in the space splits it vertically instead of horinzontally.

Remember that this option can be changed whenever you want, and not only from the `kwmrc` file. I suggest just making keybinds for switching between `optimal` and `vertical`.

**Comment by dominiklohmann** [comment]
> I would love to use the optimal setting, but the second window added in the space splits it vertically instead of horinzontally.

I had a similar issue and ended up adjusting the `optimal-ratio` used for splits in optimal mode. I had the issue where the first two splits were vertical on the monitor I'm having the dock open on.

You can adjust it like this:
```
# Default is the golden-ratio (1.618...)
kwmc config optimal-ratio 1.611 
```

**Comment by mickaelperrin** [comment]
Awesome 👍 It works for me but with a ratio of `1.6`. Thanks !

**Comment by dominiklohmann** [comment]
I'd suggest keeping the value as close to the golden ratio as possible, as the golden ratio is what makes windows split in a way that they have the most area to work with.
