### ISSUE TITLE
direction skips windows that are overlapped

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#344]
since it's checking from the center, if you have a window that has minimum constraints, and is pushed over so that it's center overlaps an adjacent window, the direction will skip that adjacent window. Maybe kwm should check from the opposite edge to the desired direction instead?

eg. ![](https://i.imgur.com/X8LdkSd.png)

here if I do `kwmc window -f east`, it will skip over and focus Terminal. maybe it should instead check from the left edge of the chrome window, since i chose `east`.

**Comment by koekeishiya** [comment]
Can you pull the latest master and re-test. I actually perform proper angle detection now (if I got the math correct), instead of adding fake weights as before.

**Comment by matthewdias** [comment]
Now, (with the same example as before) going `east` from chrome selects the next window, but when i do `east` again to wrap around, it focuses the same chrome window again.

**Comment by matthewdias** [comment]
When the two windows have the same horizontal center, wrap just doesn't do anything. When they have different horizontal centers, it behaves like I described in the previous comment.

**Comment by koekeishiya** [comment]
Directional focusing should now work properly on master. I am aware that it is broken when using `kwmc confic cycle-focus screen`. I made issue #343 for that, and so I'll close this one.

**Comment by matthewdias** [comment]
Oops, didn't see your edit, since I didn't reload the page. (github should fix that). Anyway, it works fine with cycle-focus off.

**Comment by koekeishiya** [comment]
The issue should be resolved now.
