### ISSUE TITLE
System keyboard shortcuts get lost

### ISSUE THREAD

**Issue by neon64** [koekeishiya/kwm#345]
I am new to kwm so forgive me if I have missed something obvious.

While kvm is running, 'system' or 'global' keyboard shortcuts are lost. For example, cmd+space usually opens spotlight, but when kwm is running nothing happens. Is this desired behaviour? If so is there a way to manually pass through some shortcuts?

I tried doing the following but it didn't work.

    kwmc bindsym-passthrough cmd-space exec echo hi
I'm guessing that is because `bindsym-passthrough` passes it to the app not to OS X itself.

*On a more general note:* I am loving `kwm` so far 👍 . It instantly beats my hacked-together, buggy and slow setup with Lua and Hammerspoon and makes me want to delay my fantasy of switching to i3wm under Linux. In particular I am impressed kwm's  `autofocus` option as I previously thought it was impossible for Mac OS X (http://steve-yegge.blogspot.com.au/2008/04/settling-osx-focus-follows-mouse-debate.html). Is there any reason why autoraise is the default when you have lovely autofocus?

**Comment by koekeishiya** [comment]
The system shortcuts not passing through is due to `autofocus`. This is a technical limitation and also why `autoraise` is the default option.

**Comment by neon64** [comment]
Aha thank you for your quick assistance - my favourite feature and major annoyance are actually interconnected!
So then is there a way to open Spotlight programmatically - with AppleScript or a shell command or something?

**Comment by koekeishiya** [comment]
Even if you were able to open `Spotlight`, you would not be able to write text into as long as `autofocus` is active. The only "real" option I can suggest for you as of now is to use the following bind:
`kwmc bindsym-passthrough cmd-space config focus-follows-mouse off` and then create some other bind that you can hit to enable `autofocus` again when you are done.

**Comment by neon64** [comment]
Ok thanks for the diagnosis I will probably just stick to autoraise...
