### ISSUE TITLE
Add app support to layouts

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#346]
From #249:

> recognize apps when saving/restoring tree so that apps are tiled in the same places they were on save (example: on restore, chrome is always tiled first, then sublime, then terminal)

Now that there is a rule system, maybe the functionality behind that could be used instead of just app names.

**Comment by chrishoage** [comment]
I've been desiring this quite badly lately. 

It would be super cool to be able to use the rule system to set layout tiling order. I have no need to make sure the windows are in the same order - just that the apps are in the correct order. 

I'd like to tile all my Chrome windows first, then all sublime windows, then all iterm windows, as an example. 

This would remove all of the tedium of moving windows when a new layout is applied.

**Comment by koekeishiya** [comment]
Not really sure how to implement this yet.

**Comment by chrishoage** [comment]
No worries, I just saw the ticket again and it reminded me how neat it would be.

**Comment by matthewdias** [comment]
Relevant issue for chunkwm: https://github.com/koekeishiya/chunkwm/issues/190
