### ISSUE TITLE
Keyboard Shortcuts Don't Work

### ISSUE THREAD

**Issue by kohlmannj** [koekeishiya/kwm#347]
Long story short, I feel like a complete idiot right now.

On OS X 10.11.4, running on a 2013 Retina MacBook Pro 15", I've installed the latest version of kwm avilable from Homebrew. I've then copied the contents of [the example kwmrc](https://github.com/koekeishiya/kwm/blob/master/examples/kwmrc) into `~/.kwm/kwmrc`, and I've started kwm with `brew services start homebrew/binary/kwm`. I get the example `kwmrc`'s focus border, but for the life of me I cannot activate any of the shortcuts.

What physical actions with my fingers on the keyboard should I even be performing? For example, pressing Command and Return together prematurely submitted this GitHub Issue comment rather than [launching iTerm](https://github.com/koekeishiya/kwm/blob/master/examples/kwmrc#L124).

How am I supposed to use the prefix keystroke? Is there any visual feedback when the prefix keystroke has been received?

Yes, this is a completely sullen request for help, please and thank you.

**Comment by koekeishiya** [comment]
The version on homebrew has a different syntax than the master branch. You should copy the config that came with the homebrew version instead, `cp /usr/local/Cellar/kwm/2.2.0/kwmrc ~/.kwm/` or something.

**Comment by kohlmannj** [comment]
Alright, working keybindings (but of course). Thanks very much and apologies for the inane question!
