### ISSUE TITLE
Mouse-over transition from float -> bsp between monitors, causes windows to be pulled over to bsp monitor

### ISSUE THREAD

**Issue by sieken** [koekeishiya/kwm#348]
I have an external monitor setup, and whenever I have float enabled on one of them, then mouse over to the other monitor, that has bsp enabled, it causes all windows to migrate into the screen with bsp enabled. This only happens whenever I have at least one other window on the bsp monitor.

To reproduce:
1. Enable bsp on one monitor, and open any window
2. Enable float on the other monitor, and open any window
3. Mouse over to the bsp monitor

I can not reproduce the same behaviour on any other transition between the modes, so I'm guessing this has something to do with either bsp or float, maybe?

I don't know if this is relevant or not, but it seems like if I go from float on external monitor to bsp on the built-in monitor, I can drag the pulled-over window back to the float external monitor again, and it won't happen again. However, transition from float built-in monitor to bsp external monitor, it seems to be more persistent on keeping my window on that display, and won't let me drag the window back.

**Comment by koekeishiya** [comment]
> I have an external monitor setup, and whenever I have float enabled on one of them, then mouse over to the other monitor, that has bsp enabled, it causes all windows to migrate into the screen with bsp enabled.

Ops, just an oversight on my part. I barely ever use floating mode. Thanks for noticing.
