### ISSUE TITLE
Not working for iTerm?

### ISSUE THREAD

**Issue by ranranking** [koekeishiya/kwm#349]
After updating, my iTerm is not tiling. Other applications work just fine. Only iTerm. I don't know why. I am not using any settings in kwmrc for now.

My iTerm version is: Build 2.9.20160430-nightly
OSX 10.11.4

**Comment by dominiklohmann** [comment]
Most likely due to the recent syntax change from 
 `kwmc config add-role AXDialog iTerm2` 
to 
`kwmc rule owner="iTerm2" properties={role="AXDialog"}`.

**Comment by ranranking** [comment]
Yes, it's working! Thank you very much. The syntax is changing all the time.

**Comment by koekeishiya** [comment]
from the readme:
> WARNING: The master branch is considered bleeding edge and changes may break configurations at any time! Check the latest release for a stable version.

I'm working on actually getting a proper API in place. There will probably be more syntax changes before a 3.0.0 release.

**Comment by ranranking** [comment]
@koekeishiya Alright! I will keep that in mind.
