### ISSUE TITLE
Segmentation Fault when using `alt+cmd+[l/r]arrow`

### ISSUE THREAD

**Issue by hhsnopek** [koekeishiya/kwm#35]
Segmentation Fault when using `alt+cmd+[l/r]arrow` while in Google Chrome

**Comment by koekeishiya** [comment]
alt+cmd+[l/r]arrows decrease screen padding, the focused window should not have any impact at all.

Did you happen to have external monitors connected when this happened?

**Comment by hhsnopek** [comment]
Nope, I only use the screen on my lapto
tho in Chrome those cmds actually switch between tabs, moving left and right

**Comment by koekeishiya** [comment]
Honestly I have no idea how to start debuggin this. Seems to work just fine for me, can't reproducte it.
Could be some obscure bug that happens when the stars align.

I'll let it be for now, let me know if it happens frequently.

**Comment by hhsnopek** [comment]
happens every time I attempt to switch between tabs, sorry I'm actually using `Google Chrome Canary`
this forces me to re-start kwm

**Comment by koekeishiya** [comment]
Aight hold on, I'll try and reproduce using Chrome Canary

**Comment by hhsnopek** [comment]
I just looked at my config, and I attempted to make chrome float, but only specified `Google Chrome` to do so

**Comment by koekeishiya** [comment]
Alright I've been able to reproduce the problem. I assume Google Chrome is indeed floating in your setup, that's what I had to do with mine to make the segfault happen.

So basically, what is happening is that when there are no tiled windows, after setting the screen padding, it tries to update whatever tiles exists at this point, and it appears I've forgotten to do a check here.

**Comment by hhsnopek** [comment]
Glad you were able to reproduce :smile: and that's how I've gotten mine setup as well

**Comment by koekeishiya** [comment]
The same problem exists for adjusting container gaps. I've just pushed a commit that fixes this.
Thanks

**Comment by hhsnopek** [comment]
You rock!
