### ISSUE TITLE
Swap focused window with largest window

### ISSUE THREAD

**Issue by jdve** [koekeishiya/kwm#354]
It would be great if there was a way to swap the currently focused window with whichever window is currently the biggest.  In other words, this means bringing the focused window into maximum view without adjusting anything else.  In [http://xmonad.org/manpage.html](xmonad), `mod+return` does this, and I've found it a great way to move windows around without needing to rotate or switch windows explicitly.  Right now, I use `ctrl+alt+h` to achieve a similar result, but it can take a few presses to move the right window into place.  Is this possible today?

**Comment by koekeishiya** [comment]
There is no concept of a "master" window, so the above is not something that is possible, nor will it be implemented.

If you just want the window to be maximized temporarily, toggling `kwmc window -z fullscreen` will do it. 
If you want to actually perform a swap, you can either mark the source or destination window using `kwmc window -mk focused`, then focus the window you did not mark, and perform `kwmc window -s mark`. This command will swap the focused window with the marked window.

**Comment by jdve** [comment]
Ah, I see.  Yeah, I wouldn't say it's a "master" window, since, as you said, that's not really a concept here.  I think of it more as "fit into largest space possible".

**Comment by koekeishiya** [comment]
I've decided that this is not something I want to be doing. There is a lot of swap and zoom-options available already.
