### ISSUE TITLE
Startup scripts

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/kwm#355]
The [startup.sh](https://github.com/koekeishiya/kwm/commit/fdc47969dbf019cb89c62d422e5a2ff015970983) script has been deleted from the repository.

With AwesomeWM, I wrote several scripts that helps me to move from one project to another without having the pain to relaunch / replace manually each window on each space / monitor.

So, I was wondering:

1/ is it still possible / recommended to write that kind of scripts ?
2/ could it be possible to save in a file the spaces organization. That would be a great help in the writing process of that kind of script. Kwm will generate an incomplete .sh file with windows names / screen / position / space and a manual edit will be performed to add the commands to run the displayed windows.

Thanks

**Comment by koekeishiya** [comment]
> 1/ is it still possible to write that kind of scripts ?

Kwm does still run `~/.kwm/init` upon startup, if it exists.

> > 1/ is it still recommended to write that kind of scripts ?

I personally do not use them, I very rarely shutdown my mac, so I do not have to relaunch my setup very often.
The `startup.sh` script was removed because most of the functionality provided can now be achieved in a better and more friendly manner.

You can make windows start on an assigned space by using rules:
`kwmc rule name="match some window" properties={space="2"; display="0"}` 
or whatever values. See the window-rule issue for information.

You can assign default bsp-layouts to spaces using the following command:
`kwmc config space display_id space_id tree name_of_layout`.
e.g: `kwmc config space 0 1 tree dev`

**Comment by mickaelperrin** [comment]
Thanks for the advice.

Each person has its own use case of course. I personally need to switch from one project to another multiple times in a day and for each project I need a lot of windows: 2 - 3 terminal prompts, 1 IDE, 2 -3 browser windows, and maybe additional programs.

Rules are great, I use them a lot, but not for assigning spaces /  monitors but for setting floating essentially. It was the same with AwesomeWM on Linux, I was not able to use rules, as I need the ability to run multiple projects at the same time and so assign same windows to different spaces.

For example, my typical organization is:
- space 1 : project 1 > terminals
- space 2: project 1 > IDE
- space 3: project 1 > browsers
- space 4: project 1 > other stuff

When I need to work on another project at the same time, I want that the new project displays like that: 
- space 5: project 2 > terminal
- space 6: project 2 > IDE
- space 7: project 2 > browsers
- space 8: project 2 > misc

With AwesomeWm, I resolved this feature by using some kind of *relative* spaces. When running the script I get the current space number, and use that kind of config:
- current space + 0: terminal
- current space + 1: IDE
- current space +2: browsers
- current space +3: misc

So, my question is : what is the most effective way to set programs to start up on a specific space without using rules ?

Is the pattern switch to space > sleep > run command > sleep > switch to another space > sleep > run command > sleep... is the only way to achieve that ?

I think it can become cumbersome with some applications that take some time (bigger than the sleep time) to start.

Can I create rules and automatically delete them at the end of script ?

**Comment by koekeishiya** [comment]
> Can I create rules and automatically delete them at the end of script ?

You can't really delete rules, however, you can do a `kwmc config reload` to clear all rules and only re-add those that are writtein inside `kwmrc`.

You could try something like the following:
```
kwmc=/usr/local/bin/kwmc
current_space=$($kwmc query space active id)
fst_space=$current_space+1
snd_space=$current_space+2
$kwmc rule owner="match my terminals" properties={space="$fst_space"}
$kwmc rule owner="match my ide" properties={space="$snd_space"}
./openTerminals
./openIDE

# reload config to clear above rules
# might need a sleep before this line,
# so that applications finish starting up and get moved.
$kwmc config reload
```

**Comment by mickaelperrin** [comment]
Yeah, indeed the `kwmc config reload` to flush rules should do the trick ! I should have think about it :)

Thanks again 👍

**Comment by matthewdias** [comment]
@mickaelperrin I've been working on a similar setup using bash scripts [here](https://github.com/matthewdias/dotfiles/tree/master/.kwm/scripts). See `createsession` and `opensession`. Currently using [this](https://github.com/matthewdias/kwm-alfred) to trigger them.

**Comment by mickaelperrin** [comment]
Sorry for busying you again with that.

I just gave a try today, but rules doesn't seem to apply.

Here is my test script:

    #!/usr/bin/env bash
    kwmc=/usr/local/bin/kwmc
    current_space=$($kwmc query space active id)
    space=$(($current_space + 1))

    chrome () {
        osascript &>/dev/null <<EOF
           tell application "Google Chrome"
            make new window
            open location "$1"
        end tell
    EOF
    }

    chrome_rule="$kwmc rule owner=\"Google Chrome\" properties={float=\"true\"; space=\"$space\"}"
    echo $chrome_rule
    eval $chrome_rule

    chrome "https://github.com/koekeishiya/kwm"

I tried by copying / pasting the outputed rule in my kwmrc and it work.

Copying / pasting the rule in my terminal doesn't work also.

It seems that rules defined outside `kwmrc` doesn't apply.

Any hints ?

**Comment by koekeishiya** [comment]
You need to properly escape quotes and semicolon.

You can do either of the following:
```#!/usr/bin/env bash
kwmc=/usr/local/bin/kwmc
current_space=$($kwmc query space active id)
space=$(($current_space + 1))

chrome () {
    osascript &>/dev/null <<EOF
       tell application "Google Chrome"
        make new window
        open location "$1"
    end tell
EOF
}

chrome_rule="$kwmc rule owner=\"\\\"Google Chrome\"\\\" properties={float=\"\\\"true\"\\\"\; space=\"\\\"$space\"\\\"}"
echo $chrome_rule
eval $chrome_rule

chrome "https://github.com/koekeishiya/kwm"
```
or
```
#!/usr/bin/env bash
kwmc=/usr/local/bin/kwmc
current_space=$($kwmc query space active id)
space=$(($current_space + 1))

chrome () {
    osascript &>/dev/null <<EOF
       tell application "Google Chrome"
        make new window
        open location "$1"
    end tell
EOF
}

$kwmc rule owner=\"Google Chrome\" properties={float=\"true\"\; space=\"$space\"}

chrome "https://github.com/koekeishiya/kwm"
```

**Comment by mickaelperrin** [comment]
Erf, forgot again that `kwmc` commands that are running directly in a shell must be escaped... the echo / eval was here almost as debugging purposes.

Thanks for your help
