### ISSUE TITLE
What is a quick method to go from monocle to a 2-window vertical split?

### ISSUE THREAD

**Issue by scottgrayson** [koekeishiya/kwm#356]
I usually cycle through monocle windows on my laptop because i like looking at big text, but sometimes I would like to split screen. What is the quickest way to do this? 

Example: I have 5 windows in monocle mode, and I would like to show windows 1 and 2 in a vertical split

**Comment by matthewdias** [comment]
The fastest way currently is to just go back to bsp mode and minimize the others. Potential additions that could solve this are:

- some kind of method to zoom a window to any container
- support for layouts that could tile windows until there are no more directions, and then set the remaining windows as floating, (choosing windows in order based on rules as in #346)

**Comment by scottgrayson** [comment]
When you say "minimize" are you referring to an osx command (cmd-m / cmd-h)? Or is there a kwm minimize you would use?

**Comment by matthewdias** [comment]
Yup just referring to system's minimize. Tho if you are looking for similar functionality in kwm, you can checkout the scratchpad.

**Comment by koekeishiya** [comment]
I've never really thought about the use case this issue represents and it is not something I want to spend time on implementing. The "best" option I can give you would probably be to simply move the 2windows to a new space, that is tiled using bsp mode.
