### ISSUE TITLE
Kwm prevent some app(s) to recognize shortcuts keys

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/kwm#358]
Hi,

I am not sure that it is a bug in KWM but I just installed this new app [Instant Translate](http://insttranslate.com/mac). 

I went into the properties of the app to set a shortcut to quickly open the app, but as long as KWM is running the input didn't recognize my typing. Stopping KWM makes it work normally.

I tried to play with `kwmc bindsym_passthrough alt-cmd-t`but didn't help so far.

Any hints ?

**Comment by koekeishiya** [comment]
> kwmc bindsym_passthrough alt-cmd-t

Should be `kwmc bindsym_passthrough alt+cmd-t`

**Comment by mickaelperrin** [comment]
Argh, thanks again for the quick answer, and the typo.
