### ISSUE TITLE
Refine prefix behavior

### ISSUE THREAD

**Issue by willhoag** [koekeishiya/kwm#359]
**Deactivate prefix mode after issuing a command:** It would be nice to have a `config` option to end prefix mode the moment a command is issued. As it stands now, prefix mode remains active until the `prefix-timeout` has passed with no commands being issued. For instance, one can activate prefix mode and keep it active by continually switching back and forth between windows. I've kept my `prefix-timeout` short (ie: 0.35), but it still occasionally interferes when I try typing shortly after switching windows.

i.e. `kwmc config prefix-quick-deactivate on`

**Let prefix mode be toggle-able:** In addition, it would be nice if there were the `config` option to make prefix mode toggle-able so prefixed commands could be issued in bulk without worrying about the timeout. Ideally this would be a separate `prefix-key` so both functionalities would be accessible at runtime.

i.e. `kwmc config prefix-toggle-key ctrl+shift+s`

**Comment by matthewdias** [comment]
>Deactivate prefix mode after issuing a command

Right now you can achieve this by making a shell script to use while in a binding mode. (`kwmc mode activate <bindingmode>`) It would execute the command you want and then run `kwmc mode activate default`. You could make it modular so that the script just executes the command you pass to it, that way you only need one script to handle running commands while in any prefix mode.

>Let prefix mode be toggle-able

Use binding modes, and set the same key used to activate the binding mode, to activate the default mode, while you are in the binding mode. eg:

```
kwmc bindsym ctrl-m mode activate custommode
kwmc bindsym custommode+ctrl-m mode activate default
```

**Comment by koekeishiya** [comment]
There is not really a notion of a prefix mode anymore. There are just modes.

> Deactivate prefix mode after issuing a command

This can be achieved like this:
`kwmc bindsym somebind command ; mode activate default`
Replace default with whatever mode you want to activate.

> Let prefix mode be toggle-able: 

This is just what a normal mode is, if you do not perform `kwmc my_mode prefix on`
You'd have binds like the following:
```
// Activate my_mode
`kwmc bindsym ctrl-f mode activate my_mode`

// Random binds
`kwmc bindsym my_mode+some_binds some_command`

// Exit my_mode and enter default mode when ctrl-f is pressed
`kwmc bindsym my_mode+ctrl-f mode activate default`

**Comment by matthewdias** [comment]
LOL ill remote mine.

**Comment by willhoag** [comment]
Wonderful. Will give master a try today. Thanks.
