### ISSUE TITLE
Add delay on focus follows mouse

### ISSUE THREAD

**Issue by cHoco** [koekeishiya/kwm#362]
A user on IRC proposed this features, focus a window only when the mouse is over it for X seconds.
It should be doable, we'd just need to write a wrapper around `FocusWindowBelowCursor()` call in `kwm.cpp` with some timer and some checks.

**Comment by koekeishiya** [comment]
I don't really get why this is useful?

**Comment by matthewdias** [comment]
probably cuz sometimes you want to just throw your cursor out of the way, or click on the menubar or something, and it catches a window on the way there.

**Comment by cHoco** [comment]
I don't think if I would personally use this, but I heard different users wanting something like this, so I just decided to open an issue on the tracker.

**Comment by mmmulani** [comment]
what about something like holding a modifier down disables focus following mouse?

it's often hard to navigate both menubars and random dialogs that apps pop up (e.g. iTunes connection or app updaters).

My current idea is that you can hold shift down and it would disable this feature. It would also be useful for the shift+command+4 screenshot feature.

Separately we could also disable focus follows mouse while you have a menubar open but that doesn't solve the whole problem as you need to navigate to the menubar from a focused application.

**Comment by andreaspada** [comment]
Wow, I definetely I on this. Shift (or any other custom modifier) to 
temporarily disable focus followin mouse seems a great addiction.
Looking forward

mmmulani wrote:

**Comment by mmmulani** [comment]
cool, I'll try to hack something together this weekend :)

**Comment by koekeishiya** [comment]
If you don't mind C coding, this could probably be achieved quite easily (although not a pretty solution), by adding a global boolean "ShiftKeyDown" or whatever. Toggle the value in the event-tap `kCGKeyDownEvent` and `kCGKeyUpEvent` and check the value of the modifier in ´kCGMouseMovedEvent`.

You need to extract the CGFlags from the Event to check if the ShiftMask has been set or unset.
```
CGEventFlags Flags = CGEventGetFlags(Event);
bool ShiftKeyDown = (Flags & kCGEventFlagMaskShift) == kCGEventFlagMaskShift;
```

I'll probably add this as a feature in the rewrite.

**Comment by mmmulani** [comment]
there's a rewrite coming? why?

**Comment by koekeishiya** [comment]
The current codebase is pretty entangled and there are not really any clear borders as to how the different parts should interact. This makes it more or less impossible to write proper multithreaded code, which we need for stability reasons. 

The rewrite will keep the exact same functionality from a user perspective, and will be pushed to the master branch when ready and released as version 3.0.0. That's the goal anyway.

**Comment by mmmulani** [comment]
ah cool, that makes sense and sounds pretty interesting :)

**Comment by thonixx** [comment]
Regarding the general topic: It is useful to have a delay or at least having a modifier key to reach the menubar or click on popup windows. Having i.e. 4 windows and then navigating to the menubar is not really comfortable with losing the original focus all the time when accidentally hovering over another window.

**Comment by koekeishiya** [comment]
I don't think this is something I'm interested in implementing, as it is already possible to simply just create a bind for `kwmc config focus-follows-mouse toggle`.
