### ISSUE TITLE
kwmc query space tiling mode 

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#367]
Before there was a way to get the current spaces tiling mode with out the window information. This query seems to have been removed. 

Can we get a query for the focused space tiling mode with out the window info? 

```
[bsp] iTerm2 - zsh
```

vs
```
[bsp]
```

**Comment by matthewdias** [comment]
I've been using `kwmc query space active tag | sed 's/ .*//'`

**Comment by cHoco** [comment]
I user on IRC was asking for the same thing, in the mean time you may use this quick patch https://gist.github.com/cHoco/6f2753ca0c0beed6d8fc73bbc6e67029
`kwmc query space active tiling-mode`

**Comment by chrishoage** [comment]
@cHoco Thanks, that's almost what I was looking for. 

That just gives me the mode name `monocle`. `query space active tag` gives me `[1/2]` when `monocle` is active. 

Using the sed command gets me what i'm looking for in the mean time. Thanks @matthewdias!

**Comment by koekeishiya** [comment]
`kwmc query space active mode`
