### ISSUE TITLE
Per display mode config does not work

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#368]
I have `kwmc config display 1 mode monocle` in my config. Display 1 does not use `monocle` mode, it must be manually set. 

Possibly related to #360

**Comment by koekeishiya** [comment]
Works fine for me, do you get any config errors?

**Comment by chrishoage** [comment]
I can't seem to reproduce the issue now. It happened after kwm recovered from a crash a couple times. I tried to "fake" it with `kwmc quit` but it works correctly in that scenario. 

Closing for now.
