### ISSUE TITLE
Border windows invisible in Mission Control

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#369]
When the border is on a window, and mission control is activated, the focused window is invisible in the space thumbnail. Not sure if there is a way around this.

**Comment by chrishoage** [comment]
Is anything focused when Mission Control is activated? Wouldn't there be no focused border if there was nothing focused? 

Have I misunderstood the issue?

**Comment by chrishoage** [comment]
Nevermind, I have misunderstood the issue. You're talking about what the focused window was, not the border.

**Comment by matthewdias** [comment]
Right to clarify, when using a the focused border, the focused window will always be invisible in mission control.

**Comment by chrishoage** [comment]
<img width="233" alt="screen shot 2016-05-13 at 4 31 28 pm" src="https://cloud.githubusercontent.com/assets/1056886/15264460/2b6fea88-1928-11e6-9d5f-b7b8db810105.png">

On the left side of the thumbnail there should be a tall window. 

Seems like OS X is thinking the border-window is the focused window, not the window behind it.

**Comment by matthewdias** [comment]
Right, yeah

**Comment by cHoco** [comment]
I took a look at this and this is probably a limitation (maybe a bug) of mission control.
Probably for performance reasons they just ignore the alpha value of windows when rendering them in these thumbnails.
If we can track when we enter/exit mission control we could probably clear the border so the window become visible again.

**Comment by matthewdias** [comment]
Related: the border should get moved to the new space when you switch spaces from mission control.

**Comment by koekeishiya** [comment]
> Related: the border should get moved to the new space when you switch spaces from mission control. 

Can't be fixed. After switching space through mission control, re-enter missionc ontrol and exit again, and the border will be shown.

This appears to be a side-effect of fixing the side-effect of the fix for #131.
I'm sure cHoco can fill you in if necessary.

The point I guess is, there will always be side-effects due to OSX.

**Comment by koekeishiya** [comment]
This is actually no longer an issue with the latest master. I've gone back to having kwm-overlay 'join all spaces', instead of Kwm moving it from space to space.
