### ISSUE TITLE
How to get the display id?

### ISSUE THREAD

**Issue by neon64** [koekeishiya/kwm#370]
The documentation doesn't explain what the display id is (used by commands like `kwmc config space <display> <workspace> name <name>`) or how to retrieve it.

I've tried 0, 1, and also 69730752 which is the ID returned by this Swift code:

```
let screens = NSScreen.screens()!
let screenDescription = screens[0].deviceDescription["NSScreenNumber"])
```

**Comment by neon64** [comment]
To give a full picture I'm trying to set space names like this:

```
kwmc config space 69730752 1 name FirstSpace
kwmc config space 69730752 2 name SecondSpace
```

And then recall them through `kwmc query space list` which currently returns nothing:

```
1, [no tag]
2, [no tag]
```

**Comment by koekeishiya** [comment]
from the example config:
```
/* 
Override default settings for space 1 on screen 0
   kwmc config space 0 1 mode monocle
   kwmc config space 0 1 padding 100 100 100 100
   kwmc config space 0 1 gap 40 40 
*/

/* 
Override default settings for screen 1
   kwmc config display 1 mode bsp
   kwmc config display 1 padding 100 100 100 100
   kwmc config display 1 gap 40 40 
*/
```

0 is the primary monitor. It uses the standard numbering that usual display-properties applications would use.
