### ISSUE TITLE
kwm running fine, doesn't seem to function

### ISSUE THREAD

**Issue by elakat** [koekeishiya/kwm#371]
I've tried building kwm from the master source, and tried the 2.2.0 release binaries. I've also tried the homebrew release. kwm always builds and executes with no problem but there's no indication that it's actually working.

I don't get any window tiling after executing. It's as if it's not even there.

I have, however, noticed a slew of messages coming from the Console every time I run kwm

`16/05/2016 6:23:33.533 PM com.apple.xpc.launchd[1]: (homebrew.mxcl.kwm) The UserName key is not supported for non-System services.`
`16/05/2016 6:23:33.533 PM com.apple.xpc.launchd[1]: (homebrew.mxcl.kwm) This service is defined to be constantly running and is inherently inefficient.`
`16/05/2016 6:23:33.578 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22`
`16/05/2016 6:23:33.581 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22`
`16/05/2016 6:23:33.583 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22`
`16/05/2016 6:23:33.602 PM appleeventsd[50]: SecTaskLoadEntitlements failed error=22`

I also tried to check the ports with
`lsof -i :3020`
which returns:
`COMMAND    PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME`
`kwm       4080 dayuna    4u  IPv4 0x13cc29ce3b1eb03d      0t0  TCP localhost:cifs (LISTEN)`
`kwm-overl 4082 dayuna    4u  IPv4 0x13cc29ce3b1eb03d      0t0  TCP localhost:cifs (LISTEN)`

I have command line tools installed with the latest version of Xcode. Running OS X 11.1.3

Any help would be much appreciated.

**Comment by cHoco** [comment]
Hello, if possible follow these steps:
1. In System Preferences -> Security & Privacy -> Accessibility remove from the list kwm and Terminal if present
2. Restart computer
3. Clone the repository and run `make` command, this builds a version with debug logging enabled
4. Launch `kwm` directly not with `launchctl` : `./bin/kwm` (should ask to grant kwm and or terminal accessibility privileges)
5. Make sure the `kwmrc` in the `~/.kwm` directory has the right syntax for the version your building (example kwmrc in the repository works correctly only for latest master

Report back with logs and we should be see what's wrong.

**Comment by elakat** [comment]
Hey thanks for your help.

So I uninstalled the brew version (which I was running) and removed both kwm and iTerm from Accessibility.
I restarted, cloned the repository and ran `make` and can tell I'm running a debug build as when I run `./bin/kwm` it's output in the iTerm window is verbose.

However I can't find the logfiles. I have added `StandardOutPath` and `StandardErrorPath` to the plist file but no files are being generated for me.

**Comment by elakat** [comment]
Although now that I think about it editing the plist file shouldn't change anything since I'm running natively and not through `launchctl`. Can you point me in the right direction?

**Comment by cHoco** [comment]
Oh sorry with logs I meant the output kwm in the iTerm window.

**Comment by elakat** [comment]
Hmmm...

this is what I get:
`Skytower:kwm dayuna$ ./bin/kwm`
`Local Daemon is now running..`
`ChangeSplitRatio() New Split-Ratio is 0.5`
`Creating screen info for display ID: 69503784 Resolution: 2560x1440 Origin: (0,0)`
`DisplayID 69503784 has index 0 and Identifier 787A3BBE-A85A-50D7-0B2B-CE37F71C1183`

Doesn't seem like something out of the ordinary.

**Comment by cHoco** [comment]
and opening new windows, moving from a space to another etc.. doesn't print out anything?

**Comment by elakat** [comment]
nope it hangs right at the DisplayID message and won't print any of my actions.

**Comment by cHoco** [comment]
Can you post your `kwmrc` ?

**Comment by elakat** [comment]
I'm using the default kwmrc from the `master` build.

```
/*
This is a sample config for Kwm

Commands prefixed with 'kwmc' will call
local functions corresponding to the
kwmc syntax.

To run an external program or command,
use the prefix 'exec' followed by command.
e.g 'exec mvim' would open macvim

Read file and execute commands as
if they were written inside kwmrc.

include filename

e.g: bindsym-commands in a separate file called 'binds'
include binds

Create variables that can be used in the below commands.
Variables are in file-scope and must be defined before
they can be used. Re-definition is also possible.
Variable names can not contain whitespace, where as
the value can.

define variable value

e.g: create a variable for the hyper-key
define hyper cmd+ctrl+alt+shift
kwmc bindsym hyper-h window -f west
*/

// Set default values for screen padding
kwmc config padding 40 20 20 20

// Set default values for container gaps
kwmc config gap 15 15

// Default tiling mode for Kwm (bsp | monocle | float | off)
kwmc config tiling bsp

// Let Kwm listen for hotkeys
kwmc config hotkeys on

// Automatically float windows that fail to resize
kwmc config float-non-resizable on

// Automatically resize the window to its container
kwmc config lock-to-container on

// Set focus-follows-mouse-mode to autoraise
kwmc config focus-follows-mouse autoraise

/* Focus-follows-mouse is temporarily disabled when
   a floating window has focus */
kwmc config standby-on-float on

/* The mouse will automatically move to the center
   of the focused window */
kwmc config mouse-follows-focus on

// Allow window focus to wrap-around
kwmc config cycle-focus screen

/* Override default settings for space 1 on screen 0
   kwmc config space 0 1 mode monocle
   kwmc config space 0 1 padding 100 100 100 100
   kwmc config space 0 1 gap 40 40 */

/* Override default settings for screen 1
   kwmc config display 1 mode bsp
   kwmc config display 1 padding 100 100 100 100
   kwmc config display 1 gap 40 40 */

// Set default container split-ratio
kwmc config split-ratio 0.5

// New splits become the left leaf-node
kwmc config spawn left

/* Add custom tiling rules for applications that
   does not get tiled by Kwm by default.
   This is because some applications do not have the
   AXWindowRole and AXStandardWindowSubRole */
kwmc rule owner="iTerm2" properties={role="AXDialog"}

/* The following commands create rules that
   blacklists an application from Kwms tiling

   kwmc rule owner="Steam" properties={float="true"}
   kwmc rule owner="Photoshop" properties={float="true"} */

/* The following command creates a rule that
   captures an application to the given screen,
   if the screen exists.

   kwmc rule owner="iTunes" properties={display="1"} */

// Enable border for focused window
kwmc config border focused on
kwmc config border focused size 2
kwmc config border focused color 0xFFBDD322
kwmc config border focused radius 6

// Enable border for marked window
kwmc config border marked on
kwmc config border marked size 2
kwmc config border marked color 0xFFCC5577
kwmc config border marked radius 6

// Enable the prefix mode
kwmc mode prefix prefix on
kwmc mode prefix timeout 0.75
kwmc mode prefix restore default
kwmc mode prefix color 0xFF458588

/*  Default Keybinds */
// Activate prefix mode
kwmc bindsym ctrl-s mode activate prefix

// Quit Kwm
kwmc bindsym cmd+alt+ctrl-q quit

// Launch iTerm2
kwmc bindsym cmd-return exec open -na /Applications/iTerm2.app

// Set Space Tiling Mode To BSP
kwmc bindsym cmd+ctrl-a space -t bsp

// Set Space Tiling Mode To Monocle
kwmc bindsym cmd+ctrl-s space -t monocle

// Set Space Tiling Mode To Floating
kwmc bindsym cmd+ctrl-d space -t float

// Rotate Window-Tree By 90degrees (Clockwise)
kwmc bindsym cmd+ctrl-r tree rotate 90

// Modify Container
kwmc bindsym prefix-s window -c split-mode toggle
kwmc bindsym prefix-h window -c reduce 0.05
kwmc bindsym prefix-l window -c expand 0.05
kwmc bindsym prefix-< window -c type toggle

// Set Temporary Window Container
kwmc bindsym prefix-f window -z fullscreen
kwmc bindsym prefix-d window -z parent
kwmc bindsym prefix-w window -t focused

// Mark Window
kwmc bindsym cmd+alt+ctrl-m window -mk focused
kwmc bindsym cmd+alt+ctrl-h window -mk west wrap
kwmc bindsym cmd+alt+ctrl-l window -mk east wrap
kwmc bindsym cmd+alt+ctrl-j window -mk south wrap
kwmc bindsym cmd+alt+ctrl-k window -mk north wrap

// Give Focus To Window
kwmc bindsym cmd+alt-h window -f west
kwmc bindsym cmd+alt-l window -f east
kwmc bindsym cmd+alt-j window -f south
kwmc bindsym cmd+alt-k window -f north

kwmc bindsym cmd+alt-n window -fm prev
kwmc bindsym cmd+alt-m window -fm next

// Give Focus To Screen
kwmc bindsym cmd+alt-1 display -f 0
kwmc bindsym cmd+alt-2 display -f 1
kwmc bindsym cmd+alt-3 display -f 2

// Swap Focused Window
kwmc bindsym ctrl+alt-h window -s west
kwmc bindsym ctrl+alt-j window -s south
kwmc bindsym ctrl+alt-k window -s north
kwmc bindsym ctrl+alt-l window -s east
kwmc bindsym ctrl+alt-m window -s mark

// Pseudo containers
kwmc bindsym cmd+ctrl+alt-p tree -pseudo create
kwmc bindsym cmd+ctrl+alt-o tree -pseudo destroy
kwmc bindsym ctrl+alt-p window -s prev
kwmc bindsym ctrl+alt-n window -s next

// Detach Focused Window And Reinsert In Direction
kwmc bindsym ctrl+shift-k window -m north
kwmc bindsym ctrl+shift-l window -m east
kwmc bindsym ctrl+shift-j window -m south
kwmc bindsym ctrl+shift-h window -m west

// Detach Marked Window And Reinsert At Focused Window
kwmc bindsym ctrl+shift-x window -m mark

// Move Focused Window To Space
kwmc bindsym ctrl+alt-left window -m space left
kwmc bindsym ctrl+alt-right window -m space right

// Move Focused Window To Screen
kwmc bindsym ctrl+alt-1 window -m display 0
kwmc bindsym ctrl+alt-2 window -m display 1
kwmc bindsym ctrl+alt-3 window -m display 2

// Increase Container Gaps
kwmc bindsym prefix-x space -g increase horizontal
kwmc bindsym prefix-y space -g increase vertical

// Decrease Container Gaps
kwmc bindsym prefix+shift-x space -g decrease horizontal
kwmc bindsym prefix+shift-y space -g decrease vertical

// Increase Screen Padding
kwmc bindsym prefix-left space -p increase left
kwmc bindsym prefix-right space -p increase right
kwmc bindsym prefix-up space -p increase top
kwmc bindsym prefix-down space -p increase bottom
kwmc bindsym prefix-p space -p increase all

// Decrease Screen Padding
kwmc bindsym prefix+shift-left space -p decrease left
kwmc bindsym prefix+shift-right space -p decrease right
kwmc bindsym prefix+shift-up space -p decrease top
kwmc bindsym prefix+shift-down space -p decrease bottom
kwmc bindsym prefix+shift-p space -p decrease all

// Autowrite
kwmc bindsym cmd-7 write \
kwmc bindsym cmd-8 write {
kwmc bindsym cmd-9 write }
```

**Comment by cHoco** [comment]
Everything seems in order to me, the strange thing is that nothing is getting printed after the display id message... We could probably start debugging this better by adding additional logging to figure where it is blocking, but first can you check https://github.com/koekeishiya/kwm/issues/242#issuecomment-199408816 ? The "Display have separate spaces" should be active for kwm to work.

**Comment by elakat** [comment]
That was it! It's all running very smoothly now. Thank you for all your help. Now all I have to do is add to launchctl to have it run on startup?

**Comment by cHoco** [comment]
Yep, just edit line 9 of com.koekeishiya.kwm.plist in the example directory to point it to kwm binary and copy it in the LaunchAgents directory. After that `launchctl load ~/Library/LaunchAgents/com.koekeishiya.kwm.plist` and you should be good to go.
You can also just compile a release version with `make install` instead of the debug build. You should also probably remove iTerm from the accessibility list since you probably don't want it there for security reasons.
