### ISSUE TITLE
Unable to select windows with empty string name

### ISSUE THREAD

**Issue by vilhalmer** [koekeishiya/kwm#373]
I'm trying to get kwm to float Tweetbot's image viewer window, but tile the main window. Unfortunately, Tweetbot doesn't name the image window, and it is of the same type as the main window. I tried passing an empty string to the `name` attribute of a rule, but kwm seems to treat this as the same as not passing it at all, causing all of Tweetbot's windows to float. Is it possible to tweak so that empty string is treated as a valid/distinct window name?

Thanks!

**Comment by koekeishiya** [comment]
You can make a rule to float all of Tweetbot's windows, except for the main window, assuming that the main window does have a name.

`kwmc rule owner="Tweetbot bundle-name" properties={float="true"} except="Title of tweetbots main window"`

**Comment by vilhalmer** [comment]
Ah, excellent, I didn't realize the `except` option existed. I will do this for the meantime, and also bug Tweetbot's developers about naming their windows properly. Thanks again.
