### ISSUE TITLE
Request: Horizontal Window Scaling 

### ISSUE THREAD

**Issue by einermusstot** [koekeishiya/kwm#374]
HI koekeishiya,
thanks for your great work on the windowmanager so far. I lam absolutely in love with it. 
I am using it since a month and have one small request/question.

currently the windows are splited 50/50 as in fig.1 
this is sometimes unpractical, when I use a browser in the mainarea (marked m)

would it be possible to adjust the horizontal splitting and define one focused/main area with variable scaling? see fig. 2 

![kwm](https://cloud.githubusercontent.com/assets/19464373/15386581/dd5cd45c-1da8-11e6-9a4a-6a510f3ca943.png)

this would get me closer to have a DWM like setup, which I have been using on my old thinkpad all those years. 

I hope it made sense what I just typed. 

greetings

**Comment by dominiklohmann** [comment]
You can manually adjust the split ratio using these commands (for the selected container):
```
kwmc window -c reduce 0.05
kwmc window -c expand 0.05
```

You can adjust the default split ratio using this command in your kwmrc:
```
kwmc config split-ratio 0.5
```

**Comment by einermusstot** [comment]
hi thanks for the reply, reducing and expanding nested in vertical adjustments and not horizontal. :/ 
I will have to try the split-ratio later at home though.

**Comment by dominiklohmann** [comment]
> reducing and expanding nested in vertical adjustments and not horizontal

What border gets moved depends on what container is selected. You can also specifically say which border to move. Relevant snippet from the kwmc man page:

```
 Modify container split-ratio of window in direction
        kwmc window -c reduce <opt> <arg>
        kwmc window -c expand <opt> <arg>
        <opt>: 0 < floating point number < 1
        <arg>: north | east | south | west
```

**Comment by koekeishiya** [comment]
The commands mentioned by @dominiklohmann should be able to do what you want. The commands are abit clunky at this moment.

I will probably tweak them to be more intuitive, in the far future. Currently working on rewriting the entire Kwm core for stability maintainability purposes.

**Comment by koekeishiya** [comment]
> I'd also love to see the ability to be able to hit a key and be able to use the mouse to drag around window borders and adjust other windows accordingly. I was used to doing this with Awesome.

This is not very likely to happen due to the fact that nearly all applications have a minimum window size, making it highly likely that the internal node sizes and the actual window size is not equal. 
This would cause some trouble and it would not become a smooth action like it is with Linux window managers.
