### ISSUE TITLE
Importing music in itunes makes kwm unusable

### ISSUE THREAD

**Issue by Hawgk** [koekeishiya/kwm#378]
Title pretty much says it already. I started importing music from my external drive and I couldn't use any of kwm's shortcuts etc. It seems as if kwm freezes or at least gets really really slow while importing. This issue does not occur with osx' wm. 
I don't really know what I can do to help fix this issue but if you need a specific log or something similar I'll be more then glad to help out.
And btw I freaking love this wm, keep it up!

**Comment by koekeishiya** [comment]
I do have an idea of why this problem would occur.

It should be solved when I finally get time to rewrite the core.
As of now, no ETA for when that will be.

**Comment by koekeishiya** [comment]
I believe this is solved, but I have not actually tested it. Hopefully it is not as bad in v3.0.0
