### ISSUE TITLE
Move container splitter up/down does not appear to function

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#38]
I would first like to say that this is an amazing project, thank you very much for putting this out!

I have the following in my `kwmrc`

```
kwmc bind cmd+alt-leftarrow space -m left
kwmc bind cmd+alt-rightarrow space -m right
kwmc bind cmd+alt-uparrow space -m up
kwmc bind cmd+alt-downarrow space -m down
```

Left/Right move the splitter to the left and right, Up/Down does not appear to do anything. 

Further question related to this: Is there any way to specify in the `kwmrc` what the default heights and widths should be?

**Comment by koekeishiya** [comment]
From Readme:
"The width of the left/right pane can be changed, as well as the height of the upper/lower pane.
Currently these cannot occur simultaneously, and the type of panes created is decided by the main pane split-mode.

If the main pane is split using vertical mode, a left and right pane is created.
If the main pane is split using horizontal mode, an upper and lower pane is created. "

This is something I would love to look into further, I just need to find a proper way for the user to select which container to interact with.

Not totally sure what you mean by default width and height, but if you increase screen-paddings, the width/height will be smaller. For each split that occurs, this width / height will be cut in half.

**Comment by chrishoage** [comment]
Apologies, maybe I am misunderstanding the purpose of 

```
Move container splitter
    kwmc space -m left|right|up|down
```

Playing with it in my shell when I run `./bin/kwmc space -m left` the right panels grow in width and the left panels shrink. 

When I run `./bin/kwmc space -m right` the left panels grow in width and the right panels shrink. 

When I run `./bin/kwmc space -m up` and `./bin/kwmc space -m down` nothing appears to happen. 

My (probably mistaken) understanding from the README.md is that this command should change the size of all the panels in that direction? 

> Not totally sure what you mean by default width and height
I mean setting as a default what you could do with `./bin/kwmc space -m up/down/left/right`? Again I am probably misunderstanding something here. 

Thank you for your quick response!

**Comment by koekeishiya** [comment]
Right so regarding the `space -m down` etc commands, currently they only affect the root container,
so if the first split you do is a vertical split, only the `space -m left|right` commands will work.
For the `space -m up|down` commands, a horizontal split would have had to occur.

The split-type of any child container will not change the behaviour of this, and so it is lacking a lot of functionality that I would like to try and do at some point in the future.

What you describe regarding adjusting default width and height seems like what I'd call a split-ratio.
If I understand correctly, you wanna be like "ok so when this next split happens, I want the left window to take up 2/3rd of the width, and use 1/3rd for the new window"?

**Comment by chrishoage** [comment]
>  currently they only affect the root container

Got it, sorry that didn't click for me. Thank you very much for explaining, I misunderstood how it worked.

> What you describe regarding adjusting default width and height seems like what I'd call a split-ratio.
If I understand correctly, you wanna be like "ok so when this next split happens, I want the left window to take up 2/3rd of the width, and use 1/3rd for the new window"?

You do understand correctly, and from the readme that is not possible (unsure if that is something you desire to include or not). 

I will close this ticket as this behavior is as expected.

**Comment by koekeishiya** [comment]
Currently that is indeed not possible to do. It is something that I personally would want as well, and definitely something that I will look into.

**Comment by koekeishiya** [comment]
The split-ratio seems fairly easy to implement and does not require a lot of changes to the code.
I already have this working after less than 10minutes of work, however it requires some refining and has to be made more user-friendly.

**Comment by koekeishiya** [comment]
MoveContainerSplitter() will no longer affect the root container.
Instead it will adjust the split-ratio for the focused container, this should make the window-sizing a lot more flexible for the user and will have to suffice for now.

**Comment by chrishoage** [comment]
Thank you, this is actually how I thought it worked when I was reading the documentation.

**Comment by chrishoage** [comment]
One thing I have noticed is that `up / down / left / right` all appear to only increase or increase the size of the split. 

I wonder if the command should be updated to reflect the fact the size only changes in 1 dimension (vs having directions)? Unless this is a bug, but it appears consistent with how it worked before.

**Comment by koekeishiya** [comment]
Yeah this is working as intended, using directions at this point however is misleading and should be updated. I can't really think of any description that fits atm. Any ideas?

**Comment by chrishoage** [comment]
`reduce` and `expend` sound pretty good, I was also thinking `increase` / `decrease` but I think your suggestion makes more sense.

**Comment by koekeishiya** [comment]
This has now been done. I also made it so that the user has to specify the amount to be changed.
Previously it would use 0.1 by default. This must now be specified as such: `kwmc space -m reduce 0.05` or any other value between 0 and 1. This is relative to the split-ratio the container already has.
