### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#380]
Version 3.0.0 of Kwm will be heavily event-based and this should in turn allow for a pretty powerful callback exposure.

Is this something that would be nice to have access to from an end-user perspective, and if so, what would be the best and most powerful method to access this system?

Would it be nice to be able to define actual C functions (with provided scope) in the kwmrc file?
This would allow for a wider range of customizability, as you can actually do specfic things depending on the context of an event.

Should there only be options to provide a shellscript that will be ran when a specific event is triggered?
This would not be applicable for advanced use, as you do not get access to the event context, which I consider to be important when deciding what kind of actions to perform.

The following are events that exists so far:

```
enum ax_event_type
{
    AXEvent_ApplicationLaunched,
    AXEvent_ApplicationTerminated,
    AXEvent_ApplicationActivated,

    AXEvent_WindowCreated,
    AXEvent_WindowDestroyed,
    AXEvent_WindowFocused,
    AXEvent_WindowMoved,
    AXEvent_WindowResized,
    AXEvent_WindowMinimized,
    AXEvent_WindowDeminimized,

    AXEvent_DisplayAdded,
    AXEvent_DisplayRemoved,
    AXEvent_DisplayMoved,
    AXEvent_DisplayResized,

    AXEvent_DisplayChanged,
    AXEvent_SpaceChanged,

    AXEvent_HotkeyPressed,
    AXEvent_MouseMoved,
};
```

Which kind of events would be interesting from a user-perspective ?

**Comment by dominiklohmann** [comment]
Being able to launch shell scripts for the Application*, Window*, Display* and Space* notifications would be awesome. HotkeyPressed seems to already be covered by bind, and MouseMoved I'm not so sure would be useful.

I'm assuming the shell scripts would be called with certain parameters, e.g. what application was activated, what display which window was moved to or what space was transitioned to?

> Would it be nice to be able to define actual C functions (with provided scope) in the kwmrc file?

Like the `hotkeys.so` file in older versions? I'd be for that, although I'd assume it wouldn't be used all too much since it's not very user friendly. On the other hand, does such a feature need to be too user friendly at the cost of functionality?

**Comment by matthewdias** [comment]
Maybe I'm wrong but I think the argument for shell scripts is based around the fact that you can use kwmc commands to manipulate kwm. Personally I think it would be much better to automatically have all the context by using C functions, but it would require extensive documentation.

**Comment by andreaspada** [comment]
Agreed!

Enviado do meu iPhone

**Comment by koekeishiya** [comment]
> Personally I think it would be much better to automatically have all the context by using C functions, but it would require extensive documentation.

This is the way I would prefer to do it. Regarding documentation, that should be fairly trivial to do as I actually make remarks as to how things work this time around. 

> Like the hotkeys.so file in older versions?

This is very much how it would work. But I think it would be more accessible if the functions could actually be defined inside the kwmrc file (or any of the included ones for that matter). 
This would of course require a parser that can isolate the functions, move them to a temporary .cpp file, and compile it to a shared library that Kwm can dynamically load.

> I'd be for that, although I'd assume it wouldn't be used all too much since it's not very user friendly. On the other hand, does such a feature need to be too user friendly at the cost of functionality?

I personally feel like this is a feature that should care more about functionality than user friendlyness. Of course I will be writing proper documentation of how these callbacks would work, what parameters they present and functions that take any of these and presents useful information back.

Most of the ground-work for this has already been implemented on the `Rewrite` branch, inside the `AXLib` library. Now that I actually know more or less what the end goals of this window manager is going to be, I try to spend the time necessary for doing things properly.

**Comment by andreaspada** [comment]
Sounds amazing! Can't wait for. I certainly contribute with a good donation; just do not forget about stability, there's lots of usability bugs in current release 2.2
Kudos!

Enviado do meu iPhone

**Comment by koekeishiya** [comment]
> just do not forget about stability, there's lots of usability bugs in current release 2.2

This is the primary reason why this rewrite is taking place and is going to be my main priority at all times. The core of the current system is flawed and everything is very entangled, which is pretty evident by how unstable it is. 

The new release (when it is actually finishes) should be far more stable.

**Comment by andreaspada** [comment]
Awesome, it's definitely an outstanding good news!

> Åsmund Vikane <mailto:notifications@github.com>
> June 11, 2016 at 3:28 PM
>
> This is the primary reason why this rewrite is taking place and is 
> going to be my main priority at all times. The core of the current 
> system is flawed and everything is very entangled, which is pretty 
> evident by how unstable it is.
>
> The new release (when it is actually finishes) should be far more stable.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/koekeishiya/kwm/issues/380#issuecomment-225381945>, or 
> mute the thread 
> <https://github.com/notifications/unsubscribe/AEGPu7XbOY8rArrOd18GrVS4vGqozaJ9ks5qKv42gaJpZM4IzZrl>.
>
> Åsmund Vikane <mailto:notifications@github.com>
> June 10, 2016 at 8:10 PM
>
> Version 3.0.0 of Kwm will be heavily event-based and this should in 
> turn allow for a pretty powerful callback exposure.
>
> Is this something that would be nice to have access to from an 
> end-user perspective, and if so, what would be the best and most 
> powerful method to access this system?
>
> Would it be nice to be able to define actual C functions (with 
> provided scope) in the kwmrc file?
> This would allow for a wider range of customizability, as you can 
> actually do specfic things depending on the context of an event.
>
> Should there only be options to provide a shellscript that will be ran 
> when a specific event is triggered?
> This would not be applicable for advanced use, as you do not get 
> access to the event context, which I consider to be important when 
> deciding what kind of actions to perform.
>
> The following are events that exists so far:
>
> |enum ax_event_type
> {
> AXEvent_ApplicationLaunched,
> AXEvent_ApplicationTerminated,
> AXEvent_ApplicationActivated,
>
> AXEvent_WindowCreated,
> AXEvent_WindowDestroyed,
> AXEvent_WindowFocused,
> AXEvent_WindowMoved,
> AXEvent_WindowResized,
> AXEvent_WindowMinimized,
> AXEvent_WindowDeminimized,
>
> AXEvent_DisplayAdded,
> AXEvent_DisplayRemoved,
> AXEvent_DisplayMoved,
> AXEvent_DisplayResized,
>
> AXEvent_DisplayChanged,
> AXEvent_SpaceChanged,
>
> AXEvent_HotkeyPressed,
> AXEvent_MouseMoved,
> };
> |
>
> Which kind of events would be interesting from a user-perspective ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/koekeishiya/kwm/issues/380>, or mute the thread 
> <https://github.com/notifications/unsubscribe/AEGPu-ZrhJOnHnyFX64w8HAkoQfEPJX-ks5qKe7VgaJpZM4IzZrl>.
>

-- 

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Andrea Spada :: Liuteria d'Autore
www.andreaspada.com

CNPJ: 12.027.966/0001-00
CPF: 054.545.977-08
IM: 0.586.554.9

**Comment by cHoco** [comment]
I'll go against the current and say that having C functions for configuration/customisation wouldn't be good. It would probably alienate a good chunk of the user base, it would also introduce a lot of issues on how to compile these files (user would have to have Xcode installed?) and possibly stability issues cause of people writing unstable C code.
I think the better approach would be to provide a syntax for the kwmc to setup hooks for specific events and run commands in which we can use placeholder variables that expose the context. It still would take quite a lot of work, but it would be more consistent with current customisation approach and easier for users to learn (lots of program use similar paradigm).

**Comment by chrishoage** [comment]
I wonder if there could be some plugin system, where the plugins are (complied?) C and loaded into kwm trough the `kwmrc` file. 

I agree with cHoco that C as the user facing way to interact with the callbacks is not the way to go. I still maintain that firing off a shell script in response to an event, and then using `kwmc query` to get the state of kwm would offer quite a lot of flexibility for the average user of kwm. Power users could write a C plugin and load it into kwm. 

This way we could have the best of both worlds, a plugin system for power users that are comfortable writing C, and a shell script system for simpler scripts that don't need to drop down to C or have access to the C API.

**Comment by andreaspada** [comment]
I must agree with **chrishoage**. I definitely do not have spare time enough to bother with C code, and I think most of users do not have. I feel the need for a clear, well documented way to configure the main aspect of the window manager, letting the highly customization setup in the additional/optional something.cpp in the .kwm directory. 
By the way, is what I understood from the comments of **koekeishiya**...
Could it be?

**Comment by koekeishiya** [comment]
>  I feel the need for a clear, well documented way to configure the main aspect of the window manager

So, just to clarify the situtation.

Configuration and interaction with Kwm will still remain simple as is. Tiling, rules, keybinds and so on will be defined through simple kwmc commands, or through the `kwmrc` file, as it is on master.

The callbacks are meant for people who want more advanced behaviour in certain situations, without having to fork, modify the code, compile, and keep maintaining their fork when I make changes upstream.

Imagine the folllowing scenario, for the `AXEvent_ApplicationLaunched` callback.
I get access to an ax_application pointer, letting me know which application was launched. 

Now let's say I want to have the functionality mentioned in #114, I would simply check how many windows are visible on that space, and if it matches  my criteria, I can have it modify the padding / gaps as I want. Maybe I only want this to happen for certain applications, or maybe only if the display resolution is 1920x1200, what if I only want to do this when I'm on a dual monitor setup.

The above is only possible through exposure to function calls that allow you to retrieve and modify that information. With a shellscript approach, I'd either have to decide which information should be passed along at all times, or provide an extensive amount of `kwmc` commands.

**Comment by chrishoage** [comment]
> The callbacks are meant for people who want more advanced behaviour in certain situations, without having to fork, modify the code, compile, and keep maintaining their fork when I make changes upstream.

This is my ignorance into complied languages speaking, but I still wonder if there is some way to have plugins that are written in C and compiled and placed in the `.kwm/` directory then registered in `kwmrc`. This could allow for powerful behavior modification to kwm where it was needed. 

There could be a simpler system of callbacks that launched shell scripts for people that just needed _super_ simple event notifications. For the types of things I personally would do the `kwmc query` + a shell script that was ran upon an event would cover 90% of the use cases. 

I personally see room for both a C extension system (however it is done) for power users, and shell scripts for simple tasks where dropping down to C isn't needed. 

There are probably flaws in my idea, but just a thought.

**Comment by koekeishiya** [comment]
> This is my ignorance into complied languages speaking, but I still wonder if there is some way to have plugins that are written in C and compiled and placed in the .kwm/ directory then registered in kwmrc. This could allow for powerful behavior modification to kwm where it was needed. 

This should definitely be possible, although I don't have much experience in that area myself. Will look into it at some point for sure.

> There could be a simpler system of callbacks that launched shell scripts for people that just needed super simple event notifications. For the types of things I personally would do the kwmc query + a shell script that was ran upon an event would cover 90% of the use cases. 

Agreed, having both options available would probably be for the best.

**Comment by koekeishiya** [comment]
Closing this as no longer relevant.
See [**chunkwm**](https://github.com/koekeishiya/chunkwm) instead.
