### ISSUE TITLE
Focus follows mouse doesn't work for emacs windows

### ISSUE THREAD

**Issue by SG60** [koekeishiya/kwm#382]
I've just started using kwm and am finding it very useful, but I'm having a problem with emacs. Focus follows mouse works for all my other applications, but if I move the mouse over emacs nothing changes.

I'm using the mac port version of emacs from [https://github.com/railwaycat/homebrew-emacsmacport](https://github.com/railwaycat/homebrew-emacsmacport). Both kwm and emacs are installed through homebrew.

**Comment by koekeishiya** [comment]
Have you seen #40 ?

**Comment by SG60** [comment]
Yes, I have. I think I have a different problem though, as I can still use keybindings to focus the emacs window and it also gets placed in the correct position. The only thing that doesn't work is the focus follow mouse feature.

**Comment by koekeishiya** [comment]
Right, can you issue the following command from a terminal and see if it fixes it: `kwmc config standby-on-float off`

**Comment by OrBaruk** [comment]
I was having the same issue previously, it seems to be an issue especific to the version of emacs port you are using on osx.

I solved it by installing a different emacs version, the one recommended by spacemacs at https://github.com/syl20bnr/spacemacs#os-x

```
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus --with-cocoa --with-gnutls --with-librsvg --with-imagemagick --with-spacemacs-icon
$ brew linkapps
```

**Comment by SG60** [comment]
@koekeishiya That didn't fix it :(

**Comment by SG60** [comment]
@OrBaruk Thanks, I'll try that now.

**Comment by SG60** [comment]
@OrBaruk That didn't work either. Emacs wasn't managed at all by kwm with that version, even after trying the fix that @koekeishiya mentioned from #40.

**Comment by OrBaruk** [comment]
This is the rule that I'm currently using in kwmrc
`kwmc config add-role AXStandardWindow Emacs
`

**Comment by koekeishiya** [comment]
The rule provided by @OrBaruk is the one you need. The rule specified in the linked issue, is for the master branch only.
