### ISSUE TITLE
kwm not starting/not working

### ISSUE THREAD

**Issue by senorsmile** [koekeishiya/kwm#384]
I installed kwm for the first time via brew: 

```brew install kwm```

and followed the directions to get an initial config in place and start the process:
```
mkdir -p ~/.kwm
cp /usr/local/Cellar/kwm/2.2.0/kwmrc ~/.kwm/kwmrc
brew services start homebrew/binary/kwm
```

However, nothing really seems to be working.  

brew services list shows the process "started": 

```
$ brew services list
Name           Status  User         Plist
kwm            started shaun        /Users/shaun/Library/LaunchAgents/homebrew.mxcl.kwm.plist
```

but there are no running process: 
```
ps aux | grep -i [k]wm
```

If I try to start the process manually, I get: 
```
$ /usr/local/opt/kwm/kwm
Could not access OSX Accessibility!
```

**Comment by senorsmile** [comment]
After restarting it about 10 times, mac os finally popped up with a notice to enable kwm in privacy/accessibility.  After doing this and restarting the app one more time, I finally see some daemons running.  

No tiling seems to be happening at this point though.

**Comment by koekeishiya** [comment]
Make sure you have 'displays have separate spaces' enabled in Misson Control.
There will be a warning issue for users that do not have this enabled, in a future update.

**Comment by senorsmile** [comment]
Perfect!  That was the issue.  Thanks!

Now to figure out how to set up the configuration to match my old awesome wm workflow.

**Comment by koekeishiya** [comment]
Make sure you read the documentation specified for the 2.2.0 release tag (there should also be a man file included with the homebrew install. `man kwmc` i believe).

**Comment by senorsmile** [comment]
That does indeed bring up the manual.  I see how to have the mouse move to focus different windows.  However, I don't see how to move the focus from one window to the next with a keyboard shortcut.  I can "swap focused window" but not something like "cycle focused window east" etc.

**Comment by senorsmile** [comment]
Never mind... this section covers that: 

# Give Focus To Window
kwmc bind cmd+alt-h window -f west
kwmc bind cmd+alt-l window -f east
kwmc bind cmd+alt-j window -f south
kwmc bind cmd+alt-k window -f north

kwmc bind cmd+alt-n window -fm prev
kwmc bind cmd+alt-m window -fm next
