### ISSUE TITLE
General ricing advice

### ISSUE THREAD

**Issue by AhmedAA** [koekeishiya/kwm#39]
First of all I am incredibly sorry for submitting an issue altogether, but I can't really find any other way to contact you :)

I had no idea it was even possible to remove window borders, let alone customise the bar to look so much like one of the bars I used to have in Linux..
Do you have some advice/links to share on how to achieve that?

Also, there is an issue with emacs that segfaults kwm.

Other than that, I really love your work!

Again, sorry for posting like this, not intended to piss anyone off.

**Comment by koekeishiya** [comment]
The window borders have only been removed on iTerm, and not other windows.
Uh, the OSX menu is hidden: system preferences -> general -> autohide menu bar

For more information about my config you can go here:
https://github.com/koekeishiya/kwm/issues/22

**Comment by AhmedAA** [comment]
Thank you very much, and again, very sorry for adding an issue.
I might create emacs crashing as a separate issue if you'd like :)

**Comment by koekeishiya** [comment]
Yeah please do, and don't worry about opening issues if you have questions.
Closing this for now.

**Comment by AhmedAA** [comment]
Sorry for writing on a closed issue, but I was wondering if you could share your font?
I can't seem to find it anywhere (not the plain regular version at least). Did you custom patch it?
The font I am using is starting to strain me..

Thanks in advance :)

**Comment by koekeishiya** [comment]
[Font-Input.zip](https://github.com/koekeishiya/kwm/files/120788/Font-Input.zip)
