### ISSUE TITLE
[3.0.0] Using Alfred or Spotlight to open Finder causes loss of focus after window closed

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#391]
Steps to Reproduce

1. Set space in BSP Mode with some windows open
2. Use Alfred or Spotlight to open a Finder window
3. Close finder window

Expected result: A window gains focus after the Finder window has been closed. 

Actual Result: No window gains focus, which prevents kwm focus commands from working until a window is clicked on to give focus. 

Excellent work on the v3 refactor, seems to be working great. I've had a couple crashes, working on finding steps to reproduce them.

**Comment by koekeishiya** [comment]
This is the expected behaviour in version 3.0.0.
OSX fully manages focus, to prevent sideeffects and stability-issues of previous versions.

This behaviour will happen to applications that do not quit when all their windows are closed.

**Comment by chrishoage** [comment]
But auto-raise is broken too. The explanation of letting osx manage it's focus makes sense, but the fact that even auto raise doesn't work until clicking seems sorta broken?

**Comment by koekeishiya** [comment]
> But auto-raise is broken too.

That is indeed a bug, not completely sure how to fix it yet, but I know what causes it.

**Comment by koekeishiya** [comment]
Autoraise issue has been fixed on master.

**Comment by koekeishiya** [comment]
I've added the command `kwmc window -f first` as well as an easy way to get back to being able to use the directional keyboard commands.

**Comment by chrishoage** [comment]
> I've added the command kwmc window -f first as well as an easy way to get back to being able to use the directional keyboard commands.

Does it make sense to use `window -f next | prev` instead of introducing a new command? If there is nothing focused in in the space next and prev would focus either the first or last item in the tree. 

I'm kinda curious if any of the directional commands could just focus the first too, but that's not nearly as important.

**Comment by koekeishiya** [comment]
I was actually thinking about removing the `window -f prev | next` commands. I feel like they are just leftovers from before we had directional focusing.

I could probably have `window -f west | east` focus the first and last leaf respectively if no application has focus.

**Comment by chrishoage** [comment]
> I was actually thinking about removing the window -f prev | next commands. I feel like they are just leftovers from before we had directional focusing.

That's just fine with me, I personally don't use them. 

> I could probably have window -f west | east focus the first and last leaf respectively if no application has focus.

👍

**Comment by dominiklohmann** [comment]
> I was actually thinking about removing the window -f prev | next commands. I feel like they are just leftovers from before we had directional focusing.

Please keep them, I use them all the time (binds are `cmd+^` and `cmd+shift+^`). I personally think that they are really useful.

**Comment by koekeishiya** [comment]
> Please keep them, I use them all the time (binds are cmd+^ and cmd+shift+^). I personally think that they are really useful.

Aight no problem, I'll let them be.


Both `window -f prev | next` and `window -f west | east` should now focus first / last leaf if there is no focus.
