### ISSUE TITLE
not catching window minimizing

### ISSUE THREAD

**Issue by rumbletumjum** [koekeishiya/kwm#392]
Just updated to 3.0.0, noticed that kwm isn't catching windows minimizing like it used to. What debug/console info should I supply to help with this? I haven't become that familiar with the program yet.

edit: better description of the behavior: the window will minimize as usual, but the outline border for the window stays in place, and other windows don't respond to the minimized window going away, i.e. they act like the remaining outline is still a window.

edit 2: this might be a problem with Messages. i'm playing around to recreate the behavior and it's looking like having Messages in one of the containers might be causing this behavior. Messages behaved itself on 2.2.0.

edit 3: it's not Messages, it's just that Messages only ever has the one window visible. Whenever the last visible window for a given application is minimized/hidden/closed, the container that it was in isn't being handled. if the application is subsequently quit, everything works as expected. again, let me know what debug information will be useful and I'll work on getting it out.

**Comment by koekeishiya** [comment]
The issue should be somewhat solved, at least Messages work just fine. I've been unable to reproduce this behaviour for other applications that I am using. 
Minimize / deminimize should work rather well, for the most part.

Hiding applications is currently not supported, and probably never will be.
