### ISSUE TITLE
Hiding applications (cmd+h) not supported

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#394]
This used to work in previous versions because of polling.

As we are now relying on notifications to update our state, and there are only `didHideApplication` and `didUnhideApplication` notifications available, I've decided not to bother with implementing support for this.

The solution would be to drop all cached information for every single space of all connected displays, or figure out which spaces these windows were located on and mark all of them for update upon next space activation.

I suspect there to be more complex cases which I have yet to think about as well.

Minimizing windows should work fine, for the most part, assuming that the OSX notifications that we rely on is actually delievered by the system.

**Comment by jhenahan** [comment]
Are those notifications insufficient? I'd like to see this feature, and I wouldn't mind trying to implement it, given a little more information about why those notifications won't work.

**Comment by koekeishiya** [comment]
I don't have any reason to believe that they are insufficient, however, they cause a lot of otherwise unnecessary overhead and complexity that I personally feel is not worth dealing with.

The approach you'd have to take, is pretty much what I described above. The following would have to happen every time either of those notifications were received.

> The solution would be to drop all cached information for every single space of all connected displays, or figure out which spaces these windows were located on and mark all of them for update upon next space activation.

There would also be the need to check upon space-transition end, if that space has been flagged for an update, and respond accordingly.

**Comment by chrishoage** [comment]
My main issue with this bug is I accidentally hide things when KWM does not respond sometimes (cmd + alt - h). 

Recovering from this issue is a huge pain in the ass, pretty much requires either quitting the apps I hid - or - quitting KWM. 

I don't hide things often (ever) but sometimes kwm doesn't catch a command and OS X picks it up and hides things. Huge headache

**Comment by koekeishiya** [comment]
> Recovering from this issue is a huge pain in the ass, pretty much requires either quitting the apps I hid - or - quitting KWM. 

I realize this is not a fix or anything, but simply unhiding an application and toggling the window in question float and then unfloat will force a retile.

**Comment by simonsmith** [comment]
Hi @koekeishiya,

I often have windows fall out of control of KWM, sometimes after its been hidden and other times when an app is closed and reopened.

How can I float an individual window to force a retile?

I have the keybind for floating all windows:

```
// Set Space Tiling Mode To Floating
kwmc bindsym cmd+ctrl-d space -t float
```

But this doesn't seem to change anything, and seems to stop me moving from window to window.

Any help appreciated, thanks

**Comment by koekeishiya** [comment]
The issue in question is a couple of months old, feel free to create new issues if / when you have a problem that isn't necessarily already answered in previous issues.

> I often have windows fall out of control of KWM

Not sure how this is to be interpreted. Can you elaborate on what this means exactly?

> How can I float an individual window to force a retile?

You can float individual windows using the command `kwmc window -t focused`. Performing the command twice will do a `float -> unfloat`which should trigger tiling.

Available commands can be found [here](http://koekeishiya.github.io/kwm/kwmc.html)

**Comment by simonsmith** [comment]
> Not sure how this is to be interpreted. Can you elaborate on what this means exactly?

As an example Spotify will be tiled with other windows, I'll hide it for a bit and when I unhide it KWM doesn't see it as a new window and carries on with tiling the existing windows that were there before, with Spotify just floating over the top. I'm looking for the best way to 'refresh' KWM as it were.

**Comment by koekeishiya** [comment]
> As an example Spotify will be tiled with other windows, I'll hide it for a bit and when I unhide it KWM doesn't see it as a new window and carries on with tiling the existing windows that were there before, with Spotify just floating over the top. I'm looking for the best way to 'refresh' KWM as it were.

Hm, I'm unable to reproduce this. Are you on the latest version (v3.1.3) ?
If so, feel free to create a new issue to track this
