### ISSUE TITLE
Focus border lags a lot

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/kwm#395]
Hi,

Today I used kwm at work with a multimonitor environment. 

I don't know if this is related to the use of two additional externals displays, but I noticed that the kwm border lagged a lot to highlight the focused application.

I restarted kwm multiple times, build the latest version also, but the lag is still present and important (4 to 5 seconds). 

Can I do something to improve this, or to give you more information about that ?

Regards,

**Comment by koekeishiya** [comment]
This could be related to the fact that I have not yet optimized the code in version 3.0.0.
I will be doing some profiling and so on during the next days, which should probably improve the experience a bit.

Did you experience the above when changing focus between specific applications, or does it happen for all applications?

**Comment by mickaelperrin** [comment]
Interesting... you're right the lag is far more important when switching from iterm window to iterm window (4 to 5 seconds) than any other switch ( a little bit more than 1 second).

Note: I use a borderless iterm window (if it could be related).

**Comment by chrishoage** [comment]
This seems to happen mostly when the computer is under heavy load. When I compile a large application (or encode a video, anything that uses 100% cpu) the border lags quite a lot. 

However I do not experience the border lagging when the system is idle (I am in a multi-monitor environment too)

**Comment by koekeishiya** [comment]
> This seems to happen mostly when the computer is under heavy load. When I compile a large application (or encode a video, anything that uses 100% cpu) the border lags quite a lot. 

I don't think there is anything we can do about this. Kwm relies on a `didApplicationActivate` or `focusedWindowChangedNotification` from the system, for it to know that the border must be updated.

Without knowing this for sure, I suspect that the notification itself is delayed.

**Comment by mickaelperrin** [comment]
In my case, CPU is in a normal state, not under heavy load.

In fact, I discovered that the lag is far more important when you switch from one window to another of the **same** program: tested with Chrome, Firefox, iterm.

**Comment by koekeishiya** [comment]
Gonna close this as can't fix.
