### ISSUE TITLE
Dialog boxes and other windows neither float nor tile

### ISSUE THREAD

**Issue by neon64** [koekeishiya/kwm#397]
For example, the Excel intro window is floating (it is an AXDialog so I think that is intended behaviour), and yet when I move my mouse from the Dock to interact with the window, it suddenly disappears, because autoraise raised Sublime Text instead. I am sure this has happened with other window combinations as well but I can't remember. It feels like a regression introduced by the 3.0 changes but I don't understand the code well enough to track it down.

![image](https://cloud.githubusercontent.com/assets/7961339/16259105/65770de2-38a4-11e6-8181-f8d4272b68bd.png)

**Comment by neon64** [comment]
Further diagnosis, it seems to be also that when I hover over a dialog box with a window from another application partially underneath, then the dialog box loses focus.

This is perhaps best demonstrated by another screenshot. If I move my pointer to the section of the dialog box that is above Vivaldi, then the dialog box disappears.

![image](https://cloud.githubusercontent.com/assets/7961339/16263039/9e0dffc4-38b5-11e6-9941-71e67391eaa8.png)

I'm not sure if these two are related but reporting anyway

**Comment by koekeishiya** [comment]
By default Kwm ignores all windows that are not of type: AXWindow:AXStandardWindow.
The reason I have made it so that AXDialog windows are not automatically floated, is that a lot of applications that the user might want to tile (firefox or borderless iterm2) reports that as its actual role.

You can make a window rule that accepts the AXDialog role for certain windows and makes them floating by using the following properties: {role="AXDialog"; float="true"}

**Comment by neon64** [comment]
So do AXDialogs float or tile? Because if they are meant to tile, then they are not doing that. If they are meant to float, then `standby-on-float` isn't working. I think the underlying issue is the same as #398, I just explained it badly.

**Comment by koekeishiya** [comment]
> So do AXDialogs float or tile?

They do neither. Kwm will be unaware of them until you create a rule that decides the behaviour. This is intended, due to reasons specified in my previous comment.

**Comment by koekeishiya** [comment]
See the updated rule system (the Finder example) for how you can deal with this.
