### ISSUE TITLE
[v3] Some flyout windows are not recognized by kwm

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#398]
Extracting from #232

Some flyout windows (I think they might be WebViews, not positive though) are not recognized by kwm and allow `focus-follows-mouse` to trigger the window below the flyout window. 

I have observed this behavior with Dropbox and 1Password menu trey flyout windows. 

Prior to the rewrite these flyout windows were usable with `focus-follows-mouse` enabled, and did not raise the window below the flyout window. 

Happy to collect any logs that might be useful in diagnosing the window.

**Comment by neon64** [comment]
This seems like a similar issue to what I'm having here: https://github.com/koekeishiya/kwm/issues/397.

**Comment by mickaelperrin** [comment]
I can confirm this behaviour with the flyout windows of Google Drive, [instant translate](https://insttranslate.com/) and [tripmode](https://www.tripmode.ch/), apps that are launched from the top bar.

As soon as the flyout windows appears on top of a tiled window, I click through it and can't get it to focus.

If the app appears in top of a floating window, it is working as expected.

**Comment by koekeishiya** [comment]
If you can use the OSX accessiblity application to get some information regarding the windows in question, and see if they have a common pattern, that would be great.

**Comment by chrishoage** [comment]
<img width="789" alt="screen shot 2016-06-24 at 9 26 06 am" src="https://cloud.githubusercontent.com/assets/1056886/16343753/cd3c7936-39ed-11e6-82bb-e93249ac90b3.png">
<img width="924" alt="screen shot 2016-06-24 at 9 27 27 am" src="https://cloud.githubusercontent.com/assets/1056886/16343766/e49e99e2-39ed-11e6-8107-9721042de0be.png">

**Comment by mickaelperrin** [comment]
How do you launch it ?

**Comment by koekeishiya** [comment]
Create a rule for the affected applications to allow the `AXSystemDialog` role. By default, Kwm will only care about windows with the type `AXWindow:AXStandardWindow

**Comment by chrishoage** [comment]
@koekeishiya 

do you mean this 

```
kwmc rule owner="Dropbox" properties={role="AXSystemDialog"}
kwmc rule owner="1Password" properties={role="AXSystemDialog"}
```

if so, that did not work for me

**Comment by koekeishiya** [comment]
> Are you sure this shouldn't be solved from KWMs side, this used to work in v2, so this feels like a regression. 

It worked previously because of polling. Anything that isn't reported by the applications themselves through the OSX notifications is pretty much not fixable. I really have no idea how to approach this problem.

**Comment by cHoco** [comment]
I'm not sure if it's the same issue, but sometimes window aren't recognised for me either. Even if I have a specific rule for it, the window is completely ignored. It even happens with Safari windows once in a while. Maybe the window isn't available when notification of app activation is triggered?

**Comment by mickaelperrin** [comment]
Got the same issue too, mainly with my IDE, but as you mentioned this is random. The window appears in the space under all floating windows, the window is not listed when launching `kwmc query window list`, strange...

**Comment by chrishoage** [comment]
I'd like to revive this issue. It seems related to #232 as the symptoms are very similar. 

It seems like this issue should be solvable since the accessibility inspector reports these dialogs. Is it possible to not raise if the mouse is over a `AXSystemDialog`? 

This issue is very frustrating as it makes some 1Password and Dropbox extraordinarily difficult to use. 

Even "Accessibility Inspector" itself is subject to this issue. How can I make autoraise turn off if I am over a `AXSystemDialog`. Clearly you are responding to mouse move events. Clearly in response to a mouse move event you look up what windows are below the mouse and raise the window that is below the mouse. 

How can we get it  to not raise if the mouse is above a `AXSystemDialog`?

**Comment by koekeishiya** [comment]
Try the latest commit. I reimplemented ffm to not do anything if the window that is in fact topmost, for some reason is unknown for Kwm.

**Comment by chrishoage** [comment]
@koekeishiya works great! 

> I reimplemented ffm to not do anything if the window that is in fact topmost, for some reason is unknown for Kwm.

Clever solution!
