### ISSUE TITLE
Add support for gaps

### ISSUE THREAD

**Issue by biscuitpants** [koekeishiya/kwm#4]
It would be great to have support for gaps inbetween containers, like i3-gaps does it.

**Comment by koekeishiya** [comment]
This is already supported. Default hotkeys to increase gaps are ctrl+alt+x (horizontal gap) and ctrl+alt+y (vertical gap)
To decrease gap (by default): alt+cmd+x , alt+cmd+y

**Comment by biscuitpants** [comment]
Oh that is awesome! Thanks.
