### ISSUE TITLE
How do i relaunch kwm after a crash?

### ISSUE THREAD

**Issue by scottgrayson** [koekeishiya/kwm#400]
Right now I have just been restarting my computer. is there a command i can run to instead? I installed through homebrew

**Comment by dominiklohmann** [comment]
If you have the `*.plist` file in `~/Library/LaunchAgents/`, it should try to start Kwm whenever it is not running. Because of that you can restart kwm manually by running `kwmc quit`.

**Comment by scottgrayson** [comment]
Thanks @dominiklohmann

**Comment by colonelk1** [comment]
The easiest way to do this would be to run this in terminal:

`brew services restart kwm`

This will restart kwm since you've installed it via homebrew.

**Comment by scottgrayson** [comment]
When kwm was actually running, these both successfully stopped and started kwm.

But after a crash, neither worked.

**Comment by residentsummer** [comment]
`kwm` may refuse to start if it can't bind its port (3020). When I run it under the debugger and it crashes, I have to manually kill `kwm-overlay`, because it's still listening on that port.

```
$ lsof -nPi tcp |grep 3020
kwm       87279 user    4u  IPv4 0xe9f5102fd0978065      0t0  TCP 127.0.0.1:3020 (LISTEN)
kwm-overl 87282 user    4u  IPv4 0xe9f5102fd0978065      0t0  TCP 127.0.0.1:3020 (LISTEN)
```

If this is the case, you can just kill it with `pkill -f kwm-overlay`.

**Comment by cdosborn** [comment]
I use the following alias `alias kwmr='launchctl stop com.koekeishiya.kwm;launchctl start com.koekeishiya.kwm'`
