### ISSUE TITLE
[v3] window -z parent does not return when it spawns a window

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#404]
When a window is toggled to the parent container size, then that window spawns a window, the parent zoom is removed and the new window is tiled (all good). When the new window is closed the window does not zoom back to the parent, but is still marked as if it were. `window -z parent` must be issued twice to get the window to zoom to the parent again. 

STR: 

1. Zoom a window to parent with `window -z parent`
2. Spawn a new window from that zoomed window
3. Close the spawned window

Expected result: zoomed window returns to zoomed state. 
Actual result: zoomed window stays tiled, and `window -z parent` must be issued twice to zoom again (toggle it off, then back on).

I see two possible solutions: a) zoom the window again when the spawned window closes or b) toggle the zoom setting for that container so when `window -z parent` is issued again it zooms, with out having to issue `window -z parent` twice.

**Comment by koekeishiya** [comment]
How does the following behaviour sound?

A window has toggled parent zoom. You spawn a new window that causes the parent-zoomed window to split. The parent zoomed window remains zoomed, but updates for the newly created split instead.

**Comment by chrishoage** [comment]
![screen shot 2016-07-05 at 10 26 26 am](https://cloud.githubusercontent.com/assets/1056886/16593629/09bd2d28-429b-11e6-80be-c3361ad6deea.png)

Is this odd tiling expected behavior? The new window caused a split but the previous window did not change size, it stayed the size of the previous split.

**Comment by koekeishiya** [comment]
That seems to be because of:

> A window has toggled parent zoom. You spawn a new window that causes the parent-zoomed window to split. The parent zoomed window remains zoomed, but updates for the newly created split instead.

I made this change because that's how the fullscreen zoom works, and if felt better to make them consistent.

**Comment by chrishoage** [comment]
But the parent does not remained zoomed. It collapses to the pre-zoom split, and adds a new split, but does not change the size of the windows. 

This screenshot was a zoomed window, that then had a new split, which removed the zoom and resulted in the screenshot.

**Comment by koekeishiya** [comment]
It removes the old zoom and performs the zoom appropriate after the new split has happened. At least, that's the behaviour on my end.

**Comment by chrishoage** [comment]
Ah, what confused me was the new window was focused over the zoomed window. 

I'm understanding the behavior now, just isn't super obvious what is happening.

**Comment by matthewdias** [comment]
Seemingly as a side effect of this, fullscreen zoom now gets reverted to the wrong state when spawning a new window. After zooming this terminal window fullscreen, and then spawning another terminal I get this:


![](https://i.imgur.com/0EN35Hl.png)

**Comment by koekeishiya** [comment]
In the scenario above, it's not really possible to differentiate between a parent-zoom and a fullscreen-zoom, with the current implementation. I will refine the behaviour at some point.
