### ISSUE TITLE
disable border on specific space

### ISSUE THREAD

**Issue by mnetzwur** [koekeishiya/kwm#408]
With some appliations, drawing a border causes performance problems. Unfortunately, 

> kwmc config space 0 8 border focused off 

does nothing. Would it be possible to add this? Disabling an application border via a blacklist rule appears to work inconsistently because it produces a ghost border.

**Comment by cHoco** [comment]
It's highly improbable that drawing the border is causing performance issues, I think the real lag you may notice is caused by focus follow mouse, you can try to disable that and see if that is the real bottleneck

**Comment by mnetzwur** [comment]
No, it's indeed drawing the border in some capacity. Disabling focus follows mouse globally does not fix the issue, disabling borders globally does.

**Comment by koekeishiya** [comment]
Need more information to be able to debug this. I have not had any performance problems caused by the border.

**Comment by mnetzwur** [comment]
Okay, it turns out that this is actually expected behavior with kodi, which detects when the window is "in the background" and lowers its own framerate to save resources. I suppose drawing a border somehow triggers that behavior. The question then is if you would consider adding the feature of disabling borders for a specific space or even application. Obviously that makes this a feature request and not a bug. :)

**Comment by koekeishiya** [comment]
I've decided that this is not something I will be doing, partly due to how borders work (code-wise).
