### ISSUE TITLE
Empty spaces. Does not play nicely with uBar

### ISSUE THREAD

**Issue by sebinsua** [koekeishiya/kwm#410]
Similar to #401, if you are using [`uBar`](https://brawersoftware.com/products/ubar) and click on one of the menu items then the screen gets cut and half and leaves an empty space. Every time you click on the menu item it happens again until you have no usable space on your screen.

[See here.](http://recordit.co/c4EDr2nUHj)

The only solution seems to be not using `uBar` or periodically closing all applications and opening them again.

Obviously this could be an issue with how `uBar` works, but it would be nice to have knowledge of whether it can be fixed within this app or within the other since currently it is forcing me to choose.

Edit: Just realised I can fix it by switching tiling mode back-and-forth. Annoying but better than needing to quit everything.

**Comment by chrishoage** [comment]
Not exactly sure how uBar works but if it hides / shows applications then it will not be supported by kwm apparently #394

**Comment by koekeishiya** [comment]
So I suspect uBar does rely on hide / show applications. I'll probably try to implement support for that in the future, as some third party applications seem to rely on this.

**Comment by koekeishiya** [comment]
I am going to close this as duplicate. See #434 for status.
