### ISSUE TITLE
Chrome windows resize slowly

### ISSUE THREAD

**Issue by mrala** [koekeishiya/kwm#411]
Expected behavior: windows resize instantly

Actual behavior: Chrome windows have an animation when resizing

Steps to reproduce: Interacting with Chrome windows - switching between BSP and monocle tiling modes, swapping focused windows, etc.

Here is an [example video](https://www.dropbox.com/s/xxlteloh3lafr63/kwm.m4v?dl=0).

Running kwm 3.0.1 on 10.11.5.

**Comment by koekeishiya** [comment]
I'm unable to reproduce this. On my end, chrome windows resize instantly.
Possibly some system-specific settings that you need to tweak?

**Comment by bjeanes** [comment]
That looks like Chrome thinks it is in native full screen mode to me. Very weird.
