### ISSUE TITLE
Crash on Callback_AXEvent_WindowFocused debug message

### ISSUE THREAD

**Issue by hunner** [koekeishiya/kwm#412]
I am getting `AXEvent_WindowFocused: Safari - SignalHandler() 11` when switching between safari windows consistently. Here is a gist with a gdb backtrace: https://gist.github.com/hunner/81a4ec841d4cd4cf3209da1aacea476f

Commenting out kwm/window.pp:387 causes this to not happen.

**Comment by koekeishiya** [comment]
This is happening due to some windows not having a title, fixed in latest commit.
