### ISSUE TITLE
AXSpace_FastTransition only focuses on application changes

### ISSUE THREAD

**Issue by hunner** [koekeishiya/kwm#413]
The commit 2087aee appears to have partially fixed application focus in `AXLibSpaceTransition` but only when the new space has a different application window than the old space (say, switching from 1->2 when space 1 has firefox and space 2 has iterm).

When the windows are the same application, focus is not shifted (eg transition 1->3 when both 1 and 3 have firefox windows). Focus is left on the window of the old space.

**Comment by koekeishiya** [comment]
I'm actually unable to reproduce this behaviour, tested using Firefox.

**Comment by hunner** [comment]
Hmm. Yeah, after using this for a few days it's not strictly same/different app as it often forgets focus even on spaces with different apps.

I haven't spent more time tracing the issue yet, but something is causing space switches to not focus a window on the new space. If I get some time I'll try and debug further.

**Comment by braham-snyder** [comment]
@hunner is it related to this issue? https://github.com/koekeishiya/kwm/issues/551
