### ISSUE TITLE
Clearer documentation around rules

### ISSUE THREAD

**Issue by nanzhong** [koekeishiya/kwm#414]
Would it be possible to include some clearer documentation on how rules work? I feel like I'm either looking in the wrong place, or I'm missing something really key about them.

For example, how would I specify rules for the following config for an application with the name "TestApp":
- all AXDialog windows should float
- all AXStandardWindow windows should float if their window title contains the word "float"
- all other windows should tile

To clarify, the following is what I _think_ is correct, but it doesn't seem to work.

```
kwmc rule owner="TestApp" properties={role="AXDialog"; float="true"}
kwmc rule owner="TestApp" name="float" properties={role="AXStandardWindow"; float="true"}
```

**Comment by chrishoage** [comment]
`role` gives windows from the `owner` application that role, regardless of what role the window actually has. 

```
kwmc rule owner="TestApp" properties={float="true"}
```

Will make any window from `TestApp` float. As far as I know there isn't a way to specify rules based on role, only window title. 

More Info: https://github.com/koekeishiya/kwm/issues/268

**Comment by nanzhong** [comment]
Ah I see, that's what I was missing. I didn't realize that everything in `properties` were modifiers _to apply_ vs `name` and `except` where the only filters.

**Comment by koekeishiya** [comment]
Using rules as a filter rather than a property might be a good idea, will look into it in the future.

**Comment by koekeishiya** [comment]
You can now use the current role of a window as part of the filtering process.

I have added a rules-section to the [kwmc man page](http://koekeishiya.github.io/kwm/kwmc.html)

**Comment by nanzhong** [comment]
This is awesome!
