### ISSUE TITLE
Border on fullscreen apps

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#415]
Many times when putting a window in native fullscreen mode, I get the "false" red border on the window.

**Comment by matthewdias** [comment]
This also happens on normal windows sometimes after a crash (I think)

**Comment by koekeishiya** [comment]
I've been able to reproduce upon launch of Kwm, which would confirm this statement.
> This also happens on normal windows sometimes after a crash (I think)

I don't use native fullscreen mode, so I have no information regarding that as of now.

**Comment by matthewdias** [comment]
Right, shouldn't be at all.

**Comment by koekeishiya** [comment]
> Many times when putting a window in native fullscreen mode, I get the "false" red border on the window.

I can't seem to reproduce this at all on version 3.0.3. Do you have more specific information regarding how / when this happens?

**Comment by matthewdias** [comment]
for whatever reason it seems to be gone in 3.0.3

**Comment by koekeishiya** [comment]
Gonna close this issue then. The fix should be cause by commit df5b2b9bb714019873b2843ba049d27f0c41b969
