### ISSUE TITLE
KWM not receiving key inputs

### ISSUE THREAD

**Issue by dekz** [koekeishiya/kwm#416]
`.kwmrc`
```
kwmc bindsym ctrl-s mode activate prefix
kwmc bindsym cmd+alt+ctrl-q quit
kwmc bindsym cmd+ctrl-r tree rotate 90

```

None of these settings seem to be delivered to kwm. 

Kwm has been enabled in Accessibility (as has iterm2 and terminal, which I've tested in)

Version 3.0.1

Log output:

```
⠃ kwm λ ./bin/kwm                                                                    master
ChangeSplitRatio() New Split-Ratio is 0.5
CreateBSPTree() Create pair of leafs
Secure Keyboard Entry is enabled, hotkeys will not work!
AXEvent_WindowResized: iTerm2 - kwm — 92✕48
```

**Comment by chrishoage** [comment]
Could it have anything to do with 

```
Secure Keyboard Entry is enabled, hotkeys will not work!
```

**Comment by dekz** [comment]
Yep that was definitely related.

The option was stuck permanently on in iTerm2, but Terminal.app showed it disabled. A reboot of the system fixed the issue and everything seems to be working as it should.
