### ISSUE TITLE
Kwm on homebrew?

### ISSUE THREAD

**Issue by colonelk1** [koekeishiya/kwm#417]
Hey --- this isn't really an issue, but I was wondering if there were plans to push the newest kwm updates to homebrew. I've noticed there have been about 2-3 updates to kwm in the past month, but haven't been on homebrew.

Regardless, thanks for kwm. It's a fantastic WM.

**Comment by OrBaruk** [comment]
Strange, my homebrew version is on the same as the latest release available (3.0.1).

Unless you are comparing it to the master branch?

**Comment by koekeishiya** [comment]
Version 3.0.2 should probably be released soon.

**Comment by dominiklohmann** [comment]
Is this gonna get moved to brew-cask now that the tap homebrew/binary is deprecated?

**Comment by chrishoage** [comment]
I think kwm should just host the keg itself, brew fully supports github. `brew install koekeishiya/kwm`

**Comment by koekeishiya** [comment]
> I think kwm should just host the formula itself, brew fully supports github. brew install koekeishiya/kwm/kwm

> Where there is a kwm.rb formula in this repo

I'll probably just go ahead and do this.

I have not read up on the homebrew changes yet (didn't even know that binary was deprecated).
I was under the impression that brew-cask was only for applications that made .app folders?

**Comment by chrishoage** [comment]
> I was under the impression that brew-cask was only for applications that made .app folders?

This is correct (or at least used to be correct). I can't find any info in `brew-cask` about a non `.app` formula. 

We should be able to just take the formula that used to be in`homebrew/binary` and place it in this repo. 

Moving to `brew-cask` (if that is even a viable option) would require some work done to the formula file.

**Comment by koekeishiya** [comment]
Made a repo `homebrew-kwm` which holds the formula. Updated install instructions in the README file.

**Comment by dominiklohmann** [comment]
I wonder if `homebrew/binary` maintainers will still accept 3.0.2 with a note to people updating Kwm that it has been moved to another repository. 

Sadly their `.github/CONTRIBUTING.md` says to not open new issues or pull requests and instead post them to the `brew-cask` repository, and there seems to be no mechanism in place to direct existing users to the new repository.
