### ISSUE TITLE
IntelliJ IDEA Crashes

### ISSUE THREAD

**Issue by HowardStark** [koekeishiya/kwm#418]
IntelliJ IDEA crashes a few moments after opening unless it's in fullscreen.

**Comment by koekeishiya** [comment]
Need steps to reproduce. IntelliJ works completely fine for me.

**Comment by HowardStark** [comment]
Weird. Whenever I open it, it crashes after a few seconds regardless of what I am doing. I didn't think it would have an effect but I can edit the issue title to point out that it's specifically Android Studio.

**Comment by HowardStark** [comment]
Adding a rule to make it float seemed to fix the issue.
