### ISSUE TITLE
Certain windows leave behind focused border after quit / screen transition

### ISSUE THREAD

**Issue by weruder** [koekeishiya/kwm#420]
Some windows leave behind borders when they're the only ones on a space and I quit the app. I've been able to reproduce this for safari, preview, vlc and emacs.
I have a hard time reliably reproducing the border on screen transition, but this happens to me with Chrome after I swap with another window on the same space and then transition. Using kwm on the master branch.

**Comment by koekeishiya** [comment]
> Some windows leave behind borders when they're the only ones on a space and I quit the app. I've been able to reproduce this for safari, preview, vlc and emacs.

Should be fixed.

Feel free to reopen / create a new issue for the space-transition thing. I was unable to reproduce it for now.
