### ISSUE TITLE
[Question] Resizing

### ISSUE THREAD

**Issue by GilDev** [koekeishiya/kwm#422]
Hi,
I just discovered kwm, seems really nice as I am looking for an alternative to i3 on my Mac. I'm playing with the config and I look at the sample configuration files but it just isn't right in my mind.
I would like to resize my windows simply with hjkl (while in prefix mode), moving the bottom-right corner of the focused window in the direction I want. However, I can't get this behavior to happen. I'm lost with the directions to give to `window -c`. I would like a configuration like this:
```
kwmc bindsym prefix-h window -c reduce 0.05 horizontal
kwmc bindsym prefix-j window -c expand 0.05 vertical
kwmc bindsym prefix-k window -c reduce 0.05 vertical
kwmc bindsym prefix-l window -c expand 0.05 horizontal
```
Is it possible to achieve this? Thanks a lot!

**Comment by koekeishiya** [comment]
> moving the bottom-right corner of the focused window in the direction I want. 

This is currently not possible.

The `reduce` and `expand` affects the split-ratio between two child-nodes (windows) in the binary-tree.

**Comment by nino** [comment]
You can move the bottom-right corner of the current window with this mapping:

```
kwmc bindsym prefix-h window -c reduce 0.05 east
kwmc bindsym prefix-l window -c expand 0.05 east
kwmc bindsym prefix-j window -c expand 0.05 south
kwmc bindsym prefix-k window -c reduce 0.05 south
```

The downside here is that you can't, e.g. resize the bottom-right window and instead have to move the focus to the top, left, or top-left and resize that container, but it works.

I agree that something like the split-resize-behavior of tmux would be cool.

**Comment by koekeishiya** [comment]
I've made some changes such that the `window -c` is more like resizing the window in focus, rather than just changing the split-ratio, in some sense.

Performing `window -c reduce 0.05 dir` will always shrink the focused window in that direction.
Similarly, `window -c expand 0.05 dir` will always grow the focused window in that direction.

For now, I think this is the best solution.

**Comment by dominiklohmann** [comment]
> I've made some changes (on the master branch) such that the window -c is more like resizing the window in focus, rather than just changing the split-ratio, in some sense.

After an hour of using this, I wonder how I lived with the old method. Just feels way more natural - a huge improvement. Thanks so much! 🎉

**Comment by GilDev** [comment]
Thanks a lot! That seems to be what I wanted. But when trying it I have a question. When trying to resize horizontally the windows in the middle of the screen, windows from both sides are moving, is that normal?
I also can't resize my right windows horizontally, and the bottom-right one vertically, etc. but I think this may be normal.
Here's my config:
```
kwmc bindsym prefix-c window -c reduce 0.1 east
kwmc bindsym prefix-t window -c expand 0.1 south
kwmc bindsym prefix-s window -c reduce 0.1 south
kwmc bindsym prefix-r window -c expand 0.1 east
```
And a video where I resize the middle window: https://youtu.be/kWRvvnH4pPk

**Comment by koekeishiya** [comment]
That is indeed intended. If you are interested in why that is the case, I describe pretty much how it works [Here](https://github.com/koekeishiya/kwm/issues/301#issuecomment-212939421).
