### ISSUE TITLE
Paths issues

### ISSUE THREAD

**Issue by alexfedoseev** [koekeishiya/kwm#423]
I just updated `kwm` to the latest from `homebrew`, and looks like it has troubles w/ paths, eg:

```c
// works
include settings           // file next to kwmrc

// doesn't work
include .settings          // file next to kwmrc, but w/ dot as first char
include config/settings    // file in subfolder
include ./config/settings  // file in subfolder

// this doesn't work also, I guess b/c kwm can't find script to exec
kwmc bindsym cmd+ctrl-b exec ~/.kwm/scripts/toggle-focused-border.sh
```

**Comment by dominiklohmann** [comment]
You can fix the last of these issues by defining `~` as your home directory.
```
define ~ /Users/username/
```

**Comment by alexfedoseev** [comment]
@dominiklohmann Works, thanks!

**Comment by koekeishiya** [comment]
Oops, forgot to post my comment.

So, use full paths for eveything that has to do with files.
You can use the define option to make it more readable.
