### ISSUE TITLE
Choose right/left mod keys

### ISSUE THREAD

**Issue by GilDev** [koekeishiya/kwm#424]
Hi, it's me again.
I'm using the [Bépo](http://bepo.fr/) keyboard layout. It makes use of that “Alt Gr” key on Windows which is just the right “Alt” key on Mac. I'm using a [TypeMatrix](http://typematrix.com/) keyboard so that key is really easy to access.
Anyway, my kwm config mostly uses “alt” and “alt+shift” modifiers, like an i3 default configuration. How could I specify which mod key (right or left) to use? I got the keycodes for both “Alt” keys but it seems that only the key and not the modifiers can be specified with a keycode in kmwrc.

**Comment by koekeishiya** [comment]
There is currently no way to specify only the left or right modifier.

**Comment by koekeishiya** [comment]
You can now use the following keywords to specify modifiers:

```
cmd
lcmd
rcmd

alt
lalt
ralt

shift
lshift
rshift
```

e.g: 
cmd will require either the left or the right cmd-key to be down.
lcmd will require the left cmd-key to be down.
rcmd will require the right cmd-key to be down, and so on.

**Comment by GilDev** [comment]
What an active developer, listening to the community! Thanks a lot! =)
I'll try when it gets updated on brew.
