### ISSUE TITLE
Listing configured keybinds

### ISSUE THREAD

**Issue by vendion** [koekeishiya/kwm#426]
OS: 10.11.6
kwm version: 3.0.4

I'm trying to troubleshoot some custom keybinds that don't seem to be working.  All the default keybinds are working, but that is about it.  I've tried testing the keybinds on a space with a application open (Chrome/finder/iTerm2), and a space with no application and nothing happens either way.  I have also tried testing the keybinding with `kwmc pless {keys}` still with no luck.  At this point I'm starting to wonder if they key bindings are even set.  Is there a command like `kwmc query bindsyms` to list all set key bindings for kwm?

**Comment by matthewdias** [comment]
there isnt, but you can enable the logs by building with 'make' rather than 'make install', and then running it manually.

**Comment by koekeishiya** [comment]
Can you post your config and some of the binds that are not working?

**Comment by vendion** [comment]
It would be useful if the released binary had some kind of debugging/logging capabilities so users won't need to build a version from Git just to have this ability.  Being able to list all know keybinding is fairly common among tiling window managers, see [herbstluftwm commands list](http://herbstluftwm.org/herbstluftwm.html#COMMANDS) for examples or some common commads.  As it stands it seems like there is little to no reason to install the version from homebrew or running `make install` as it would just make things harder to troubleshoot/debug.

Anyways I think I may have figured it out I had the following set in my configs
```
define hyper cmd+alt+ctrl
define HOME /Users/vendion
define pull HOME/.config/kwm/scripts/pull
define openappdir HOME/.config/kwm/scripts/openappdir

kwmc bindsym hyper-return exec openappdir iTerm2.app
kwmc bindsym cmd+alt+shift-2 exec pull 2
```

I noticed that in the output I was seeing thing like the following

```
KwmExecuteHotkey: Number of commands 1
KwmExecuteHotkey() exec HOME/.config/kwm/scripts/openappdir iTerm2.app
Exec: FORK SUCCESS
Exec argument 0: HOME/.config/kwm/scripts/openappdir
Exec argument 1: iTerm2.app
Exec failed with code: -1
```

So even though I defined `HOME` previously in my config it wasn't getting evaluated when used in another variable.  I hardcoded the path instead and it seems to work now.  I don't know if variables are meant to work like that or not, or if using the `$HOME` environment variable is even allowed, I was just trying to avoid typing out the full path multiple times out of laziness.

One key binding that I can't get to work, even using the default keybindings is

`kwmc bindsym cmd-return exec open -na /Applications/iTerm2.app`

When I run it I get `FSPathMakeRef(/Applications/iTerm2.app) failed with error -43.`, iTerm2 is already running and there are already windows open, but if possible I want kwm to open a new window in the active space when I hit a key combination.  Currently the only way I can find to do this is go to a space that has a iTerm2 window give it focus and either hit `CMD-n` or a keybinding inside iTerm2's preferences to open a new window, then move that window to the desired space (or move an active window there) not sure if this is possible inside OSX/Kwm but it would be nice to get things to work that way.

**Comment by dominiklohmann** [comment]
> if possible I want kwm to open a new window in the active space when I hit a key combination

See this: https://www.iterm2.com/documentation-scripting.html - you can just create a `kwmc` bind to execute an AppleScript with `osascript`.

**Comment by vendion** [comment]
@dominiklohmann I'm not familiar with working with AppleScript, but wouldn't that only work if iTerm2 is already running?  Only way I see that working is to create a wrapper script around the AppleScript that either runs that or `open` depending on if iTerm2 is running or not.  This is something that I would like to avoid if possible.

**Comment by chrishoage** [comment]
@vendion 

I have a file called `open-iTerm.applescript` that I use to open iTerm with a key combo, or create a new window if it is already open. 

```applescript
#!/usr/bin/env osascript

if application "iTerm2" is running then
    tell application "iTerm2"
        create window with default profile
    end tell
else
    activate application "iTerm2"
end if
```

**Comment by koekeishiya** [comment]
> So even though I defined HOME previously in my config it wasn't getting evaluated when used in another variable.

This is intended. The substitution only  does a single pass. I thought this was documented, but it appears to not be in the documentation.. might've been a github issue.

Regarding listing of keybinds, I guess that could be implemented.

Debug information will not be switchable in release builds in the foreseeable future, as they are all removed (along with assertions) using the preprocessor, when building in release mode.

**Comment by vendion** [comment]
I'm having some odd behaviour with keybindings.  Using the above applescript that @chrishoage provided and testing from my shell it seemed to work (was able to open up a new iTerm2 window regardless of if iTerm2 is running or not with some modifications... why this couldn't be done via sh/bash/zsh/ksh/etc is beyond me (guess I could run the applescript stuff in a subshell but that could get messy)).

It also works when running the version of `kwm` I built from Git, but if I try using the version installed via Homebrew (thus no logging) it does not work.  Both versions are using the same _kwmrc_ and _binds_ file.  Due to the difficulties of debugging this with the release version here are my config files:

kwmrc: https://gist.github.com/anonymous/8af4991cabad3944576bac225555f17f
binds: https://gist.github.com/anonymous/2b7704cf9dc9b40aa5e2f773fb6f99b2

**Comment by koekeishiya** [comment]
I use the following, and it works fine.

```
define iterm osascript /Users/Koe/.kwm/scripts/iterm2.applescript
kwmc bindsym MODE_MANAGER-return exec iterm ; mode activate default
```

**Comment by vendion** [comment]
Even though `$HOME/bin/open-iTerm` is in my $PATH should I hard code it in my KWM configs?  (Not sure why that would cause it to break in the release version but work when debugging/logging is compiled in).

**Comment by chrishoage** [comment]
> if I try using the version installed via Homebrew (thus no logging) it does not work.

How are you running the version from homebrew? if it is though `launchctl` it will not have the `$PATH`. (this is due to how `launchctl` works with OS X and nothing to do with kwm)

If you would like `$PATH` to work from `launchctl` you can follow this http://stackoverflow.com/a/26586170

**Comment by vendion** [comment]
Yes I was being launched via `launchctl`

**Comment by paradox460** [comment]
I believe the crash issue with Snagit is due to the overlay/border. When i disabled overlay/border, snagit worked properly

**Comment by koekeishiya** [comment]
Closing this issue due to #478
