### ISSUE TITLE
Tile qt window launched from shell

### ISSUE THREAD

**Issue by dvcrn** [koekeishiya/kwm#428]
For development I am using neovim-qt compiled from source. To launch it I am using a little alias around launching the program from shell

```
gnvim() {
  ABSOLUTEPATH=`realpath $1`
  open -n -a ~/src/neovim-qt/build/bin/nvim-qt --args -- $ABSOLUTEPATH
}
```

I tried adding
```
kwmc rule owner="nvim-qt" properties={float="true"}
```

and
```
kwmc rule owner="nvim-qt" properties={role="AXStandardWindow"}
```

but the window is still getting ignored by kwm. `./kwmc query window list` doesn't list the window either.

**Comment by dominiklohmann** [comment]
Can you share what Accessibility Inspector has to say about that window?

**Comment by dvcrn** [comment]
<img width="500" alt="screen shot 2016-08-04 at 8 17 44 pm" src="https://cloud.githubusercontent.com/assets/688326/17400023/a69e3810-5a80-11e6-9c83-39364ad2d5f2.png">

It seems to be nothing out of the ordinary from what I can tell. How can I debug this?

**Comment by koekeishiya** [comment]
Can you confirm that it tiles properly if not launched through the shell?
I had this issue with some applications as well, only when launching from the shell.

It caused OSX to set a "background only" flag in the process information, which Kwm filters away due to most of them not being interactable. See https://github.com/koekeishiya/kwm/blob/master/kwm/axlib/carbon.cpp#L31

**Comment by dvcrn** [comment]
I'm not able to launch the app without the shell. Double-clicking the binary it will spawn a terminal window which then executes `nvim-qt`. 

`open -a /path/to/nvim-qt` has the same result as my custom shell command. 

Can I mark this window inside kwm for it to find it or remove the background flag or do I have to package it into a .app?

**Comment by koekeishiya** [comment]
You can try to edit out the return statement in the code I linked above and see if that is indeed the issue.

**Comment by dvcrn** [comment]
I can confirm, this is indeed the issue. Removing that statement is tiling the nvim-qt window correctly

**Comment by koekeishiya** [comment]
Aight, gonna try come up with some system that allows whitelisting of processes through the kwmrc config file.

**Comment by dvcrn** [comment]
Thank you. Is it harmful if I leave that code removed for now on my system? What could happen?

**Comment by koekeishiya** [comment]
Not harmful, just tries to create accessibility references to processes that most likely does not have it enabled, thus using a bit more resources.

Things like safari.webkit and so on.

**Comment by koekeishiya** [comment]
I've added the command `kwmc whitelist processname` in the latest commit.

In your case, simply add `kwmc whitelist neovim-qt` in one of your config files.

**Comment by dvcrn** [comment]
Works great! Thank you for being so fast with these issues 👍 👍 👍
