### ISSUE TITLE
kwm no longer detects modifier keys

### ISSUE THREAD

**Issue by nathyong** [koekeishiya/kwm#429]
As stated. I can't use any bindings that involve the alt, command or shift keys in kwm 3.0.4, even in the default kwmrc. Running the 3.0.3 kwm binary works as expected.

I suspect this is related to b4708250186598760a46a7780461788341b3732d which changed the modifier behaviour, but I am not able to compile a build to test it out for myself.

El Capitan 10.11.5. Other applications that might interfere include karabiner, seil, hammerspoon. Is there debugging output that I can use to help diagnose this issue?

**Comment by koekeishiya** [comment]
Should be fixed on latest commit on master. It appears that some of the masks that apple define only work on some devices (...thanks apple). Can you clone the latest commit and do a `make install` and see if the issue has been fixed?

**Comment by nathyong** [comment]
I can confirm that the issue appears to be fixed on the master branch of kwm.

**Comment by koekeishiya** [comment]
Great, thanks.

Will proably do a new release by the end of the day
