### ISSUE TITLE
Switch space on display containing mouse cursor

### ISSUE THREAD

**Issue by dvcrn** [koekeishiya/kwm#430]
I am using Totalspaces but this should be applicable to other applications as well.

Steps to reproduce:
- CTRL+n or CTRL+-> to switch to a space to verify it works -> switches space on display 1
- cmd+alt+2 to switch to display 2
- CTRL+n or CTRL+-> to switch to a space

Expected:
- Switch space on display 2 since the mouse cursor is on that one

Actual:
- Mouse cursor jumps back to display 1 and space switches

If I manually hover to display 2 without using kwm and then use CTRL+n, it switches spaces correctly on display 2. Just when using kwm to switch displays it doesn't.

**Comment by koekeishiya** [comment]
> If I manually hover to display 2 without using kwm and then use CTRL+n, it switches spaces correctly on display 2. Just when using kwm to switch displays it doesn't. 

Not sure I understand, do you use Kwms space transition commands, or the ones provided by OSX?

**Comment by dvcrn** [comment]
I didn't know kwm already has space transitions built in. How do they work?

I am currently using Totalspaces transition commands but had the same problem with native OSX ones

**Comment by koekeishiya** [comment]
> I am currently using Totalspaces transition commands but had the same problem with native OSX ones

Will look into it.

**Comment by koekeishiya** [comment]
Uh, can you describe a bit more what the problem appears to be?
When I use OSX native spaces shortcuts, everything works as expected.

**Comment by dvcrn** [comment]
Sure! 

The problem happens when you try to switch to a different space on a separate display. 

Apps like Totalspaces have a mode where they switch spaces on whatever display the mouse currently is. When you switch to the second display with kwm and try to switch spaces (on display 2), the mouse jumps back to display  one and the space of display one changes. 

With normal OS X  as well I wasn't able to switch spaces with "move to the space on the right " and only with the direct "jump to space x" shortcut

**Comment by koekeishiya** [comment]
Hmm, which version of Kwm are you running? `kwm --version`

**Comment by dvcrn** [comment]
I am using 3.0.4, fresh compiled from this github repository

**Comment by koekeishiya** [comment]
Hm, I'm still unable to reproduce the issue with normal OSX shortcuts.

**Comment by dvcrn** [comment]
I think it might have been been caused by Totalspaces and the extension it installs. 
I removed Totalspaces, re-installed kwm and the OSX keybindings seem to work now. 

I replaced Totalspaces with kwm-only keybindings and things work great! 

```
// Switch between spaces
kwmc bindsym ctrl-1 space -fExperimental 1
kwmc bindsym ctrl-2 space -fExperimental 2
kwmc bindsym ctrl-3 space -fExperimental 3
kwmc bindsym ctrl-4 space -fExperimental 4


// Move Focused Window To Space
kwmc bindsym ctrl+alt-left window -m space left
kwmc bindsym ctrl+alt-right window -m space right
kwmc bindsym ctrl+alt-1 window -m space 1
kwmc bindsym ctrl+alt-2 window -m space 2
kwmc bindsym ctrl+alt-3 window -m space 3
kwmc bindsym ctrl+alt-4 window -m space 4
```

Thank you a lot for the help. I should have used the Experimental spaces switcher earlier 

Another issue now is that when switching spaces the window border remains on the screen but I might just create a new ticket for that

<img width="1321" alt="2016-08-05 1 54 09" src="https://cloud.githubusercontent.com/assets/688326/17426559/24a499c8-5b14-11e6-8b96-4dc6ff057e8c.png">

**Comment by koekeishiya** [comment]
> I replaced Totalspaces with kwm-only keybindings and things work great! 

If I remember correctly, Mission Control will not work properly if you use Kwms fast transition  though.

**Comment by dvcrn** [comment]
> If I remember correctly, Mission Control will not work properly if you use Kwms fast transition though.

Luckily I don't care about Mission Control 😄

**Comment by koekeishiya** [comment]
Aight sounds good. I believe the issue you mentioned have been solved in the latest commit.
