### ISSUE TITLE
Remember focused window when swapping displays

### ISSUE THREAD

**Issue by kylebrandt** [koekeishiya/kwm#432]
Is it possible to make it so when cycle through displays `display -f prev|next wrap` that the focused window within the display is remembered when I cycle back to it?

So for example, if I have two monitors, and monitor A has a split and monitor B has a split. If I am on the second split of monitor A, switch to monitor (display) B, then switch back to monitor A, the focus will be on the first split window, not the second split window that I was on last time I was on monitor A.

With the current behavior I am seeing it makes so if I want to jump back forth between the same set of windows on different displays, extra keystrokes are required.  As an analogy, it is like if jumping between two different browser windows with tabs would always go back to the first tab, instead of the last tab I was on.

Other than this kwm is working great for me and has really helped me with my window management so far, thanks!

**Comment by koekeishiya** [comment]
That sounds annoying indeed, not sure how that went through. Implemented suggest behaviour on master.
