### ISSUE TITLE
Native OSX fullscreen window intereferes with tiling

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#435]
See #11 for information.

**Comment by koekeishiya** [comment]
Thanks to ianyh, creator of amethyst for insight into the problem. This would've been one heck of an issue to debug.

**Comment by koekeishiya** [comment]
Issue #390 still applies even though this bug has been fixed.

After bringing a window back to fullscreen mode, issue `kwmc window -t focused` twice, to force a retile (floats and unfloat the window).

**Comment by cHoco** [comment]
Wouldn't it be possible to do that automatically? A window leaving fullscreen will trigger a spacechanged notification, so when processing that event when we rebalance the window tree shouldn't be able to see a window that is present but not flagged as floating and add it to the window tree? 

I'm referring to the ```RebalanceBSPTree``` function where we check for the windows to remove. I'm also probably missing something but I'm not sure how that function works. If I'm reading the logic right, if a window is not present in the space tree but is in the current space when calling ```AXLibGetAllVisibleWindows``` in ```GetAllAXWindowIDsToRemoveFromTree``` and is not floating, shouldn't it be added to the window tree instead of getting removed?

**Comment by koekeishiya** [comment]
There are multipel reasons why it may be not in the tree. For example, if you simply switch back to the space, instead of leaving fullscreen mode, the above scenario would trigger, when it should not. There are other issues with simply basing this upon space transitions as well.

**Comment by koekeishiya** [comment]
Log from starting notes, entering fullscreen and leaving fullscreen.

```
AXEvent_WindowFocused: Notes - Notes
AXEvent_ApplicationActivated: Notes
AXEvent_WindowCreated: Notes - 
AXEvent_WindowFocused: Notes - 
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_SpaceChanged
AXEvent_WindowMoved: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowDestroyed: Notes - 
GetScratchpadSlotOfWindow()  -1
AXEvent_WindowCreated: Notes - 
AXEvent_WindowFocused: Notes - 
AXEvent_WindowResized: Notes - Notes
AXEvent_WindowResized: Notes - Notes
AXEvent_SpaceChanged
AXEvent_WindowDestroyed: Notes - 
GetScratchpadSlotOfWindow()  -1
```

> I'm referring to the RebalanceBSPTree function where we check for the windows to remove. I'm also probably missing something but I'm not sure how that function works. If I'm reading the logic right, if a window is not present in the space tree but is in the current space when calling AXLibGetAllVisibleWindows in GetAllAXWindowIDsToRemoveFromTree and is not floating, shouldn't it be added to the window tree instead of getting removed?

I tried something very similar to this, but it did not get triggered at all.
