### ISSUE TITLE
kwmc window -m <dir> activates border

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#437]
When I use this command it seems like its also marking the window that is in the direction that I am moving to. I can get rid of it by marking and unmarking the current window. Here's a screencast: 

![](http://i.giphy.com/l3vQYlAG7cpq5HfZ6.gif)

**Comment by koekeishiya** [comment]
Well this is awkward, I can't reproduce..

**Comment by matthewdias** [comment]
i got a `fatal: corrupt patch at line 35`. need to push some changes first?

**Comment by matthewdias** [comment]
yup, that fixed it.
