### ISSUE TITLE
[3.0.7] Mouse Follows Focus is triggered when moving between displays

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#441]
STR:

1. Have a 2 display environment with MFF and Autoraise turned on. 
2. Use the mouse to bring focus to window on alternate display. 
3. Observe mouse snapping to center of focus window. 

Expected Result: 
Mouse Follows Focus is only triggered when a keyboard focus command is given

Actual Result: 
Mouse Follows Focus is triggered when the mouse gives focus to a display

**Comment by koekeishiya** [comment]
Uh, so yeah.. Apparently I went a bit too fast when refactoring some code.
