### ISSUE TITLE
[3.0.7] Focus follows mouse only on 2nd external monitor, not 1st

### ISSUE THREAD

**Issue by thonixx** [koekeishiya/kwm#442]
I have a strange issue since branch tag 0.3.2 (I tried some versions) which concerns focus follows mouse. With the latest tag 0.3.7 the issue still persists so I switched back now to 0.3.1. The focus follows mouse only works on the 2nd monitor but not on the 1st monitor. I have 2 monitors plugged in and the window tiling works fine. Can I assist you in this issue with some logs or something similar? In v0.3.6 one of the windows of the 1st monitor steals the focus and centers the mouse into it when switching the workspace on the 1st monitor.

**Comment by koekeishiya** [comment]
Tested just now on the master branch (no changes regarding ffm since 3.0.7) and im unable to reproduce. You probably have to remove Kwm from the osx-accessibility options, reboot and readd it. This issue seems to happen to other accessibility related applications as well, as far as I can tell.

I always codesign the Kwm binary after every compilation to avoid having to do the above.

**Comment by thonixx** [comment]
It is annoying that I had to switch back. After every recompile I remove the kwm from the privacy settings and reapprove as OSX asks again for the permissions and the kwm reappears. I just went through all versions from 0.3.7 to 0.3.1 and with 0.3.1 it works just fine.

**Comment by thonixx** [comment]
I now tried with a clean installation. I removed the config file, removed the bin/obj folder, switched to master, made everything up to date and recompiled. But it still occurs.

So maybe it has something to do with my specs:

I have a Macbook Air 11" with an external monitor plugged in via display port and the other monitor via DisplayLink (USB 3 and some driver magic). Can I assist you with more information? Log files or something like that?

**Comment by koekeishiya** [comment]
Does focusing windows using keybindings still work on the monitor where focus-follows-mouse fails?

Also, does this happen on every window / application, or just some?
The only change for focus-follows-mouse after 3.0.1 was to fix #398

**Comment by thonixx** [comment]
@koekeishiya I never got the keybindings working. Either I am too dumb or something is wrong with them. So I can not check with the keybinding. It concerns every application, every window.

**Comment by Jurikay** [comment]
I have a similar problem. ffm suddenly stopped working on my mbp. I haven't tested a second monitor though. I checked kwmrc and tried an earlier version (3.0.5). I also tried to remove and add kwm in the Accessibility tab multiple times but without success.
All hotkeys et cetera are working fine. It affects every window of every application. 

I am already missing the functionality quite much so any help is greatly appreciated.

**Comment by koekeishiya** [comment]
After further testing, the fix provided for issue #398 seems to break focus follows mouse when the Dock is visible. This is a bug and would also explain why ffm works on the second monitor.

Please do confirm that you do indeed have your dock visible, thanks.

**Comment by thonixx** [comment]
Yes, I have it visible.

**Comment by koekeishiya** [comment]
The issue should now be fixed (I'm unable to reproduce now with my previous method).

If this is really annoying, I would recommend to just clone master. I will be releasing 3.0.8 this weekend probaby. I have done a lot of refactoring and need some more time to make sure that this didn't cause any unwanted sideffects, it should be stable.
