### ISSUE TITLE
Executing shortcut at wrong time

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#443]
Kwm occasionally gets into a state where it doesn't know that a window is focused (I think. This is not kwms fault. Another app has opened something in another app, but kept the previous app focused). The window is in the foreground, but there is no border. I have `kwmc bindsym_passthrough cmd-w press cmd+alt-q stubborn -i` which quits the app if it is in the `stubborn` list. When kwm is in this state and I hit the shortcut, it quits the app regardless of if it is in the list.

**Comment by matthewdias** [comment]
Actually the weird state might be a kwm problem. Sometimes when I command tab, for example, from slack to chrome, it moves to the space that the chrome window is on, but the active application is still Slack on the other space. Might be related to #419?

**Comment by koekeishiya** [comment]
> Actually the weird state might be a kwm problem. Sometimes when I command tab, for example, from slack to chrome, it moves to the space that the chrome window is on, but the active application is still Slack on the other space. Might be related to #419?

Doesn't seem to be related to #419. Is this on master or v3.0.7?

**Comment by matthewdias** [comment]
I've been seeing this issue for awhile. I'm on master right now, but it was there at 3.0.7 as well.

**Comment by matthewdias** [comment]
ok so the issue is being caused by another app (https://github.com/johnste/finicky/issues/29) closing for now.
