### ISSUE TITLE
Tweaks to window floating

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#444]
Would be nice to have these:

- set insertion point to the place where the window was floated from, so when unfloating it goes back to the same spot
- configure the dimensions of the window when floated (i just got a 21:9 monitor so its a pretty awkward shape)

**Comment by koekeishiya** [comment]
> set insertion point to the place where the window was floated from, so when unfloating it goes back to the same spot

This would be rather hard to do considering how the bsp implementation works.

> configure the dimensions of the window when floated (i just got a 21:9 monitor so its a pretty awkward shape)

This sounds like a reasonable thing to provide, any idea of what the config command could be?

**Comment by matthewdias** [comment]
maybe something like `kwmc config float-size <x> <y>`

**Comment by dominiklohmann** [comment]
> maybe something like kwmc config float-size <x> <y>

Should probably be a per-display setting.

**Comment by matthewdias** [comment]
ah yeah, good point

**Comment by koekeishiya** [comment]
The dimensions used for 'center-on-float' can now be set using the following:

`kwmc config display <display_id> float-dim <width> <height>`
e.g: `kwmc config display 0 float-dim 500 350`

> set insertion point to the place where the window was floated from, so when unfloating it goes back to the same spot

Again, this is not something I will be doing, so I consider this issue solved.
