### ISSUE TITLE
Focus previous window when closing

### ISSUE THREAD

**Issue by oetting** [koekeishiya/kwm#45]
When a window is closed the first window of the current space is focused (if focus follows mouse is disabled). As discussed earlier it would be nice if the previously focused window was selected instead. 

For instance when composing an email in Mail.app and sending it, it can be annoying that focus is not returned to the main Mail.app window. 

Would it be possible to focus (in the kwm sense) the window that OS X focuses, at least if it is in the same space? 

Alternatively I guess it would require implementing a focus-history.

**Comment by koekeishiya** [comment]
I do agree that default-focusing the first window of the current space is really annoying and I hate this as well. I have thought about the two following fixes for this:

1. When a window is closed, focus the nearest remaining window. This would essentially give focus to the container that filled up the space of the container that was removed.

2. Implement a focus-stack and simply pop from that to decide where focus goes.

I personally feel like the first proposal would fit my own usage of Kwm the most, and is probably the change that will be made.

**Comment by oetting** [comment]
2 sounds like a good simple solution. Fairly certain it would solve my use case as well.
