### ISSUE TITLE
Request: mouse drag bindings

### ISSUE THREAD

**Issue by akdor1154** [koekeishiya/kwm#451]
Hi,
I'm not sure if you've used Awesome WM on X11, but their default config has some intuitive mouse bindings as well as full keyboard control. For example, mod+drag moves a window (it then swaps with whatever window it is dragged over), and mod+rightdrag resizes splits. In a quick look at the config, it looks like this is not possible at the moment with kwm (please correct me if I'm wrong, I haven't looked at the source!) How easy would this sort of functionality be to add in a configurable way?

Cheers
Jarrad

**Comment by koekeishiya** [comment]
As far as I know, there is no way to prevent a mouse-click from "clicking", so having a mod-left (anywhere on the window) to drag is not possible without the window also receiving the click event.

Mouse controls might also be a bit awkward to use due to minimum and maximum window sizes.

If anyone has any information regarding any of these problems, it would be a nice feature to have.

**Comment by matthewdias** [comment]
Maybe you could just update the layout of the other windows, as they would be if you dropped the window at the current position (drop area). that would be the indication that you could let go of the window and it would tile the way you wanted.

**Comment by koekeishiya** [comment]
> As far as I know, there is no way to prevent a mouse-click from "clicking", so having a mod-left (anywhere on the window) to drag is not possible without the window also receiving the click event.

So this is actually not true, even though I read this somewhere in the Apple docs. 
I can actually prevent it from clicking if desired.

The only real problem would be dealing with minimum and maximum sizes, and how to interact with the binary-tree.

**Comment by koekeishiya** [comment]
>  For example, mod+drag moves a window (it then swaps with whatever window it is dragged over),

Implemented on master. The `mod` key is hardcoded to the `shift-key` during testing. This will become a configurable option if this appears to be a stable feature.

There is no visual indication for the above as of now (if that is even possible), but you can `shift+drag`a window on top of some other `tiled` window, and they will swap positions, as if you performed a `window -m ..` command.

**Comment by chrishoage** [comment]
> There is no visual indication for the above as of now (if that is even possible)

There was talk of re-writing the border to be Obj-C and controlling it though the kwm C code, I wonder if that happened the border system could be used as a visual indicator for dragging windows?

**Comment by koekeishiya** [comment]
> There was talk of re-writing the border to be Obj-C and controlling it though the kwm C code, I wonder if that happened the border system could be used as a visual indicator for dragging windows? 

I can do this already, for the most part. The problem is that we don't receive `mouse moved`events while a mouse button is down, so I can't put a border around the window the mouse is currently on. I think I read about some `mouse dragged` events at some point, so that might be the solution.

**Comment by koekeishiya** [comment]
> and mod+rightdrag resizes splits.

I'm still not sure if this is achievable in the way that a lot of X11 window managers do it.

It should be quite easy for floating window, but rather tricky for tiled ones.

**Comment by koekeishiya** [comment]
You can now use the setting `kwmc config mouse-drag on | off` to set the state of this.
If no setting is specified in the config file, the default value is set to `on`.

**Comment by chrishoage** [comment]
> If no setting is specified in the config file, the default value is set to `on`.

Wouldn't `off` be safer? Particularly since you can't modify the `mod` yet?

**Comment by koekeishiya** [comment]
> Wouldn't off be safer? Particularly since you can't modify the mod yet? 

That kinda makes sense, even if you can specify the modifiers.

**Comment by koekeishiya** [comment]
This setting is now disabled by default. To enable it, place `kwmc config mouse-drag on` somewhere in the kwmrc file.

The modifiers can be set using `kwmc config mouse-drag mod mod+mod+mod`.
e.g: `kwmc config mouse-drag mod lshift+cmd`

**Comment by matthewdias** [comment]
would be cool to also have this for `kwmc window -m <dir>`

**Comment by koekeishiya** [comment]
> would be cool to also have this for kwmc window -m dir

Need to figure a smart way to be able to handle both cases. Maybe at some point in the future.

**Comment by koekeishiya** [comment]
I'm gonna consider this issue as solved.

> and mod+rightdrag resizes splits.

This is not going to happen in the foreseeable future.

**Comment by akdor1154** [comment]
Jeez man, you are a coding machine! Nice job :)
