### ISSUE TITLE
How to disable windows moving following mouse

### ISSUE THREAD

**Issue by magicmark** [koekeishiya/kwm#452]
Similar symptoms as https://github.com/koekeishiya/kwm/issues/445, but making a new issue because it's probably a slightly different problem.

When I make a new window, or use a keybinding to move a window to a different physical monitor, if I then subsequently move my mouse about, the window appears to follow the mouse and move window/placement. This is undesired.

Is this is a problem with my config or the same issue as previously described?

Config file: http://pastebin.com/wDZ8wEg4 (I have disabled everything relating to the mouse)

**Comment by koekeishiya** [comment]
> //kwmc config focus-follows-mouse autoraise

Commenting these out are not the same as disabling it. 

If there are no setting for them in the kwmrc file, they are enabled by default.
You need to explicitly set them to 'off'.

**Comment by magicmark** [comment]
Ah thanks

I have set them to off and reloaded/restarted kwmc

Issue still persists

**Comment by koekeishiya** [comment]
> When I make a new window, or use a keybinding to move a window to a different physical monitor, if I then subsequently move my mouse about, the window appears to follow the mouse and move window/placement. This is undesired.

Not sure I totally get what you're saying here. Do you drag the window with the mouse afterwards?

Simply moving a window using keybindings (`kwmc window -m ..`) works just fine for me.

Which version of Kwm are you running (kwm --version) ?

**Comment by magicmark** [comment]
installed with brew; at version 3.0.7

Steps to reproduce for me:
- iterm window is in monitor 1
- with the iterm window focused, I press ctrl-alt-2 to move it to monitor 2
- as soon as I move my mouse (not dragging, literally just moving it) a window (somtimes a different window that was on the other monitor) will just snap back

Here's a gif i just took that shows this issue: (click to play gif)
![image](https://cloud.githubusercontent.com/assets/1590756/18128492/eeb81c44-6f7d-11e6-9a91-ea69231215af.png)

**Comment by koekeishiya** [comment]
Hm, I'm still unable to reproduce on my end.

**Comment by magicmark** [comment]
Is there any other diagnostic info I can provide? As it stands I can't really use kwm :(

**Comment by koekeishiya** [comment]
I don't think there is any info regarding this operation that would be useful, that is being logged.
Logging is turned off in release builds such as the one provided through brew, so you would have to clone master and build manually with `make`

Logs are written to stderr and stdout, so you'd have to pipe to file.

Does this only happen with iTerm? How about Terminal.app?

**Comment by magicmark** [comment]
Hmmmm well I blitzed my brew installation, built from source and am calling kwm directly.

I am no longer encountering the issues 🎉
