### ISSUE TITLE
[3.0.7] mouse-follows-focus clashes with focus-follows-mouse

### ISSUE THREAD

**Issue by carymrobbins** [koekeishiya/kwm#453]
It's really nice to have `mouse-follows-focus` when you use a key binding to move the focus; however, when accompanied by `focus-follows-mouse` the mouse will move immediately to the center of a window after moving your mouse to it.  I assume this is because the mouse is triggering the focus, and the focus is triggering the mouse to move to the center of the focused window.

Ideally, `mouse-follows-focus` would only apply after using a key binding and _not_ when the focus is the result of a mouse movement.  Otherwise, I find myself fighting with kwm at times.

**Comment by koekeishiya** [comment]
See #441
