### ISSUE TITLE
[master] kwmc query space active | tag incorrect when defaults are applied

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#454]
Steps to reproduce: 

Prerequisites: 2 displays

1. Set 2nd display config to `kwmc config display 1 mode monocle`
2. Open a terminal window on the 2nd display
3. Run `kwmc query space active mode`

Expected: 

mode to return `[1/2]`

Actual:

`[bsp]` mode returned

Notes: 

When `kmwc space -t monocle` is issued on the already monocle space the `mode` is as expected. This appears to only affect a mode applied at when kwm start up.

**Comment by chrishoage** [comment]
Hrm, not able to reproduce this 100% of the time. Very odd. It happens, but only _sometimes_.

**Comment by koekeishiya** [comment]
I don't think this has anything to do with the default mode being changed.

I can reproduce this behaviour every time i perform a `window -m display 1` command from a bsp -> monocle display, regardless of how the display was put into monocle mode.
