### ISSUE TITLE
[3.1.0] Focus follow mouse does not work within iTerm2 with no title bar windows

### ISSUE THREAD

**Issue by OrBaruk** [koekeishiya/kwm#455]
The focus follow mouse does not switch focus when moving the mouse between _iTerm2_ windows that have no title bar.

**Reproducing:**
Open two _iTerm2_ windows and any other window (_finder_ in this case).  Focus-follow works from and to, any of the two _iTerm_ windows to _finder_, however it does not working when switching from one _iTerm_ window to another.

It appears that for the purpose of focus-follow _kwm_ is considering that multiple windows from _iTerm_ are considered as one

**kwm version**: 3.0.5 does not have this issue but all version up to 3.1.0  presents this behavior

``` 
$ kwmc query window list
12941, Finder, Users
12822, iTerm2, Or@Alexandres-MacBook-Pro: ~/ (zsh)
12940, iTerm2, Or@Alexandres-MacBook-Pro: ~/ (zsh)
```
iTerm2 version: Build 3.0.8

**kwmrc config:**
`kwmc rule owner="iTerm2" properties={role="AXDialog"}`

**Comment by chrishoage** [comment]
I am not able to reproduce this issue on `master` FWIW.

**Comment by koekeishiya** [comment]
Unable to reproduce as well.

**Comment by OrBaruk** [comment]
Weird, must be a conflict with something else I have installed here.  Managed to find a solution though. 

Enabling the focus follow mouse option from _iTerm_ in ```Preferences > Pointer > Focus follows mouse``` solves the problem.
