### ISSUE TITLE
[3.1.0] Focus Follows Mouse not working between iTerm windows

### ISSUE THREAD

**Issue by field-sleep** [koekeishiya/kwm#458]
I noticed this issue back in 3.0.7 but it persists for me in 3.1.0, focus follows mouse is working as expected across all other windows, however, it will only focus the first iTerm window that's been moused over after the last iTerm window.

i.e.: mousing between chrome -> atom -> itermA -> itermB will highlight chrome, atom, then itermA but never itermB. However, mousing between chrome -> itermA -> atom -> itermB works as expected, with each window being focused and highlighted in order.

(note: clicking between iterm windows still focuses and applies the border as expected.)

**Comment by koekeishiya** [comment]
Same as #455, I'm still unable to reproduce on my end.

**Comment by dominiklohmann** [comment]
I've been having the same issue, but enabling iTerms own Focus Follows Mouse functionality fixes it for me.

<img width="1130" alt="screen shot 2016-09-06 at 8 48 07 pm" src="https://cloud.githubusercontent.com/assets/4488655/18286474/4a1ab11a-7473-11e6-831d-f87a78f5cf07.png">

**Comment by chrishoage** [comment]
FWIW I have iTerm2 `Build 3.0.20160720` with the iTerm2 Focus Follows Mouse _disabled_. 

On `master` at d33699c

I can no repo this at all.

**Comment by field-sleep** [comment]
@dominiklohmann's suggestion resolved this for me
