### ISSUE TITLE
[3.1.0] kwmrc parse errors

### ISSUE THREAD

**Issue by carymrobbins** [koekeishiya/kwm#459]
In 3.0.7 [this config](https://github.com/cary-weather/dotfiles/blob/c157d2c47476ac78d9d46deb879afb6550551775/.kwm/kwmrc) works fine; however, in 3.1.0 it I get parse errors.

```
Parse error: Unknown token 'space'
Parse error: Unknown token '-'
Parse error: Unknown token 'fExperimental'
Parse error: Unknown token 'left'
Parse error: Unknown token 'rcmd'
Parse error: Unknown token '-'
Parse error: Unknown token ','
Parse error: Unknown token 'space'
Parse error: Unknown token '-'
Parse error: Unknown token 'fExperimental'
Parse error: Unknown token 'right'
Parse error: Unknown token 'rcmd'
Parse error: Unknown token '-'
Parse error: Unknown token '.'
```

Note that trying to start kwm via brew services didn't make me privy to these errors, I had to run kwm from the command line.  Are errors logged somewhere as part of the launchd process?

**Comment by koekeishiya** [comment]
Not sure why that would parse properly in 3.0.7

The commands below are not valid
```
kwmc space -fExperimental left mod1-,
kwmc space -fExperimental right mod1-.
```

I suspect you wanted the following
```
kwmc bindsym mod1-, space -fExperimental left
kwmc bindsym mod1-. space -fExperimental right
```

for launchd to log, you need to specify that in the .plist file. You also have to be running a debug build of Kwm. (The homebrew version is a release build and does not include these logs).

**Comment by carymrobbins** [comment]
Thanks! Unfortunately, even with those fixes, the 3.1.0 release build doesn't seem to work for me. It exits with a non-zero status without anything put on stderr.  Luckily there's was a 3.0.7 binary in the `bin/` dir of the repo in a previous rev, so I'm using that for now (since I can't seem to get old versions of kwm from brew).

I've been having trouble building kwm from source, but I'll open a separate issue for that.

**Comment by koekeishiya** [comment]
Probably related to #456 

try adding the following to your config:
```
kwmc config border focused on
kwmc config border color 0x00000000
```

**Comment by carymrobbins** [comment]
The following sufficed, thanks!

```
kwmc config border focused on
```
