### ISSUE TITLE
Mail.app recipient suggestion list is registred as a window

### ISSUE THREAD

**Issue by oetting** [koekeishiya/kwm#46]
When composing an email with Mail.app and entering recipients, Mail.app will suggest recipients. Kwm sees this list of suggestions as a window, and relayouts the screen. Would it be possible to avoid this?

This issue is extra annoying in combination with #45 where the "new mail" window will not be focused after the suggestion list is closed.

**Comment by koekeishiya** [comment]
Never used the mail app. Will look into what is causing this, however if my assumptions are correct, it could be tricky to apply a proper fix.

**Comment by dominiklohmann** [comment]
The same happens with the recipient list in Messages.app btw.

**Comment by koekeishiya** [comment]
This is definitly happening because OSX returns these "windows" or whatever you wanna call them with the following roles: AXWindow, AXStandardWindow. 

I would have to implement a system for blacklisting specific windows somehow, in a way that can catch all these cases. It will probably take me quite some time to think of a good way to handle this situation.

The reason for this is that usually these roles are only used by actual windows of applications that we want to tile.

**Comment by oetting** [comment]
Thank you for the suggestion, and looking into this. The fix for #45 removed the most annoying part of the lists being normal windows.

**Comment by koekeishiya** [comment]
So I've been thinking about this and there is really no way for me to handle this kind of issues.
The only option I can really give you is to make applications like this always floating:

> kwmc config float application

**Comment by dominiklohmann** [comment]
Couldn't you add an option to float all windows without a title for a certain application? Wouldn't that work?

**Comment by koekeishiya** [comment]
I  believe I have made some progress on this.
Clone the latest master, and add this to your kwmrc: `kwmc config float-non-resizable enable`

**Comment by dominiklohmann** [comment]
It seems to kinda work so far, crashes sometimes and when it works the non-resizable windows get moved to the center of the screen sometimes (can't figure out what causes it). Will check it out again later as you said.

Thanks for your work on this!

**Comment by koekeishiya** [comment]
I believe this issue should be solved now.

**Comment by dominiklohmann** [comment]
New issue: When a non-resizable window opens, it gets added to the window tree and then removed. This can change your window focus and it also looks kinda weird to see the parent window get changed to half the size for a split second.

**Comment by koekeishiya** [comment]
I'll create a new issue for that.
I assume that this bug is fixed tho, with a side-effect as of now.
