### ISSUE TITLE
[master] Bogus query commands result in hung process

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#468]
Steps to reproduce: 

Issue a bogus query command: `kwmc query foo`

Observe process never exits. 

Expected Result: 

`exit 1` at minimum? 

Error message would be icing on the cake. 

Actual Result: 

Hung process.

**Comment by koekeishiya** [comment]
The above fix is temporary and only applies for "root" commands.
e.g: `kwmc query <invalid>` will return with an error message.
Doing `kwmc query space invalid` will still have the above problem.

This will get a proper fix for version 3.1.4

**Comment by koekeishiya** [comment]
Most commands should now return an error message. It might not be all that informative, but better than nothing I suppose.
