### ISSUE TITLE
[master] Secure Keyboard Entry

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#475]
I have Secure Keyboard Entry disabled, but I'm getting the error for it, and my binds do not work. This kind of randomly happened while I was working, so I have no idea what could have caused it.

**Comment by matthewdias** [comment]
A restart fixed it.

**Comment by koekeishiya** [comment]
There are apparently other applications that might activate secure keyboard entry at times, see for example #446.

I tried to deactivate it automatically upon launching Kwm, if it was enabled and `config hotkeys on` was set, but that didn't work.
