### ISSUE TITLE
Removal of keybindings

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#478]
So, I've been thinking quite a bit about the feature set of Kwm, and it has reached a point where it is more than a "window manager".

I've noticed that some people only use focus-follows-mouse, does not want/use keybindings or are only interested in tiling. I'm thinking it might be a good idea to factor these features into stand-alone applications, that can work together. This is imo a better structure / "philosophy".

What this might look like:

Before:
 - Kwm

After:
 - kwm, window management
 - [khd](https://github.com/koekeishiya/khd), bind management
 - ~~\<insert name>, focus-follows-mouse (autoraise)~~

Edit: So focus-follows-mouse has some special behaviour due to `standby-on-float` and so on, so that will probably have to remain as a part of Kwm.

**Comment by koekeishiya** [comment]
So I've decided that I am gonna move the hotkey functionality out of Kwm into a stand-alone application. This will require some modification to the `mouse-drag` system, but will also make it more flexible / extendable.

The main reason for this decision that the current way of defining and parsing hotkeys in Kwm is really bad and kinda annoys me (single line only..). Another problem is that when / if Kwm terminates unexpectedly, hotkeys stop working temporarily, which is also a nuisance.

See [khd](https://github.com/koekeishiya/khd) for progress. Suggestions are welcome, however I have pretty made up how I want the syntax to be.

It will be be based upon a modal system, as the current one is, and should keep the prefix support. 
I am leaning towards not including application specific hotkeys, however this is yet to be decided.

There will probably be a way to enable `kwm specific mode` such that the behaviour of changing color of the focused border depending on the active mode, will persist.

**Comment by koekeishiya** [comment]
> I am leaning towards not including application specific hotkeys, however this is yet to be decided.

Would anyone actually miss this feature if it was to NOT be implemented in *khd*?

**Comment by dominiklohmann** [comment]
> Would anyone actually miss this feature if it was to NOT be implemented in khd?

I'm still here, I requested that feature back then. I could work around it with Alfred or some Applescript, though... if you want to stop supporting because it's too much work to leave in, go ahead. Otherwise I'd really love to continue using it for some custom keymappings for certain applications.

**Comment by koekeishiya** [comment]
> if you want to stop supporting because it's too much work to leave in

It's not necessarily too much work, I just don't currently know how to get the `currently focused window` information in an efficient manner.

In Kwm this was trivial, as all that information was already cached.

**Comment by koekeishiya** [comment]
Just keeping notes for my own convenience:

> This will require some modification to the mouse-drag system, but will also make it more flexible / extendable.

This is not true, and the `mouse-drag` system does not require any modification due to these changes.

**Comment by chrishoage** [comment]
> The way I see it, that leaves basically two options.

> Option 1. Khd would have to subscribe to the didActivateApplication notification, and cache the state just as Kwm does.

> Option 2. Khd tracks the focused application through some sort of signal sent by Kwm, when it receives its notification.

If khd is meant to be a stand alone program, and not require kwm, Option 1 seems like the best solution to support app specific binds.

**Comment by koekeishiya** [comment]
> If khd is meant to be a stand alone program, and not require kwm, Option 1 seems like the best solution to support app specific binds. 

I agree that would be the correct approach.

Sidenote:
Would a `ternary operator` be useful in this context?
e.g: 

cmd + t ? [ list, of, apps ] : \<command if app in list>
                                             \<command if app not in list>

**Comment by koekeishiya** [comment]
The following has now been implemented:
```
cmd - t [ list, of, apps ] : <command> #only if in list:
cmd - t ! [ list, of, apps ] : <command> #only if not in list:
```
