### ISSUE TITLE
Whitelist rule

### ISSUE THREAD

**Issue by v4n** [koekeishiya/kwm#479]
Is there an a way to get KWM to only tile whitelisted apps e.g. iTerm 2?

I mainly use the tiling resizing with my terminals and have ended up with a bunch  of `kwmc rule owner="" properties={float="true"}` rules as most of my os x apps do not resizing nicely with KWM.

**Comment by koekeishiya** [comment]
The `owner=""` identifier can take a regexp, so you can probably make something that matches everything but "iTerm2"

**Comment by koekeishiya** [comment]
So the following rule should do it: `kwmc rule owner="(?!iTerm2).*" properties={float="true"}`

**Comment by v4n** [comment]
@koekeishiya perfect. Thanks!
