### ISSUE TITLE
No way to get list of displays outside of AXLib

### ISSUE THREAD

**Issue by akdor1154** [koekeishiya/kwm#487]
Hey, this is probably a better question for a some IM system but you are quite hard to track down!

I'm trying to implement a simple function, RemoveWindowFromOtherDisplays(), that loops through all Displays that do not have that Window in them, and calls RemoveWindowFromNodeTree on each one. This would probably clear up a lot of the strange behaviour seen when windows get moved from some other source than kwm itself (I'm aware this isn't supported, but the fact is it happens, so it would be good to cope as best as possible when it does.)

However, it looks like the list of displays is internal to axlib, and kwm doesn't have access to it. Is there any way to iterate through all current displays from the kwm side of things? I don't really want to go around punching holes in AXLib :)

Cheers
Jarrad

**Comment by koekeishiya** [comment]
You can use the following to loop through displays:

```
ax_display *MainDisplay = AXLibMainDisplay();
ax_display *Display = MainDisplay;
do
{
    // Do stuff with Display

    Display = AXLibNextDisplay(Display);
} while(Display != MainDisplay);
```

**Comment by akdor1154** [comment]
Cool, I'll amend the PR. :)
