### ISSUE TITLE
weird stuff I discovered

### ISSUE THREAD

**Issue by roylockhart** [koekeishiya/kwm#49]
oi ! I was messing with kwm because I really like it, it might replace Slate in my workflow :)  
But I noticed something strange : I lost [cli-visualizer]'s spectrum visualizer, also, mpd stream seem buggy ! The music have some little bump moments, stops and starts in ms.  
For mpd it might be something else, but for cli-visualizer I was able to reproduce it. (Confirmed, it's not kwm's fault, it's the fault of ncmpcpp's visualizer)

Thanks for kwm, gotta work on a bar now ahah

EDIT : I don't get it, is it supposed to be run with a kwm command or with ./bin/kwm ?
Plus, when I run `make` I have two warnings : 

````
g++ kwm/hotkeys.cpp  -O3 -shared -o bin/hotkeys.so
g++ kwm/kwm.cpp kwm/tree.cpp kwm/window.cpp kwm/display.cpp kwm/daemon.cpp kwm/interpreter.cpp kwm/keys.cpp  -O3 -lpthread -framework ApplicationServices -framework Carbon -framework Cocoa -o bin/kwm
kwm/window.cpp:1043:5: warning: 'GetProcessForPID' is deprecated: first deprecated in OS X 10.9
      [-Wdeprecated-declarations]
    GetProcessForPID(Window->PID, &NewPSN);
    ^
/System/Library/Frameworks/ApplicationServices.framework/Frameworks/HIServices.framework/Headers/Processes.h:930:1: note:
      'GetProcessForPID' has been explicitly marked deprecated here
GetProcessForPID(
^
kwm/window.cpp:1054:9: warning: 'SetFrontProcessWithOptions' is deprecated: first deprecated in OS X
      10.9 [-Wdeprecated-declarations]
        SetFrontProcessWithOptions(&FocusedPSN, kSetFrontProcessFrontWindowOnly);
        ^
/System/Library/Frameworks/ApplicationServices.framework/Frameworks/HIServices.framework/Headers/Processes.h:658:1: note:
      'SetFrontProcessWithOptions' has been explicitly marked deprecated here
SetFrontProcessWithOptions(
^
2 warnings generated.
````

**Comment by koekeishiya** [comment]
Regarding the warnings, that is fine, just ignore them.
To start kwm, just execute the binary located in /bin/kwm.
If you are in the projects root directory, you either hav to `cd bin`and then `./kwm`, or you can simply do `./bin/kwm` from the root directory.

Regarding the mentioned issues with cli-visualizer and mpd, could you elaborate on this.

**Comment by roylockhart** [comment]
Can I detach kwm from the window ? If I close kwm's window, the deamon stops.

Ok weird, after a restart, everything work mpd-side. Checked, double checked, was not able to reproduce :+1:

**Comment by koekeishiya** [comment]
By default you need the terminal open yes. If you add Kwm to launchd, it will automatically start the next time you log in, so a relog would be necessary the first time this is done.

Glad thinks seem to work, gonna close this then.

**Comment by roylockhart** [comment]
thanks for your help ! I made aliases and run the deamon in an hotkey window to keep it hidden.

**Comment by koekeishiya** [comment]
You could simply do `kwmc config launchd enable` and relog. This way you will not have to run it manually every time.

Also consider building using `make install` instead of make to turn off debug prints. This should give better performance.

**Comment by roylockhart** [comment]
Yeah I know, but I have tons of scripts launching when I start my mac, I don't want to have windows dancing all around at the same time haha
