### ISSUE TITLE
extended/ reduce no longer working

### ISSUE THREAD

**Issue by kylebrandt** [koekeishiya/kwm#490]
Not sure which version I was on before (master now), but the following isn't working for me anymore:
```

kwmc bindsym hyper-u window -c reduce 0.05
kwmc bindsym hyper-o window -c expand 0.05
```

Other hyper bindings still work.

**Comment by kylebrandt** [comment]
Oh I see this now:

https://github.com/koekeishiya/kwm/commit/a101e34236172c238a5de655407bd91ca79ad1c1

But I actually like the old way better, Basically I should shrink or reduce with the same set of two key bindings regardless of the rotation - any way to still configure this behavior?

**Comment by kylebrandt** [comment]
I supposed I can work around it as follows and keep to keep bindings, i.e. with:

```
kwmc bindsym hyper-u window -c expand 0.05 north
kwmc bindsym hyper-o window -c expand 0.05 west
```

I can transpose 90 2x, swap the to bottom window, change north, transpose back, swap back ... but that kind of hurts my head....

**Comment by koekeishiya** [comment]
The old behaviour can now be achieved with the "focused" selector.

```
kwmc bindsym hyper-u window -c reduce 0.05 focused
kwmc bindsym hyper-o window -c expand 0.05 focused
```

This works in a linear fashion, and reduce / expand literally means which way the 'split' moves in the interval \<0, 1>  - reduce moves towards zero, and expand moves towards 1. Thus, the reduce / expand naming does not reflect the action taken on your focused window.
It will also be limited to the parent node of the focused window.

 Unless you have very simble layouts (2-3 windows open only), I would suggest getting used to the directional versions, as they will always increase or decrease the size of the window, as stated in the command.

**Comment by kylebrandt** [comment]
Confirmed working, does it exactly what I want.

I actually do tend to have pretty simple layouts (never more than 4
windows):
 - 3x Monitors
 - Most of the things I have utilize another (layer):
    - Chrome (Tabs for each window for course)
    - Iterm (Panes)
    - Slack (Orgs and Rooms)
    - VSCode, splits, file browser

Thanks for the super fast response - this will make my week easier :)


Side note: I'd love to see a video of this in action and you explaining the
features (or images with prose etc). Might help to have a deeper
understanding for users. Although as a OS project maintainer myself, I
totally understand writing code vs guides :)
