### ISSUE TITLE
[3.1.3] Window resizing on move from primary display to the secondary one

### ISSUE THREAD

**Issue by alexfedoseev** [koekeishiya/kwm#491]
I have small issue w/ resizing window on `window -m display N`. When I move window from primary display (which is external and it's significantly bigger) to secondary (which is laptop's one), then the right side of the window is a bit off the screen (left side is ok):

![image](https://cloud.githubusercontent.com/assets/4244251/18844446/d5f7574c-844f-11e6-8862-effb6880b6d4.png)

Minimize/restore usually triggers re-resize and it fixes the issue.
If I move in reverse direction — everything works fine.

Placement:

![screen shot 2016-09-27 at 01 26 33](https://cloud.githubusercontent.com/assets/4244251/18844813/81c7cfa6-8451-11e6-94fb-07420ad8fb93.png)

macOS: 10.11.6
My config: https://github.com/alexfedoseev/dotfiles/tree/master/.kwm

**Comment by koekeishiya** [comment]
I've noticed this with some applications as well (specifically Mail), without the need for them to be moved across displays.

I'm not completely sure what causes it to happen.

**Comment by alexfedoseev** [comment]
> I've noticed this with some applications as well (specifically Mail)

In my case it's every app (tested w/ Slack, Skype, 1Password, Chrome etc)

**Comment by alexfedoseev** [comment]
Upgraded to `4.0.4` recently and looks like it's solved. Closing.
