### ISSUE TITLE
[3.1.3] Switch between subtrees

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [koekeishiya/kwm#492]
I have two subtrees

```
---------------------   
|         |         |   
|    1    |    3    |   
|    |    |    |    |   
|    2    |    4    |   
|         |         |   
|         |         |   
|         |         |  
--------------------- 
```

2 is active. I change active window to right subtree and switch back, 1 is now active. I would really prefer that I could switch back to previously active window in left subtree instead of root. Is it possible?

Also window -f prev/next cycles between windows, -fm don't. It would be convenient to also cycle windows in subtree.

I'm using version 3.1.3 with macOS Sierra.
Thanks.

**Comment by koekeishiya** [comment]
The `window -fm ..` command is now also affected by the `cycle-focus` option.

> 2 is active. I change active window to right subtree and switch back, 1 is now active. I would really prefer that I could switch back to previously active window in left subtree instead of root. Is it possible?

This is tricky to do because we select the window based on minimum distance from our current window, and don't really have access to what kind of a container that window is stored in.

**Comment by koekeishiya** [comment]
I'll be closing this issue and creating a new one for the remaining part, to keep it up to date.
