### ISSUE TITLE
calling CloseBorder after mouse-drag, causes a hang

### ISSUE THREAD

**Issue by akdor1154** [koekeishiya/kwm#493]
CloseBorder hangs kwm, it appears that currently it's never actually called, but I'm trying to use it while implementing mouse resizing.
Something to do with closing pipes and waiting on subprocess, oh my! I've been looking at this for the past four hours and it's giving me a headache, hopefully the solution is simple and I'm just missing it...

**Comment by koekeishiya** [comment]
Uh, this was not a problem pre-xcode8 (swift3)

**Comment by cHoco** [comment]
Can you try this diff?

``` diff
diff --git a/kwm-overlay/kwm-overlay.swift b/kwm-overlay/kwm-overlay.swift
index f0e9c3c..600cf9b 100644
--- a/kwm-overlay/kwm-overlay.swift
+++ b/kwm-overlay/kwm-overlay.swift
@@ -214,12 +214,12 @@ class OverlayController: NSObject, NSApplicationDelegate
             if (data.count > 0) {
                 if let str = NSString(data: data, encoding: String.Encoding.utf8.rawValue) as String? {
                     str.enumerateLines { (line, stop) -> () in
-                        let trimmedString = trim(line);
+                        let trimmedString = trim(line)
 
                         if (trimmedString == "clear") {
                             self.window.contentView = nil
                         } else if (trimmedString == "quit") {
-                            exit(0)
+                            NSApplication.shared().terminate(nil)
                         } else {
                             let args = trimmedString.components(separatedBy: " ")
                                 self.showOverlayView(args)
```

**Comment by koekeishiya** [comment]
confirmed, the diff solved the problem.

**Comment by koekeishiya** [comment]
It appears that simply removing the semicolon was enough. It works as expected with the shared().terminate() instead of exit() though.

**Comment by akdor1154** [comment]
Are the drag event handlers performed in a different thread? Because that's where I was calling CloseBorder myself.

**Comment by akdor1154** [comment]
A possibly way of working around this (with nuclear-bomb levels of overkill)  - I am currently playing with building a swift file as dylib, and linking it directly to a C program, with initially pleasing results. Would you consider a PR that overhauled kwm_overlay to be a library called like this? I'm aware this is excessive for just this one bug. :)

**Comment by koekeishiya** [comment]
> Are the drag event handlers performed in a different thread?

Indeed they are.

> even though the POSIX standard reckons they are to be thread-safe.

I assumed this was the case. Apparently not?

Anyway, this is something that deserves a proper fix within Kwm.
There are tons of other changes I want to make as well, regarding 
the program flow, when I have enough time to get started.

**Comment by cHoco** [comment]
Can you post code/steps to reproduce? Maybe I can take a look.
