### ISSUE TITLE
Introduce "disable auto-raise window" and "auto-raise delay"

### ISSUE THREAD

**Issue by thonixx** [koekeishiya/kwm#494]
I am asking for an enhancement of kwm regarding auto-raise. It would be nice to have an option to delay the auto-raise function so the windows does not pop up instantly and rather after half a second or so (option with ability to set miliseconds for auto-raise). Or maybe it would be good to turn off auto-raise completely but I think it would be better to have an option for a delay.

**Comment by chrishoage** [comment]
Duplicate of #476

**Comment by thonixx** [comment]
I will close this as I have put in my thoughts on #476 (it had a title which did not seem to me the same issue so I created a new one, sorry ;))
