### ISSUE TITLE
tested with macOS Sierra?

### ISSUE THREAD

**Issue by codecheffy** [koekeishiya/kwm#499]
Has this been tested with macOS Sierra? Not sure if kwm caused it, but some of the boot files got messed up.

**Comment by fabean** [comment]
I'm currently running this on Sierra. I'm a complete noob at this as I just downloaded this today but I can tell you tiling & mouse follow work completely fine. I'm currently struggling to get keyboard shortcuts working but not sure if that's Sierra or just me.

**Comment by codecheffy** [comment]
@fabean does your mac go to sleep and shutdown properly after you installed kwm?

**Comment by fabean** [comment]
@codecheffy I can test that after work today, but you're asking me to shutdown a computer which isn't something I'd normally do 😛

**Comment by codecheffy** [comment]
@fabean haha yea, i don't do that too often either. Trying to figure out if it's a kwm issue or if it was an upgrade to sierra issue.

**Comment by koekeishiya** [comment]
> Has this been tested with macOS Sierra? Not sure if kwm caused it, but some of the boot files got messed up.

Kwm does not touch any system files. Actually it doesn't touch anything on the filesystem at all, except for its own config file.

I personally haven't upgraded to Sierra yet, but that does not matter in this case.

**Comment by fabean** [comment]
@codecheffy I know @koekeishiya already chimed in but I wanted to let you know sleeping and restarting work fine for me.

**Comment by sinoforever** [comment]
How did you fix your key bindings? I've put my kwmrc at $HOME/.kwm/ and brew restarted, but it doesn't seem to recognize keystrokes.

**Comment by dominiklohmann** [comment]
> but it doesn't seem to recognize keystrokes.

The keybindings functionality has been moved over to https://github.com/koekeishiya/khd

**Comment by orlandini** [comment]
@fabean How did you get keybindings to work? I feel like I am in the same situation that you were!
