### ISSUE TITLE
Restarting crashes Kwm

### ISSUE THREAD

**Issue by a-morales** [koekeishiya/kwm#5]
Running `kwmc restart` crashes `Kwm` with the error being that the daemon could not be started. This is for `Kwm 1.0.0 Beta 5`

**Comment by koekeishiya** [comment]
Ah yeah I forgot to remove this functionality. Currently there is no real reason to have the restart option anymore in my opinion. Is there any specific reason why you need this option?

**Comment by a-morales** [comment]
No specific reason, was just playing with `Kwmc` to see how I can configure it with `Hammerspoon`. I ran  the commands for `Kwmc` to see what they do and came across the crash

**Comment by koekeishiya** [comment]
Alright, thanks for letting me know, although I will probably remove that command in the future.
You also might want to clone the master branch and compile from there as well, as there have been some updates to what kind of operations you can perform on the window-tree that are not available in the Beta 5.

**Comment by a-morales** [comment]
I am running the master branch. I have a script I run every morning to keep everything up to date, including `Kwm`

**Comment by koekeishiya** [comment]
Aight sounds good. Keep opening issues if you come across any problems, or a feature that you think could be useful. I really appreciate it.

**Comment by koekeishiya** [comment]
KwmRestart is no longer a thing. Replaced with KwmQuit.
Closing.

-- Koe
