### ISSUE TITLE
launchd issues

### ISSUE THREAD

**Issue by dathinaios** [koekeishiya/kwm#50]
Hello :)

First of all thanks for making this. Very useful!

I had everything working fine when I am running `kwm` from the terminal but the daemon was not working which made it very awkward to use. I followed the instructions but the plist file was not moved to `~/Library/LaunchAgents` (`kwm` printed the `mv` standard instructions when it failed). In the end I just copied it manually and everything is working fine.

I see browsing the issues that there are a few people suggesting homebrew to streamline the installation process and I do want to voice my +1 towards this. In my opinion, even if the issue I am experiencing is resolved it is really awkward (and wrong from a security perspective) to have to give access to the terminal to accessibility and then return to it again and give access to `kwm` (and remember to untick the terminal access).

Best wishes,

Dionysis

**Comment by koekeishiya** [comment]
I agree that giving the entire terminal permissions for the accessibility APIs to run Kwm is bad. Being able to use homebrew for installation and removing the launchd-code would be a welcomed change, just waiting for the people that suggested it to proceed with the brew formula.

I'm not completely sure why it failed to move the generated plist file, however this part of the code will be removed when an installation through homebrew has been accepted, so I doubt that a fix will be made.

It's pretty amazing how many people seem to like Kwm, even in its current state. Development has only been going on for about 2 and a half month or so. I'm hoping to be able to add quite some features still, but it is limited what can be done within the restrictions of OSX. The current functionality of Kwm has surpassed any expectations I had when I first started.

**Comment by dathinaios** [comment]
Good to know that the project is going towards the direction of using Homebrew. In that case as you said there is no need to look into the issue I had.

Keep up the good work!

**Comment by Alok** [comment]
@koekeishiya  I think the reason for `kwm's` popularity is that it is really easy to set up and OSX has no good tiling window managers. Amethyst, mjolnir, and Hammerspoon are rather trickier to get their window managing working.
