### ISSUE TITLE
What is the purpose of monocle subtrees?

### ISSUE THREAD

**Issue by antoine1fr** [koekeishiya/kwm#500]
I don't understand the purpose of monocle subtrees? I can't find much information about them in the documentation.

What are the use cases from a user perspective?

**Comment by cHoco** [comment]
For example on smaller screen monocle subtree can be really usefull, you got hald of the screen for an app and then use the other half as monocle subtree and switch between the windows in this other half taking full advantage of the container size.

Everyone has their own usecases, you don't have necessarily have to use all features! Different needs call for different solutions.
