### ISSUE TITLE
[3.1.3] Move window to space hides window

### ISSUE THREAD

**Issue by carymrobbins** [koekeishiya/kwm#501]
When using the `window -m space` command, I often have issues with the window becoming completely inaccessible. Here's my exact config -

```
kwmc bindsym mod2-, window -m space left
kwmc bindsym mod2-. window -m space right
kwmc bindsym mod2-1 window -m space -fExperimental 1
kwmc bindsym mod2-2 window -m space -fExperimental 2
// ...
```

One workaround is to get focus of the window by using <kbd>⌘</kbd>+<kbd>tab</kbd> then toggle fullscreen mode. Unfortunately, this doesn't seem perfect as focus seems stuck on Finder for a while.

**Comment by koekeishiya** [comment]
> kwmc bindsym mod2-1 window -m space -fExperimental 1
kwmc bindsym mod2-2 window -m space -fExperimental 2

should be

```
kwmc bindsym mod2-1 window -m space 1
kwmc bindsym mod2-2 window -m space 2
```

**Comment by carymrobbins** [comment]
Oh ok, so `-fExperimental` is only for moving focus between spaces. Thanks!
