### ISSUE TITLE
Ctrl + HJKL arrows stopped working

### ISSUE THREAD

**Issue by scottgrayson** [koekeishiya/kwm#502]
This is probably not KWM (3.1.3) related, but maybe someone knows where the problem may be.

After upgrading to Sierra and losing the vim mappings i had with Karabiner. I wrote some applescripts to be triggered by KWM. They were working for about a month then the ctrl+hjkl stopped working after a computer restart.  The next block of hyper+hjkl shortcuts still work though.

```
//  --------------- hjkl settings {{{

kwmc bindsym ctrl-h exec osascript ~/.applescripts/left-arrow.scpt
kwmc bindsym ctrl-j exec osascript ~/.applescripts/down-arrow.scpt
kwmc bindsym ctrl-k exec osascript ~/.applescripts/up-arrow.scpt
kwmc bindsym ctrl-l exec osascript ~/.applescripts/right-arrow.scpt

kwmc bindsym hyper-h exec osascript ~/.applescripts/home-key.scpt
kwmc bindsym hyper-j exec osascript ~/.applescripts/page-down.scpt
kwmc bindsym hyper-k exec osascript ~/.applescripts/page-up.scpt
kwmc bindsym hyper-l exec osascript ~/.applescripts/end-key.scpt

// }}}
```
left-arrow.scpt
```
tell application "System Events"
key code 123
end tell
```

Version 3.1.3

**Comment by scottgrayson** [comment]
Reinstalling that Karabiner-Elements fixed my problem. Maybe i should start doing all my key remaps in KWM and applescripts instead of Karabiner!

**Comment by koekeishiya** [comment]
Applescripts should not be necessary. You can do `kwmc press <some key combination>`

Also I take it you have not yet seen #478., in short, keybinding system in Kwm is deprecated in favour of https://github.com/koekeishiya/khd

**Comment by scottgrayson** [comment]
Thanks for the quick response. i'm still having the problem actually. i thought it was momentarily fixed after reinstalling Karabiner, but it is not. I'll try replacing karabiner-elements with khd
