### ISSUE TITLE
Should overlay border change to mode color when activating mode via khd? [kwm 4.0.2] [khd 1.1.0]

### ISSUE THREAD

**Issue by acmcelwee** [koekeishiya/kwm#505]
First, thanks for making the best tiling WM for macos. I just switched from kwm 3.1.3 to the latest released kwm + khd and converted my configs over, but I don't see the overlay color change until I change window focus, either via mousing to a new window w/ focus-follows-mouse or via kwm focus navigation via khd binds. I have kwm compatibility mode turned on via `khd kwm on`. Is this expected behavior, or maybe just some missing functionality after the overlay rewrite?

**Comment by cHoco** [comment]
Can you post your kwmrc and khdrc?

**Comment by acmcelwee** [comment]
I think it was a path issue where I had a mixed environment of old and new things binaries around. I don't know the exact point it all started working, though, so it's hard to say if it was a config change or path conflicts that got it going. All is working as expected now.
