### ISSUE TITLE
[master] Mouse drag functionality flipped

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#506]
mouse drag is always enabled, and to click in windows i have to hold down the mouse-drag mod

**Comment by koekeishiya** [comment]
Hm works the same as previously for me.. weird.
I'm still on El Capitan though.

**Comment by dominiklohmann** [comment]
Mouse drag works for me on Sierra as well. Seems really weird that it's flipped, maybe some conflict with the khd/kwm configs?

**Comment by matthewdias** [comment]
that's the only thing i can think of, but im not mapping the mod itself to anything in khd. it's just combined with keys

**Comment by koekeishiya** [comment]
Any update on this?

**Comment by matthewdias** [comment]
Still getting the same bug with
```
kwmc config mouse-drag on
kwmc config mouse-drag mod rctrl
```
It doesn't happen with other mods tho. Must be a conflict with Karabiner-Elements.

**Comment by koekeishiya** [comment]
I don't think I actually added separate r/l modifiers in Kwm, so that is probably it.

**Comment by matthewdias** [comment]
ah right. support is in for the others but not ctrl. mind if I reopen that pr, or would you prefer to leave it as is?

**Comment by koekeishiya** [comment]
Feel free to reopen #484. Due to the mouse-drag system that is probably something that should be supported in Kwm as well.

**Comment by matthewdias** [comment]
Alright I updated that pull, and mouse-drag with rctrl is fixed 👌

**Comment by koekeishiya** [comment]
Would you mind doing a rebase before the merge?

Thanks.

**Comment by matthewdias** [comment]
done 😅

**Comment by koekeishiya** [comment]
Merged, thanks!
