### ISSUE TITLE
Update to 4.0.2 breaks keybindings/padding etc.

### ISSUE THREAD

**Issue by webgefrickel** [koekeishiya/kwm#509]
I installed kwm via homebrew, and recently just updated every brew package, including kwm. Now, tiling is still working, but none of my keyboard-shortcuts and/or globally assigned var seem to do so any longer. My config can be found here: https://github.com/webgefrickel/dotfiles/blob/master/kwm/kwmrc

Is there some kind of a changelog (or migration guide) what breaks from v3 to v4?

Thanks a lot!

**Comment by dominiklohmann** [comment]
See https://github.com/koekeishiya/kwm/issues/478 and https://github.com/koekeishiya/khd.

tl;dr Keybindings have been moved to a separate application called khd, while kwm is now for window management only.

**Comment by webgefrickel** [comment]
Ah, thanks a lot. This seems like a nice weekend project, convertig config files ;)

**Comment by koekeishiya** [comment]
Regarding changelog, I always post changes in the releases section: https://github.com/koekeishiya/kwm/releases

I use semantic versioning more or less, so it should be straightforward when an update will break configurations.
