### ISSUE TITLE
Bitbar Enhancement

### ISSUE THREAD

**Issue by hhsnopek** [koekeishiya/kwm#51]
Hey!

Just thought of this - we could easily have a [bitbar](//github.com/matryer/bitbar) plugin that could display positions. I was thinking a list version for displaying the orders of windows, similarly the plugin could display the current mode kwm is in.

It has endless possibilities :smile:

**Comment by koekeishiya** [comment]
I'll look into adding some kwmc commands to get a list of the window order during monocle mode.
`kwmc focused` already does show what mode kwm is in for the current space, e.g: "[bsp] Application - Title". Haven't looked at bitbar yet since I still use nerdTool, however all you have to do really is make bitbar show the output of this command.

**Comment by chrishoage** [comment]
I have thrown this together. It allows you to set the space to bsp, monocle, and float. It also lets you reload the config and quit kwm. 

https://gist.github.com/chrishoage/4a767c064bbd75f65d58

<img width="184" alt="screen shot 2016-01-10 at 7 00 02 pm" src="https://cloud.githubusercontent.com/assets/1056886/12226150/62ff9c5e-b7cc-11e5-87c4-011f1c3549d5.png">


It assumes you have kwmc at `$HOME/bin/kwmc` if you do not update that line before use.

**Comment by koekeishiya** [comment]
See `kwmc help read`, added some things I figured could be useful. Let me know if you'd like access to more and I'll see what can be done

**Comment by koekeishiya** [comment]
A bitbar plugin is not something that I will be making myself, as I'm quite happy with using Übersicht, however if you need access to information that Kwm stores for something, so that youl can utilize that in bitbar or something similar, I am open to suggestions.
