### ISSUE TITLE
[master] Extend center-on-float to work with windows floating because of a rule and float-non-resizable

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#510]
`center-on-float` currently does not apply to windows floating because of a rule (e.g. `kwmc rule owner="Mail" name="" properties={float="true"}`) or because of `float-non-resizable`.

**Comment by koekeishiya** [comment]
Uh, I have not confirmed this, but sounds like a bug if this doesn't work.

**Comment by dominiklohmann** [comment]
For what it's worth, the `float-dim` setting doesn't work with them either.

**Comment by koekeishiya** [comment]
> For what it's worth, the float-dim setting doesn't work with them either.

Note: The float-dim setting will only apply to resizable windows.
Non-resizable windows will be given (x, y) -> (width / 4, height / 4)

**Comment by dominiklohmann** [comment]
Makes sense, not sure what I was thinking there back in October. 

Thanks for the fix! 👍

**Comment by koekeishiya** [comment]
So due to #555 I suppose windows affected by float-non-resizable should not conform to this.
