### ISSUE TITLE
[master] Faulty AXEvent_DisplayChanged

### ISSUE THREAD

**Issue by choco** [koekeishiya/kwm#516]
Not sure if this is related to https://github.com/koekeishiya/kwm/issues/511 but I've seen the above happens only when the callback mentioned in the title was triggered.
Basically when some application (mainly games), take control of the screen (game goes fullscreen, must be different kind of fullscreen :/) a AXEvent_DisplayChanged is triggered, even though the display doesn't change.
I think a basic check at the beginning  

```
    ax_display *current_main_display = AXLibMainDisplay();
    if( current_main_display->ID != FocusedDisplay->ID ) {
```

to make sure the display actually changed should be enough.

**Comment by koekeishiya** [comment]
Applied suggested fix, Thanks.
