### ISSUE TITLE
[master] Weird borders

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#519]
For some reason that I have yet to identify, there will be borders drawn when inbetween a space transition. After a transition ends, these borders disappear and only the focused border remains (as expected).

These borders also persist after the focused and marked border has been disabled.

This causes huge lag when trying to perform space transitions using gestures.

**Comment by cHoco** [comment]
I think the cause of this is that borders aren't getting reused, i.e. each time we change space a new borders is created.

**Comment by akdor1154** [comment]
I'm happy to look into this (it might be my code causing the problem!) - I'm a bit confused by the report though. 
When I do a space transition (e.g. go to space left) with keystroke, I see the active border disappear from the old space, and re-appear in the same position on the new space at the beginning of the transition. At the end of the transition, the border resizes to the active window on the new space. No other borders are visible throughout this.
This doesn't seem much like what you are describing. Is it easy to upload a screencast or something?

**Comment by chrishoage** [comment]
You appear to be using a keystroke

> When I do a space transition (e.g. go to space left) with keystroke

The ticket describes the issue is with gestures

> This causes huge lag when trying to perform space transitions using gestures.

Could that be the reason you have trouble repoing the issue @akdor1154?

**Comment by akdor1154** [comment]
just tested with a gesture (three finger swipe on mbp trackpad) and behaviour is the same as I described before.

**Comment by koekeishiya** [comment]
![screen shot 2016-11-07 at 15 10 46](https://cloud.githubusercontent.com/assets/6175959/20060654/78176b1c-a4fc-11e6-81ba-3949cecbf4cf.png)

**Comment by koekeishiya** [comment]
So I can reproduce this by transitioning to an empty space and going back to some other space. There will now be 1 additional border.

**Comment by koekeishiya** [comment]
Unable to reproduce in version 4.0.4
