### ISSUE TITLE
Remember window position+size when switching between fullscren <-> btree

### ISSUE THREAD

**Issue by dvcrn** [koekeishiya/kwm#523]
I love the ability to quickly switch between monocle/fullscreen mode and btree, however one annoying thing is that kwm doesn't remember the previous layout. 

If I resize windows in btree, then switch to fullscreen and back to btree, it tiles the windows from scratch which resets window sizes and position. 

Is it possible to remember this information? I'm also happy to help with trying to implement this if you could poke me into the right direction. 

Using version 4.0.1

**Comment by chrishoage** [comment]
Any reason to not just fullscreen a window in your bsp tree? that way when the window exists fullscreen your bsp tree remains intact.

**Comment by dvcrn** [comment]
@chrishoage I didn't know that was possible to be honest. Let me give t a try! 

Still I think it would be great if kwm could retain the previous layout, even if optional

**Comment by koekeishiya** [comment]
> Still I think it would be great if kwm could retain the previous layout, even if optional

It is possible to do this (no idea how much work it would be though), but I don't really see this as a necessity. 

The zoom options (`kwmc window -z ..`), specifically  `kwmc window -z fullscreen` was added for this exact purpose. Often when in a bsp-layout, you want to focus on just a single window, but only temporarily.

**Comment by dvcrn** [comment]
I tested the fullscreen bsp option and am happy with it. Thanks for making me aware of it, I am closing this issue.
