### ISSUE TITLE
[master] Float next window to be created on space

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#525]
There are still some tiling issues with some applications preference windows (see #481 for an example). This could be solved by adding a command that makes the next window to be created on the current space floating when it spawns. 

This way, you could create the following keybinding in khd:
```
cmd - , [ Safari ] -> : kwmc float-next-window
```

**Comment by koekeishiya** [comment]
The existing command to toggle the float status of a window is `kwmc window -t focused`.
I have added `kwmc window -t next` to make the next window be treated as floating.

**Comment by dominiklohmann** [comment]
> Would you prefer this 'flag' to reset upon a space-transition? 

My only use case for the functionality is for pass-through `cmd-,` mapping, so I don't really mind either option. I think resetting upon transitioning feels more natural, though.

Thanks for implementing this! 👍

**Comment by dominiklohmann** [comment]
This fix has now been released. I ended up adding this to my `.khdrc` to fix the issue:

```
cmd - 0x2B [ Safari ] -> : kwmc window -t next
```
