### ISSUE TITLE
[4.0.2] Right click menu on Dock disappears if it's over iTerm.

### ISSUE THREAD

**Issue by simonsmith** [koekeishiya/kwm#526]
If I have iTerm open and I right click on the Dock, as I move my mouse over the menu it is closed straight away. This does not seem to happen with other apps.

Trying to right click on a Dock item with iTerm present
https://cl.ly/i1eq

Same issue on the top bar with CloudApp:
https://cl.ly/i1iE

I tested with Finder and iTerm side by side and only the dock on the left over iTerm app has a problem:
<img width="543" alt="screen shot 2016-11-07 at 14 33 17" src="https://cloud.githubusercontent.com/assets/360703/20061346/6f7fb8ba-a4f7-11e6-8a52-3ee7f38c9ce2.png">

**Comment by chrishoage** [comment]
![screen shot 2016-11-07 at 9 51 44 am](https://cloud.githubusercontent.com/assets/1056886/20069051/d5986430-a4cf-11e6-8249-543e8242a1ec.png)


I think there might be more to this issue. I am not able to reproduce it with 10.11.6 and kwm 4.0.2

**Comment by simonsmith** [comment]
Sorry, I forgot to mention I'm on Sierra, but I did see this issue before upgrading

**Comment by dominiklohmann** [comment]
I cannot reproduce this issue on Sierra (10.12.1).

Do you happen to have iTerms own window management functionality enabled?

**Comment by choco** [comment]
Cannot reproduce either :(
Just a random test, can you enable titlebar on iTerm in styles and restart it and see if you can still reproduce the issue?

**Comment by simonsmith** [comment]
Issue still remains. I'm using iTerm 3.0.12 as well. How odd that none of you can reproduce. This issue has persisted to a new Mac with Sierra. Perhaps it's something I have configured in iTerm.

My KWM config is here - https://github.com/simonsmith/dotfiles/blob/master/dots/kwmrc

**Comment by dominiklohmann** [comment]
> kwmc config focus-follows-mouse off

Do you have focus-follows-mouse enabled in iTerm? I know from my own experience that it works well with both enabled, but I'm not sure how well this works when it's disabled in Kwm.

![screen shot 2016-11-07 at 8 05 58 pm](https://cloud.githubusercontent.com/assets/4488655/20071659/9e41b77e-a525-11e6-8f59-8ce446815bba.png)

**Comment by simonsmith** [comment]
@dominiklohmann That was it! Great suggestion.

I think that setting was there from when I did use `focus-follows-mouse` as it allowed movement between iterm windows.
