### ISSUE TITLE
Shouldn't "reduce" and "expand" work regardless of orientation?

### ISSUE THREAD

**Issue by MaiaVictor** [koekeishiya/kwm#529]
The command "expand x north" only works if you're focusing the southmost split, for example. In a way, those commands:

    cmd + alt - h               :    kwmc window -c expand 0.05 west
    cmd + alt - j               :    kwmc window -c expand 0.05 south
    cmd + alt - k               :    kwmc window -c expand 0.05 north
    cmd + alt - l               :    kwmc window -c expand 0.05 east

    cmd + shift + alt - h       :    kwmc window -c reduce 0.05 west
    cmd + shift + alt - j       :    kwmc window -c reduce 0.05 south
    cmd + shift + alt - k       :    kwmc window -c reduce 0.05 north
    cmd + shift + alt - l       :    kwmc window -c reduce 0.05 east

Take up 8 hotkeys. They could be greatly simplified by having just two commands, "expand" and "reduce", which would expand/reduce the focused window regardless of its split/orientation.

**Comment by choco** [comment]
You should use these then
```
kwmc window -c reduce 0.05 focused
kwmc window -c expand 0.05 focused
```

**Comment by MaiaVictor** [comment]
I guess I misinterpreted the command. Makes sense. Thanks!

**Comment by choco** [comment]
Yeah, we need to work on a better documentation :> glad I could help 👍

**Comment by MaiaVictor** [comment]
Maybe just change that part on the default configuration file? Expect if there is an use case for those 8 hotkeys but I'm not sure what it would be?

**Comment by choco** [comment]
Well, they actually do slightly different things. It is far easier to understand the difference if you try yourself by creating 4-5 five windows. Basically with `focused` you resize the split ration of the container the window you're inside. With the others you can do that, but also resize the outer container split ratio.
