### ISSUE TITLE
Starting a mouse-drag inside a window and ending it outside, without moving the window, causes kwm to float the window

### ISSUE THREAD

**Issue by oetting** [koekeishiya/kwm#53]
I guess kwm thinks the window is being dragged. Could for example be reproduced by dragging the scroll bar, and releasing the mouse button while the mouse is outside the window being scrolled.

**Comment by koekeishiya** [comment]
Aye, nothing I can do about this due to technical limitations. Just disable the option through config if this is annoying (I dont really use this feature myself either, I find a hotkey to be more useful)

**Comment by oetting** [comment]
Thanks

**Comment by koekeishiya** [comment]
Kwm now checks for actual window-movement and not just a "mouse-down -> mouse-up" sequence.
