### ISSUE TITLE
Docs up to date?

### ISSUE THREAD

**Issue by alex-wilmer** [koekeishiya/kwm#533]
Installed via brew today (Nov.15 / 2016)

was the `~/,kvm` folder supposed to created for me? I made it but then I don't have the `init` script.

When running the kwmc commands nothing seems to happen? Also it's hard to tell what padding, gap are meant to do. I think screenshots or a gif would help a lot.

Also is this the default setting? Really I would just like the edges (is that gap?) to go away. some windows seem to stretch beyond the bottom of the screen, not sure why.

I'd be happy to do a PR on the docs to make it easier for others once I figure some of this stuff out

<img width="1440" alt="screen shot 2016-11-15 at 9 46 27 pm" src="https://cloud.githubusercontent.com/assets/2880089/20332908/0d395350-ab7d-11e6-8f8e-22b58c7fc1b7.png">

**Comment by z3t0** [comment]
@alex-wilmer yes those edge "gaps" are padding and can be found [here](https://github.com/koekeishiya/kwm/blob/master/examples/kwmrc#L39)

Feel free to ask more questions and I will try and respond with the necessary information

**Comment by alex-wilmer** [comment]
Thanks for getting back so soon.

what's the correct procedure for changing this value?

running `kwmc config padding 0 0 0 0` from the command line doesn't throw an error but also doesn't change anything.

**Comment by dominiklohmann** [comment]
> Running `kwmc config padding 0 0 0 0` from the command line doesn't throw an error but also doesn't change anything.

Change the setting in your config file and then reload Kwm. It doesn't update automatically.

> was the ~/.kwm folder supposed to created for me? I made it but then I don't have the init script.

`brew info kwm` shows this information:
```
==> Caveats
Copy the example config from /usr/local/Cellar/kwm/4.0.2/kwmrc into your home directory.
  mkdir -p ~/.kwm
  cp /usr/local/Cellar/kwm/4.0.2/kwmrc ~/.kwm/kwmrc

To have launchd start koekeishiya/kwm/kwm now and restart at login:
  brew services start koekeishiya/kwm/kwm
```

You should probably read [the documentation](https://koekeishiya.github.io/kwm/kwmc.html). It is very sparse, but it does exist.

**Comment by alex-wilmer** [comment]
I did read the docs. Maybe I'm sleepy but some things don't seem clear.

> Kwm can apply all of these settings during runtime, and so live testing of options is possible before writing them into the config file.

I think amending the Install instructions to mention unlocking / adding accessibility controls to kwm is necessary for the daemon to start. I didn't notice the popup until I switched to a window that wasn't full screened. 

As I mentioned above, screenshots and gifs would make some of these things more clear (ie, what is gap vs padding?)

**Comment by dominiklohmann** [comment]
> Kwm requires access to the OSX accessibility API.

Quoted straight from the projects README. 

> As I mentioned above, screenshots and gifs would make some of these things more clear (ie, what is gap vs padding?)

What do you not understand about the difference between gap and padding? They do exactly what the words suggest. Also the example configuration file contains more information:

```
# Set default values for screen padding
kwmc config padding 40 20 20 20

# Set default values for container gaps
kwmc config gap 15 15
```

**Comment by alex-wilmer** [comment]
Ok sorry ~~ I'm going to take a fresh look in the morning. If I have some suggestions for improvements I'll come back here. Thanks for the help

**Comment by jcrben** [comment]
I downloaded this and tried to give it a shot, but the docs were so unclear that I couldn't get anything to happen. It seems that the default config defines no keyboard shortcuts. The README says that I "can" use `khd` to get shortcuts, but what does this give me without shortcuts? Typing `kwmc config` gives me the message `Connection failed!`. (running `v4.0.4` for brew)

Also, when it says that the Accessibility API is required, does that mean I need to somehow add it to the list?
![image](https://cloud.githubusercontent.com/assets/5614134/22856347/4dd9be48-f044-11e6-960b-3a414d1ef3db.png)
