### ISSUE TITLE
Disable all features except focus-follows-mouse?

### ISSUE THREAD

**Issue by bitpusher-real** [koekeishiya/kwm#534]
I'd like to use kwm for the focus-follows-mouse feature only, with all other tiling/management functionality disabled. Is there a way to do that?

**Comment by z3t0** [comment]
Just an idea, not sure what this will achieve exactly though. Maybe set the tiling mode to float and see what happens?

**Comment by chrishoage** [comment]
```
kwmc config tiling float
kwmc config focus-follows-mouse on
```

in your kwmrc file will do what you want.

**Comment by koekeishiya** [comment]
Answered by chrishoage-
