### ISSUE TITLE
[master] mouse-follows-focus not working?

### ISSUE THREAD

**Issue by choco** [koekeishiya/kwm#535]
I never use mouse-follows-focus before but today I tried turning it on and it doesn't work.
Can anyone else confirm? I don't know if it's an issue with master or a new one introduced in Sierra.

**Comment by koekeishiya** [comment]
Works fine for me. Still on El Capitan.

**Comment by koekeishiya** [comment]
> Works for me with the built-in focus change commands. However, I cannot get it to work when alt-tabbing between applications on the same space.

This is intended behaviour.

**Comment by chrishoage** [comment]
>  I cannot get it to work when alt-tabbing between applications on the same space.

IIRC this was an intentional decision to allow the mouse to access dialogs that might appear below a window of a different applicaiton

**Comment by dominiklohmann** [comment]
TIL. Never used that feature before, it always seemed quite annoying to me to be honest. In that case it seems to work as intended on Sierra for me.

**Comment by choco** [comment]
Is it supposed to work when alt-tabbing across displays? That was the use case I had in mind.

**Comment by chrishoage** [comment]
IIRC `mouse-follows-focus` should only be triggered when using kwm to do a focus change. 

Let me try and pull up the ticket

**Comment by koekeishiya** [comment]
I'm gonna close this as intended behaviour. Feel free to open a new issue for discussion regarding modification of this behaviour
