### ISSUE TITLE
[master] Change color of border for different modes

### ISSUE THREAD

**Issue by Linuus** [koekeishiya/kwm#536]
Is it possible to change the border colours for different tiling modes? Sometimes I'm in bsp and switch to floating because some config window or something behaves weirdly in bsp. Then I forget that I'm in floating mode because I suck.

It would be cool if the it was possible to change the border colour (or some other indicator) of what mode is currently present.

(I know it's possible to add Ubersicht, nerdbar and so on and print the mode there but I'd like to avoid that if possible)

**Comment by chrishoage** [comment]
This isn't _quite_ what you're asking for, but I have made a [bitbar](https://getbitbar.com/) script that allows for some toggles and shows the current spaces tag. 

Looks like this: 

![screen shot 2016-11-23 at 10 24 30 am](https://cloud.githubusercontent.com/assets/1056886/20573940/0db6f702-b167-11e6-9a28-437ef3394382.png)

Here is the script:

https://gist.github.com/chrishoage/c06b3f864dbb9e1e637206d8799d1133

**Comment by Linuus** [comment]
@chrishoage that looks great! Thanks!

**Comment by Linuus** [comment]
With that bitbar script I don't need this request anymore, so I'll close it :)
