### ISSUE TITLE
Add --HEAD flag to brew installation options

### ISSUE THREAD

**Issue by Feliix42** [koekeishiya/kwm#537]
I just noticed that the annoying bug #524 was finally fixed. First: Thanks for that! 🙂 

I straightly went over to my terminal and tried to update my kwm via brew, just to notice that I can't pass the `--HEAD` flag during installation.
I would love to see that feature!

**Comment by chrishoage** [comment]
kwm requires a codesigned binary to work properly, with out being codesigned you would have to "approve" accessibility access every time you updated kwm though brew when complied with `HEAD`. 

It is not feasible to be able to allow the `--HEAD` option though brew. 

You can check out the repo and buildit your self and uninstall in from brew though.

**Comment by koekeishiya** [comment]
Pretty much what chrishoage said. I don't think a --head flag in brew is necessary.
