### ISSUE TITLE
new-ish kwm install, shift and cmd click no longer work

### ISSUE THREAD

**Issue by er0ck** [koekeishiya/kwm#538]
love kwm, thanks so much!!
running version 4.0.2

mostly the same config all around as:
https://github.com/koekeishiya/dotfiles/blob/master/kwm/binds

i tried commenting out the shift-1,2,3 settings, but it didn't help.

ideas?  these work fine when i stop kwm.

**Comment by chrishoage** [comment]
Since 4.0.1 kwm no longer controls key bindings. Keybindings have been moved to khd: https://github.com/koekeishiya/khd

**Comment by er0ck** [comment]
ok.  i don't have that installed, so probably is not why i'm having this problem.

**Comment by chrishoage** [comment]
Can you describe the issue a little more? The title says `shift` and `cmd` click no longer work. 

The way I am reading that is you are having trouble with your keybindings. If you are running version 4.0.2 that means that keybindings will no longer work as they have been removed since version 4.0.1. 

Can you help me understand your issue a little better?

**Comment by er0ck** [comment]
when i try to use shift-(mouse)click or cmd-(mouse)click, they don't add to the current selection.
e.g.: cells in a spreadsheet, or email checkboxes in gmail.
when i stop kwm, this works.

**Comment by dominiklohmann** [comment]
The issue seems to be that he copied koekeishiyas `~/.kwm` folder from his Dotfiles repo, which has not been updated to the syntax changes of version 4.0.1 and newer.

**Comment by chrishoage** [comment]
@er0ck Ah, ok. You must have the following enabled in your `kwmrc` file 

```
/*
    Allows a window to be moved by dragging,
    when a modifier key and left-click is held down.

    Allows a window to be resized by dragging
    when a modifier key and right-click is held down.
*/
kwmc config mouse-drag on

# The modifier keys to be held down to initiate mouse-drag
kwmc config mouse-drag mod shift+ctrl
```

If you set `kwmc config mouse-drag off` you should get your `shift + click` back.

**Comment by er0ck** [comment]
ah yes.  it has `kwmc config mouse-drag mod shift`
i should have just pointed to my rc files.  i forgot i pushed them already:
https://github.com/er0ck/dotfiles/blob/master/kwm/kwmrc#L16

**Comment by er0ck** [comment]
uh... if i comment that one out, and restart kwm mouse clicks don't work unless i hold cmd :-\

**Comment by chrishoage** [comment]
Dunno about that one. My only advice would be to try commenting everything out in your `kwmrc` file until you find the offending line. 

I'm running master and don't have that issue.
