### ISSUE TITLE
Question on full screen split screen functionality on MacOS

### ISSUE THREAD

**Issue by dimitrieh** [koekeishiya/kwm#542]
@koekeishiya a quick question :) 

Let's say we run Iterm2 in native full screen mode on MacOS. Would it be possible to open let's say Atom and bring it within the same full screen space as Iterm activating [split screen](https://support.apple.com/en-us/HT204948)?

I would like to restore this setup with a single command.

**Comment by koekeishiya** [comment]
There are no API available to interact with the native fullscreen, as far as I know.

**Comment by matthewdias** [comment]
BTT does it, but it's very buggy. I think it just emulates the mouse gesture.

**Comment by dimitrieh** [comment]
strange i was wondering about that, i'd say let's close this until some api's become available.
