### ISSUE TITLE
[master] Crashes when restoring nonexistent layout

### ISSUE THREAD

**Issue by matthewdias** [koekeishiya/kwm#543]
Woke up to a really weird issue this morning. Nothing about my setup has changed, but when a window is about to be tiled _only on Space 2_, kwm segfaults: 

```
kwm git:master ❯ bin/kwm                                                                           ⏎
OverlayLib initialized!
Notice: Signal handlers disabled!
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
AXEvent_WindowMoved: Terminal - kwm — bin/kwm — bin/kwm
AXEvent_WindowMoved: Terminal - kwm — bin/kwm — bin/kwm
AXEvent_WindowMoved: Google Chrome - 
AXEvent_WindowResized: Google Chrome - 
AXEvent_SpaceChanged
[1]    75569 segmentation fault  bin/kwm
```
All other spaces are unaffected, and it doesn't happen when moving floating windows to the space.

**Comment by matthewdias** [comment]
Ah, it happened when it tried to restore a layout file that didn't exist.

**Comment by koekeishiya** [comment]
> Ah, it happened when it tried to restore a layout file that didn't exist.

..well that has to be the dumbest bug yet
