### ISSUE TITLE
Execution delay

### ISSUE THREAD

**Issue by willhoag** [koekeishiya/kwm#547]
The delay between my keyboard input and execution is large enough that it is cumbersome to use. Working with Stable 4.0.2 and a slightly modified version of the suggested default settings.

**Comment by dominiklohmann** [comment]
Duplicate of koekeishiya/khd#23. Solution might be downgrading Khd until this is fixed.

**Comment by willhoag** [comment]
Thanks, missed that issue. Closing.

**Comment by koekeishiya** [comment]
I have so far not been able to reproduce the problem with my current config.

Any input regarding your config and what you to do get said execution delay would be helpful in diagnosing the problem. Also, if you did indeed try to downgrade to `1.0.1`, could you confirm if the delay is no longer an issue?

Thanks.
