### ISSUE TITLE
Add an option for kwmc bind to work only for listed Applications or for all Applications but the listed ones

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#55]
This would be very much appreciated - I have switched to using kwmc bind for almost all my custom global hotkeys, but the ones I can't replace are those that only work for specific applications or are supposed to work globally except for a few specific applications.

From what I understand of the code this would most likely require a rewrite of the kwmc command parser to not just parse word by word.

Also, thanks for the development you're doing on this. I've been searching for a good WM for OS X for years and this is absolutely awesome.

**Comment by koekeishiya** [comment]
Not sure if this is something that I want to do. The live-code system (hotkeys.cpp) was meant to be the system for more advanced use (such as the above) and so I would prefer to have the bind system remain simple as is. Will come back to this later, unsure of what to do as of now.

**Comment by koekeishiya** [comment]
I've been thinking about the complexity introduced by doing this, and I believe it is something that I can implement without too much trouble. This should allow for both exclusion of applications, or working only for the ones specified.

The bind command for excluding applications would look something like the following:
`kwmc bind mod+mod+mod-key command {App1,App2,App3} -e`
e.g `kwmc bind cmd+alt-1 sys open -na /Applications/iTerm.app {App1,App2,App3} -e`

The bind command that only works for specific applications would look something like the following:
`kwmc bind mod+mod+mod-key command {App1,App2,App3} -i`
e.g `kwmc bind cmd+alt-1 sys open -na /Applications/iTerm.app {App1,App2,App3} -i`

No idea when this will be implemented tho.
