### ISSUE TITLE
[master] Improve default split insertion

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#553]
Improve behaviour of split-insertion upon initial bsp creation and if a window is tiled without regards to the currently focused / marked window.

**Comment by koekeishiya** [comment]
Instead of always inserting a window in the top-left leaf, we find the minimum-depth leaf node and split that node.

**Comment by cjpetrus** [comment]
@koekeishiya can I help with chunkwm?

**Comment by koekeishiya** [comment]
@cjpetrus I'd like to do the ground-work myself first, but after the initial work has been done, sure.
