### ISSUE TITLE
[4.0.2] Blacklist from tiling

### ISSUE THREAD

**Issue by kirkegaard** [koekeishiya/kwm#554]
Hi, im using the hole Adobe suite a lot. I cant seem to blacklist them from kwm which results in some wonky tiling and position of the windows.

![screen shot 2017-01-09 at 11 47 32](https://cloud.githubusercontent.com/assets/43752/21764063/77bca04c-d661-11e6-97c2-677d93a7d5a9.png)

As you can see it kind of moves the window out of the screen area with no way of moving it back.

Ive added the apps with the full app name but it doesnt seem to matter. I also tried escaping the names like `adobe\ illustrator` but with the same result.
![screen shot 2017-01-09 at 11 53 34](https://cloud.githubusercontent.com/assets/43752/21764236/51ed8ccc-d662-11e6-80b6-20d69739f373.png)

Actually After Effects works perfectly and I havent even defined that application in my config file. It might have something to do with the `Application Frame` setting in some Adobe apps. If I disable application frame in photoshop it seems to get stuck in a tiling loop with the open windows. The open image window will jump around on the screen trying to fit somewhere.

Does anyone know how to make kwm ignore specific apps?

**Comment by koekeishiya** [comment]
I use the following for photoshop:
```
kwmc rule owner="Photoshop" properties={float="true"}
```
The name to supply can be found within: `/Applications/Adobe\ Photoshop\ CC/Adobe\ Photoshop\ CC.app/Contents/Info.plist` as BundleName.

**Comment by kirkegaard** [comment]
Ive tried that without any luck. 

![screen shot 2017-01-09 at 13 53 55](https://cloud.githubusercontent.com/assets/43752/21767232/18c47e7c-d673-11e6-9fd2-68993c1f10d7.png)

Are you using the `Application frame` option? Its under the `window menu`?

**Comment by koekeishiya** [comment]
> Are you using the Application frame option? Its under the window menu?

I do have this option checked, yeah.

tried turning it off now and it seemed to cause problems.

**Comment by koekeishiya** [comment]
@kirkegaard I noticed you wrote it as "Photoshop CC" and "Illustrator CC". I believe that the "CC" should be left out. You may have already tried this though.

**Comment by kirkegaard** [comment]
Yeah you said to use the BundleName which has the CC part as well. At least it has in the 2017 version of the apps. It seems to have the same effect even if i remove the CC part from the name though.

My best guess would be that Adobe uses some weird thing for UI that differes from regular osx apps but Im not really knowledgable about that kind of stuff

**Comment by kirkegaard** [comment]
I didnt know about the `kwmc query window list` command! It looks like that fixed it for me. The space rule doesnt move illustrator to 3 but seems to work just fine. I can live with that though :)

![screen shot 2017-01-09 at 15 34 57](https://cloud.githubusercontent.com/assets/43752/21769935/60dc34bc-d681-11e6-856b-517330ac1ba6.png)

**Comment by kirkegaard** [comment]
Would you happen to know if its possible to make Finder popup windows float? You know when you copy files it pops up a dialog box showing progress and so on.

**Comment by choco** [comment]
Just for posterity and completeness, since Adobe likes to implement stuff their own way, the owner name of the app can change depending on when is queried. Personally I have the following rule that hasn't failed me yet
```
kwmc rule owner=".*Photoshop CC.*"            properties={float="true"}
```

**Comment by choco** [comment]
@kirkegaard The copy one can be made to float with the following rule
```
kwmc rule owner="Finder" name=".*\bCopy\b.*"  properties={float="true"}
```
Not sure why I added word boundaries, since in Sierra the title seems always to be Copy, so I can probably simplified like this
```
kwmc rule owner="Finder" name="Copy"  properties={float="true"}
```

**Comment by kirkegaard** [comment]
Oooh you can actually use wildcards? Didnt know about that either. Thats pretty useful!

Thanks buddy! Will give that a try right now

**Comment by koekeishiya** [comment]
Closing this as resolved. Please do reopen or recreate if there are more issues.

**Comment by kirkegaard** [comment]
Thank you for all the help! I dont know if theres any documentation for this thing anywhere? If not I would love to submit a PR with some :) I think I got the gist of how this works now

**Comment by koekeishiya** [comment]
Wouldn't really call it documentation, but [here](http://koekeishiya.github.io/kwm/kwmc.html)
