### ISSUE TITLE
[master] fly-outs get floated

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#555]
I have built mater and I have started to see "fly-outs" (things like the auto-complete window in chrome, or the tab completion in Sublime text) get centered in the screen (as if a float rule was being applied to them), then snap back to the position they are supposed to be in. 

This didn't happen before I updated today, so one of the recent commits seems to be the culprit. (If I have more time later this week I can step back though the commits to find the offending one).

**Comment by koekeishiya** [comment]
Seems like a sideeffect of https://github.com/koekeishiya/kwm/issues/510
