### ISSUE TITLE
Homebrew tap change

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#558]
Currently, I have separate taps for every homebrew formula.
This is getting kinda annoying and I am therefore gathering them all in a single repository.

This means that the tap previously used for Kwm will no longer receive new updates (beyond version 4.0.3) and the repository will be deleted in the future. You can relocate to the new tap by doing the following:
```
brew untap koekeishiya/kwm
brew tap koekeishiya/formulae
```

The homebrew instructions in the readme has also been updated with the proper tap.

Edit: version 4.0.4 is also up on the old tap, with a deprecated warning and the above instructions.

**Comment by benjamreynolds** [comment]
Have you considered submitting these formulae to [homebrew-cask](https://github.com/caskroom/homebrew-cask)? I think they are popular enough to be accepted there. Or is there a reason you want to keep them in you own repository?

**Comment by chrishoage** [comment]
@benjamreynolds 

Cask is for things that live in the `/Applications` directory, `kwm` and `kwmc` are CLI applications that are meant to be accessed from your `$PATH` 

Due to this, cask is not the right place for kwm to live, and homebrew supporting their binaries repo

**Comment by benjamreynolds** [comment]
Would they not be a good candidate the fore [homebrew-core](https://github.com/Homebrew/homebrew-core)?

**Comment by chrishoage** [comment]
No, homebrew-core needs to be able to be complied from source. kwm need to be codesigned as well as use some libraries from XCode which makes compiling for source impractical for kwm.

This has been discussed before and a custom tap is really the best option for kwm, if you're curious you can search for other GHIs about kwm and homebrew to get more context.
