### ISSUE TITLE
[4.0.3] Keyboard shortcuts no longer work

### ISSUE THREAD

**Issue by apierz** [koekeishiya/kwm#559]
After updating to 4.0.3 I can no longer use keyboard shortcuts to control kwm. All the other rules and settings in my kwmrc file are being respected. I've tried removing kwm and reinstalling via homebrew, removing and rea-dding kwm to the list of applications that can control my computer in the settings menu and starting and stopping the kwm service, but so far nothing has worked.

**Comment by keithyang** [comment]
use khd?

**Comment by chrishoage** [comment]
To expand on the comment above me, since version 4.0.2 the keybindings have been moved to https://github.com/koekeishiya/khd as a standalone program. 

If you are coming from a version before 4.0.2 you will need to convert your keybindings to the new program and format for them to work.

**Comment by apierz** [comment]
Ah got it. I have khd installed and it's working fine. Thanks for the help.
