### ISSUE TITLE
Windows forced behind dock

### ISSUE THREAD

**Issue by eli-oat** [koekeishiya/kwm#56]
I'm not 100% certain if this is actually a bug, per-se, but it'd be nice if kwm treated the doc as the edge of the screen so that window content can't appear underneath the dock. 

Seeing this behavior with the dock on the bottom, left, and right of the screen. 

![screen shot 2016-01-10 at 3 18 37 pm](https://cloud.githubusercontent.com/assets/3342274/12223766/b0b6a240-b7ad-11e5-9dbf-d013608cca4a.png)

**Comment by koekeishiya** [comment]
This is not something i can forcefully do. However, see `kwmc config padding bottom`

**Comment by eli-oat** [comment]
Opplah! Would you look at that! That is perfect. :100: 

Thanks! :+1:
