### ISSUE TITLE
[ 4.0.4 ] kwm borders persistent over iTerm2 fullscreen 

### ISSUE THREAD

**Issue by JackyChiu** [koekeishiya/kwm#566]
iTerm2 provides the ability to have a hotkey window take up the full screen (not on a new desktop), but when using kwm, the borders from windows are persist and overlap on top of the terminal. 

I was wondering if this is possible to fix or if there's a work around to this situation. If there is I'd really like to know! Thanks

Border on window:
<img width="1920" alt="screen shot 2017-01-25 at 8 26 41 pm" src="https://cloud.githubusercontent.com/assets/11095732/22316651/a6653674-e33c-11e6-9f16-fb4a3837aa08.png">

Border still there after pressing hotkey
<img width="1920" alt="screen shot 2017-01-25 at 8 30 34 pm" src="https://cloud.githubusercontent.com/assets/11095732/22316780/764e4c72-e33d-11e6-8c9b-b6c7bd556cf9.png">

**Comment by dominiklohmann** [comment]
There's one solution that works, but it requires you to always both summon and dismiss iTerm2 using a set hotkey and not through any other way.

Here's what you need in your `.khdrc` file for it to work:

This will disable the border when you press the `summon-hotkey` when iTerm2 is not active and then forward the keypress to summon iTerm2.
```
summon-hotkey [ iTerm2 ] ! -> : kwmc config border focused off
```

This will enable the border when you press the `dismiss-hotkey` when iTerm2 is active and then forward the keypress to dismiss iTerm2.
```
dismiss-hotkey [ iTerm2 ] -> : kwmc config border focused on
```

This is likely to also require you to have iTerm2 show in your dock, as I don't think the active app filters work when that option is disabled.

**Comment by JackyChiu** [comment]
@dominiklohmann Wow thanks for the quick reply! This solution sounds good, I'll try it out. Much appreciated

**Comment by JackyChiu** [comment]
@dominiklohmann 
<img width="347" alt="screen shot 2017-01-25 at 9 17 05 pm" src="https://cloud.githubusercontent.com/assets/11095732/22317740/b106e6ac-e343-11e6-9cd0-adff03b5459e.png">

Is `summon-hotkey` something that is integrated with iTerm2 already (as in the picture) and `khd` is aware of this? Or do I also have to define the `summon-hotkey` value in the `.khdrc`?

**Comment by dominiklohmann** [comment]
`summon-hotkey` is just whatever hotkey you use to summon iTerm2. Same with `dismiss-hotkey`, except for dismissing iTerm2. If I read your screenshot correctly, they're both the same hotkey (acting as a toggle) and you should configure it like this:

```
alt - space ![ iTerm2 ] -> : kwmc config border focused off ; kwmc config border marked off
alt - space  [ iTerm2 ] -> : kwmc config border focused on ; kwmc config border marked on
```

**Comment by JackyChiu** [comment]
Ahh that makes a lot of sense, my bad haha. 

Tried the config above:
Good news is that when entering the full-screen mode with the hotkey the borders do get turned off! 

But when dismissing the borders do not return,  I will play around with this at a later time

**Comment by JackyChiu** [comment]
Closing issue since it's not an issue with kwm

**Comment by dominiklohmann** [comment]
So upon further investigation you can actually solve this issue without Kwm/Khd trickery by enabling the "floating window" option for your hotkey window. It will then draw over the border.

<img width="1128" alt="screen shot 2017-01-26 at 03 45 46" src="https://cloud.githubusercontent.com/assets/4488655/22318356/19110896-e37a-11e6-8d84-d3c04dd7bc62.png">

**Comment by JackyChiu** [comment]
That's perfect! Thanks much appreciated 🥇
