### ISSUE TITLE
[4.0.4] Focused border persists during transition to new space

### ISSUE THREAD

**Issue by embern** [koekeishiya/kwm#569]
When I move to another space the current focused border will appear on the new space until the transition animation has finished. Once the animation completes the border goes away and the correct window is focused. This happens with both gestures and shortcuts.

Sorry if this is a duplicate, I looked through some issues related to borders but didn't see any that specifically addressed this.

<img width="640" alt="screen shot 2017-01-29 at 3 11 33 pm" src="https://cloud.githubusercontent.com/assets/25420950/22407489/4990889e-e635-11e6-9523-d71bdf430827.png">

**Comment by chrishoage** [comment]
This is expected, IIRC the focus change notification doesn't happen until the animation is complete.

**Comment by embern** [comment]
Ah OK. I suspected it might have to do with OSX but wanted to make sure.

**Comment by koekeishiya** [comment]
As chrisohage said, we do not get notified until after the transition has actually ended.

Theoretically, we could set up our own notification system by polling on a separate thread to know if a transition is in progress and have it notify our callback when the state changes. 

I do not think that is something that is worth to implement for such an insignificant change in behaviour.
