### ISSUE TITLE
Allow display/screen to be configured with specifc layout

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#57]
This would allow different displays to have different default display modes. This would override what is set with `kwmc config space` for that screen.

Example config (feel free to change as needed to fit in with current config options and style)

```
kwmc config space bsp
kwmc config screen 0 bsp
kwmc config screen 1 monocle
```

This would have the following behavior: Screen 0 defaults to bsp. Screen 1 defaults to monocle. If Screen 2 is connected it defaults to `kwmc config space` (bsp in this case). Created spaces default to what their screen is. If the knowledge of what screen a space is created on is unavailable default to `kwmc config space`. If a space is changed away from it's default it is persisted until `kwm` quits or the space is destroyed.

(Moved from https://github.com/koekeishiya/kwm/issues/42)

**Comment by koekeishiya** [comment]
I've given some thought to how to add this, and may be implemented in the near future.

**Comment by chrishoage** [comment]
Sorry some how missed this comment. 

Not sure if this makes it easier or is moot but what about using the resolution of the display instead of the display ID?

For my specific case this would be 

```
kwmc config screen 3840x2160 bsp
kwmc config screen 2880x1800 monocle
```

Perhaps this is not the concern you are describing though.

**Comment by koekeishiya** [comment]
Ah nah that isn't related to the issue. Uh, the problem is just that because screen padding can be specified in the config file, the config must be executed before Kwm tries to check which monitors are active, so that it can correctly apply this setting.

That means that all the config has already been executed before Kwm detects monitors.
The problem is that to apply this kind of setting for individual screens, I would have to be able to change this value after Kwm has finished detecting the monitors. 

This causes a conflict where the config has to be executed both before and after, because the settings for individual screens would only be specified in the config file.

Now I can create some workaround here, but I'm just waiting til I find the right one.

**Comment by chrishoage** [comment]
I have no idea how any of the data layer is implemented so this is all super handwavy. 

What about having defaults you "extend" from when a monitor is detected. When one is detected it looks up to see if it knows about that display ID, if it does, it uses the layout for that display instead of what ever is set in `config space`. 

This way the config does not have to be applied after a display is detected, it just looks up to see if it knows about that ID. 

Just random ideas, I'm sure there is complexity I have no idea about due to the headache that has been multiple display support.

**Comment by koekeishiya** [comment]
Something like that is the workaround I currently have in mind, yeah.
Just need to make sure that it won't cause unwanted complexity in the future.

I'll probably do some more code refactoring as to how variables are stored and so on, when I implement this change. It is definitely a feature that will be possible to do, just requires some more thinking.

**Comment by koekeishiya** [comment]
The commands used for this is: `kwmc config screen id bsp|monocle|float`. 
If a screen is not specified, it will use the default mode set by `kwmc config space ..`

A screen can be specified even if it is NOT currently connected.
This will allow you to always have a specific mode set for say screen 1.
This will not interfere with anything if you do not have a display with id 1 connected.

If you do connect a display, it will use the tiling mode set in the config without having to restart Kwm or reload config or anything.
