### ISSUE TITLE
KWM does not account for dock position

### ISSUE THREAD

**Issue by Synapz1** [koekeishiya/kwm#571]
Kwm 4.0.4

I prefer the dock to be on the left of my screen, but Kwm assumes the dock is on the bottom and leaves some padding for it. It does not detect where the dock is and assumes it is on the bottom so the window is resized and overlaps under the dock. This results in me not able to click the X button easily:

![screen shot 2017-02-10 at 8 51 20 pm](https://cloud.githubusercontent.com/assets/6752306/22850131/c9789708-efd2-11e6-868e-093ad5c2bb6b.png)

See there is no padding on the left side so the window is not accounting for that size difference with the dock there.

**Comment by matthewdias** [comment]
padding is configurable. see http://koekeishiya.github.io/kwm/kwmc#global-defaults

**Comment by Synapz1** [comment]
Oh! That is awesome, I did not realize 

So I guess this is what I should edit:
Set default padding
kwmc config padding {padding}
    {padding}: top bottom left right

I tried
`./kwmc config padding left`
But it results in an error
`Unknown config padding top value 'left'`

**Comment by matthewdias** [comment]
you actually need to sub in all four values. like `kwmc config padding 0 0 20 0`

**Comment by Synapz1** [comment]
Thank you so much It worked
