### ISSUE TITLE
[4.0.4] Unable to change default mode for space

### ISSUE THREAD

**Issue by jared-hess** [koekeishiya/kwm#573]
KWM is installed and tiling works, but using the following command or placing it into my kwmrc has no effect:
```
kwm config space 0 1 mode float
```
I only have 1 monitor so my understanding is that the ID for this should be 0 (based on issue #370). However, I am able to specify the mode of a particular window by using the following:
```
kwmc window -t next
```
And that works as expected. Am I doing something wrong here? Is the window ID something other than 0?

**Comment by chrishoage** [comment]
To be clear, you placed 

```
kwm config space 0 1 mode float
```

into `.kwm/kwmrc`

or 

```
kwmc config space 0 1 mode float
```

Because the `kwmc` is the program that actually controls `kwm`.

**Comment by jared-hess** [comment]
Sorry, yes I did use kwmc. Entire contents of my kwmrc:

```
kwmc config space 0 1 mode float
kwmc rule owner="iTerm2" properties={role="AXDialog"}
```

**Comment by jared-hess** [comment]
Odd, it seems to be working now, not sure what changed. I guess I'll re-open if I see any other issues.
Thanks!
