### ISSUE TITLE
Vim syntax file for kwmrc

### ISSUE THREAD

**Issue by kidpixo** [koekeishiya/kwm#574]
I'm on the kwm stable [4.0.4] from homebrew.

I search a little bit, but I didn't find this here : I wrote a simple Vim syntax file for kwmrc file, based on the command I have in my configuration.
It could be easily extended to khd too.

A (maybe) stupid question : how can I get all the possible option for kwmc / khd ?

The code is in this gist > https://gist.github.com/kidpixo/fdc47c39d50c8f24a9221cd02265a24b

![screenshot](https://cloud.githubusercontent.com/assets/2255209/23169424/fd810f0e-f84b-11e6-9b36-59bc20bf2b7f.png)

**Comment by koekeishiya** [comment]
> A (maybe) stupid question : how can I get all the possible option for kwmc / khd ?

http://koekeishiya.github.io/kwm/kwmc.html

Interesting addition, I can see that being helpful with how verbose the kwmc config can become.
Could be interesting to have for **khd** as well.

**Comment by kidpixo** [comment]
>Could be interesting to have for khd as well.

Easy to implement, I just have to extract all the parameters from the `README.md`

You mean this [khd/README.md](https://github.com/koekeishiya/khd/blob/master/README.md) ? I was hoping to grab the source of [koekeishiya.github.io/kwm/kwmc.html](http://koekeishiya.github.io/kwm/kwmc.html) and get everything from there. Is the source available somewhere?

You get for free all the bonus as commenting-shortcuts via "[scrooloose/nerdcommenter: Vim plugin for intensely orgasmic commenting](https://github.com/scrooloose/nerdcommenter)" for example

Maybe I have to package the whole thing as a vim plugin...

PS: thanks for the great tool! I was searching for a i3wm like and kwm is the best experience so far.
