### ISSUE TITLE
[4.0.3] Huge performance issues

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/kwm#575]
Hi,

I love kwm since it's early stage, but I encounter huge performance issues with the WindowServer process. It looks like that stopping the `kwm` service immediately reduce the CPU usage.

This seems to appear exclusively when using my multi-monitor setup (2 FHD external displays + the internal).

Do you have some tips to provide more informations on this ? and/or some ways to debug this ?

Could it be related to rules ? 

Has someone encounter such an issue ?

Thanks

**Comment by koekeishiya** [comment]
Seems like this is related to https://github.com/koekeishiya/kwm/issues/540
Already fixed in v4.0.4

**Comment by mickaelperrin** [comment]
thanks, indeed I just saw I wasn't on the latest release.

Just updated to 4.0.4. I close the issue and will reopen it if I encounter the problem again.

Thanks for your answer and your hard work !
