### ISSUE TITLE
[4.0.4] 3 “columns” (wide layout)

### ISSUE THREAD

**Issue by Hywan** [koekeishiya/kwm#576]
Hello,

I would like to know if this is possible to have a wife layout, based on 3 columns. I have a wide display and this would be very useful.

Thanks!

**Comment by koekeishiya** [comment]
You can set the split-mode to vertical to achieve this, either while Kwm is running or in the config file:

`kwmc display -c vertical`

**Comment by Hywan** [comment]
Thank you for the quick reply.

How can we “equalize” the layout? I mean:

```
|  A  |  B  |  C  |
```

instead of:

```
| A | B |    C    |
```

Thanks!

**Comment by koekeishiya** [comment]
There is currently no easy way to equalize, but you can adjust the size (split-ratio).

Issuing the following command when window 'C' is focused should do the trick:
```
kwmc window -c reduce 0.05 west
```
You can set a higher or lower value than 0.05 if needed.
I usually issue the above command twice.

You can also use, say alt + right-mouse + drag to resize windows, provided you have
```
kwmc config mouse-drag mod alt
kwmc config mouse-drag on
```

After doing this once, you can save the layout using `kwmc tree save col_3` and at any point in the future, simply issue `kwmc tree load col_3` to apply that layout to the active space.

**Comment by koekeishiya** [comment]
Closing this as resolved, see my post above.
