### ISSUE TITLE
[4.0.4] kwm command is not in added to path when installing via brew

### ISSUE THREAD

**Issue by levitanong** [koekeishiya/kwm#579]
However, kwmc is, which could lead to some confusion.

**Comment by darvelo** [comment]
I don't think `kwm` is meant to be run from the command line. If you really needed to though, you could run it from its full path. I think this is a feature because it prevents accidentally starting kwm or accidentally starting another instance of kwm when one is already running.

**Comment by koekeishiya** [comment]
> I don't think kwm is meant to be run from the command line. 

This is true for homebrew versions. The only time Kwm should be ran from the terminal is if you are building manually for whatever reason, in which you just run it from the bin directory or manually symlink it.
