### ISSUE TITLE
Add the ablity to save and restore a bsp tree

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#58]
This would allow the ability to restore a tree layout via a key command. This would be irrespective of application or window, only restoring the sizes and number of containers. 

These layout files could be in `~/.config/kwm/` or `~/.kwm/` or at a location specified in `.kwmrc`. 

I had some thoughts about how to serialize this until I realized the `kwmc` commands could probably be used with little modification. These commands could be serialized by the program and saved to a location and still be editable by humans. 

A possible example of this layout file might look like this:

```
# takes the first two windows and places them in a new tree. places focus on the 2nd
kwmc tree apply start 
kwmc window -f 0 # place focus on the first window
kwmc window -c split vertical # or horizontal or toggle
kwmc window -c reduce 0.1 
kwmc tree apply add # creates next window using current focus. places focus on new window
kwmc window -c reduce 0.1
kwmc window -f 1 # focuses window on right 
kwmc tree apply add # creates next window using current focus. places focus on new window
kwmc window -c reduce 0.4
kwmc tree window -f 2
kwmc tree apply add
kwmc tree window -f 1
kwmc tree apply end 
```
Any windows left in the stack will be applied using normal bsp logic where the last focused window was. any `tree apply add` commands will exit the script early if there are no windows left to add. `kwmc tree apply start` would only start the script if there are at least 2 windows. 

I don't imagine that this would be an actual shell script. But I do think that as long as application and windows are ignored layouts can be expressed as a series of `kwmc` commands. I don't know how feasible this is but it would allow it to still be editable by humans with a familiar syntax.  

`kwmc tree save my-tree` would serialize the layout as the commands that got it there. `kwmc tree load my-tree` would restore the tree using the configuration file at `~/.kwm/my-tree`. It could be bound via `kwmc bind ctrl+cmd+shift-z tree load my-tree`

Moved from https://github.com/koekeishiya/kwm/issues/42

**Comment by koekeishiya** [comment]
I really like the approach you've described above. Will definitely look into that.

**Comment by chrishoage** [comment]
Thanks! Feel free to update any of the syntax or commands. I'm terrible with naming things but it _seems_ like the idea would work as long as layouts were kept fairly simple (always ignoring the window or application)

**Comment by koekeishiya** [comment]
Felt like posting an update on the progress of this, so currently a tree can be saved and loaded to file.
It successfully restores the containers and their size, and fills in open windows starting from the left-most container. There is a little issue with how i re-create the tree (the deserialization step) and it fails to load layouts that have more than 3 containers.

I simplifed the serialization a lot compared to the above, sample layout:
```
kwmc tree root create parent #This is the 'master' root node
kwmc tree split-mode 1 # This root uses vertical split
kwmc tree split-ratio 0.400000 # The container-proportion
kwmc tree child # Prepare to set up a child-container
kwmc tree root create left # This child-container is of type 'root' and is the left child
kwmc tree split-mode 2 # Horizontal split-mode
kwmc tree split-ratio 0.750000 # Container split proportion 
kwmc tree child # The '2nd root container also has children
kwmc tree leaf create left # This is the left child and is a leaf
kwmc tree child # Another child for the 2nd root container
kwmc tree leaf create right # This is the right child of the 2nd container and is a leaf
kwmc tree child # Another child container 
kwmc tree leaf create right # The right child container of the 'master' root
```

Settings are only stored in the 'root' containers. These contain split-mode, split-ratio and their children.
The children can themselves be 'root' containers etc to create the nested tree structure.
For each `kwmc tree child & kwmc tree root|leaf create left|right` pair, that part of a 'root' container is done.

**Comment by chrishoage** [comment]
will `~/.kwmrc` still be read or will it only be read in `~/.kwm/kwmrc`? having a little (eventual) flexibility there would be nice

**Comment by koekeishiya** [comment]
It will only read ~/.kwm/kwmrc atm. I guess you could put up a symlink for now

**Comment by chrishoage** [comment]
Linking works fine for now. I noticed this saves all windows, not just limited to the display that it is on. 

Is that expected behavior? Or should it only save and restore a single display / space? 

```
kwmc tree root create parent
kwmc tree split-mode 1
kwmc tree split-ratio 0.400000
kwmc tree child
kwmc tree root create left
kwmc tree split-mode 2
kwmc tree split-ratio 0.600000
kwmc tree child
kwmc tree leaf create left
kwmc tree child
kwmc tree leaf create right
kwmc tree child
kwmc tree root create right
kwmc tree split-mode 2
kwmc tree split-ratio 0.800000
kwmc tree child
kwmc tree leaf create left
kwmc tree child
kwmc tree leaf create right
```

I have 4 windows open on my main display and 2 on my secondary display. I count 6 `child` commands.

**Comment by koekeishiya** [comment]
It should only save the active space (not all monitors). However it does appear to look correct.
The "invisible" root containers also count as a `child` command, however there are only 4 `tree leaf` listed, which is the container used for actual windows.

**Comment by chrishoage** [comment]
> The "invisible" root containers also count as a child

Got it thank you. 

Seems to be working!

**Comment by koekeishiya** [comment]
That layout seems quite effective, gonna steal that one. Thanks :>

**Comment by chrishoage** [comment]
I have noticed that if you do not have the same number window as there are saved containers it will create space for the window even if there are no windows to fill it. 

Is that expected behavior, or would you like me to open a ticket?

**Comment by koekeishiya** [comment]
Expected behaviour for now.
