### ISSUE TITLE
[4.0.4] Readme Usage could use some clarification

### ISSUE THREAD

**Issue by levitanong** [koekeishiya/kwm#580]
I'm aware `brew services start kwm` is part of the installation process, but it also acts as usage.

However, when trying to use a different config path, `brew services start kwm` is inappropriate, and kwm should instead be started via `kwm -c /path/to/kwmrc`. 

Can someone confirm if my understanding is correct? If so, I can make a PR on the readme and add the necessary clarifications.

**Comment by darvelo** [comment]
If you want to use a different config file you need to not use `brew services` and instead

1. copy the `~/Library/LaunchAgents/homebrew.mxcl.kwm.plist` file to another file in that same directory and modify it as needed
2. run `brew services stop kwm`
3. run `launchctl load -w ~/Library/LaunchAgents/the_file_you_created.plist`

Your custom configured kwm should now launch on startup. If you ever need to prevent that from happening use `launchctl unload -w ~/Library/LaunchAgents/the_file_you_created.plist` and kill kwm with `killall kwm`.

**Comment by levitanong** [comment]
Whoa, this info doesn't seem to be in the current Readme. Perhaps you'd like to add it in?
