### ISSUE TITLE
Homebrew Issue with 'brew update'

### ISSUE THREAD

**Issue by klaus385** [koekeishiya/kwm#583]
Version 4.0.4 according to 'brew reinstall kwm'. Which btw works fine but, some reason the tap for this homebrew is failing. 

As seen ->

![brew-issue](https://cloud.githubusercontent.com/assets/12820328/23559410/3004cfba-fff4-11e6-8ebf-923442a2b43e.png)

**Comment by koekeishiya** [comment]
The old tap `koekeishiya/homebrew-kwm` was deprecated a long time ago, and was recently deleted.

The new tap is `koekeishiya/formulae`, not `koekeishiya/formulae/kwm`.

See #558 and notes under latest release [here](https://github.com/koekeishiya/kwm/releases/tag/v4.0.5)
