### ISSUE TITLE
Force tiling on only a part of a screen for a specific monitor

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/kwm#585]
Hi,

I was wondering if there was some ways to force KWM to tile windows only in a part of a screen and not in the entire screen. For example, act like if the montitor was of resolution 3840x1440 instead of 3840x2160.

I know this looks dumb :)

My use case, I have a  40inch monitor that I was using sitting on my desk with a typical mouse and keyboard. 

Problem: I now use exclusively my laptop keyboard and trackpad. And my monitor is now above my laptop. It is now 30cm higher which is uncomfortable for reading in the higher corners.

Switching to floating windows on that screen would do the job, but I would love to keep automatic tiling.

Any workarounds ?

Thx

**Comment by dominiklohmann** [comment]
Should be doable with per-display padding settings if I understood your intention correctly.

**Comment by mickaelperrin** [comment]
Of course !

> Override default padding for display
kwmc config display display_id padding {padding}
    {padding}: top bottom left right

Many thanks !
