### ISSUE TITLE
Cannot get spaces to work properly [4.0.5]

### ISSUE THREAD

**Issue by hahuang65** [koekeishiya/kwm#587]
I have in my `kwmrc`
```
# Workspaces
kwmc config space 0 1 tree Shell
kwmc config space 0 1 name Shell
kwmc config space 0 2 tree Firefox
kwmc config space 0 2 name Firefox
```

And in my `khdrc`
```
# Switch workspaces
cmd - 1 : kwmc space -fExperimental 1
cmd - 2 : kwmc space -fExperimental 2
```

But when I press `cmd - 2` absolutely nothing happens.

Am I misunderstanding the feature?

**Comment by hahuang65** [comment]
This was a PEBKAC. I have to create the spaces first of course!

**Comment by MikeBarnhardt** [comment]
Did you find a way to programmatically create the spaces first?

**Comment by koekeishiya** [comment]
> Did you find a way to programmatically create the spaces first?

There is no offical API from Apple to do this. You can try to reverse-engineer how the Dock and Mission Control application works. There are the following private functions `CGSSpaceCreate()` and `CGSSpaceDestroy(..)` to do this, but there are other steps also required to keep the system from going out of sync.

The creater of TotalSpaces2 seem to have been able to work this out, so it is definitely possible, but there is no information about this to be found.

**Comment by MikeBarnhardt** [comment]
Alright, I figured as much in my quick Googling of it.

Thanks for the quick response.
