### ISSUE TITLE
Window ratio size and position becomes incorrect when moving focus between monitors

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#59]
Occasionally the window position and/or ratio size get's changed to an incorrect value when moving focus between displays. The tree appears to be reverted and all ratio sizes are lost until `window -c refresh` is used on every window in the space. When this command is given the previous correct ratio sizes are restored. 

For me, this happens even when the monitor is not disconnected and reconnected, merely from moving focus between displays. 

Moved from https://github.com/koekeishiya/kwm/issues/42#issuecomment-170395761

**Comment by koekeishiya** [comment]
This may happpen (very rarely, but I believe it's fixed. To the best of my ability at least).
If this should happen at any time, there is a command you can use to manually "re-apply" the entire tree at once: `kwmc tree -c refresh`. This will re-apply the window container for every window of the focused space.
