### ISSUE TITLE
'kwmc help' - no output

### ISSUE THREAD

**Issue by jottr** [koekeishiya/kwm#590]
```
kwm: 4.0.5
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
```

Installed as per README, copied default config via ` cp /usr/local/opt/kwm/kwmrc ~/.kwm/kwmrc` and started kwm via `brew services start kwm`

`$ kwmc help` yields no output. 

kwm does tile my windows though.

**Comment by koekeishiya** [comment]
kwmc help is not a thing. see doc linked in config section of the readme

**Comment by jottr** [comment]
I had the impression that [it was a thing](https://github.com/koekeishiya/kwm/issues/269) though, you seem to have [removed it](https://github.com/koekeishiya/kwm/commit/eaf781087b95c3388947a2d79f51f267ec89c83c). 
While it eludes me right now why one would want to remove any helpful messages, I'm sure you have historical reasons for that decision.

**Comment by koekeishiya** [comment]
there used to be the help command, a man file and the website for kwmc and a readme in the github repo. when a syntax change was made  or new commands were added, i  had to update 4 files,  and i just could not be bothered at some point. The one official page i update is the one i linked above
