### ISSUE TITLE
[4.0.5] Seems to restart randomly

### ISSUE THREAD

**Issue by simonsmith** [koekeishiya/kwm#597]
Occasionally I'll have my window config reset as if I'd run `brew services restart kwm`. It seems to happen randomly and not just when I'm interacting with KWM.

Is there a way for me to see a debug output to see why it restarts?

**Comment by chrishoage** [comment]
kwm just isn't super stable and crashes sometimes. There are logs, and you probably have crash reports but in all likelihood the crashes will not be fixed as the author of this application has focused attention to a full rewrite of kwm https://github.com/koekeishiya/chunkwm

Chunkkwm will be more stable as the author is avoiding some pitfalls that were experienced in kwm.

**Comment by simonsmith** [comment]
@chrishoage Interesting, I was unaware of the rewrite. I'll keep an eye on that repo. Thanks
