### ISSUE TITLE
Explain code signing

### ISSUE THREAD

**Issue by jonashaag** [koekeishiya/kwm#6]
> Kwm requires access to osx accessibility. Creating a certificate and codesigning the binary works as well.
> Tested on Osx El Capitan (10.11.1 / 10.11.2).

This should be explained more thoroughly in the README as I don't know how to do it.

**Comment by D-Roch** [comment]
:+1:

**Comment by sergeatrelayr** [comment]
stuck here as well

**Comment by MrMage** [comment]
I suspect that this means using Apple's [codesign](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/codesign.1.html) tool to sign the binary with your own [Gatekeeper](https://developer.apple.com/developer-id/) certificates.

However, I'd also be very interested in how this can automatically grant access to the Accessibility API :-)

**Comment by koekeishiya** [comment]
As MrMage said, it basically means using Apple's codesign tool to sign the binary. However this is not really needed. The first time Kwm is started, it will prompt for accessibility access and so just allowing that is enough.

**Comment by MrMage** [comment]
Thank you. Do you know which exact parameters (or entitlements?) to use in order to automatically allow Accessibility? My own app also uses Accessibility but prompts even when signed.

**Comment by koekeishiya** [comment]
Uh I dont' really use the codesign approach myself, so I can't really say. All I did was run codesign -f -s certificate binary. This had to be done every time the binary changed.
