### ISSUE TITLE
BSP mode always start with vertical-split mode 

### ISSUE THREAD

**Issue by mingsu** [koekeishiya/kwm#602]
BSP mode always split the windows in vertical  mode. I prefer to split the screen to left|right, not always top|bottom.
Although it can be toggle the mode by `kmwc window -c split-mode toggle`, I still want it to initialize as user-specified mode, and even remember the mode after toggle it (it forget the mode after moving window to other space and moving back).

**Comment by chrishoage** [comment]
> BSP mode always split the windows in vertical mode.

I'm not sure this is a true statement. It follows the golden ratio (1.618)

```
kwmc config optimal-ratio {ratio}
    {ratio}: floating point number
```

```
kwmc display -c {mode}
    {mode}: optimal | vertical | horizontal
```

These two commands might be of use to you. The `optimal-ratio` will change the ratio of the container required to change the split mode. 

The second command can change the split mode of the current display.

**Comment by mingsu** [comment]
it works very well. thanks!
