### ISSUE TITLE
Padding and space in between Windows

### ISSUE THREAD

**Issue by knightjp** [koekeishiya/kwm#604]
![screen shot 2017-05-06 at 7 59 39 am](https://cloud.githubusercontent.com/assets/14360736/25773429/0c7def20-3232-11e7-8bc7-873f4d41dcc7.png)

I have been trying to edit the kwmrc file to remove the padding on the edges of the screen. But I can't seem to do it. Any ideas?

**Comment by dominiklohmann** [comment]
```
kwmc config padding 0 0 0 0
kwmc config gap 0 0
```

**Comment by knightjp** [comment]
@dominiklohmann Thanks for the info. I tried that. But it does not seem to work. The gaps still remain the same.

**Comment by dominiklohmann** [comment]
You might wanna link your kwmrc here, because those lines work as intended on my computer.

**Comment by knightjp** [comment]
Here is the file. 
[kwmrc.txt](https://github.com/koekeishiya/kwm/files/981353/kwmrc.txt)

**Comment by knightjp** [comment]
I switched back to Amethyst not being able to sort out this issue. On my computer I hide the taskbar and the Dock. Amethyst uses all of the available space for the app as it should, KWM is stuck on the padding. Doesn't make sense as the kwmrc file should show that I've edited it correctly.

**Comment by dominiklohmann** [comment]
```
/+ACo- Override default settings for space 1 on screen 0
   kwmc config space 0 1 mode monocle
   kwmc config space 0 1 padding 100 100 100 100
   kwmc config space 0 1 gap 40 40 +ACo-/

/+ACo- Override default settings for screen 1
   kwmc config display 1 mode bsp
   kwmc config display 1 padding 100 100 100 100
   kwmc config display 1 gap 40 40 +ACo-/
```

That part is overriding it for the first space and for the first display. Gotta remove it.

GitHub didn't send me a mail for your reply 2 days ago with the kwmrc, so I've seen it only just now, sorry for the late reply.

**Comment by knightjp** [comment]
@dominiklohmann thank you for the reply. So I just remove that complete section from the kwmrc file and it should work as intended? 
Thanks, that is brilliant. 
Personally I found kwm is a bit more faster than Amethyst. 
I would like to know... is this still being supported by the author and how does it compare with Amethyst in your experience?

**Comment by dominiklohmann** [comment]
The author of Kwm is rewriting it under the name [chunkwm](github.com/koekeishiya/chunkwm) which looks to be relatively close to its first alpha release. For now, development of Kwm itself seems to have stopped to focus work on its successor.

**Comment by knightjp** [comment]
What is your opinion on kwm as compared with Amethyst? I'm relatively new to both. So I haven't used either long enough to have an opinion.

**Comment by dominiklohmann** [comment]
It's been over a year since I last used Amethyst, but it always seemed slow to react to new windows to me back then.

**Comment by knightjp** [comment]
I was using Moom for a very long time till I came across video about Amethyst. In doing research about it, i came across this... [https://medium.com/@geekuillaume/a-tweaker-guide-to-osx-personalization-e3f2eef0eebc](url)
I thought that I would give KWM a shot.

**Comment by knightjp** [comment]
@dominiklohmann I'm sorry.. your advice did not work. Rather seemed to make the matter worse actually. Large windows were over flowing into the next screen and not resizing as they are supposed to be.  Now I put it back to the standard settings and this is what I have. 
![screen shot 2017-05-09 at 6 41 43 pm](https://cloud.githubusercontent.com/assets/14360736/25856486/32801862-34e7-11e7-8f33-e22c424e179d.png)

**Comment by dominiklohmann** [comment]
<img width="1680" alt="screen shot 2017-05-09 at 16 57 01" src="https://cloud.githubusercontent.com/assets/4488655/25857185/90737a7c-34d8-11e7-9016-edcd3eb9145f.png">

**Comment by koekeishiya** [comment]
Your kwmrc seems to be from an older versin (3.x.x ??), at least the parts about keybindings.
Try using the one provided in the examples directory instead: https://github.com/koekeishiya/kwm/blob/master/examples/kwmrc

With that said, **kwm** will probably not be receiving updates from this point on.
I spend my time on **chunkwm**, and **kwm** will be officially deprecated as soon as **chunkwm** gets the last 2 major features that it currently lacks.

**Comment by knightjp** [comment]
@koekeishiya I removed my previous install and reinstalled it again. This is the kwmrc file that I am using now - with the suggested settings from @dominiklohmann 
[kwmrc.pdf](https://github.com/koekeishiya/kwm/files/987067/kwmrc.pdf)

**Comment by knightjp** [comment]
I just do not understand why none of the changes to the spacing and the padding in the kwmrc file are not showing up. It just looks like a stock installation of 4.0.5 kwm 
I've tried removing it and reinstalling it, but nothing has worked.

**Comment by koekeishiya** [comment]
Make sure that the config you have edited is placed at $HOME/.kwm/kwmrc

You can also try to launch *kwm* from a terminal with the *config* argument:
`kwm -c /path/to/config`

**Comment by knightjp** [comment]
The kwmrc file is located in /usr/local/Cellar/kwm/4.0.5/
Is it supposed to be in a different location to that one? Is there another kwmrc file that I do not know about?

**Comment by koekeishiya** [comment]
If you installed using brew, you need to copy the sample provided by brew to $HOME/.kwm/kwmrc.
I believe this should be a part of the caveats printed after the homebrew install finishes.

*kwm* only reads `$HOME/.kwm/kwmrc`. If one does not exist, it will default to internally-specified settings.

**Comment by knightjp** [comment]
Then the instructions that I saw in here was wrong. 
https://www.youtube.com/watch?v=E4F1-DVNlHg

**Comment by knightjp** [comment]
After pasting the edited kwmrc file in ~/.kwm I was able to see the changes and get everything the way I want it. 
Thank you for assistance.
