### ISSUE TITLE
v4.0.5 - Blacklisting/Rules troubleshooting

### ISSUE THREAD

**Issue by gyangstar** [koekeishiya/kwm#609]
Before going into my question, Thank you all ... especially koekeishiya for supporting this app.

In general, I have solved most of my issues like tiling without a title bar. BTW if you have created and copied over the .kwmrc file into your home directory ... I had to restart kwm services and then it worked.

I have applications like Chrome, Atom, Outlook and Skype for Business which I would like not to be tiled when launched. I have made the entries into .kwmrc but they do not seem to take ... i have tried to troubleshoot by reading all of the posts, but have reached a point where I must ask if anybody has experience with this issue?

Here is the relevant code I have in .kwmrc

/*
The following commands create rules that
blacklists an application from Kwms tiling

    kwmc rule owner="Atom" properties={float="true"}
    kwmc rule owner="Chrome" properties={float="true"}
    kwmc rule owner="Steam" properties={float="true"}
    kwmc rule owner="Photoshop" properties={float="true"}

Thanks in advance for any answers or solutions ...

**Comment by koekeishiya** [comment]
This is a long shot, but if you are using the example config,

> /*
The following commands create rules that
blacklists an application from Kwms tiling

>    kwmc rule owner="Steam" properties={float="true"}
    kwmc rule owner="Photoshop" properties={float="true"}
*/

Make sure to remove the starting and ending `/*` and `*/` as they mark the enclosing text as coments and make kwm ignore them during parsing.

**Comment by gyangstar** [comment]
Thank you. I think that was it ... cleaned up all the */ in the previous lines. Thank you
