### ISSUE TITLE
[Master] Ignore some/all applications for tiling?

### ISSUE THREAD

**Issue by jwcorell** [koekeishiya/kwm#610]
Please forgive me if this is an ignorant question, I'm a new user.  Is it possible to disable auto-tiling for all windows and just use the app for the focus-follows-mouse feature?  I've spent a bunch of time browsing the documentation and experimenting in the config file, but I have not gotten it to successfully leave any apps out of the tiling process.

**Comment by koekeishiya** [comment]
if you set the tiling mode to `float`, no tiling will happen.

**Comment by jwcorell** [comment]
Thank you that did the trick.  Much appreciated
