### ISSUE TITLE
kwm does not respond to keyboard events from RehabMan/OS-X-Voodoo-PS2-Controller

### ISSUE THREAD

**Issue by kenthinson** [koekeishiya/kwm#611]
Hello, 
I'm not sure if this is a kwm issue or a Voodoo-PS2 issue. However as all other apps seem to work with Voodo-PS2 I'm leaning towards kwm. 

I'm running a hackintosh laptop. The keyboard is connected via a ps2 bus not the Usb bus like a real Mac. I'm using the RehabMan/OS-X-Voodoo-PS2-Controller driver to be able to get the keyboard to work. All apps seem to work excluding kwm. I understand you probably have more pressing issues that need fixing but I'm hoping you can point me in the right direction so maybe I can send you a pull request after I get it working. Thanks!

**Comment by chrishoage** [comment]
kwm does not have keyboard events. You need khd for keybindings 

https://github.com/koekeishiya/khd

**Comment by koekeishiya** [comment]
as chrishoage said ,you need to use **khd** or some other program that allows you to create system-wide hotkeys.
