### ISSUE TITLE
What's the difference between bsp, float and monocle?

### ISSUE THREAD

**Issue by KevinSjoberg** [koekeishiya/kwm#612]
Hi,

First of all. I really appreciate the time and effort put in into both `kwm` and `khd`. I just started using both.

What are the differences between `bsp`, `float` and `monocle`? What are the use-cases for using one over the other?

Thanks

**Comment by koekeishiya** [comment]
[info regarding bsp](https://en.wikipedia.org/wiki/Binary_space_partitioning)
simply put, (by default) even division of the screen between windows

monocle simply maximizes all windows, and lets you interact with a single window and switch between them.

float just means that kwm will not interfere with the window layout for this particular desktop, and is more or less the same as not running kwm at all.

**Comment by KevinSjoberg** [comment]
Thank you. Crystal clear. 👍

**Comment by vanjad-dev** [comment]
@koekeishiya Hi, just was asking myself the same question, and thought maybe suggest putting this in the docs? 

Thanks for awesome work,
Cheers
