### ISSUE TITLE
Window Split Vertically

### ISSUE THREAD

**Issue by knightjp** [koekeishiya/kwm#613]
How do I change the layout for the windows to split into columns first?

![screen shot 2017-06-30 at 12 54 33 pm 2](https://user-images.githubusercontent.com/14360736/27729516-3ffca5a4-5d97-11e7-8627-99b53dc05cdd.png)
![screen shot 2017-06-30 at 1 13 02 pm 2](https://user-images.githubusercontent.com/14360736/27729521-44ab25c6-5d97-11e7-8f49-7f772c91cc84.png)

**Comment by dominiklohmann** [comment]
You can change the split ratio to not be the golden ratio (1.618...) using `kwmc config optimal-ratio <value>`. Alternatively, use `kwmc display -c vertical` to always use vertical splits.

**Comment by knightjp** [comment]
"kwmc display -c vertical" worked.. but it made all the splits into columns. 
I would like the first split to be column and then each window to split equally after that. Much like what happen with the vanilla kwmrc file. 

Here is my kwmrc file
[kwmrc.pdf](https://github.com/koekeishiya/kwm/files/1114911/kwmrc.pdf)

**Comment by dominiklohmann** [comment]
As I said, change the split ratio to a value different from 1.618 instead.

**Comment by knightjp** [comment]
the split ratio is set to 0.5

**Comment by dominiklohmann** [comment]
No, the optimal ratio as I said in my above post

> You can change the split ratio to not be the golden ratio (1.618...) using kwmc config optimal-ratio <value>.

**Comment by knightjp** [comment]
Thanks for the assistance.. I finally got it done. Posting a pdf copy of my kwmrc here for reference. 
[kwmrc.pdf](https://github.com/koekeishiya/kwm/files/1116550/kwmrc.pdf)
