### ISSUE TITLE
[4.0.5] Shaking Windows and not able to move Windows.

### ISSUE THREAD

**Issue by knightjp** [koekeishiya/kwm#614]
![img_5610_jul 2 2017 12 21 00 am](https://user-images.githubusercontent.com/14360736/27765205-b86e32e8-5ebc-11e7-8a1b-bfe4189b9703.png)
The window on the top left is shaking left to right and I do not know what causes it. 

Plus I am not able to move to switch or move the windows. 
For instance if I want the youtube window to be moved to the right. I can't do it. If I try moving a window, the shaking thing happens. 
![screen shot 2017-07-02 at 12 17 29 am](https://user-images.githubusercontent.com/14360736/27765228-43a6a05c-5ebd-11e7-9d84-fd6e128a2755.png)

**Comment by knightjp** [comment]
@koekeishiya Are these problems caused because I did not install Xquartz? Is XQuartz a requirement for KWM?

**Comment by koekeishiya** [comment]
kwm does not relate to xquartz. xquartz is a standalone application for starting an x windowing server. 

you need to disable `lock-to-container` if you want to drag windows using the mouse.
`kwmc config lock-to-container off`

**Comment by knightjp** [comment]
@koekeishiya Thank you for the info. Sorry if I have been pain with all the questions. 
Maybe this is the setting that causes the windows to shake...
