### ISSUE TITLE
Can't input specific character anymore

### ISSUE THREAD

**Issue by ITler** [koekeishiya/kwm#619]
I'm using iTerm2 3.1.5 on Mac Sierra.
So far everything worked fine from my perspective, but suddenly during my daily work I'm not able to put in a `}` anymore. A few minutes ago, it perfectly worked. While typing in my shell, I could image, I was hitting some cruel Keyboard shortcut causing this issue, but I have no idea which one and how to investigate, as I never intentionally did a keyboard mapping for that particular key.
However, as there is no problem within other applications like vim or default Mac Terminal, the conclusion is, that it really relates to iTerm2. I've got no problems with other keys, i.e. `{`. This problem persists after closing iTerm2 and even rebooting the machine.
Could anybody help?

**Comment by dominiklohmann** [comment]
I'm assuming this is a misconfiguration of [khd](https://github.com/koekeishiya/khd), remapping the key combination used to type a closing brace to something else. This is unlikely to be related to kwm at all. You should check your `~/.khdrc` file for relevant entries.

**Comment by ITler** [comment]
It seems I ended up in the wrong repository ...sorry... Thursday fail
