### ISSUE TITLE
Inconsistent Movement of Floating Windows

### ISSUE THREAD

**Issue by Amar1729** [koekeishiya/kwm#621]
kwm version: 4.0.5
macOS: Sierra

I saw [this earlier issue](https://github.com/koekeishiya/kwm/issues/82) asking for a command to move floating windows. I know `kwm` is deprecated, but I wanted to make sure whether I'm doing something wrong or if there's actually something wrong with the `kwmc window -m xoff yoff` command.

When I try `kwmc window -m 10 10`, I receive the error `Expected token of type 'Token_Digit'`. I tried it with three numbers after `-m` instead, and while the command works it results in inconsistent movement of the focused floating window:

```
0	0	0	nothing
0	0	10	down 10 px
0	10	0	right 10 px
10	0	0	nothing
0	10	10	down/right 10 px
10	0	10	down 10 px
10	10	0	right 10 px

0	0	-0	Expected token of type 'Token_Digit'
0	-0	0	Expected token of type 'Token_Digit'
-0	0	0	nothing
0	-0	-0	Expected token of type 'Token_Digit'
-0	0	-0	nothing
-0	-0	0	Expected token of type 'Token_Digit'
-0	-0	-0	Expected token of type 'Token_Digit'

10	10	-10	Expected token of type 'Token_Digit'
10	-10	10	Expected token of type 'Token_Digit'
-10	10	10	down/right 10 px
10	-10	-10	Expected token of type 'Token_Digit'
-10	10	-10	down/right 10 px
-10	-10	10	Expected token of type 'Token_Digit'
-10	-10	-10	Expected token of type 'Token_Digit'

-0	10	10	down 10 px
-0	10	0	down 10 px
-0	0	10	nothing
-0	0	0	nothing
-10	10	10	down/right 10 px
-10	10	0	down/right 10 px
-10	0	10	right 10 px
-10	0	0	right 10 px

-0	0	-0	nothing
-10	0	-0	right 10 px
-0	10	-0	down 10 px
-10	10	-0	down/right 10 px
-0	0	-10	nothing
-10	0	-10	right 10 px
-0	10	-10	down 10 px
-10	10	-10	down/right 10 px

[north|south|west|east] 10 10	nothing
```

In general it seems that:
* second token can't have a hyphen
* third can only have a hyphen if the first does
* can move a floating window south and east, but not north or west

**Comment by koekeishiya** [comment]
Honestly , I don't remember much how any of the code in kwm works, but I would assume that this is a bug.

**Comment by Amar1729** [comment]
Yeah, figured. I'm switching to chunkwm soon anyway.

**Comment by koekeishiya** [comment]
I would definitely recommend that. If there is a feature that kwm has that chunkwm does not, just create an issue in the chunkwm repo and we can take it from there.
