### ISSUE TITLE
Notification Center prevents kwm from working

### ISSUE THREAD

**Issue by flou** [koekeishiya/kwm#66]
As long as there is a notification displayed (from Notification Center) on screen kwm no longer seems to work : focus doesn't follow the mouse and keybindings have no.

When the notification is gone, everything goes back to normal and works properly.

**Comment by koekeishiya** [comment]
see `kwmc config menu-fix` , disable this in config to prevent this.
The reason for having this is so that users can interact with their menubar/context menus without focus-follows-mouse causing the menu to close.
