### ISSUE TITLE
Should not focus window below cursor when focus mode is disabled

### ISSUE THREAD

**Issue by oetting** [koekeishiya/kwm#67]
When cleaning up it looks like you have mistakenly removed the code that made sure osx focus was used when focus mode is disabled. (it worked very well, so thank you for implementing that :) )

I think line 496 and 512 of window.cpp should have `&& KwmFocusMode != FocusModeDisabled` added to the if statements.

**Comment by koekeishiya** [comment]
line 496 is a fix that has to be there for multiple monitor support I believe, 512 can be changed however.
The 496 should not impact how focus works when cycling through screens with `winidow -f prev|next` and `config cycle-focus all` is set.

**Comment by oetting** [comment]
Ok. I am not currently using the multi monitor support, so I did not test that. It just looked like it should be there to make sure it is the previously focused window that gets focus, and not the one with the mouse above it. 

Sounds good with a fix for the space change thing.
