### ISSUE TITLE
OSX Accessibility permissions have to be reapplied after each new build

### ISSUE THREAD

**Issue by twouters** [koekeishiya/kwm#68]
After rebuilding kwm with `make install` and stopping the currently running daemon with `launchctl stop com.koekeishiya.kwm`, launchd immediately restarts kwm and a dialog appears requesting permission to use OSX Accessibility API.
The dialogs keeps popping up as launchd tries to start kwm until the permission has been toggled (uncheck kwm and recheck kwm).

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/kwm/issues/44
