### ISSUE TITLE
Subsequent builds don't always result in the same binary

### ISSUE THREAD

**Issue by twouters** [koekeishiya/kwm#69]
I don't know if this is an issue or not, but I've noticed that building kwm doesn't always result in the same CRC.

Resulting binaries after running the following until I see a CRC change `while true; do make > /dev/null 2>&1 && date && crc=$(crc32 bin/kwm) && echo $crc && mkdir -p $crc && cp -a bin $crc && make clean ; done` on bf03e9b043d8a8dfcb2bd9e6f5c29e641ade1c0c:

~~~
$ crc32 6bf27359/bin/kwm 6fffe9c4/bin/kwm
6bf27359	6bf27359/bin/kwm
6fffe9c4	6fffe9c4/bin/kwm
$ cmp -b 6bf27359/bin/kwm 6fffe9c4/bin/kwm
6bf27359/bin/kwm 6fffe9c4/bin/kwm differ: byte 1793, line 3 is 152 j 216 M-^N
~~~

**Comment by koekeishiya** [comment]
This is most likely due to compiler optimization (I have specified -O3 in the makefile).

**Comment by twouters** [comment]
I've removed -O3 from BUILD_FLAGS and it still happens - I really don't know if this is something to worry about, it's just something that I've noticed.

**Comment by koekeishiya** [comment]
I have no clue really why this is happening, on the latest commit these are the 2checksum that keep repeating for me: "fe251aab" and "3de0fcc6".

I'll try build with -Wall and fix up some things, maybe it could be related.

**Comment by koekeishiya** [comment]
This still happens, but everything appears to be working just fine regardless of which binary is generated. I'm gonna assume that this is due to the carbon framework and out of my control.
