### ISSUE TITLE
Autoraise / autofocus not working

### ISSUE THREAD

**Issue by dvcrn** [koekeishiya/kwm#72]
Hi, just found out about this cool project and playing around with it right now. 

Most of the window operations work fine to me but I couldn't manage to get autofocus or autoraise working. I'm using the default config on the latest OSX 

![screen shot 2016-01-13 at 11 11 55 am](https://cloud.githubusercontent.com/assets/688326/12283029/7f50d1a4-b9e6-11e5-98e7-219395aeb168.png)

I was wondering if I missed any requirements or if it should work "out of the box". Everything in accessibility is enabled

(Also I noticed that on first start after the grid is applied, most keybindings (especially the ctrl+alt+cmd group) are not working. I have to apply monocle layout and then bsp layout again before it starts registering them)

**Comment by koekeishiya** [comment]
Since you do not have auto-hide set for OSX menubar, make sure that you have `kwmc config menu-fix disable` in the kwmrc file.

**Comment by dvcrn** [comment]
Yep, that was it! Amazing project by the way. Will definitely try to keep it running over the next days :)
