### ISSUE TITLE
Makefile fails to create ~/.kwm directory

### ISSUE THREAD

**Issue by nwertman** [koekeishiya/kwm#74]
After puling master this morning, I noticed that ~/.kwmrc had moved to ~/.kwm/kwmrc.  Unfortunately, it doesn't seem that the makefile is making the directory properly:

```
g++ kwmc/kwmc.cpp kwmc/help.cpp -O3 -Wall -o bin/kwmc
cp -n examples/kwmrc /Volumes/Data/Users/local/.kwm/kwmrc
cp: /Volumes/Data/Users/local/.kwm/kwmrc: No such file or directory
make: *** [/Volumes/Data/Users/local/.kwm/kwmrc] Error 1
```

**Comment by nwertman** [comment]
Pull Request: https://github.com/koekeishiya/kwm/pull/75

**Comment by koekeishiya** [comment]
Accepted pull request, thanks.
