### ISSUE TITLE
'make' fails if .kwm/kwmrc is a symlink

### ISSUE THREAD

**Issue by nwertman** [koekeishiya/kwm#77]
I use 'stow' to keep all my dot files in a git repo.  This command automatically symlinks dot files into my repository checkout.

It appears that kwm's makefile isn't smart enough to detect that the .kwm/kwmrc file exists (since it is a symlink) causing the make process to fail.

```
$ ls -lad ~/.kwm/kwmrc
-rw-r--r--  1 local  staff   3.9K Jan 15 15:48 /Volumes/Data/Users/local/.kwm/kwmrc
$ make
mkdir -p /Volumes/Data/Users/local/.kwm
cp -n examples/kwmrc /Volumes/Data/Users/local/.kwm/kwmrc
make: *** [/Volumes/Data/Users/local/.kwm/kwmrc] Error 1
$
```

**Comment by koekeishiya** [comment]
So apparently the "test ! -e" flag does not work as it should..

**Comment by nwertman** [comment]
Thanks!
