### ISSUE TITLE
Allow marked window to be moved to a new leaf 

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#78]
I often find my self wanting to move a window to a new leaf in the tree. Currently what I do is float the window I want to move, mark the window I want to move to, then unfloat the window to create the new leaf. 

I purpose a command to automate this task (as always feel free to change as you see fit):

```
kwmc window -t mark # mark for cut 
kwmc window -f next # focus desired window to create new container
kwmc window -x # create container and move marked window
```

This command would essentially automate the manual process described above. Mark a window you want to move, focus the window you want to create a leaf and issue command to create leaf with the marked window.

**Comment by koekeishiya** [comment]
Works as you described.

Mark a window you want to move, focus the window where you want to create a leaf and issue command `kwmc window -x` to insert a new leaf at the focused container.
