### ISSUE TITLE
Regarding the screenshot

### ISSUE THREAD

**Issue by fjolnir** [koekeishiya/kwm#8]
This is not an issue, just a question.

How are you achieving the titlebar free / outlined iTerm windows? Is it simply a mod of iTerm itself, or did you write a plugin to do it?

**Comment by rastasheep** [comment]
It's in Preferences > Profiles > Window > 'Style' drop-down > No Title Bar.

(I'm not sure if it's still only feature of nightly builds)

**Comment by will118** [comment]
Ah thanks, I was also curious about that. The beta has it now (just grabbed it).

I have another question though: What about that menu bar?

**Comment by koekeishiya** [comment]
The Apple menubar is hidden using the option that was added with El Capitan. I'm using the program nerdTool to create the illusion of a bar that you see in the screenshot.

**Comment by Zhann** [comment]
@koekeishiya care to share/export that bar configuration? It looks great.

**Comment by koekeishiya** [comment]
[nerdTool-Bar.zip](https://github.com/koekeishiya/kwm/files/69650/nerdTool-Bar.zip)
Scripts have to be customized for your system according to resolution.
The actual bar is just an image file that is displayed below the printed info.

**Comment by fjolnir** [comment]
Thanks for the explanation.

(Side note: when I was writing http://github.com/fjolnir/xnomad I achieved focus follows mouse via SIMBL(squeezed into http://github.com/fjolnir/afloat))

**Comment by koekeishiya** [comment]
Oh right, uh the titlebar free iTerm is done with the iTerm setting as rastasheep explained.
If you are wondering about the green border, I wrote a script that basically draws a transparent rectangle using (hammerspoon) hs.drawing extension. This can be found here:  https://gist.github.com/koekeishiya/dc48db74f4fdbfbf5648

**Comment by anders-dc** [comment]
Really liking kwm so far, especially now that keybindings aren't compiled but set in `.kwmrc`.

Quick question, what is the name of the web browser in the two panes on the left in the new screenshot?
https://cloud.githubusercontent.com/assets/6175959/12092967/8d8853d8-b300-11e5-8a44-ec1245efdc74.png

**Comment by koekeishiya** [comment]
I'm using firefox with stylish for custom css

**Comment by vanillasoap** [comment]
Is that "archey" you're running there? I really like how the apple logo is looking. Possible to share?

side note: I love kwm, can't live without it. keep up the good work :+1:

**Comment by koekeishiya** [comment]
The logo and information is printed using the program screenfetch.

**Comment by herrbischoff** [comment]
Just wanted to add that I recreated @koekeishiya's NerdBar configuration for use in [Übersicht](http://tracesof.net/uebersicht/):

https://github.com/herrbischoff/nerdbar.widget

Maybe that's of interest for someone else but me. ;)

**Comment by koekeishiya** [comment]
That looks great, I'll be using it for sure. Übersicht seems a lot easier to main and change than nerdTool is. Thanks.

I may put it up as an example in the readme.md for how to get a decent bar if you don't mind?

**Comment by herrbischoff** [comment]
@koekeishiya: Sure, go ahead. License is MIT btw, just as `kwm`. Please also feel free to send PRs in case you adjust something like distances, etc. Those may be off as I didn't spend a lot of time optimizing them. The colors were mostly grabbed through a color picker, so feel free to adjust them where necessary as well.

**Comment by koekeishiya** [comment]
I have now added a some description / link regarding your widget to the readme.md.
Thanks again : >

**Comment by herrbischoff** [comment]
You're very welcome! The least I can do for my now favorite window manager. ;)
