### ISSUE TITLE
focus-follows-mouse raises windows below preferences window

### ISSUE THREAD

**Issue by herrbischoff** [koekeishiya/kwm#80]
To better illustrate, I have made a short screen recording:

![untitled](https://cloud.githubusercontent.com/assets/8957346/12373073/97e70af6-bc6d-11e5-8133-32ba815a9749.gif)

Is this to be considered a bug or do I have configured something wrong?

Relevant excerpt from `.kwm/kwmrc`:

```
# Turn off focus-follows-mouse if any
# context-menus or the menubar is visible.
# If the menubar is not set to auto-hide,
# disable this setting.
kwmc config menu-fix disable

# Set focus-follows-mouse-mode to autoraise
# kwmc config focus autoraise

# Enable mouse-follows-focus
kwmc config focus mouse-follows disable
```

I suspect it may be the `menu-fix disable` part I changed [as per your suggestion](https://github.com/koekeishiya/kwm/issues/73#issuecomment-171766670).

**Comment by koekeishiya** [comment]
This is due to focus-follows-mouse being autoraise. Which gives focus and brings the window to the front. You could try looking into autofocus, but I have no idea how well that performs as I rarely use it myself.

**Comment by herrbischoff** [comment]
> Edit: Ok what, this should not be happening unless the cursor actually moves outside of the preferences window.

That's exactly what was bugging me. Autoraise is completely expected, once the pointer actually *leaves* the current window, not before.

**Comment by koekeishiya** [comment]
I have a feeling that this is not caused by any focus-follows-mouse settings in general, but rather Kwm not detecting that the preference window is there at all, which is also why it did not get tiled.

This is not something I can fix within Kwm, but I have provided a system that allows user to allow specific windows that misbehave, to be detected by Kwm.

See last edit of my previous post.

**Comment by herrbischoff** [comment]
Thanks. I have added the following line and restarted `kwm`:
```
kwmc config add-role AXSystemDialog Bartender Preferences
```

Unfortunately, this did not work. According to Accessibility Inspector, the hierarchy of the window is:
```
AXApplication
    AXWindow:AXSystemDialog
```

**Comment by koekeishiya** [comment]
`kwmc config add-role AXSystemDialog Bartender 2` should do it.

To find the proper name, you can add the following to line 152 of window.cpp:
> DEBUG(KWMTiling.WindowLst[WindowIndex].Owner)

**Comment by herrbischoff** [comment]
Indeed, this did it. Thanks! But why `Bartender 2`?

**Comment by koekeishiya** [comment]
You need the name of the application, and not the specific window.

In all cases I've come across so far, the name you have to specify seems to match the name of the .app file/folder, which I assumed was Bartender 2.

**Comment by herrbischoff** [comment]
Great, that should make it easier to set it up. Thanks!
