### ISSUE TITLE
Removal of live-coded hotkeys (hotkeys.cpp)

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#81]
The bind-system has been going through a lot of changes recently, so I was wondering if there is any reason at all to keep the live-coding hotkey system. I currently do not use this myself, although it does allow for more advanced things, that the current bind system cannot (and will not) support.

Examples of this may be simple things such as performing different commands depending on if a program is running or not, time of day, or really anything you could think of.

If there have been no objections here after a week or so, I will simply get rid of this system.
The ability to remap keys will also be lost if this goes through.

**Comment by chrishoage** [comment]
I personally think that it can be removed _especially_ if you plan on releasing codesigned binaries for consumption in package managers (homebrew). 

The current binding system is plenty powerful and should cover 90% of use cases. The other 10% could fork the project and make modifications as they see fit.

**Comment by koekeishiya** [comment]
I'm just gonna go ahead and remove this.
If anyone wants to have this, just clone latest commit that still has this system and copy paste the code inside your own fork.
