### ISSUE TITLE
Command to move/resize floating windows

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#82]
It could be useful to be able to interact with floating windows using the keyboard.

**Comment by herrbischoff** [comment]
:+1:

**Comment by oetting** [comment]
It might also be useful to be able to navigate between the floating windows of a space (next/previous floating window) and to switch back and forth between the floating and the non-floating window list.

**Comment by pldubouilh** [comment]
+1

**Comment by geekuillaume** [comment]
I just tried KWM and indeed, not being able to focus floating windows with the shortcuts feels like a bug. The floating windows should be treated like the others windows for this functionality.

**Comment by koekeishiya** [comment]
> I just tried KWM and indeed, not being able to focus floating windows with the shortcuts feels like a bug. The floating windows should be treated like the others windows for this functionality.

This is something that 99% will not happen, due to the complexity I

**Comment by koekeishiya** [comment]
Still not sure how to best make use of floating windows, as Kwm is not really supposed to be a manager for floating windows at all.

To move a floating window around for now, the command `kwmc window -m xoff yoff` can be used.
