### ISSUE TITLE
Floating window focusing issues

### ISSUE THREAD

**Issue by dvcrn** [koekeishiya/kwm#85]
I noticed these when I was playing with floating windows and the floating layout:

- Alert / message boxes always loose focus when the mouse hovers over a position where a underlaying window is positioned at
- Menus like 

![screen shot 2016-01-18 at 10 49 28 am](https://cloud.githubusercontent.com/assets/688326/12381626/3529fa58-bdd1-11e5-9115-75c30a8302b9.png) 

loose focus either immediately when navigating to a position where a other window is positioned or on "clickdown". Mostly it happens that the click doesn't even finish on the menu item and it directly focuses the other window

**Comment by koekeishiya** [comment]
See `kwmc config menu-fix enable|disable`. Turning this on might cause issues if you do not have the OSX menubar set to autohide.

**Comment by dvcrn** [comment]
Since this is the second ticket I opened caused by the autohide of the menubar, could you maybe explain how exactly `menu-fix` is working? This might help me to understand when I need it and when not.

**Comment by koekeishiya** [comment]
Uh, basically if `menu-fix` is enabled, you have to autohide the OSX menubar.
What it essentially does, is disable focus-follows-mouse while there is a window visible on screen, that has a window layer not equal to 0 (the value used for normal windows). 
Floating windows, dock, context menus and so on has a value that is non zero. This includes the menubar, which is why autohide of OSX menubar must be enabled if `menu-fix` is enabled

**Comment by oetting** [comment]
Would it be possible to get the target of the mouse down event, instead of finding the window that is beneath the mouse location? That would make it easier to know if the click hit something we care about.

**Comment by koekeishiya** [comment]
`menu-fix` has been removed in the latest commit.

All context-menus, dialogs and whatever should now properly get focused (and not be lost).
This should work regardless of having the OSX menubar visible or not.

**Comment by herrbischoff** [comment]
> All context-menus, dialogs and whatever should now properly get focused (and not be lost).
> This should work regardless of having the OSX menubar visible or not.

Yay! I will give it a spin right away. :)
