### ISSUE TITLE
focused-border glitches out for notifications

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#89]
<img width="1440" alt="screen shot 2016-01-19 at 16 14 17" src="https://cloud.githubusercontent.com/assets/4488655/12422612/1cbf40de-bec8-11e5-844e-8c2810ebf78d.png">

**Comment by koekeishiya** [comment]
The kwm-overlay application wasn't written by me, and I have no experience programming in Swift (or towards Cocoa for that matter). This is not an issue I will be able to resolve.

Maybe @chrishoage may know more about this.

**Comment by chrishoage** [comment]
I  am not able to reproduce this issue. 

I have tried `osascript -e 'display notification "Lorem ipsum dolor sit amet" with title "Title"'` and the overlay stays put. 

@dominiklohmann do you have steps to reproduce this issue?

**Comment by dominiklohmann** [comment]
Only thing I do to reproduce this is move my mouse towards the notification. Also tested it with the default kwmrc with enabled borders, same issue.

<img width="1440" alt="screen shot 2016-01-19 at 19 08 59" src="https://cloud.githubusercontent.com/assets/4488655/12427537/22565894-bee0-11e5-9da4-02528c0d31bf.png">

**Comment by chrishoage** [comment]
There really isn't much I can do unless I can repo the issue. 

Please keep me posted if you find out any more information about what might contribute to this issue. 

<img width="448" alt="screen shot 2016-01-19 at 10 12 49 am" src="https://cloud.githubusercontent.com/assets/1056886/12427655/4bc62538-be95-11e5-918f-20e10b453389.png">

**Comment by chrishoage** [comment]
Apologies, I was not on head. I am able to repo this issue. 

@koekeishiya this appears to be due to the menu fix changes?

**Comment by dominiklohmann** [comment]
The Alfred window and the notification center also get a highlight border if you move your mouse towards them, don't think that should be a thing either. As does the Safari address window... Do these fall into the same category somehow?

**Comment by chrishoage** [comment]
Yeah it looks like the removal / change of the menu fix code (which I had disabled) caused these issues. This actually is isn't something I can fix. 

@koekeishiya will have to be selective with what types of windows get the border?

**Comment by koekeishiya** [comment]
This will prevent the border from being applied to some dialog-windows and so on. Kwm-Focus will shift even if the border remains in the old place.

This is the limitations we have to live with. I could potential have it clear the border if leaving it in the "previous focused" position.

**Comment by chrishoage** [comment]
This fix seems perfectly fine to me. 

I don't mind having the "previous focused" behavior. In fact it's in line with how the behavior was before.
