### ISSUE TITLE
Moving windows between screens is broken

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#91]
So in the latest commit, it appears that moving a window between screens is now broken.
No idea yet why this happened, as there has been no change to this part of the code.

How it used to work:
> `screen -m prev|next|id` would untile the focused window, move and resize it to the new screen.
The old screen would rebalance the window tree. The new screen would be flagged for update.

What happens now:
> `screen -m prev|next|id` does not untile the focused window, it does not move and resize the window before the cursor moves to the next screen. The old screen then appears broken and does not rebalance before the cursor is moved back to this screen.

**Comment by chrishoage** [comment]
Could the overlay be interfering with this?

**Comment by koekeishiya** [comment]
Are you able to reproduce said behaviour?

I have disabled the border code, along with the AXObserver calls, and the problem still seems to persist for me...

**Comment by chrishoage** [comment]
Not consistently, no. Sometimes it works, other times I see behavior like you described. 

It mostly works though

**Comment by chrishoage** [comment]
Oh shoot. I'm not on head. I'll update and test.

**Comment by chrishoage** [comment]
Exact behavior you described on HEAD. So it broke in the last 24 hours of commits.

**Comment by koekeishiya** [comment]
Still broken in 7ca022f

**Comment by chrishoage** [comment]
I was on 63710ab before I updated.

**Comment by koekeishiya** [comment]
Still broken in: 564fd0c4f1a79c10d174df328d69867398363b8e

**Comment by koekeishiya** [comment]
I believe I have found the cause of this issue. It is most likely when I added option for new windows to become the "left" or "right" split.
