### ISSUE TITLE
Laggy key-input in some applications while Kwm is running

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#92]
While typing in the urlbar-field of firefox, the input appears to be really laggy and not register all keypresses. I have not experienced this in other applications so far.

This is only happening while Kwm is active, and returns to normal if I quit Kwm.

**Comment by koekeishiya** [comment]
This randomly stopped happening after a system reboot.

**Comment by chrishoage** [comment]
I have been experiencing this, gonna try a restart and see if it fixes it.

**Comment by koekeishiya** [comment]
This appears to have something to do with the focused border.
When typing in a textbox, that spawns a listbox or similar, the focused-border callback kicks inlike 6 times for no reason, causing lag.

I do not know why this happens, because Kwm does not change focus.

**Comment by chrishoage** [comment]
I have seen this behavior in Slack several times still. Only Slack as far as I can tell. Chrome and iTerm and Sublime Text (all which I type a lot in) haven't had this issue. 

Slack also appears to ignore `capture` commands when the screen is empty. Other windows capture fine with an empty screen. Slack seems to have some strange behavior for some reason

**Comment by chrishoage** [comment]
I've had this happen in chrome too in a regular `textarea`, nothing that spawned a list box. 

I still can't place any exact steps to reproduce. This has happened to me monocle and tiled windows alike. 

So far I've seen this in text areas in Slack, and Chrome. This has never happened in Sublime Text. 

All keypresses eventually make it to the text area, it's almost as if KWM gets stuck in some loop for a few moments then delivers captured keypresses.

**Comment by koekeishiya** [comment]
Hm weird, I have not had any issues with this in monocle / bsp tiled windows.
Kwm no longer has any loops that it could get stuck in anymore, so that is not it.

I suspect it could have to do with how it monitors events (keydown, keyup,mousemove) etc,
although there is really nothing I can change about that, as it relies on a callback function that the system will call passing the approriate information.

**Comment by chrishoage** [comment]
Maybe it has to do with the window notification updates in order to keep the border over floating windows. 

It might be worth looking into removing that code entirely and never drawing a border over floating windows. That way that observer could be taken out?

**Comment by chrishoage** [comment]
I'm curious if different `WindowLevel`s might help you? 

https://github.com/MaddTheSane/SwiftMacTypes/blob/master/SwiftAdditions/AppKit.swift#L12

Maybe the fact that focused border is a "floating" window causes issues?

**Comment by chrishoage** [comment]
For example would `DesktopWindowLevelKey` with some math to make the border big enough to be seen from "behind" the window make any difference in your ability to keep track of windows?

**Comment by koekeishiya** [comment]
All I really know is that it happens because of the AXObserver thing.

**Comment by koekeishiya** [comment]
If you still have this problem, I believe I have found a way that appears to allow for global hotkeys without the use of the event taps (which is most likely the reason for this).

**Comment by chrishoage** [comment]
I actually do still have this problem. It's pretty rare, but it gobbles up keypresses for a few seconds when it does.

**Comment by koekeishiya** [comment]
I'll try and implement the method I discovered, when I have time.
If it ended up solving the problem, that would be pretty great.

**Comment by chrishoage** [comment]
Yeah throw it in a branch and ping me whenever you do. I'll try it out for a while. It's seriously rare, but pretty frustrating when it does happen.

**Comment by chrishoage** [comment]
I have been running with kwm logging on the past couple days. I have been having this pop up every once in a while still. 

I noticed this log happens when I get laggy key input

```
Restarting Event Tap
Restarting Event Tap
Restarting Event Tap
Restarting Event Tap
```

does that mean anything to you and would it have anything to do with laggy key input?
