### ISSUE TITLE
Tools like PopClip do not work any more

### ISSUE THREAD

**Issue by herrbischoff** [koekeishiya/kwm#93]
Since #85 and the removal of `menu-fix` I cannot use [PopClip](http://pilotmoon.com/popclip/) any more. I suspect other tools relying on an interactive overlay may be broken as well. `kwm` switches to the PopClip application and thereby losing the context to act on.

<img width="221" alt="screen shot 2016-01-20 at 12 21 06" src="https://cloud.githubusercontent.com/assets/8957346/12447415/55d637da-bf70-11e5-8f9c-85ef5af68b37.png">

**Comment by koekeishiya** [comment]
I really hate the layer system implemented in OSX..
Will see if something can be done about this in the future.

**Comment by herrbischoff** [comment]
Thanks, because until there is a fix I need to unload `kwm`.

**Comment by koekeishiya** [comment]
I have a fix working atm, that still allows for menubar/dock/context menus to work, but I'm not sure if it may break focusing of other window types.

Basically it has to do with:
```
 enum _CGCommonWindowLevelKey {
   kCGBaseWindowLevelKey         = 0,
   kCGMinimumWindowLevelKey      = 1,
   kCGDesktopWindowLevelKey      = 2,
   kCGBackstopMenuLevelKey       = 3,
   kCGNormalWindowLevelKey       = 4,
   kCGFloatingWindowLevelKey     = 5,
   kCGTornOffMenuWindowLevelKey  = 6,
   kCGDockWindowLevelKey         = 7,
   kCGMainMenuWindowLevelKey     = 8,
   kCGStatusWindowLevelKey       = 9,
   kCGModalPanelWindowLevelKey   = 10,
   kCGPopUpMenuWindowLevelKey    = 11,
   kCGDraggingWindowLevelKey     = 12,
   kCGScreenSaverWindowLevelKey  = 13,
   kCGMaximumWindowLevelKey      = 14,
   kCGOverlayWindowLevelKey      = 15,
   kCGHelpWindowLevelKey         = 16,
   kCGUtilityWindowLevelKey      = 17,
   kCGDesktopIconWindowLevelKey  = 18,
   kCGNumberOfWindowLevelKeys    = 19 
```

**Comment by herrbischoff** [comment]
Cool, thank you very much for the quick turnaround! It appears to work for me.
