### ISSUE TITLE
Smarter bind-parser to allow concatenated commands

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#95]
As stated in the title, I'd like to be able to allow for multiple commands to be executed in a single bind. This is something I feel is really lacking now that the "live-coded hotkey system" that allowed for doing this, has been removed.

The way I see it, this could work in a few different ways.

1. If you want to move a window to a differnt screen, and at the same time work on that screen, you would currently have to execute `screen -m 1` AND `screen -f 1`. I'm thinking something like `screen -mf 1` could be used to combine these actions. This would restrict the system to commands related to each other.

2. Allow for arbitrary joining of commands through simple chaining. By this, I mean something like the following: `bind cmd+alt-2 screen -m 1 && screen -f 1`. This would move a window AND focus the screen. Because this is done through chaining, you would be able to combine the commands you'd like regardless of their relation.

If we had 2. implemented, it would allow for things such as restoring a bsp-layout and automatically open applications (in the order you yourself specify) which would bring up an entire "dev workspace" at the press of a hotkey.

Or more trivial things, such as making a window floating and automatically set the focus mode to autofocus instead of autoraise and so on.

**Comment by chrishoage** [comment]
I think option 2 is more powerful, because it could be used with `sys`. One thing that would be nice is to allow the chain to span across multiple lines. 

For example one thing I have wanted is a command to increase and decrease the padding of all sides, and change the gaps of both x, and y at the same time. 

Now this could be achieved with an `all` keyword, but I think it would be interesting to allow for what you suggested to cover that case 

```
kwmc bind prefix-uparrow space -p increase top && 
                         space -p increase right &&
                         space -p increase bottom &&
                         space -p increase left

kwmc bind prefix-uparrow space -p decrease top && 
                         space -p decrease right &&
                         space -p decrease bottom &&
                         space -p decrease left

```

**Comment by a-morales** [comment]
I also think option 2 is more powerful, since it can potentially allow the recreation of the "live-coded hotkey system" with the use of `sys` commands. Though with chaining there should be a check when using `sys` commands to check the exit code before running the next command in the chain.

**Comment by koekeishiya** [comment]
I will probably go for option 2. That's the one I personally prefer to have as well.

**Comment by koekeishiya** [comment]
Not sure if I'm gonna bother doing this due to complexity, as it can more or less be achieved by the user creating a bash script, that is bound using kwmc bind.

**Comment by chrishoage** [comment]
I think just using `sys` command  + shell scripts to achieve this is fine. It would be nice however to be able to specify a `commands` directory. Getting `$PATH` to be read my processes managed by `launchd` is a little bit of a [pain in the ass](http://apple.stackexchange.com/questions/106355/setting-the-system-wide-path-environment-variable-in-mavericks). 

Being able to specify like

`kwmc config path ~/.kwm/commands`

then 

`kwmc bind prefix-return sys open-iTerm.applescript`

would be convenient and would allow for the dotfiles to be much more portable between systems.

**Comment by koekeishiya** [comment]
would this be required, or can I simply force users to put them inside $HOME/.kwm/commands/move-and-focus.sh

**Comment by chrishoage** [comment]
I figured it would be optional, and I really should have used another folder other than `.kwm` because 

`kwmc bind prefix-return sys ~/.kwm/commands/open-iTerm` actually already works. 


After thinking on this some more I don't actually think you should add support for this. It's not worth the added complexity since it can be achieved though OSX features.

**Comment by koekeishiya** [comment]
Guess this is not gonna happen, just bind usercreated scripts instead.
