### ISSUE TITLE
Floating focused border no longer updates

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#96]
As of the most recent commit, a floating windows border (I tested with system preferences and istat menus) border no longer updates upon moving the window.

**Comment by koekeishiya** [comment]
Can confirm, think I know how this broke. Will fix asap.

**Comment by koekeishiya** [comment]
Im starting to think this has never worked for system preferences or any other window that is automatically made floating due to the `float-non-resizable` option.

It works fine for windows that are floated manually.

**Comment by chrishoage** [comment]
Hrm, I actually have both `kwmc config float System Preferences` and `kwmc config float-non-resizable enable` in my `kwmrc` file. 

I can assure you tat Sys Prefs did update the border upon move the very first time you added support for it (it is what I used to very it worked).

Maybe there is some odd incompatibility with both those settings?

**Comment by koekeishiya** [comment]
If i have `kwmc config float System Preferences` everything works as expected, regardless of `float-non-resizable`.

If I do not have either of them, and I open system preferences and float it manually, things work as expected.

If I only have `float-non-resizable` the border will move, but fail to update. It starts working if I issue `window -t float` on the system pref window.

**Comment by chrishoage** [comment]
This started working for me with beaddde ??? 

Or maybe restarting kwm fixed the issue? 

So odd. You say it's not working, and it just started working for me.

**Comment by koekeishiya** [comment]
Does it work without having `kwmc config float System Preferences` ?

**Comment by chrishoage** [comment]
So, it breaks _only_ the first time the floating window (with out `config float`) gains focus. If I give a window behind the floating window focus and go back to the floating window it updates properly)

**Comment by koekeishiya** [comment]
Indeed that is the only way to figure out if it is resizable, by trying to tile and notice that it fails.
The weird thing is that the observer callback is created as the very last part of giving the window focus.
And it does get focus properly (both OSX and Kwms), and the mouse is moved accordingly as well if mouse-follows is enabled.

So, I have no idea why it happens.

**Comment by koekeishiya** [comment]
I'm gonna assume that this issue is connected to how `float-non-resizable`works, #83

**Comment by koekeishiya** [comment]
Confirmed working in first commit: bf3fe2c7f44ad87302f76e9ce503fd7cc25bd3f2
Broken in 0575e8691452d46df78ccd55ab832bd8ce6fdd8d
