### ISSUE TITLE
Option to disable autorise / autofocus when floating window has focus

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#97]
When I either toggle a window floating, or add a `config float` option for an app, it is typically because it doesn't play nicely with tiling for what ever reason. I would like it so that if a floating window has focus (for any reason, toggled of set though a config) that `autoriase` is disabled until a floating window no longer has focus. 

The reason for this is often times these floating windows generate other windows or alerts and auto rise makes it very difficult to work with these windows while enabled. I usually just end up disabling autorise while I have to work with these windows anyway. 

I feel it would go well with this config option which I keep enabled.
```
kwmc config float-non-resizable enable
````

Please feel free to close this if it is too difficult to implement or you deem it doesn't fit in.

**Comment by koekeishiya** [comment]
This would more or less be the same as auto-disabling focus-follows-mouse when a floating window gains focus?

As it can not react to other windows while a floating window has focus, it will remain "disabled" til the user manually initiates a hotkey or mouse click a non-floating window.

**Comment by chrishoage** [comment]
Yes that is pretty much what I was thinking. I wasn't even thinking a hot key would do anything (I can already bind a hotkey to disable / enable focus follows mouse)

This would just auto disable / enable focus-follows-mouse whenever a floating window gained / lost focus.

**Comment by koekeishiya** [comment]
Any idea what the config command could be for this? (I do have it working as you've described, but I feel like it should be an option)

**Comment by a-morales** [comment]
Well since there are already a couple of config options for focus what about `focus follows-on-float enable|disable`?

**Comment by chrishoage** [comment]
kwmc config floating-focus-fix enable ?

This particular command is a little difficult to express tersely. Open to
other ideas if anyone has one.

**Comment by koekeishiya** [comment]
I'm gonna use something similar to what @a-morales suggested.
I think the command `kwmc config focus standby-on-float` seems reasonable.
This seems to be working fine, however I'm just gonna do #96 as well before pushing to HEAD.
