### ISSUE TITLE
kwm-overlay disallows taking screenshots of a window

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/kwm#98]
In OS X, you can take a screenshot of a window using cmd+shift-4 and then space. kwm-overlay breaks this, giving you screenshots of the border only.

**Comment by koekeishiya** [comment]
Don't think there is anything to do about that, except for turning the border off before taking screenshots.
This is due to how these borders are achieved by OSX, as they are simply just a floating window that is transparent.

**Comment by dominiklohmann** [comment]
Is there maybe a way to detect the screenshot cursor and then add an option to disable borders when it's active?

**Comment by koekeishiya** [comment]
Dont think there is a way to do that no.
I've fixed so that disable now also clears the border instantly (not pushed to HEAD yet).

What I can do, which is a slightly ugly way to handle this, is detect that cmd+alt-4 has been pressed, and assuming that Kwm does not have a hotkey with this bind, disable the focused border, and reenable it after the next left-mouse-down event.

**Comment by dominiklohmann** [comment]
It's actually cmd+shift-4, I totally forgot I remapped that ages ago.

I assume that'd, despite being an ugly solution, work.

**Comment by koekeishiya** [comment]
The only downside is that I assume a lot of users customize their keybinds, so not everyone is gonna have "cmd+shift-4" to screenshot an app.

With the border instantly disappearing upon `focused-border disable`, is still something you still need?
I  assume that just making a bind in Kwm to enable/disable the border, and just hit them before the screenshot, would be doable.

**Comment by dominiklohmann** [comment]
I'll probably just create a bind for toggling the border and then do the screenshot after that. 

Is there maybe a file you can read these keybinds from? 
<img width="712" alt="screen shot 2016-01-20 at 20 35 34" src="https://cloud.githubusercontent.com/assets/4488655/12460722/701d8ca2-bfb5-11e5-99e7-61ef17e66012.png">

**Comment by koekeishiya** [comment]
It may be possible, but I don't really feel like having to do a solution like that.
I think just having the user disable the border through a bind before taking the screenshot is the appropriate solution here.

In the latest commit, the border should clear instantly when disabled.

**Comment by cHoco** [comment]
I found myself having the same problem and worked around it with a script that I bind to `cmd+shift-4` https://gist.githubusercontent.com/cHoco/ca85b489b7843034cc55/raw/b8aa2a534cf45da037bf957ab039639f39764cb2/screenshot.kwm

**Comment by dominiklohmann** [comment]
I'm using the following:

.kwm/kwmrc
```
kwmc bind cmd+shift-3 sys ~/.kwm/scripts/screencapture
kwmc bind cmd+shift-4 sys ~/.kwm/scripts/screencapture -i
kwmc bind ctrl+cmd+shift-3 sys ~/.kwm/scripts/screencapture -c
kwmc bind ctrl+cmd+shift-4 sys ~/.kwm/scripts/screencapture -c -i
```

.kwm/scripts/screencapture
```shell
#! /bin/sh

kwmc=/usr/local/bin/kwmc
screencapture=/usr/sbin/screencapture

FOCUSED_BORDER=$($kwmc read border focused)
PREFIX_BORDER=$($kwmc read border prefix)
MARKED_BORDER=$($kwmc read border marked)

$kwmc config focused-border disable
$kwmc config prefix-border disable
$kwmc config marked-border disable

$screencapture $@ ~/Desktop/$(date +%s).png

if [ "$FOCUSED_BORDER" = "1" ]
then
	$kwmc config focused-border enable
fi

if [ "$PREFIX_BORDER" = "1" ]
then
	$kwmc config prefix-border enable
fi

if [ "$MARKED_BORDER" = "1" ]
then
	$kwmc config marked-border enable
fi
```

**Comment by cHoco** [comment]
Yours is a lot nicer than mine! You should post it in the wiki and replace mine :)

**Comment by dominiklohmann** [comment]
Done - compacted it a bit and added a comment in the script explaining example usage.
